[game]
name = "Boiling Point: Road To Hell"
exe = "xenus.exe"
notes = "Converted from a Cheat Engine table by needmypandora. Source: https://fearlessrevolution.com/viewtopic.php?t=26587"
verified = []
author = "needmypandora"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "godmode"
name = "GODMODE"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Xenus.exe
  Version: 
  Date   : 2023-11-22
  Author : RESTLESSONE

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(HP,game.dll,D9 99 94 A0 01 00) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  fstp dword ptr [ecx+0001A094]
  mov dword ptr [ecx+0001A094],(float)1.033229232
  jmp return

HP:
  jmp newmem
  nop
return:
registersymbol(HP)

[DISABLE]

HP:
  db D9 99 94 A0 01 00

unregistersymbol(HP)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: game.t_player::RecalcGeneralHealth+109

game.t_player::RecalcGeneralHealth+E4: DF E0              - fnstsw ax
game.t_player::RecalcGeneralHealth+E6: F6 C4 05           - test ah,05
game.t_player::RecalcGeneralHealth+E9: 7A 08              - jp game.t_player::RecalcGeneralHealth+F3
game.t_player::RecalcGeneralHealth+EB: D9 81 18 01 01 00  - fld dword ptr [ecx+00010118]
game.t_player::RecalcGeneralHealth+F1: EB 06              - jmp game.t_player::RecalcGeneralHealth+F9
game.t_player::RecalcGeneralHealth+F3: D9 81 14 01 01 00  - fld dword ptr [ecx+00010114]
game.t_player::RecalcGeneralHealth+F9: DC 0D B0 79 0F 62  - fmul qword ptr [game.t_placeitem::`vftable'+198]
game.t_player::RecalcGeneralHealth+FF: D9 C9              - fxch st(1)
game.t_player::RecalcGeneralHealth+101: DC 0D 10 79 0F 62  - fmul qword ptr [game.t_placeitem::`vftable'+F8]
game.t_player::RecalcGeneralHealth+107: DE C1              - faddp 
// ---------- INJECTING HERE ----------
game.t_player::RecalcGeneralHealth+109: D9 99 94 A0 01 00  - fstp dword ptr [ecx+0001A094]
// ---------- DONE INJECTING  ----------
game.t_player::RecalcGeneralHealth+10F: C3                 - ret 
game.t_player::UpdateWearout: 56                 - push esi
game.t_player::UpdateWearout+1: 8B F1              - mov esi,ecx
game.t_player::UpdateWearout+3: 8B 86 B0 A0 01 00  - mov eax,[esi+0001A0B0]
game.t_player::UpdateWearout+9: 68 C4 EC 0E 62     - push game.t_startpoint::`vftable'+202C
game.t_player::UpdateWearout+E: 50                 - push eax
game.t_player::UpdateWearout+F: FF 15 94 92 0E 62  - call dword ptr [game.gameModelGetParamName+D854]
game.t_player::UpdateWearout+15: DC 0D 08 79 0F 62  - fmul qword ptr [game.t_placeitem::`vftable'+F0]
game.t_player::UpdateWearout+1B: 83 C4 08           - add esp,08
game.t_player::UpdateWearout+1E: D9 9E B4 A0 01 00  - fstp dword ptr [esi+0001A0B4]
}"""

[[cheat]]
id = "money"
name = "MONEY"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Xenus.exe
  Version: 
  Date   : 2023-11-20
  Author : RESTLESSONE

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(MONEY,game.dll,8B 80 4C 01 01 00) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov [eax+0001014C],#1000000
  mov eax,[eax+0001014C]
  jmp return

MONEY:
  jmp newmem
  nop
return:
registersymbol(MONEY)

[DISABLE]

MONEY:
  db 8B 80 4C 01 01 00

unregistersymbol(MONEY)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: game.gamecodeGetAmountOfMoney+3F

game.gamecodeGetAmountOfMoney+1D: 51                    - push ecx
game.gamecodeGetAmountOfMoney+1E: FF 15 7C 92 0E 62     - call dword ptr [game.gameModelGetParamName+D83C]
game.gamecodeGetAmountOfMoney+24: 83 C4 08              - add esp,08
game.gamecodeGetAmountOfMoney+27: 85 C0                 - test eax,eax
game.gamecodeGetAmountOfMoney+29: A1 A4 9A 0E 62        - mov eax,[game.gameModelGetParamName+E064]
game.gamecodeGetAmountOfMoney+2E: 75 0C                 - jne game.gamecodeGetAmountOfMoney+3C
game.gamecodeGetAmountOfMoney+30: 8B 14 B0              - mov edx,[eax+esi*4]
game.gamecodeGetAmountOfMoney+33: 81 7A 08 79 61 6C 70  - cmp [edx+08],UMPDC.dll+6179
game.gamecodeGetAmountOfMoney+3A: 75 D5                 - jne game.gamecodeGetAmountOfMoney+11
game.gamecodeGetAmountOfMoney+3C: 8B 04 B0              - mov eax,[eax+esi*4]
// ---------- INJECTING HERE ----------
game.gamecodeGetAmountOfMoney+3F: 8B 80 4C 01 01 00     - mov eax,[eax+0001014C]
// ---------- DONE INJECTING  ----------
game.gamecodeGetAmountOfMoney+45: 5E                    - pop esi
game.gamecodeGetAmountOfMoney+46: C3                    - ret 
game.gamecodeGetAmountOfMoney+47: CC                    - int 3 
game.gamecodeGetAmountOfMoney+48: CC                    - int 3 
game.gamecodeGetAmountOfMoney+49: CC                    - int 3 
game.gamecodeGetAmountOfMoney+4A: CC                    - int 3 
game.gamecodeGetAmountOfMoney+4B: CC                    - int 3 
game.gamecodeGetAmountOfMoney+4C: CC                    - int 3 
game.gamecodeGetAmountOfMoney+4D: CC                    - int 3 
game.gamecodeGetAmountOfMoney+4E: CC                    - int 3 
}"""

[[cheat]]
id = "sleepiness"
name = "SLEEPINESS"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Xenus.exe
  Version: 
  Date   : 2023-11-22
  Author : RESTLESSONE

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(SLEEPINESS,game.dll,D9 9C B8 08 A2 01 00) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  fstp dword ptr [eax+edi*4+0001A208]
  mov dword ptr [eax+edi*4+0001A208],(float)0.0
  jmp return

SLEEPINESS:
  jmp newmem
  nop 2
return:
registersymbol(SLEEPINESS)

[DISABLE]

SLEEPINESS:
  db D9 9C B8 08 A2 01 00

unregistersymbol(SLEEPINESS)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: game.hpAddExperience+95

game.hpAddExperience+70: A1 A4 9A 0E 62        - mov eax,[game.gameModelGetParamName+E064]
game.hpAddExperience+75: 8B 04 90              - mov eax,[eax+edx*4]
game.hpAddExperience+78: 83 C4 04              - add esp,04
game.hpAddExperience+7B: 85 C0                 - test eax,eax
game.hpAddExperience+7D: 74 1D                 - je game.hpAddExperience+9C
game.hpAddExperience+7F: 81 78 08 79 61 6C 70  - cmp [eax+08],dcomp.DllGetClassObject+C679
game.hpAddExperience+86: 75 14                 - jne game.hpAddExperience+9C
game.hpAddExperience+88: 83 B8 38 09 00 00 0A  - cmp dword ptr [eax+00000938],0A
game.hpAddExperience+8F: 74 0B                 - je game.hpAddExperience+9C
game.hpAddExperience+91: D9 44 24 0C           - fld dword ptr [esp+0C]
// ---------- INJECTING HERE ----------
game.hpAddExperience+95: D9 9C B8 08 A2 01 00  - fstp dword ptr [eax+edi*4+0001A208]
// ---------- DONE INJECTING  ----------
game.hpAddExperience+9C: 5F                    - pop edi
game.hpAddExperience+9D: 5E                    - pop esi
game.hpAddExperience+9E: C3                    - ret 
game.hpAddExperience+9F: CC                    - int 3 
game.hpGetExpLevel: 6A 0A                 - push 0A
game.hpGetExpLevel+2: FF 15 00 93 0E 62     - call dword ptr [game.gameModelGetParamName+D8C0]
game.hpGetExpLevel+8: 8B 0D A4 9A 0E 62     - mov ecx,[game.gameModelGetParamName+E064]
game.hpGetExpLevel+E: 0F BF C0              - movsx eax,ax
game.hpGetExpLevel+11: 8B 0C 81              - mov ecx,[ecx+eax*4]
game.hpGetExpLevel+14: 83 C4 04              - add esp,04
}"""

[[cheat]]
id = "medaddict"
name = "MEDADDICT"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Xenus.exe
  Version: 
  Date   : 2023-11-22
  Author : RESTLESSONE

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(MEDADDICT,game.dll,D9 9C 90 08 A2 01 00) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  fstp dword ptr [eax+edx*4+0001A208]
  mov dword ptr [eax+edx*4+0001A208],(float)0.0
  jmp return

MEDADDICT:
  jmp newmem
  nop 2
return:
registersymbol(MEDADDICT)

[DISABLE]

MEDADDICT:
  db D9 9C 90 08 A2 01 00

unregistersymbol(MEDADDICT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: game.hpSetExperience+35

game.hpSetExperience+11: 8B 04 81              - mov eax,[ecx+eax*4]
game.hpSetExperience+14: 83 C4 04              - add esp,04
game.hpSetExperience+17: 85 C0                 - test eax,eax
game.hpSetExperience+19: 74 21                 - je game.hpSetExperience+3C
game.hpSetExperience+1B: 81 78 08 79 61 6C 70  - cmp [eax+08],dcomp.DllGetClassObject+C679
game.hpSetExperience+22: 75 18                 - jne game.hpSetExperience+3C
game.hpSetExperience+24: 83 B8 38 09 00 00 0A  - cmp dword ptr [eax+00000938],0A
game.hpSetExperience+2B: 74 0F                 - je game.hpSetExperience+3C
game.hpSetExperience+2D: D9 44 24 08           - fld dword ptr [esp+08]
game.hpSetExperience+31: 8B 54 24 04           - mov edx,[esp+04]
// ---------- INJECTING HERE ----------
game.hpSetExperience+35: D9 9C 90 08 A2 01 00  - fstp dword ptr [eax+edx*4+0001A208]
// ---------- DONE INJECTING  ----------
game.hpSetExperience+3C: C3                    - ret 
game.hpSetExperience+3D: CC                    - int 3 
game.hpSetExperience+3E: CC                    - int 3 
game.hpSetExperience+3F: CC                    - int 3 
game.hpGetExperience: 6A 0A                 - push 0A
game.hpGetExperience+2: FF 15 00 93 0E 62     - call dword ptr [game.gameModelGetParamName+D8C0]
game.hpGetExperience+8: 8B 0D A4 9A 0E 62     - mov ecx,[game.gameModelGetParamName+E064]
game.hpGetExperience+E: 0F BF C0              - movsx eax,ax
game.hpGetExperience+11: 8B 04 81              - mov eax,[ecx+eax*4]
game.hpGetExperience+14: 83 C4 04              - add esp,04
}"""
