[game]
name = "Super Lucky's Tale"
exe = "superlucky.exe"
notes = "Converted from a Cheat Engine table by SvT. Source: https://fearlessrevolution.com/viewtopic.php?t=11223"
verified = []
author = "SvT"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "activate-cheats"
name = "Activate Cheats"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : SuperLucky.exe
  Version: Windows Store - December 31, 2019
  Date   : 2019-12-31
  Author : SovietWristwatch.jpg
}

[ENABLE]
aobscanmodule(_playerSharedOpcode,GameAssembly.dll,F3 0F 11 34 C1)
alloc(newmem,$1000,GameAssembly.dll)

label(code)
label(return)
label(getLives)
label(_playerLives)
label(_Coins)
label(_coinMultiplier)
registersymbol(getLives)
registersymbol(_playerSharedOpcode)
registersymbol(_playerLives)
registersymbol(_Coins)
registersymbol(_coinMultiplier)

// Shared Opcode Cheats (Lives, Hearts, Coins)

newmem:
mov [getLives],rcx
cmp rax,15 // lives
jne @f
cmp [_playerLives],0
je code
mov [rcx+rax*8],(float)99
@@:
cmp [_Coins],0
je code
cmp rax,09 // coins 1
jne @f
fld [rcx+rax*8]
fadd [_coinMultiplier]
fstp [rcx+rax*8]
@@:
cmp [_Coins],0
je code
cmp rax,1B // coins 2
jne @f
fld [rcx+rax*8]
fadd [_coinMultiplier]
fstp [rcx+rax*8]
@@:
cmp [_Coins],0
je code
cmp rax,18 // coins 3
jne @f
fld [rcx+rax*8]
fadd [_coinMultiplier]
fstp [rcx+rax*8]
jmp code

code:
  mov ecx,[rcx+rax*8]
  mov al,01
  jmp return

_playerLives:
dd 0

_Coins:
dd 0

_coinMultiplier:
dd (float)5

getLives:

_playerSharedOpcode:
  jmp newmem
return:

// Mega Clock Time

aobscanmodule(_megaClockTime,GameAssembly.dll,F3 0F 10 7E 44 ?? ?? ?? ?? C0)
alloc(newmem3,$1000,GameAssembly.dll)

label(code3)
label(return3)
label(_megaClockTimeFlag)
registersymbol(_megaClockTime)
registersymbol(_megaClockTimeFlag)


newmem3:
cmp [_megaClockTimeFlag],0
je code3
mov [rsi+44],(float)120
jmp return3

code3:
  mov [rsi+44],(float)18
  movss xmm7,[rsi+44]
  jmp return3

_megaClockTimeFlag:
dd 0

_megaClockTime:
  jmp newmem3
return3:
registersymbol(_megaClockTime)

[DISABLE]

_playerSharedOpcode:
  db F3 0F 11 34 C1

_megaClockTime:
  db F3 0F 10 7E 44

unregistersymbol(_playerSharedOpcode)
unregistersymbol(_playerLives)
unregistersymbol(_Coins)
unregistersymbol(_coinMultiplier)
unregistersymbol(_megaClockTime)
unregistersymbol(_megaClockTimeFlag)
dealloc(newmem)
dealloc(newmem2)
dealloc(newmem3)"""

[[cheat]]
id = "unlimited-lives"
name = "Unlimited Lives"
category = "player"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
_playerLives:
dd 1

[DISABLE]
_playerLives:
dd 0"""

[[cheat]]
id = "unlimited-hearts"
name = "Unlimited Hearts"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : SuperLucky.exe
  Version: Windows Store - December 31, 2019
  Date   : 2019-12-31
  Author : SovietWristwatch.jpg
}

[ENABLE]

aobscanmodule(infiniteHearts,GameAssembly.dll,8D 56 01 39 50 20)
alloc(newmem,$1000,GameAssembly.dll)

label(code)
label(return)

newmem:

code:
  lea edx,[rsi+01]
  cmp [rax+20],edx
  mov [rax+20],3
  jmp return

infiniteHearts:
  jmp newmem
  nop
return:
registersymbol(infiniteHearts)

[DISABLE]
infiniteHearts:
  db 8D 56 01 39 50 20

unregistersymbol(infiniteHearts)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "GameAssembly.dll"+F8EF7E

"GameAssembly.dll"+F8EF58: E8 93 B4 38 00              -  call GameAssembly.dll+131A3F0
"GameAssembly.dll"+F8EF5D: 84 C0                       -  test al,al
"GameAssembly.dll"+F8EF5F: 74 52                       -  je GameAssembly.dll+F8EFB3
"GameAssembly.dll"+F8EF61: 49 8B 4E 20                 -  mov rcx,[r14+20]
"GameAssembly.dll"+F8EF65: 48 85 C9                    -  test rcx,rcx
"GameAssembly.dll"+F8EF68: 0F 84 1F 03 00 00           -  je GameAssembly.dll+F8F28D
"GameAssembly.dll"+F8EF6E: 33 D2                       -  xor edx,edx
"GameAssembly.dll"+F8EF70: E8 9B 8A 91 FF              -  call GameAssembly.dll+8A7A10
"GameAssembly.dll"+F8EF75: 48 85 C0                    -  test rax,rax
"GameAssembly.dll"+F8EF78: 0F 84 09 03 00 00           -  je GameAssembly.dll+F8F287
// ---------- INJECTING HERE ----------
"GameAssembly.dll"+F8EF7E: 8D 56 01                    -  lea edx,[rsi+01]
"GameAssembly.dll"+F8EF81: 39 50 20                    -  cmp [rax+20],edx
// ---------- DONE INJECTING  ----------
"GameAssembly.dll"+F8EF84: 7D 12                       -  jnl GameAssembly.dll+F8EF98
"GameAssembly.dll"+F8EF86: 48 85 FF                    -  test rdi,rdi
"GameAssembly.dll"+F8EF89: 0F 84 EC 02 00 00           -  je GameAssembly.dll+F8F27B
"GameAssembly.dll"+F8EF8F: 48 8B 15 CA 5B 59 01        -  mov rdx,[GameAssembly.dll+2524B60]
"GameAssembly.dll"+F8EF96: EB 10                       -  jmp GameAssembly.dll+F8EFA8
"GameAssembly.dll"+F8EF98: 48 85 FF                    -  test rdi,rdi
"GameAssembly.dll"+F8EF9B: 0F 84 E0 02 00 00           -  je GameAssembly.dll+F8F281
"GameAssembly.dll"+F8EFA1: 48 8B 15 D0 5A 59 01        -  mov rdx,[GameAssembly.dll+2524A78]
"GameAssembly.dll"+F8EFA8: 45 33 C0                    -  xor r8d,r8d
"GameAssembly.dll"+F8EFAB: 48 8B CF                    -  mov rcx,rdi
}"""

[[cheat]]
id = "unlimited-jumps"
name = "Unlimited Jumps"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game   : SuperLucky.exe
  Version: Windows Store - December 31, 2019
  Date   : 2019-12-31
  Author : SovietWristwatch.jpg
}


[ENABLE]
aobscanmodule(infiniteJumps1,GameAssembly.dll,C6 87 08 01 00 00 01 C6)
alloc(newmem,$1000,"GameAssembly.dll"+89B377)
aobscanmodule(infiniteJumps2,GameAssembly.dll,C6 87 AC 00 00 00 01 F2)
alloc(newmem2,$1000,"GameAssembly.dll"+89B37E)

label(code)
label(return)
label(code2)
label(return2)

newmem:

code:
  db 90 90 90 90 90 90 90 90
  jmp return

infiniteJumps1:
  jmp newmem
  nop 2
return:
registersymbol(infiniteJumps1)

newmem2:

code2:
  db 90 90 90 90 90 90 90 90
  jmp return2

infiniteJumps2:
  jmp newmem2
  nop 2
return2:
registersymbol(infiniteJumps2)


[DISABLE]
infiniteJumps1:
  db C6 87 08 01 00 00 01

infiniteJumps2:
  db C6 87 AC 00 00 00 01

unregistersymbol(infiniteJumps1)
dealloc(newmem)
unregistersymbol(infiniteJumps2)
dealloc(newmem2)

{
// ORIGINAL CODE - INJECTION POINT: "GameAssembly.dll"+89B377

"GameAssembly.dll"+89B34C: F2 0F 11 45 07           -  movsd [rbp+07],xmm0
"GameAssembly.dll"+89B351: 89 45 0F                 -  mov [rbp+0F],eax
"GameAssembly.dll"+89B354: F2 0F 11 75 F7           -  movsd [rbp-09],xmm6
"GameAssembly.dll"+89B359: 89 5D FF                 -  mov [rbp-01],ebx
"GameAssembly.dll"+89B35C: E8 9F 29 A8 00           -  call GameAssembly.dll+131DD00
"GameAssembly.dll"+89B361: 84 C0                    -  test al,al
"GameAssembly.dll"+89B363: 0F 85 16 02 00 00        -  jne GameAssembly.dll+89B57F
"GameAssembly.dll"+89B369: 0F 29 BC 24 80 00 00 00  -  movaps [rsp+00000080],xmm7
"GameAssembly.dll"+89B371: 44 38 7F 5D              -  cmp [rdi+5D],r15l
"GameAssembly.dll"+89B375: 75 0E                    -  jne GameAssembly.dll+89B385
// ---------- INJECTING HERE ----------
"GameAssembly.dll"+89B377: C6 87 08 01 00 00 01     -  mov byte ptr [rdi+00000108],01
// ---------- DONE INJECTING  ----------
"GameAssembly.dll"+89B37E: C6 87 AC 00 00 00 01     -  mov byte ptr [rdi+000000AC],01
"GameAssembly.dll"+89B385: F2 0F 10 87 D0 00 00 00  -  movsd xmm0,[rdi+000000D0]
"GameAssembly.dll"+89B38D: 33 D2                    -  xor edx,edx
"GameAssembly.dll"+89B38F: 8B 87 D8 00 00 00        -  mov eax,[rdi+000000D8]
"GameAssembly.dll"+89B395: 48 8B CF                 -  mov rcx,rdi
"GameAssembly.dll"+89B398: F3 0F 10 77 7C           -  movss xmm6,[rdi+7C]
"GameAssembly.dll"+89B39D: F3 0F 10 BF E0 00 00 00  -  movss xmm7,[rdi+000000E0]
"GameAssembly.dll"+89B3A5: F2 0F 11 45 07           -  movsd [rbp+07],xmm0
"GameAssembly.dll"+89B3AA: 89 45 0F                 -  mov [rbp+0F],eax
"GameAssembly.dll"+89B3AD: E8 FE 51 CA 00           -  call GameAssembly.dll+15405B0
}"""

[[cheat]]
id = "mega-coins-5-x-multiplier"
name = "Mega Coins (5 x Multiplier)"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
_Coins:
dd 1

[DISABLE]
_Coins:
dd 0"""

[[cheat]]
id = "mega-clock-time-2-minutes"
name = "Mega Clock Time (2 minutes)"
category = "game"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
_megaClockTimeFlag:
dd 1

[DISABLE]
_megaClockTimeFlag:
dd 0"""
