[game]
name = "Buckshot Roulette"
exe = "buckshot roulette.exe"
notes = "Converted from a Cheat Engine table by The Mogician. Source: https://fearlessrevolution.com/viewtopic.php?t=28474"
verified = []
author = "The Mogician"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "own-health"
name = "Own Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "Buckshot Roulette.exe"
offset = "0x35ad2c0"
hops = [
    "+0x48",
    "+0x0",
    "+0x18",
    "+0x20",
    "+0x318",
    "+0x0",
    "+0x68",
    "+0x28",
    "+0x110",
]

[[cheat]]
id = "dealer-health"
name = "Dealer Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "Buckshot Roulette.exe"
offset = "0x35ad2c0"
hops = [
    "+0x48",
    "+0x0",
    "+0x18",
    "+0x20",
    "+0x318",
    "+0x0",
    "+0x68",
    "+0x28",
    "+0x128",
]
