[game]
name = "Empire TV Tycoon Money Cheat FIXED"
exe = "empiretv.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=2364"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "money"
name = "Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 5101720

[cheat.locator]
find = "static"
module = "EmpireTV.exe"
offset = "0x10c09a8"
hops = [
    "+0x260",
    "+0x498",
    "+0xc8",
    "+0x2e0",
    "+0x69c",
]

[[cheat]]
id = "money-2"
name = "Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 5101720

[cheat.locator]
find = "static"
module = "EmpireTV.exe"
offset = "0x1084e60"
hops = [
    "+0x7d0",
    "+0x508",
    "+0xc8",
    "+0x2e0",
    "+0x69c",
]

[[cheat]]
id = "money-3"
name = "Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 5101720

[cheat.locator]
find = "static"
module = "EmpireTV.exe"
offset = "0x110d538"
hops = [
    "+0x5d0",
    "+0x740",
    "+0xc8",
    "+0x2e0",
    "+0x69c",
]

[[cheat]]
id = "money-4"
name = "Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 5101720

[cheat.locator]
find = "static"
module = "EmpireTV.exe"
offset = "0x1152cb0"
hops = [
    "+0x630",
    "+0x740",
    "+0xc8",
    "+0x2e0",
    "+0x69c",
]

[[cheat]]
id = "money-5"
name = "Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 5101720

[cheat.locator]
find = "static"
module = "EmpireTV.exe"
offset = "0x10670d0"
hops = [
    "+0x660",
    "+0x740",
    "+0xc8",
    "+0x2e0",
    "+0x69c",
]

[[cheat]]
id = "money-6"
name = "Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 5101720

[cheat.locator]
find = "static"
module = "EmpireTV.exe"
offset = "0x10c09a0"
hops = [
    "+0x4a8",
    "+0x598",
    "+0x130",
    "+0x2e0",
    "+0x69c",
]

[[cheat]]
id = "money-7"
name = "Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 5101720

[cheat.locator]
find = "static"
module = "EmpireTV.exe"
offset = "0x10c09a0"
hops = [
    "+0x2a0",
    "+0x6c0",
    "+0x58",
    "+0x3a0",
    "+0x69c",
]
