[game]
name = "Diablo 1 HD Belzebub"
exe = "belzebub.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=986"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "encode"
name = "Encode"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
alloc(newmem,256)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here

originalcode:
mov ecx,[ebp+0C]
mov [eax],ecx
mov edx,ecx
pop ebp
ret
//push esi
//mov esi,[6D8D9448]

exit:
jmp returnhere

"mvar.dll"+32F6:
jmp newmem
nop
nop
nop
nop
nop
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
"mvar.dll"+32F6:
mov ecx,[ebp+0C]
push esi
mov esi,[6D8D9448]
//Alt: db 8B 4D 0C 56 8B 35 48 94 8D 6D"""

[[cheat]]
id = "decode"
name = "Decode"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
alloc(newmem,256)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here

originalcode:
mov ecx,[ebp+08]
mov edx,[ecx]
mov [eax],edx
pop ebp
ret

exit:
jmp returnhere

"mvar.dll"+3206:
jmp newmem
nop
nop
nop
nop
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
"mvar.dll"+3206:
mov ecx,[ebp+08]
mov [eax],00000000
//Alt: db 8B 4D 08 C7 00 00 00 00 00"""

[[cheat]]
id = "hero-stats"
name = "Hero Stats"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
alloc(newmem,128)
label(returnhere)
label(originalcode)
label(exit)

label(HeroAdr)
registersymbol(HeroAdr)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here

originalcode:
add eax,00002760

mov [HeroAdr],eax

exit:
jmp returnhere

HeroAdr:
dd 0

"Belzebub.exe"+56029:
jmp newmem
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
unregistersymbol(HeroAdr)

"Belzebub.exe"+56029:
add eax,00002760
//Alt: db 05 60 27 00 00"""

[[cheat]]
id = "hero-name-lenght"
name = "Hero Name Lenght"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0x10"]

[[cheat]]
id = "flag"
name = "flag ???"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0x14"]

[[cheat]]
id = "xp"
name = "XP"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xdc"]

[[cheat]]
id = "points-to-distribute"
name = "Points to Distribute"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffd910"]

[[cheat]]
id = "str"
name = "STR"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffd8c8"]

[[cheat]]
id = "mag"
name = "MAG"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffd8da"]

[[cheat]]
id = "dex"
name = "DEX"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffd8ec"]

[[cheat]]
id = "vit"
name = "VIT"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffd8fe"]

[[cheat]]
id = "magic-find"
name = "Magic Find"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe1ec"]

[[cheat]]
id = "extra-gold-from-monsters"
name = "Extra Gold from monsters %"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe2c4"]

[[cheat]]
id = "add-points-to-all-attributes"
name = "Add points to all attributes"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffde56"]

[[cheat]]
id = "attack-speed"
name = "Attack Speed"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe02a"]

[[cheat]]
id = "increase-spells-cast"
name = "Increase Spells Cast %"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe15c"]

[[cheat]]
id = "increase-all-spells-levels"
name = "Increase All Spells levels"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe16e"]

[[cheat]]
id = "chance-to-hit"
name = "Chance to hit"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe03c"]

[[cheat]]
id = "walk-run-speed"
name = "Walk/Run Speed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe006"]

[[cheat]]
id = "hit-point-increases"
name = "Hit Point Increases"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffdec2"]

[[cheat]]
id = "armor-increase"
name = "Armor Increase"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffdf64"]

[[cheat]]
id = "life-regen"
name = "Life Regen"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffdfbe"]

[[cheat]]
id = "hit-steals-life"
name = "Hit Steals Life %"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe138"]

[[cheat]]
id = "mana-regen"
name = "Mana Regen"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffdfd0"]

[[cheat]]
id = "resist-all"
name = "Resist all"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffdef8"]

[[cheat]]
id = "damage-reduction-from-ennemy"
name = "Damage reduction from ennemy"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffdff4"]

[[cheat]]
id = "add-points-to-damage"
name = "Add Points to damage"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe0ba"]

[[cheat]]
id = "magic-damage-min"
name = "Magic damage - Min"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe102"]

[[cheat]]
id = "magic-damage-max"
name = "Magic damage - Max"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe10b"]

[[cheat]]
id = "fire-damage-min"
name = "Fire damage - Min"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe0de"]

[[cheat]]
id = "fire-damage-max"
name = "Fire damage - Max"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe0e7"]

[[cheat]]
id = "lightnight-damage-min"
name = "Lightnight damage - Min"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe0cc"]

[[cheat]]
id = "lightning-damage-max"
name = "Lightning damage - Max"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe0d5"]

[[cheat]]
id = "cold-damage-bonus-min"
name = "Cold damage bonus- Min"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe0f0"]

[[cheat]]
id = "cold-damage-bonus-max"
name = "Cold damage bonus- Max"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe0f9"]

[[cheat]]
id = "critical-hit-damage"
name = "Critical Hit damage %"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe1c8"]

[[cheat]]
id = "critical-hit-chance"
name = "Critical Hit Chance"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "HeroAdr"
hops = ["+0xffffe1b6"]
