[game]
name = "Jazz Jackrabbit 2"
exe = "jazz2.exe"
notes = "Converted from a Cheat Engine table by erfg12. Source: https://fearlessrevolution.com/viewtopic.php?t=7306"
verified = []
author = "erfg12"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "health"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 5

[cheat.locator]
find = "static"
module = "jazz2.exe"
offset = "0x1c859e"
hops = []

[[cheat]]
id = "lives"
name = "Lives"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 3

[cheat.locator]
find = "static"
module = "jazz2.exe"
offset = "0x1c8700"
hops = []

[[cheat]]
id = "score"
name = "Score"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 2000

[cheat.locator]
find = "static"
module = "jazz2.exe"
offset = "0x1c8928"
hops = []

[[cheat]]
id = "ammo"
name = "Ammo"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0

[cheat.locator]
find = "static"
module = "jazz2.exe"
offset = "0x1c8964"
hops = []

[[cheat]]
id = "flame-thrower-fuel"
name = "Flame Thrower Fuel"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0

[cheat.locator]
find = "static"
module = "jazz2.exe"
offset = "0x1c8974"
hops = []

[[cheat]]
id = "gold-coins"
name = "Gold Coins"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 91

[cheat.locator]
find = "static"
module = "jazz2.exe"
offset = "0x1c8934"
hops = []

[[cheat]]
id = "silver-coins"
name = "Silver Coins"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 91

[cheat.locator]
find = "static"
module = "Jazz2.exe"
offset = "0x1c8934"
hops = []

[[cheat]]
id = "sugar-rush-timer"
name = "Sugar Rush Timer"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0

[cheat.locator]
find = "static"
module = "jazz2.exe"
offset = "0x1c8a1c"
hops = []

[[cheat]]
id = "shield-timer"
name = "Shield Timer"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0.000000000000000000000000000000000000000003311268271

[cheat.locator]
find = "static"
module = "Jazz2.exe"
offset = "0x1c89d0"
hops = []
