[game]
name = "Good Company"
exe = "crex_-_good_company.exe"
notes = "Converted from a Cheat Engine table by CrexTheDead. Source: https://fearlessrevolution.com/viewtopic.php?t=12013"
verified = []
author = "CrexTheDead"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "inf-money"
name = "Inf Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "static"
module = "DLLInterface.dll"
offset = "0x125c8f8"
hops = [
    "+0x8",
    "+0x8",
    "+0x398",
    "+0x38",
    "+0x0",
]

[[cheat]]
id = "inf-money-2"
name = "inf money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "static"
module = "DLLInterface.dll"
offset = "0x12839f0"
hops = [
    "+0xf0",
    "+0xa8",
    "+0x3b0",
    "+0x38",
    "+0x0",
]

[[cheat]]
id = "inf-money-3"
name = "inf money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "static"
module = "DLLInterface.dll"
offset = "0x125c918"
hops = [
    "+0x8",
    "+0x8",
    "+0x3b0",
    "+0x38",
    "+0x0",
]

[[cheat]]
id = "inf-money-4"
name = "inf money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "static"
module = "DLLInterface.dll"
offset = "0x1283148"
hops = [
    "+0x8",
    "+0x8",
    "+0x398",
    "+0x38",
    "+0x0",
]
