[game]
name = "Rayman 3 PC"
exe = "rayman3.exe"
notes = "Converted from a Cheat Engine table by Danny06. Source: https://fearlessrevolution.com/viewtopic.php?t=33190"
verified = []
author = "Danny06"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "heavy-metal"
name = "Heavy Metal"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 5
choices = [
    "5:Normal",
    "6:x2 meter",
    "0:Vortex",
    "1:Helicopter",
    "2:Lock Jaw",
    "3:Rocket",
    "4:Heavy Metal",
]

[cheat.locator]
find = "static"
module = "Rayman3.exe"
offset = "0x3dc82c"
hops = [
    "+0xc",
    "+0x0",
    "+0xc",
    "+0x8",
    "+0x0",
]

[[cheat]]
id = "hp"
name = "HP"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "Rayman3.exe"
offset = "0x3dc82c"
hops = [
    "+0xc",
    "+0x0",
    "+0xc",
    "+0x8",
    "+0x63c",
]

[[cheat]]
id = "max-hp-read-only"
name = "Max HP (Read-only)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "static"
module = "Rayman3.exe"
offset = "0x3dc82c"
hops = [
    "+0xc",
    "+0x0",
    "+0xc",
    "+0x8",
    "+0x640",
]

[[cheat]]
id = "level-score-pause-menu"
name = "Level Score (Pause Menu)"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "Rayman3.exe"
offset = "0x3d9a78"
hops = [
    "+0x0",
    "+0x30",
    "+0x84",
    "+0x120",
    "+0x18c",
    "+0x3a8",
    "+0xff8",
]

[[cheat]]
id = "x"
name = "X"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "Rayman3.exe"
offset = "0x3a8490"
hops = ["+0x138"]

[[cheat]]
id = "y"
name = "Y"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "Rayman3.exe"
offset = "0x3a8490"
hops = ["+0x13c"]

[[cheat]]
id = "z"
name = "Z"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "Rayman3.exe"
offset = "0x3a8490"
hops = ["+0x140"]

[[cheat]]
id = "y-2"
name = "Y"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "Rayman3.exe"
offset = "0x4043c4"
hops = []
