[game]
name = "Persona 4 Arena Ultimax"
exe = "p4u2.exe"
notes = "Converted from a Cheat Engine table by zerotang. Source: https://fearlessrevolution.com/viewtopic.php?t=37550"
verified = []
author = "zerotang"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "st"
name = "St"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "P4U2.exe"
offset = "0xd0e38c"
hops = []

[[cheat]]
id = "ma"
name = "Ma"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "P4U2.exe"
offset = "0xd0e390"
hops = []

[[cheat]]
id = "en"
name = "En"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "P4U2.exe"
offset = "0xd0e394"
hops = []

[[cheat]]
id = "ag"
name = "Ag"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "P4U2.exe"
offset = "0xd0e398"
hops = []

[[cheat]]
id = "lu"
name = "Lu"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "P4U2.exe"
offset = "0xd0e39c"
hops = []

[[cheat]]
id = "network-exp-4-152-300xp-is-requirement-to-lv30"
name = "Network EXP (4,152,300XP is requirement to Lv30)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "P4U2.exe"
offset = "0x8e0e74"
hops = []
