[game]
name = "The whispered world (Special Edition)"
exe = "twwse.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=3532"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "spot-s-disguise"
name = "Spot's disguise"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 209

[cheat.locator]
find = "static"
module = "twwse.exe"
offset = "0xba9508"
hops = [
    "+0x0",
    "+0x428",
    "+0x468",
    "+0x368",
    "+0x0",
]

[[cheat]]
id = "spot-s-disguise-2"
name = "Spot's disguise"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 209

[cheat.locator]
find = "static"
module = "twwse.exe"
offset = "0xba9508"
hops = [
    "+0x0",
    "+0x400",
    "+0x3d8",
    "+0xf8",
    "+0x200",
]

[[cheat]]
id = "spot-s-disguise-3"
name = "Spot's disguise"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 209

[cheat.locator]
find = "static"
module = "twwse.exe"
offset = "0xba9508"
hops = [
    "+0x0",
    "+0x428",
    "+0x48",
    "+0x1b8",
    "+0x4e0",
]
