[game]
name = "While the iron is hot Assembly-CSharp.dll cheat file"
exe = "hot.exe"
notes = "Converted from a Cheat Engine table by gorsan. Source: https://fearlessrevolution.com/viewtopic.php?t=26777"
verified = []
author = "gorsan"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "unlimited-energy"
name = "Unlimited Energy"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game   : While the Iron's Hot.exe
  Version: 1.0.3.0 Gamepass
  Date   : 2023-12-13
  Author : JRem

  Unlimited Energy, Adds 100 Energy everytime it attempts to subtract
}

[ENABLE]

aobscan(INJECT,C1 F2 0F 5A E8 F3 0F 11 6E 14 F3) // should be unique
alloc(newmem,$1000,INJECT)

label(code)
label(return)

newmem:

code:
  // save rax (we'll overwrite it later)
  push rax
  // push value to add to stack
  push (float)100
  // load and add from stack
  addss xmm5, dword ptr [rsp]
  // remove from stack
  pop rax
  // restore rax
  pop rax
  movss [rsi+14],xmm5
  jmp return

INJECT+05:
  jmp newmem
return:
registersymbol(INJECT)

[DISABLE]

INJECT+05:
  db F3 0F 11 6E 14

unregistersymbol(INJECT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 1A36C3E87E6

1A36C3E87B8: 48 89 7C 24 08     - mov [rsp+08],rdi
1A36C3E87BD: 4C 89 7C 24 10     - mov [rsp+10],r15
1A36C3E87C2: 48 8B F1           - mov rsi,rcx
1A36C3E87C5: F3 0F 11 4C 24 20  - movss [rsp+20],xmm1
1A36C3E87CB: F3 0F 10 46 14     - movss xmm0,[rsi+14]
1A36C3E87D0: F3 0F 5A C0        - cvtss2sd xmm0,xmm0
1A36C3E87D4: F3 0F 10 4C 24 20  - movss xmm1,[rsp+20]
1A36C3E87DA: F3 0F 5A C9        - cvtss2sd xmm1,xmm1
1A36C3E87DE: F2 0F 58 C1        - addsd xmm0,xmm1
1A36C3E87E2: F2 0F 5A E8        - cvtsd2ss xmm5,xmm0
// ---------- INJECTING HERE ----------
1A36C3E87E6: F3 0F 11 6E 14     - movss [rsi+14],xmm5
// ---------- DONE INJECTING  ----------
1A36C3E87EB: F3 0F 10 46 14     - movss xmm0,[rsi+14]
1A36C3E87F0: F3 0F 5A C0        - cvtss2sd xmm0,xmm0
1A36C3E87F4: 66 0F 57 C9        - xorpd xmm1,xmm1
1A36C3E87F8: 66 0F 2F C8        - comisd xmm1,xmm0
1A36C3E87FC: 76 0F              - jna 1A36C3E880D
1A36C3E87FE: 66 0F 57 C0        - xorpd xmm0,xmm0
1A36C3E8802: F2 0F 5A E8        - cvtsd2ss xmm5,xmm0
1A36C3E8806: F3 0F 11 6E 14     - movss [rsi+14],xmm5
1A36C3E880B: EB 2C              - jmp 1A36C3E8839
1A36C3E880D: F3 0F 10 46 14     - movss xmm0,[rsi+14]
}"""

[[cheat]]
id = "unlimited-durability"
name = "Unlimited Durability"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : While the Iron's Hot.exe
  Version: 
  Date   : 2023-12-14
  Author : JRem

  Unlimited Durability
}

[ENABLE]

aobscan(INJECT,F3 0F 11 68 24 F3 0F 10) // should be unique
alloc(newmem,$1000,INJECT)

label(code)
label(return)

newmem:

code:
  // save rax (we'll overwrite it later)
  push rax
  // push value to add to stack
  push (float)100
  // load and add from stack
  addss xmm5, dword ptr [rsp]
  // remove from stack
  pop rax
  // restore rax
  pop rax
  movss [rax+24],xmm5
  jmp return

INJECT:
  jmp newmem
return:
registersymbol(INJECT)

[DISABLE]

INJECT:
  db F3 0F 11 68 24

unregistersymbol(INJECT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 22D5E672473

22D5E67243F: 48 8B 85 68 FE FF FF           - mov rax,[rbp-00000198]
22D5E672446: 48 85 C0                       - test rax,rax
22D5E672449: 0F 84 84 00 00 00              - je 22D5E6724D3
22D5E67244F: 48 8B 85 68 FE FF FF           - mov rax,[rbp-00000198]
22D5E672456: F3 0F 10 40 24                 - movss xmm0,[rax+24]
22D5E67245B: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
22D5E67245F: F3 0F 10 0D 79 07 00 00        - movss xmm1,[22D5E672BE0]
22D5E672467: F3 0F 5A C9                    - cvtss2sd xmm1,xmm1
22D5E67246B: F2 0F 5C C1                    - subsd xmm0,xmm1
22D5E67246F: F2 0F 5A E8                    - cvtsd2ss xmm5,xmm0
// ---------- INJECTING HERE ----------
22D5E672473: F3 0F 11 68 24                 - movss [rax+24],xmm5
// ---------- DONE INJECTING  ----------
22D5E672478: F3 0F 10 40 24                 - movss xmm0,[rax+24]
22D5E67247D: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
22D5E672481: 66 0F 57 C9                    - xorpd xmm1,xmm1
22D5E672485: 66 0F 2F C8                    - comisd xmm1,xmm0
22D5E672489: 0F 82 44 00 00 00              - jb 22D5E6724D3
22D5E67248F: 48 B8 F0 32 ED 89 2C 02 00 00  - mov rax,0000022C89ED32F0
22D5E672499: 48 8B 00                       - mov rax,[rax]
22D5E67249C: 48 8B C8                       - mov rcx,rax
22D5E67249F: 83 39 00                       - cmp dword ptr [rcx],00
22D5E6724A2: 48 8B 80 98 00 00 00           - mov rax,[rax+00000098]
}"""

[[cheat]]
id = "unlimited-hammer-minigame"
name = "Unlimited Hammer Minigame"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : While the Iron's Hot.exe
  Version: 
  Date   : 2023-12-14
  Author : Jrem

  Hammer Minigame
}

[ENABLE]

aobscan(INJECT,89 86 F0 01 00 00 48 8B 8E) // should be unique
alloc(newmem,$1000,INJECT)

label(code)
label(return)

newmem:

code:
  mov [rsi+000001F0],eax
  mov [rsi+000001F0],(Int)9
  jmp return

INJECT:
  jmp newmem
  nop
return:
registersymbol(INJECT)

[DISABLE]

INJECT:
  db 89 86 F0 01 00 00

unregistersymbol(INJECT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 22D5F8611F4

22D5F8611C3: 4C 89 7D F8                    - mov [rbp-08],r15
22D5F8611C7: 48 8B F1                       - mov rsi,rcx
22D5F8611CA: C7 45 B8 00 00 00 00           - mov [rbp-48],00000000
22D5F8611D1: C7 45 BC 00 00 00 00           - mov [rbp-44],00000000
22D5F8611D8: 48 8B CE                       - mov rcx,rsi
22D5F8611DB: 66 66 90                       - nop 3
22D5F8611DE: 49 BB 00 17 86 5F 2D 02 00 00  - mov r11,0000022D5F861700
22D5F8611E8: 41 FF D3                       - call r11
22D5F8611EB: 48 63 86 F0 01 00 00           - movsxd  rax,dword ptr [rsi+000001F0]
22D5F8611F2: FF C8                          - dec eax
// ---------- INJECTING HERE ----------
22D5F8611F4: 89 86 F0 01 00 00              - mov [rsi+000001F0],eax
// ---------- DONE INJECTING  ----------
22D5F8611FA: 48 8B 8E C0 01 00 00           - mov rcx,[rsi+000001C0]
22D5F861201: F3 0F 10 05 87 04 00 00        - movss xmm0,[22D5F861690]
22D5F861209: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
22D5F86120D: F2 0F 10 C8                    - movsd xmm1,xmm0
22D5F861211: F2 0F 5A C9                    - cvtsd2ss xmm1,xmm1
22D5F861215: 90                             - nop 
22D5F861216: 49 BB A0 19 86 5F 2D 02 00 00  - mov r11,0000022D5F8619A0
22D5F861220: 41 FF D3                       - call r11
22D5F861223: 48 8B 8E 80 01 00 00           - mov rcx,[rsi+00000180]
22D5F86122A: 48 85 F6                       - test rsi,rsi
}"""

[[cheat]]
id = "unlimited-sharpening-minigame"
name = "Unlimited Sharpening Minigame"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : While the Iron's Hot.exe
  Version: 
  Date   : 2023-12-14
  Author : JRem

  Sharpening Minigame
}

[ENABLE]

aobscan(INJECT,89 86 8C 01 00 00 48 8B CE) // should be unique
alloc(newmem,$1000,INJECT)

label(code)
label(return)

newmem:

code:
  mov [rsi+0000018C],eax
  mov [rsi+0000018C],(Int)9
  jmp return

INJECT:
  jmp newmem
  nop
return:
registersymbol(INJECT)

[DISABLE]

INJECT:
  db 89 86 8C 01 00 00

unregistersymbol(INJECT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 22D5F91C60D

22D5F91C5DF: 48 8B 06                       - mov rax,[rsi]
22D5F91C5E2: FF 90 A0 00 00 00              - call qword ptr [rax+000000A0]
22D5F91C5E8: 48 8B CE                       - mov rcx,rsi
22D5F91C5EB: 49 8B D6                       - mov rdx,r14
22D5F91C5EE: 49 BB 00 C8 91 5F 2D 02 00 00  - mov r11,0000022D5F91C800
22D5F91C5F8: 41 FF D3                       - call r11
22D5F91C5FB: 45 85 F6                       - test r14d,r14d
22D5F91C5FE: 0F 85 21 00 00 00              - jne 22D5F91C625
22D5F91C604: 48 63 86 8C 01 00 00           - movsxd  rax,dword ptr [rsi+0000018C]
22D5F91C60B: FF C8                          - dec eax
// ---------- INJECTING HERE ----------
22D5F91C60D: 89 86 8C 01 00 00              - mov [rsi+0000018C],eax
// ---------- DONE INJECTING  ----------
22D5F91C613: 48 8B CE                       - mov rcx,rsi
22D5F91C616: 49 BB B0 07 92 5F 2D 02 00 00  - mov r11,0000022D5F9207B0
22D5F91C620: 41 FF D3                       - call r11
22D5F91C623: EB 26                          - jmp 22D5F91C64B
22D5F91C625: 48 63 86 94 01 00 00           - movsxd  rax,dword ptr [rsi+00000194]
22D5F91C62C: FF C0                          - inc eax
22D5F91C62E: 89 86 94 01 00 00              - mov [rsi+00000194],eax
22D5F91C634: 48 8B CE                       - mov rcx,rsi
22D5F91C637: 48 8B D7                       - mov rdx,rdi
22D5F91C63A: 4D 8B C7                       - mov r8,r15
}"""

[[cheat]]
id = "craft-table-dupe-fixed-really-this-time"
name = "Craft Table Dupe (Fixed)(Really This Time)"
category = "game"
description = ""
hint = ""
type = "script"
source = """
{ Game   : While the Iron's Hot.exe
  Version: 
  Date   : 2023-12-15
  Author : JRem

  Dupe Items
}

[ENABLE]

aobscan(INJECT,03 CC 89 48 18 48 B8 00 DA ?? ?? ?? ?? 00 00) // should be unique
alloc(newmem,$1000,INJECT)

label(code)
label(return)

newmem:

code:
  mov [rax+18],ecx
  mov [rax+18]],(Int)999
  jmp return

INJECT+02:
  jmp newmem
  nop 8
return:
registersymbol(INJECT)

[DISABLE]

INJECT+02:
  db 89 48 18 48 B8 00 DA ?? ?? ?? 01 00 00

unregistersymbol(INJECT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 1E5614F40E5

1E5614F40BE: 83 39 00                       - cmp dword ptr [rcx],00
1E5614F40C1: 48 8B 40 18                    - mov rax,[rax+18]
1E5614F40C5: 4C 63 60 18                    - movsxd  r12,dword ptr [rax+18]
1E5614F40C9: 44 89 A5 D0 FE FF FF           - mov [rbp-00000130],r12d
1E5614F40D0: 48 8B 47 18                    - mov rax,[rdi+18]
1E5614F40D4: 48 8B 40 10                    - mov rax,[rax+10]
1E5614F40D8: 48 8B C8                       - mov rcx,rax
1E5614F40DB: 48 8B D1                       - mov rdx,rcx
1E5614F40DE: 48 63 49 18                    - movsxd  rcx,dword ptr [rcx+18]
1E5614F40E2: 41 03 CC                       - add ecx,r12d
// ---------- INJECTING HERE ----------
1E5614F40E5: 89 48 18                       - mov [rax+18],ecx
// ---------- DONE INJECTING  ----------
1E5614F40E8: 48 B8 00 DA BF 8B E4 01 00 00  - mov rax,000001E48BBFDA00
1E5614F40F2: 48 8B 00                       - mov rax,[rax]
1E5614F40F5: 48 8B C8                       - mov rcx,rax
1E5614F40F8: 83 39 00                       - cmp dword ptr [rcx],00
1E5614F40FB: 48 8B 40 18                    - mov rax,[rax+18]
1E5614F40FF: 48 8B C8                       - mov rcx,rax
1E5614F4102: 48 8B D1                       - mov rdx,rcx
1E5614F4105: 48 63 49 18                    - movsxd  rcx,dword ptr [rcx+18]
1E5614F4109: 41 2B CC                       - sub ecx,r12d
1E5614F410C: 89 48 18                       - mov [rax+18],ecx
}"""
