[game]
name = "Super Duper Party Pooper"
exe = "superduperpartypooper.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=1469"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "ammo"
name = "ammo"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 7

[cheat.locator]
find = "static"
module = "mono.dll"
offset = "0x20a90c"
hops = [
    "+0xb0",
    "+0xc",
    "+0x194",
    "+0x134",
]

[[cheat]]
id = "score"
name = "score"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 710

[cheat.locator]
find = "static"
module = "mono.dll"
offset = "0x20a90c"
hops = [
    "+0xb0",
    "+0xc",
    "+0x194",
    "+0x128",
]

[[cheat]]
id = "happy"
name = "happy"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 100

[cheat.locator]
find = "static"
module = "mono.dll"
offset = "0x20a90c"
hops = [
    "+0xb0",
    "+0xc",
    "+0x194",
    "+0x124",
]
