[game]
name = "The Evil Within [Final]"
exe = "evilwithin.exe"
notes = "Converted from a Cheat Engine table by XxRaPiD4K3LLERxX. Source: https://fearlessrevolution.com/viewtopic.php?t=1071"
verified = []
author = "XxRaPiD4K3LLERxX"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "current-green-gel"
name = "Current Green Gel"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x9acd1c8"
hops = [
    "+0x390",
    "+0x30",
    "+0x20",
    "+0x70",
    "+0x10",
]

[[cheat]]
id = "health"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x27b2530"
hops = [
    "+0x3b8",
    "+0x320",
    "+0x30",
    "+0x2f8",
    "+0x544",
]

[[cheat]]
id = "health-2"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x27b2630"
hops = [
    "+0xb8",
    "+0x490",
    "+0x170",
    "+0x2f8",
    "+0x544",
]

[[cheat]]
id = "do-not-use"
name = "DO NOT USE"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : EvilWithin.exe
  Version: 
  Date   : 2016-01-21
  Author : xxdem

  This script does blah blah blah
}

[ENABLE]


aobscanmodule(unlimitedhealthv2,evilwithin.exe,F3 0F 11 89 C4 08 00 00) // should be unique
alloc(newmem,$1000,"evilwithin.exe"+886E18)

label(code)
label(return)

newmem:

code:
  mov eax, 99
  jmp return

unlimitedhealthv2:
  jmp code
  nop
  nop
  nop
return:
registersymbol(unlimitedhealthv2)

[DISABLE]

unlimitedhealthv2:
  db F3 0F 11 89 C4 08 00 00

unregistersymbol(unlimitedhealthv2)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "evilwithin.exe"+886E18

"evilwithin.exe"+886DEF: CC                             -  int 3 
"evilwithin.exe"+886DF0: F3 0F 10 05 78 0A C1 00        -  movss xmm0,[evilwithin.exe+1497870]
"evilwithin.exe"+886DF8: 0F 2F C1                       -  comiss xmm0,xmm1
"evilwithin.exe"+886DFB: 76 0B                          -  jna evilwithin.exe+886E08
"evilwithin.exe"+886DFD: C7 81 C4 08 00 00 00 C0 79 C4  -  mov [rcx+000008C4],C479C000
"evilwithin.exe"+886E07: C3                             -  ret 
"evilwithin.exe"+886E08: F3 0F 10 81 C0 08 00 00        -  movss xmm0,[rcx+000008C0]
"evilwithin.exe"+886E10: 0F 2F C1                       -  comiss xmm0,xmm1
"evilwithin.exe"+886E13: 77 03                          -  ja evilwithin.exe+886E18
"evilwithin.exe"+886E15: 0F 28 C8                       -  movaps xmm1,xmm0
// ---------- INJECTING HERE ----------
"evilwithin.exe"+886E18: F3 0F 11 89 C4 08 00 00        -  movss [rcx+000008C4],xmm1
// ---------- DONE INJECTING  ----------
"evilwithin.exe"+886E20: C3                             -  ret 
"evilwithin.exe"+886E21: CC                             -  int 3 
"evilwithin.exe"+886E22: CC                             -  int 3 
"evilwithin.exe"+886E23: CC                             -  int 3 
"evilwithin.exe"+886E24: CC                             -  int 3 
"evilwithin.exe"+886E25: CC                             -  int 3 
"evilwithin.exe"+886E26: CC                             -  int 3 
"evilwithin.exe"+886E27: CC                             -  int 3 
"evilwithin.exe"+886E28: CC                             -  int 3 
"evilwithin.exe"+886E29: CC                             -  int 3 
}"""

[[cheat]]
id = "sets-the-value-to-99"
name = "Sets the value to 99"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x27d2ba0"
hops = [
    "+0x8",
    "+0x600",
    "+0x628",
    "+0x80",
    "+0x10",
]

[[cheat]]
id = "sets-the-value-to-99-2"
name = "Sets the value to 99"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x9acd1c8"
hops = [
    "+0x2f8",
    "+0x7b8",
    "+0x20",
    "+0xf0",
    "+0x10",
]

[[cheat]]
id = "handgun-stock-ammo"
name = "Handgun Stock Ammo"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x9acd1c0"
hops = [
    "+0x2c0",
    "+0x140",
    "+0x650",
    "+0xc0",
    "+0x10",
]

[[cheat]]
id = "unlimited-locker-key"
name = "Unlimited Locker Key"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : EvilWithin.exe
  Version: 
  Date   : 2015-12-28
  Author : xxdem

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(lockerkeys,evilwithin.exe,01 51 10 8B 51 18) // should be unique
alloc(newmem,$1000,"evilwithin.exe"+7C4E00)

label(code)
label(return)

newmem:

code:
  //add [rcx+10],edx
  //mov edx,[rcx+18]
  jmp return

lockerkeys:
  jmp code
  nop
return:
registersymbol(lockerkeys)

[DISABLE]

lockerkeys:
  db 01 51 10 8B 51 18

unregistersymbol(lockerkeys)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "evilwithin.exe"+7C4E00

"evilwithin.exe"+7C4DE4: 48 85 C0                 -  test rax,rax
"evilwithin.exe"+7C4DE7: 75 02                    -  jne evilwithin.exe+7C4DEB
"evilwithin.exe"+7C4DE9: F3 C3                    - repe  ret 
"evilwithin.exe"+7C4DEB: 48 8B 40 08              -  mov rax,[rax+08]
"evilwithin.exe"+7C4DEF: 48 8B 88 A0 02 00 00     -  mov rcx,[rax+000002A0]
"evilwithin.exe"+7C4DF6: 8B 81 50 02 00 00        -  mov eax,[rcx+00000250]
"evilwithin.exe"+7C4DFC: C3                       -  ret 
"evilwithin.exe"+7C4DFD: CC                       -  int 3 
"evilwithin.exe"+7C4DFE: CC                       -  int 3 
"evilwithin.exe"+7C4DFF: CC                       -  int 3 
// ---------- INJECTING HERE ----------
"evilwithin.exe"+7C4E00: 01 51 10                 -  add [rcx+10],edx
"evilwithin.exe"+7C4E03: 8B 51 18                 -  mov edx,[rcx+18]
// ---------- DONE INJECTING  ----------
"evilwithin.exe"+7C4E06: 8B 41 10                 -  mov eax,[rcx+10]
"evilwithin.exe"+7C4E09: 85 D2                    -  test edx,edx
"evilwithin.exe"+7C4E0B: 79 1E                    -  jns evilwithin.exe+7C4E2B
"evilwithin.exe"+7C4E0D: 48 8B 51 08              -  mov rdx,[rcx+08]
"evilwithin.exe"+7C4E11: 44 0F B7 82 DC 01 00 00  -  movzx r8d,word ptr [rdx+000001DC]
"evilwithin.exe"+7C4E19: 66 45 85 C0              -  test r8w,r8w
"evilwithin.exe"+7C4E1D: 78 06                    -  js evilwithin.exe+7C4E25
"evilwithin.exe"+7C4E1F: 41 0F BF D0              -  movsx edx,r8w
"evilwithin.exe"+7C4E23: EB 06                    -  jmp evilwithin.exe+7C4E2B
"evilwithin.exe"+7C4E25: 8B 92 04 02 00 00        -  mov edx,[rdx+00000204]
}"""

[[cheat]]
id = "unlimited-ammo-loaded-backup-script"
name = "Unlimited Ammo Loaded (Backup Script)"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : EvilWithin.exe
  Version: 
  Date   : 2015-12-31
  Author : xxdem

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(unlimitedammoloaded,evilwithin.exe,10 8B 41 10 85 D2) // should be unique
alloc(newmem,$1000,"evilwithin.exe"+7C37CE)

label(code)
label(return)

newmem:

code:
  //mov eax,[rcx+10]
  //test edx,edx
  jmp return

unlimitedammoloaded+01:
  jmp code
return:
registersymbol(unlimitedammoloaded)

[DISABLE]

unlimitedammoloaded+01:
  db 8B 41 10 85 D2

unregistersymbol(unlimitedammoloaded)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "evilwithin.exe"+7C37CE

"evilwithin.exe"+7C37A8: 48 85 C9                 -  test rcx,rcx
"evilwithin.exe"+7C37AB: 74 56                    -  je evilwithin.exe+7C3803
"evilwithin.exe"+7C37AD: 39 35 E5 A0 2F 09        -  cmp [evilwithin.exe+9ABD898],esi
"evilwithin.exe"+7C37B3: 75 4E                    -  jne evilwithin.exe+7C3803
"evilwithin.exe"+7C37B5: 48 8B 47 08              -  mov rax,[rdi+08]
"evilwithin.exe"+7C37B9: 40 38 B0 C0 03 00 00     -  cmp [rax+000003C0],sil
"evilwithin.exe"+7C37C0: 75 41                    -  jne evilwithin.exe+7C3803
"evilwithin.exe"+7C37C2: 8B 80 CC 03 00 00        -  mov eax,[rax+000003CC]
"evilwithin.exe"+7C37C8: 8B 51 18                 -  mov edx,[rcx+18]
"evilwithin.exe"+7C37CB: 29 41 10                 -  sub [rcx+10],eax
// ---------- INJECTING HERE ----------
"evilwithin.exe"+7C37CE: 8B 41 10                 -  mov eax,[rcx+10]
"evilwithin.exe"+7C37D1: 85 D2                    -  test edx,edx
// ---------- DONE INJECTING  ----------
"evilwithin.exe"+7C37D3: 79 1E                    -  jns evilwithin.exe+7C37F3
"evilwithin.exe"+7C37D5: 48 8B 51 08              -  mov rdx,[rcx+08]
"evilwithin.exe"+7C37D9: 44 0F B7 82 DC 01 00 00  -  movzx r8d,word ptr [rdx+000001DC]
"evilwithin.exe"+7C37E1: 66 45 85 C0              -  test r8w,r8w
"evilwithin.exe"+7C37E5: 78 06                    -  js evilwithin.exe+7C37ED
"evilwithin.exe"+7C37E7: 41 0F BF D0              -  movsx edx,r8w
"evilwithin.exe"+7C37EB: EB 06                    -  jmp evilwithin.exe+7C37F3
"evilwithin.exe"+7C37ED: 8B 92 04 02 00 00        -  mov edx,[rdx+00000204]
"evilwithin.exe"+7C37F3: 85 C0                    -  test eax,eax
"evilwithin.exe"+7C37F5: 79 04                    -  jns evilwithin.exe+7C37FB
}"""

[[cheat]]
id = "unlimited-ammo-loaded"
name = "Unlimited Ammo Loaded"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : EvilWithin.exe
  Version: 
  Date   : 2015-12-31
  Author : xxdem

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(unlimitedammoloaded,evilwithin.exe,29 41 10 8B 41 10) // should be unique
alloc(newmem,$1000,"evilwithin.exe"+7C37CB)

label(code)
label(return)

newmem:

code:
  //sub [rcx+10],eax
  //mov eax,[rcx+10]
  jmp return

unlimitedammoloaded:
  jmp code
  nop
return:
registersymbol(unlimitedammoloaded)

[DISABLE]

unlimitedammoloaded:
  db 29 41 10 8B 41 10

unregistersymbol(unlimitedammoloaded)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "evilwithin.exe"+7C37CB

"evilwithin.exe"+7C37A6: 75 5B                    -  jne evilwithin.exe+7C3803
"evilwithin.exe"+7C37A8: 48 85 C9                 -  test rcx,rcx
"evilwithin.exe"+7C37AB: 74 56                    -  je evilwithin.exe+7C3803
"evilwithin.exe"+7C37AD: 39 35 E5 A0 2F 09        -  cmp [evilwithin.exe+9ABD898],esi
"evilwithin.exe"+7C37B3: 75 4E                    -  jne evilwithin.exe+7C3803
"evilwithin.exe"+7C37B5: 48 8B 47 08              -  mov rax,[rdi+08]
"evilwithin.exe"+7C37B9: 40 38 B0 C0 03 00 00     -  cmp [rax+000003C0],sil
"evilwithin.exe"+7C37C0: 75 41                    -  jne evilwithin.exe+7C3803
"evilwithin.exe"+7C37C2: 8B 80 CC 03 00 00        -  mov eax,[rax+000003CC]
"evilwithin.exe"+7C37C8: 8B 51 18                 -  mov edx,[rcx+18]
// ---------- INJECTING HERE ----------
"evilwithin.exe"+7C37CB: 29 41 10                 -  sub [rcx+10],eax
"evilwithin.exe"+7C37CE: 8B 41 10                 -  mov eax,[rcx+10]
// ---------- DONE INJECTING  ----------
"evilwithin.exe"+7C37D1: 85 D2                    -  test edx,edx
"evilwithin.exe"+7C37D3: 79 1E                    -  jns evilwithin.exe+7C37F3
"evilwithin.exe"+7C37D5: 48 8B 51 08              -  mov rdx,[rcx+08]
"evilwithin.exe"+7C37D9: 44 0F B7 82 DC 01 00 00  -  movzx r8d,word ptr [rdx+000001DC]
"evilwithin.exe"+7C37E1: 66 45 85 C0              -  test r8w,r8w
"evilwithin.exe"+7C37E5: 78 06                    -  js evilwithin.exe+7C37ED
"evilwithin.exe"+7C37E7: 41 0F BF D0              -  movsx edx,r8w
"evilwithin.exe"+7C37EB: EB 06                    -  jmp evilwithin.exe+7C37F3
"evilwithin.exe"+7C37ED: 8B 92 04 02 00 00        -  mov edx,[rdx+00000204]
"evilwithin.exe"+7C37F3: 85 C0                    -  test eax,eax
}"""

[[cheat]]
id = "auto-assemble-script"
name = "Auto Assemble script"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game   : EvilWithin.exe
  Version: 
  Date   : 2016-01-03
  Author : xxdem

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(unlimitedstamina,evilwithin.exe,F3 41 0F 11 45 04 F3 0F) // should be unique
alloc(newmem,$1000,"evilwithin.exe"+3600CD)

label(code)
label(return)

newmem:

code:
  //movss [r13+04],xmm0
  jmp return

unlimitedstamina:
  jmp code
  nop
return:
registersymbol(unlimitedstamina)

[DISABLE]

unlimitedstamina:
  db F3 41 0F 11 45 04

unregistersymbol(unlimitedstamina)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "evilwithin.exe"+3600CD

"evilwithin.exe"+3600A5: F3 41 0F 11 45 00        -  movss [r13+00],xmm0
"evilwithin.exe"+3600AB: 66 0F 6E C5              -  movd xmm0,ebp
"evilwithin.exe"+3600AF: F3 41 0F 11 4D 0C        -  movss [r13+0C],xmm1
"evilwithin.exe"+3600B5: 48 8B 6C 24 30           -  mov rbp,[rsp+30]
"evilwithin.exe"+3600BA: 03 C1                    -  add eax,ecx
"evilwithin.exe"+3600BC: 66 41 0F 6E CB           -  movd xmm1,r11d
"evilwithin.exe"+3600C1: 0F 5B C0                 -  cvtdq2ps xmm0,xmm0
"evilwithin.exe"+3600C4: 33 C1                    -  xor eax,ecx
"evilwithin.exe"+3600C6: F3 0F 59 C2              -  mulss xmm0,xmm2
"evilwithin.exe"+3600CA: 0F 5B C9                 -  cvtdq2ps xmm1,xmm1
// ---------- INJECTING HERE ----------
"evilwithin.exe"+3600CD: F3 41 0F 11 45 04        -  movss [r13+04],xmm0
// ---------- DONE INJECTING  ----------
"evilwithin.exe"+3600D3: F3 0F 59 0D C9 70 14 01  -  mulss xmm1,[evilwithin.exe+14A71A4]
"evilwithin.exe"+3600DB: 66 0F 6E C6              -  movd xmm0,esi
"evilwithin.exe"+3600DF: 48 8B 74 24 38           -  mov rsi,[rsp+38]
"evilwithin.exe"+3600E4: F3 41 0F 11 4D 10        -  movss [r13+10],xmm1
"evilwithin.exe"+3600EA: 0F 5B C0                 -  cvtdq2ps xmm0,xmm0
"evilwithin.exe"+3600ED: F3 0F 59 C2              -  mulss xmm0,xmm2
"evilwithin.exe"+3600F1: F3 41 0F 11 45 08        -  movss [r13+08],xmm0
"evilwithin.exe"+3600F7: 66 0F 6E C0              -  movd xmm0,eax
"evilwithin.exe"+3600FB: 0F 5B C0                 -  cvtdq2ps xmm0,xmm0
"evilwithin.exe"+3600FE: F3 0F 59 05 9E 70 14 01  -  mulss xmm0,[evilwithin.exe+14A71A4]
}"""

[[cheat]]
id = "health-3"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x27d2d88"
hops = [
    "+0x530",
    "+0x8",
    "+0x198",
    "+0xa0",
    "+0x39c",
]

[[cheat]]
id = "health-4"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x28224b0"
hops = [
    "+0x8",
    "+0x700",
    "+0x2a8",
    "+0x200",
    "+0x39c",
]

[[cheat]]
id = "health-5"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x9a67d88"
hops = [
    "+0x460",
    "+0x58",
    "+0x548",
    "+0x0",
    "+0x39c",
]

[[cheat]]
id = "current-coins"
name = "Current Coins"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "evilwithin.exe"
offset = "0x9a34960"
hops = [
    "+0x8",
    "+0x680",
    "+0x628",
    "+0x40",
    "+0x10",
]
