[game]
name = "Butcher"
exe = "butcher.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=1454"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "on-off"
name = "ON/off "
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:off",
    "1:ON",
]

[cheat.locator]
find = "symbol"
symbol = "ActorHurtMessage"
hops = []

[[cheat]]
id = "hurt-mul-to-player"
name = "hurt mul, to player "
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0.25

[cheat.locator]
find = "symbol"
symbol = "ActorHurtMessage"
hops = []

[[cheat]]
id = "hurt-mul-from-player"
name = "hurt mul, from player "
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 4

[cheat.locator]
find = "symbol"
symbol = "ActorHurtMessage"
hops = []

[[cheat]]
id = "on-off-rapid"
name = "ON/off Rapid"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:off",
    "1:ON",
]

[cheat.locator]
find = "symbol"
symbol = "RapidAmmo"
hops = []

[[cheat]]
id = "rapid-rate"
name = "rapid rate"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 7

[cheat.locator]
find = "symbol"
symbol = "RapidAmmo"
hops = []

[[cheat]]
id = "on-off-ammo"
name = "ON/off Ammo"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:off",
    "1:ON",
]

[cheat.locator]
find = "symbol"
symbol = "RapidAmmo"
hops = []

[[cheat]]
id = "minimum-ammo"
name = "minimum Ammo"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 8

[cheat.locator]
find = "symbol"
symbol = "RapidAmmo"
hops = []

[[cheat]]
id = "on-off-minhp"
name = "ON/off minHp"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:off",
    "1:ON",
]

[cheat.locator]
find = "symbol"
symbol = "PlayerUpdate"
hops = []

[[cheat]]
id = "min-hp-amount"
name = "min Hp Amount"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 150

[cheat.locator]
find = "symbol"
symbol = "PlayerUpdate"
hops = []

[[cheat]]
id = "on-off-jump"
name = "ON/off Jump"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:off",
    "1:ON",
]

[cheat.locator]
find = "symbol"
symbol = "PlayerUpdate"
hops = []
