[game]
name = "ARMA 3 Cheat Engine"
exe = "arma3_x64.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=9432"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "activate-trainer"
name = "Activate Trainer"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : arma3_x64.exe
  Version: 
  Date   : 2017-05-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(playeridentifier,Arma3_x64.exe,48 8B 8F 58 01 00 00 48 8B 87 D0 00 00 00 89) // should be unique
alloc(newmem,$1000,"Arma3_x64.exe"+5D1DC5)

label(code)
label(return)
label(playerstruct)
registersymbol(playerstruct)
newmem:
mov [playerstruct], rdi
code:
  mov rcx,[rdi+00000158]
  jmp return

playerstruct:
dq 0

playeridentifier:
  jmp newmem
  nop
  nop
return:
registersymbol(playeridentifier)

[DISABLE]

playeridentifier:
  db 48 8B 8F 58 01 00 00

unregistersymbol(playeridentifier)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Arma3_x64.exe"+5D1DC5

"Arma3_x64.exe"+5D1D8E: 48 8B CF                    -  mov rcx,rdi
"Arma3_x64.exe"+5D1D91: E8 7A 1D 00 00              -  call Arma3_x64.exe+5D3B10
"Arma3_x64.exe"+5D1D96: 84 C0                       -  test al,al
"Arma3_x64.exe"+5D1D98: 0F 84 D7 12 00 00           -  je Arma3_x64.exe+5D3075
"Arma3_x64.exe"+5D1D9E: 48 8B 55 98                 -  mov rdx,[rbp-68]
"Arma3_x64.exe"+5D1DA2: 44 0F 29 8C 24 50 02 00 00  -  movaps [rsp+00000250],xmm9
"Arma3_x64.exe"+5D1DAB: 48 8B CF                    -  mov rcx,rdi
"Arma3_x64.exe"+5D1DAE: 44 0F 29 A4 24 20 02 00 00  -  movaps [rsp+00000220],xmm12
"Arma3_x64.exe"+5D1DB7: 44 0F 29 AC 24 10 02 00 00  -  movaps [rsp+00000210],xmm13
"Arma3_x64.exe"+5D1DC0: E8 7B 2A 00 00              -  call Arma3_x64.exe+5D4840
// ---------- INJECTING HERE ----------
"Arma3_x64.exe"+5D1DC5: 48 8B 8F 58 01 00 00        -  mov rcx,[rdi+00000158]
// ---------- DONE INJECTING  ----------
"Arma3_x64.exe"+5D1DCC: 48 8B 87 D0 00 00 00        -  mov rax,[rdi+000000D0]
"Arma3_x64.exe"+5D1DD3: 89 75 88                    -  mov [rbp-78],esi
"Arma3_x64.exe"+5D1DD6: 48 85 C9                    -  test rcx,rcx
"Arma3_x64.exe"+5D1DD9: 75 07                       -  jne Arma3_x64.exe+5D1DE2
"Arma3_x64.exe"+5D1DDB: 48 8B 8F 50 01 00 00        -  mov rcx,[rdi+00000150]
"Arma3_x64.exe"+5D1DE2: 8B 90 C8 00 00 00           -  mov edx,[rax+000000C8]
"Arma3_x64.exe"+5D1DE8: E8 F3 0B FF FF              -  call Arma3_x64.exe+5C29E0
"Arma3_x64.exe"+5D1DED: 48 8B 8F 50 01 00 00        -  mov rcx,[rdi+00000150]
"Arma3_x64.exe"+5D1DF4: 48 8B 97 D0 00 00 00        -  mov rdx,[rdi+000000D0]
"Arma3_x64.exe"+5D1DFB: 4C 8B 81 40 1D 00 00        -  mov r8,[rcx+00001D40]
}"""

[[cheat]]
id = "unlimited-health"
name = "Unlimited Health"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : arma3_x64.exe
  Version: 
  Date   : 2017-05-27
  Author : STN

  This script does blah blah blah
}

{ Game   : arma3_x64.exe
  Version: 
  Date   : 2017-05-27
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(health,Arma3_x64.exe,0F 2F F0 F3 0F 11 31 72) // should be unique
alloc(newmem,$1000,"Arma3_x64.exe"+CC3B8D)

label(code)
label(return)

newmem:
cmp [playerstruct],rbx
jne code
xorps xmm6,xmm6
code:
  comiss xmm6,xmm0
  movss [rcx],xmm6
  jmp return

health:
  jmp newmem
  nop
  nop
return:
registersymbol(health)

aobscanmodule(healthsecond,Arma3_x64.exe,F3 0F 11 34 A8 E8) // should be unique
label(code2)
label(return2)

newmem+200:
cmp [playerstruct],rdi
jne code2
xorps xmm6,xmm6
code2:
//  movss [rax+rbp*4],xmm6
db F3 0F 11 34 A8
  jmp return2

healthsecond:
  jmp newmem+200
return2:
registersymbol(healthsecond)

[DISABLE]

health:
  db 0F 2F F0 F3 0F 11 31

unregistersymbol(health)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Arma3_x64.exe"+CC3B8D

"Arma3_x64.exe"+CC3B66: EB 03                    -  jmp Arma3_x64.exe+CC3B6B
"Arma3_x64.exe"+CC3B68: 48 8B C1                 -  mov rax,rcx
"Arma3_x64.exe"+CC3B6B: 48 8B D0                 -  mov rdx,rax
"Arma3_x64.exe"+CC3B6E: 48 8B CF                 -  mov rcx,rdi
"Arma3_x64.exe"+CC3B71: E8 6A AC FF FF           -  call Arma3_x64.exe+CBE7E0
"Arma3_x64.exe"+CC3B76: 48 8B 03                 -  mov rax,[rbx]
"Arma3_x64.exe"+CC3B79: 48 8B CB                 -  mov rcx,rbx
"Arma3_x64.exe"+CC3B7C: FF 90 A8 07 00 00        -  call qword ptr [rax+000007A8]
"Arma3_x64.exe"+CC3B82: 48 8B 0F                 -  mov rcx,[rdi]
"Arma3_x64.exe"+CC3B85: F3 0F 10 05 F3 AF 1E 01  -  movss xmm0,[Arma3_x64.exe+1EAEB80]
// ---------- INJECTING HERE ----------
"Arma3_x64.exe"+CC3B8D: 0F 2F F0                 -  comiss xmm6,xmm0
"Arma3_x64.exe"+CC3B90: F3 0F 11 31              -  movss [rcx],xmm6
// ---------- DONE INJECTING  ----------
"Arma3_x64.exe"+CC3B94: 72 03                    -  jb godmode2
"Arma3_x64.exe"+CC3B96: 0F 28 F0                 -  movaps xmm6,xmm0
"Arma3_x64.exe"+CC3B99: E9 62 C4 30 FF           -  jmp 011F0000
"Arma3_x64.exe"+CC3B9E: 90                       -  nop 
"Arma3_x64.exe"+CC3B9F: 75 5E                    -  jne Arma3_x64.exe+CC3BFF
"Arma3_x64.exe"+CC3BA1: 48 8B 03                 -  mov rax,[rbx]
"Arma3_x64.exe"+CC3BA4: 48 8B CB                 -  mov rcx,rbx
"Arma3_x64.exe"+CC3BA7: FF 90 A8 07 00 00        -  call qword ptr [rax+000007A8]
"Arma3_x64.exe"+CC3BAD: 84 C0                    -  test al,al
"Arma3_x64.exe"+CC3BAF: 74 4E                    -  je Arma3_x64.exe+CC3BFF
}
healthsecond:
  db F3 0F 11 34 A8

unregistersymbol(healthsecond)
{
// ORIGINAL CODE - INJECTION POINT: "Arma3_x64.exe"+B4C002

"Arma3_x64.exe"+B4BFD6: F3 44 0F 10 14 A8           -  movss xmm10,[rax+rbp*4]
"Arma3_x64.exe"+B4BFDC: 0F 84 A6 00 00 00           -  je Arma3_x64.exe+B4C088
"Arma3_x64.exe"+B4BFE2: 8B D5                       -  mov edx,ebp
"Arma3_x64.exe"+B4BFE4: 48 8B CF                    -  mov rcx,rdi
"Arma3_x64.exe"+B4BFE7: 44 0F 29 4C 24 30           -  movaps [rsp+30],xmm9
"Arma3_x64.exe"+B4BFED: E8 2E 75 00 00              -  call Arma3_x64.exe+B53520
"Arma3_x64.exe"+B4BFF2: 48 8B 87 70 02 00 00        -  mov rax,[rdi+00000270]
"Arma3_x64.exe"+B4BFF9: 8B D5                       -  mov edx,ebp
"Arma3_x64.exe"+B4BFFB: 48 8B CF                    -  mov rcx,rdi
"Arma3_x64.exe"+B4BFFE: 44 0F 28 C8                 -  movaps xmm9,xmm0
// ---------- INJECTING HERE ----------
"Arma3_x64.exe"+B4C002: F3 0F 11 34 A8              -  movss [rax+rbp*4],xmm6
// ---------- DONE INJECTING  ----------
"Arma3_x64.exe"+B4C007: E8 14 75 00 00              -  call Arma3_x64.exe+B53520
"Arma3_x64.exe"+B4C00C: 44 0F 28 C0                 -  movaps xmm8,xmm0
"Arma3_x64.exe"+B4C010: F3 0F 10 05 64 26 36 01     -  movss xmm0,[Arma3_x64.exe+1EAE67C]
"Arma3_x64.exe"+B4C018: 44 0F 2F C8                 -  comiss xmm9,xmm0
"Arma3_x64.exe"+B4C01C: 73 06                       -  jae Arma3_x64.exe+B4C024
"Arma3_x64.exe"+B4C01E: 44 0F 2F C0                 -  comiss xmm8,xmm0
"Arma3_x64.exe"+B4C022: 73 28                       -  jae Arma3_x64.exe+B4C04C
"Arma3_x64.exe"+B4C024: F3 0F 10 05 74 26 36 01     -  movss xmm0,[Arma3_x64.exe+1EAE6A0]
"Arma3_x64.exe"+B4C02C: 44 0F 2F C8                 -  comiss xmm9,xmm0
"Arma3_x64.exe"+B4C030: 73 06                       -  jae Arma3_x64.exe+B4C038
}"""

[[cheat]]
id = "unlimited-stamina"
name = "Unlimited Stamina"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game   : arma3_x64.exe
  Version: 
  Date   : 2017-05-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(stamina,Arma3_x64.exe,F3 44 0F 10 97 94 10 00 00) // should be unique
alloc(newmem,$1000,"Arma3_x64.exe"+7B1168)

label(code)
label(return)

newmem:
//mov [rdi+00001094],(float)47
mov [rdi+00001094],423C0000
code:
  movss xmm10,[rdi+00001094]
  jmp return

stamina:
  jmp newmem
  nop
  nop
  nop
  nop
return:
registersymbol(stamina)

[DISABLE]

stamina:
  db F3 44 0F 10 97 94 10 00 00

unregistersymbol(stamina)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Arma3_x64.exe"+7B1168

"Arma3_x64.exe"+7B113C: F3 0F 10 B0 98 00 00 00     -  movss xmm6,[rax+00000098]
"Arma3_x64.exe"+7B1144: EB 08                       -  jmp Arma3_x64.exe+7B114E
"Arma3_x64.exe"+7B1146: F3 0F 10 35 EE D5 6F 01     -  movss xmm6,[Arma3_x64.exe+1EAE73C]
"Arma3_x64.exe"+7B114E: E9 AD EE 83 FF              -  jmp 01210000
"Arma3_x64.exe"+7B1153: 90                          -  nop 
"Arma3_x64.exe"+7B1154: 90                          -  nop 
"Arma3_x64.exe"+7B1155: 48 85 C0                    -  test rax,rax
"Arma3_x64.exe"+7B1158: 75 07                       -  jne Arma3_x64.exe+7B1161
"Arma3_x64.exe"+7B115A: 48 8B 87 50 01 00 00        -  mov rax,[rdi+00000150]
"Arma3_x64.exe"+7B1161: 48 8B 80 48 1D 00 00        -  mov rax,[rax+00001D48]
// ---------- INJECTING HERE ----------
"Arma3_x64.exe"+7B1168: F3 44 0F 10 97 94 10 00 00  -  movss xmm10,[rdi+00001094]
// ---------- DONE INJECTING  ----------
"Arma3_x64.exe"+7B1171: 48 8B CF                    -  mov rcx,rdi
"Arma3_x64.exe"+7B1174: F3 44 0F 5E 50 18           -  divss xmm10,[rax+18]
"Arma3_x64.exe"+7B117A: E8 71 D8 35 00              -  call Arma3_x64.exe+B0E9F0
"Arma3_x64.exe"+7B117F: 48 8B C8                    -  mov rcx,rax
"Arma3_x64.exe"+7B1182: E8 F9 DD AF 00              -  call Arma3_x64.exe+12AEF80
"Arma3_x64.exe"+7B1187: 48 8D 93 E4 09 00 00        -  lea rdx,[rbx+000009E4]
"Arma3_x64.exe"+7B118E: 48 8D 0D B3 D8 DA 01        -  lea rcx,[Arma3_x64.exe+255EA48]
"Arma3_x64.exe"+7B1195: 44 0F 28 C8                 -  movaps xmm9,xmm0
"Arma3_x64.exe"+7B1199: F3 44 0F 59 CE              -  mulss xmm9,xmm6
"Arma3_x64.exe"+7B119E: 41 0F 28 F2                 -  movaps xmm6,xmm10
}"""

[[cheat]]
id = "no-reload"
name = "No Reload"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
{ Game   : arma3_x64.exe
  Version: 
  Date   : 2017-05-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(ammo,Arma3_x64.exe,89 97 90 00 00 00 81) // should be unique
alloc(newmem,$1000,"Arma3_x64.exe"+C866BE)

label(code)
label(return)

newmem:
cmp [playerstruct],rbp
jne code
mov edx, #99
mov [rdi+00000090],edx
jmp return
code:
xor edx, edx
  mov [rdi+00000090],edx
  jmp return

ammo:
  jmp newmem
  nop
return:
registersymbol(ammo)

[DISABLE]

ammo:
  db 89 97 90 00 00 00

unregistersymbol(ammo)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Arma3_x64.exe"+C866BE

"Arma3_x64.exe"+C86697: 8B 5E 28                          -  mov ebx,[rsi+28]
"Arma3_x64.exe"+C8669A: 48 8B CF                          -  mov rcx,rdi
"Arma3_x64.exe"+C8669D: FF 90 D8 00 00 00                 -  call qword ptr [rax+000000D8]
"Arma3_x64.exe"+C866A3: 8B 97 94 00 00 00                 -  mov edx,[rdi+00000094]
"Arma3_x64.exe"+C866A9: 3B D8                             -  cmp ebx,eax
"Arma3_x64.exe"+C866AB: 0F 4F D8                          -  cmovg ebx,eax
"Arma3_x64.exe"+C866AE: 03 97 8C 00 00 00                 -  add edx,[rdi+0000008C]
"Arma3_x64.exe"+C866B4: 81 F2 B6 C8 BA BA                 -  xor edx,BABAC8B6
"Arma3_x64.exe"+C866BA: 8B C3                             -  mov eax,ebx
"Arma3_x64.exe"+C866BC: 2B D3                             -  sub edx,ebx
// ---------- INJECTING HERE ----------
"Arma3_x64.exe"+C866BE: 89 97 90 00 00 00                 -  mov [rdi+00000090],edx
// ---------- DONE INJECTING  ----------
"Arma3_x64.exe"+C866C4: 81 F2 B6 C8 BA BA                 -  xor edx,BABAC8B6
"Arma3_x64.exe"+C866CA: 8B CA                             -  mov ecx,edx
"Arma3_x64.exe"+C866CC: D1 F9                             -  sar ecx,1
"Arma3_x64.exe"+C866CE: 2B D1                             -  sub edx,ecx
"Arma3_x64.exe"+C866D0: 89 8F 8C 00 00 00                 -  mov [rdi+0000008C],ecx
"Arma3_x64.exe"+C866D6: 89 97 94 00 00 00                 -  mov [rdi+00000094],edx
"Arma3_x64.exe"+C866DC: 48 8B 5C 24 30                    -  mov rbx,[rsp+30]
"Arma3_x64.exe"+C866E1: 48 8B 6C 24 38                    -  mov rbp,[rsp+38]
"Arma3_x64.exe"+C866E6: 48 8B 74 24 40                    -  mov rsi,[rsp+40]
"Arma3_x64.exe"+C866EB: 48 83 C4 20                       -  add rsp,20
}"""
