[game]
name = "Victoria 3 table v: 1.0 CT"
exe = "victoria3.exe"
notes = "Converted from a Cheat Engine table by N3rveMods. Source: https://fearlessrevolution.com/viewtopic.php?t=31815"
verified = []
author = "N3rveMods"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "fast-interest"
name = "Fast Interest"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]


aobscanmodule(fastinterest_Aob,victoria3.exe,74 04 B1 01 EB 25 E8 * * * * 8B 48 08 B8 AB AA AA 2A 2B 4E 28 F7 E9 C1 FA 02 8B C2 C1 E8 1F) // should be unique

fastinterest_Aob:
  nop 2
registersymbol(fastinterest_Aob)

[DISABLE]

fastinterest_Aob:
  db 74 04

unregistersymbol(fastinterest_Aob)"""
