[game]
name = "Overload"
exe = "overload.exe"
notes = "Converted from a Cheat Engine table by Csimbi. Source: https://fearlessrevolution.com/viewtopic.php?t=8756"
verified = []
author = "Csimbi"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "benableinfiniteenergy"
name = "bEnableInfiniteEnergy"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:Disabled",
    "1:Enabled",
]

[cheat.locator]
find = "symbol"
symbol = "bEnableInfiniteEnergy"
hops = []

[[cheat]]
id = "benableinfinitearmour"
name = "bEnableInfiniteArmour"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:Disabled",
    "1:Enabled",
]

[cheat.locator]
find = "symbol"
symbol = "bEnableInfiniteArmour"
hops = []

[[cheat]]
id = "ixp"
name = "iXP"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i64"

[cheat.locator]
find = "symbol"
symbol = "pPlayerShip"
hops = [
    "+0x80",
    "+0x114",
]

[[cheat]]
id = "iupgradepoints"
name = "iUpgradePoints"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "pPlayerShip"
hops = [
    "+0x80",
    "+0x134",
]

[[cheat]]
id = "isuperupgradepoints"
name = "iSuperUpgradePoints"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "pPlayerShip"
hops = [
    "+0x80",
    "+0x138",
]

[[cheat]]
id = "drefiretimedecaymod"
name = "dRefireTimeDecayMod"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "symbol"
symbol = "dRefireTimeDecayMod"
hops = []

[[cheat]]
id = "ixp-2"
name = "iXP"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i64"

[cheat.locator]
find = "symbol"
symbol = "pPlayerShip"
hops = [
    "+0x80",
    "+0x11c",
]

[[cheat]]
id = "iupgradepoints-2"
name = "iUpgradePoints"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "pPlayerShip"
hops = [
    "+0x80",
    "+0x13c",
]

[[cheat]]
id = "isuperupgradepoints-2"
name = "iSuperUpgradePoints"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "pPlayerShip"
hops = [
    "+0x80",
    "+0x140",
]

[[cheat]]
id = "drefiretimedecaymod-2"
name = "dRefireTimeDecayMod"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "symbol"
symbol = "dRefireTimeDecayMod"
hops = []

[[cheat]]
id = "dflarelightrangemod"
name = "dFlareLightRangeMod"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "symbol"
symbol = "dFlareLightRangeMod"
hops = []
