[game]
name = "Train Sim World 6 Cheat Table (Made For Steam)"
exe = "trainsimworld.exe"
notes = "Converted from a Cheat Engine table by MrGoldGiver. Source: https://fearlessrevolution.com/viewtopic.php?t=38426"
verified = []
author = "MrGoldGiver"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "easy-ap-points"
name = "Easy AP Points"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanmodule(originalcode_2617,$process,8B 8B A4 02 00 00) //unique
registersymbol(originalcode_2617)
label(originalcode_2617Restore)
registersymbol(originalcode_2617Restore)
alloc(codecave,1024,$process)
label(code)
label(return)

codecave:



code:
add [rbx+2A4],#5000
mov ecx,[rbx+2A4]

jmp return

originalcode_2617Restore:
readmem(originalcode_2617,6)


originalcode_2617:
jmp codecave
nop 1

return:



[DISABLE]
originalcode_2617:
readmem(originalcode_2617Restore,6)

unregistersymbol(originalcode_2617)
unregistersymbol(originalcode_2617Restore)
dealloc(codecave)

{
\t INJECTION POINT: TrainSimWorld.png_get_uint_16+AC217A / 7FF7C8E9D78A

TrainSimWorld.exe+104D6D0:            48 89 5C 24 08 - mov [rsp+8],rbx
TrainSimWorld.exe+104D6D5:            48 89 6C 24 10 - mov [rsp+10],rbp
TrainSimWorld.exe+104D6DA:            48 89 74 24 18 - mov [rsp+18],rsi
TrainSimWorld.exe+104D6DF:                        57 - push rdi
TrainSimWorld.exe+104D6E0:               48 83 EC 60 - sub rsp,60 // 96
TrainSimWorld.exe+104D6E4:                  48 8B 01 - mov rax,[rcx]
TrainSimWorld.exe+104D6E7:                  48 8B FA - mov rdi,rdx
TrainSimWorld.exe+104D6EA:                  48 8B D9 - mov rbx,rcx
TrainSimWorld.exe+104D6ED:         FF 90 58 01 00 00 - call qword ptr [rax+158]
TrainSimWorld.exe+104D6F3:                  48 8B C8 - mov rcx,rax
TrainSimWorld.exe+104D6F6:            E8 05 2B FD FF - call 7FF7C8E70200
TrainSimWorld.exe+104D6FB:                     33 C9 - xor ecx,ecx
TrainSimWorld.exe+104D6FD:            48 89 4C 24 20 - mov [rsp+20],rcx
TrainSimWorld.exe+104D702:               48 63 70 08 - movsxd rsi,[rax+8]
TrainSimWorld.exe+104D706:                  48 8B 28 - mov rbp,[rax]
TrainSimWorld.exe+104D709:               89 74 24 28 - mov [rsp+28],esi
TrainSimWorld.exe+104D70D:                     85 F6 - test esi,esi
TrainSimWorld.exe+104D70F:                     75 06 - jne 7FF7C8E9D717
TrainSimWorld.exe+104D711:               89 4C 24 2C - mov [rsp+2C],ecx
TrainSimWorld.exe+104D715:                     EB 22 - jmp 7FF7C8E9D739
TrainSimWorld.exe+104D717:                  45 33 C0 - xor r8d,r8d
TrainSimWorld.exe+104D71A:            48 8D 4C 24 20 - lea rcx,[rsp+20]
TrainSimWorld.exe+104D71F:                     8B D6 - mov edx,esi
TrainSimWorld.exe+104D721:            E8 2A F3 78 FF - call 7FF7C862CA50
TrainSimWorld.exe+104D726:            48 8B 4C 24 20 - mov rcx,[rsp+20]
TrainSimWorld.exe+104D72B:                  4C 8B C6 - mov r8,rsi
TrainSimWorld.exe+104D72E:                  4D 03 C0 - add r8,r8
TrainSimWorld.exe+104D731:                  48 8B D5 - mov rdx,rbp
TrainSimWorld.exe+104D734:            E8 56 BF A8 02 - call 7FF7CB92968F
TrainSimWorld.exe+104D739:                  48 8B 03 - mov rax,[rbx]
TrainSimWorld.exe+104D73C:                  48 8B CB - mov rcx,rbx
TrainSimWorld.exe+104D73F:         FF 90 58 01 00 00 - call qword ptr [rax+158]
TrainSimWorld.exe+104D745:                  48 8B C8 - mov rcx,rax
TrainSimWorld.exe+104D748:            E8 83 2B FD FF - call 7FF7C8E702D0
TrainSimWorld.exe+104D74D:                  48 8B 08 - mov rcx,[rax]
TrainSimWorld.exe+104D750:            48 89 4C 24 30 - mov [rsp+30],rcx
TrainSimWorld.exe+104D755:               48 8B 48 08 - mov rcx,[rax+8]
TrainSimWorld.exe+104D759:            48 89 4C 24 38 - mov [rsp+38],rcx
TrainSimWorld.exe+104D75E:                  48 85 C9 - test rcx,rcx
TrainSimWorld.exe+104D761:                     74 04 - je 7FF7C8E9D767
TrainSimWorld.exe+104D763:               F0 FF 41 08 - lock inc dword ptr [rcx+8]
TrainSimWorld.exe+104D767:                  8B 40 10 - mov eax,[rax+10]
TrainSimWorld.exe+104D76A:               48 8D 4F 20 - lea rcx,[rdi+20]
TrainSimWorld.exe+104D76E:            48 8D 54 24 20 - lea rdx,[rsp+20]
TrainSimWorld.exe+104D773:               89 44 24 40 - mov [rsp+40],eax
TrainSimWorld.exe+104D777:            E8 D4 12 78 FF - call 7FF7C861EA50
TrainSimWorld.exe+104D77C:               48 8D 4F 30 - lea rcx,[rdi+30]
TrainSimWorld.exe+104D780:            48 8D 54 24 30 - lea rdx,[rsp+30]
TrainSimWorld.exe+104D785:            E8 36 B7 79 FF - call 7FF7C8638EC0
\t ---------- INJECTING HERE ----------
TrainSimWorld.exe+104D78A:         8B 8B A4 02 00 00 - mov ecx,[rbx+2A4]
\t ---------- DONE INJECTING  ----------
TrainSimWorld.exe+104D790:                     8B 17 - mov edx,[rdi]
TrainSimWorld.exe+104D792:                  8D 04 0A - lea eax,[rdx+rcx]
TrainSimWorld.exe+104D795:                     85 C0 - test eax,eax
TrainSimWorld.exe+104D797:                     79 06 - jns 7FF7C8E9D79F
TrainSimWorld.exe+104D799:                     8B D1 - mov edx,ecx
TrainSimWorld.exe+104D79B:                     F7 DA - neg edx
TrainSimWorld.exe+104D79D:                     89 17 - mov [rdi],edx
TrainSimWorld.exe+104D79F:      80 BB A0 02 00 00 00 - cmp byte ptr [rbx+2A0],0
TrainSimWorld.exe+104D7A6:         0F 84 91 00 00 00 - je 7FF7C8E9D83D
TrainSimWorld.exe+104D7AC:      48 63 AB B0 02 00 00 - movsxd rbp,[rbx+2B0]
TrainSimWorld.exe+104D7B3:                  8D 45 01 - lea eax,[rbp+1]
TrainSimWorld.exe+104D7B6:         89 83 B0 02 00 00 - mov [rbx+2B0],eax
TrainSimWorld.exe+104D7BC:         3B 83 B4 02 00 00 - cmp eax,[rbx+2B4]
TrainSimWorld.exe+104D7C2:                     7E 0E - jle 7FF7C8E9D7D2
TrainSimWorld.exe+104D7C4:                     8B D5 - mov edx,ebp
TrainSimWorld.exe+104D7C6:      48 8D 8B A8 02 00 00 - lea rcx,[rbx+2A8]
TrainSimWorld.exe+104D7CD:            E8 0E BC 7C FF - call 7FF7C86693E0
TrainSimWorld.exe+104D7D2:      48 8B 83 A8 02 00 00 - mov rax,[rbx+2A8]
TrainSimWorld.exe+104D7D9:   48 8D 0C ED 00 00 00 00 - lea rcx,[rbp*8]
TrainSimWorld.exe+104D7E1:                  48 03 CD - add rcx,rbp
TrainSimWorld.exe+104D7E4:                  48 8B D7 - mov rdx,rdi
TrainSimWorld.exe+104D7E7:               48 8D 0C C8 - lea rcx,[rax+rcx*8]
TrainSimWorld.exe+104D7EB:            E8 70 31 FF FF - call 7FF7C8E90960
TrainSimWorld.exe+104D7F0:                     8B 07 - mov eax,[rdi]
TrainSimWorld.exe+104D7F2:         01 83 A4 02 00 00 - add [rbx+2A4],eax
TrainSimWorld.exe+104D7F8:               48 8B 47 08 - mov rax,[rdi+8]
TrainSimWorld.exe+104D7FC:      44 8B 83 A4 02 00 00 - mov r8d,[rbx+2A4]
TrainSimWorld.exe+104D803:            48 89 44 24 48 - mov [rsp+48],rax
TrainSimWorld.exe+104D808:               48 8B 47 10 - mov rax,[rdi+10]
TrainSimWorld.exe+104D80C:            48 89 44 24 50 - mov [rsp+50],rax
TrainSimWorld.exe+104D811:                  48 85 C0 - test rax,rax
TrainSimWorld.exe+104D814:                     74 0B - je 7FF7C8E9D821
TrainSimWorld.exe+104D816:               F0 FF 40 08 - lock inc dword ptr [rax+8]
TrainSimWorld.exe+104D81A:      44 8B 83 A4 02 00 00 - mov r8d,[rbx+2A4]
TrainSimWorld.exe+104D821:                  8B 47 18 - mov eax,[rdi+18]
TrainSimWorld.exe+104D824:      48 8D 8B 48 09 00 00 - lea rcx,[rbx+948]
TrainSimWorld.exe+104D82B:                     8B 17 - mov edx,[rdi]
TrainSimWorld.exe+104D82D:            4C 8D 4C 24 48 - lea r9,[rsp+48]
TrainSimWorld.exe+104D832:               89 44 24 58 - mov [rsp+58],eax
TrainSimWorld.exe+104D836:            E8 75 1A 00 00 - call 7FF7C8E9F2B0
TrainSimWorld.exe+104D83B:                     8B 17 - mov edx,[rdi]
TrainSimWorld.exe+104D83D:                  48 8B CB - mov rcx,rbx
TrainSimWorld.exe+104D840:            E8 8B 02 00 00 - call 7FF7C8E9DAD0
TrainSimWorld.exe+104D845:            48 8B 4C 24 38 - mov rcx,[rsp+38]
TrainSimWorld.exe+104D84A:                  48 85 C9 - test rcx,rcx
TrainSimWorld.exe+104D84D:                     74 35 - je 7FF7C8E9D884
TrainSimWorld.exe+104D84F:            BE FF FF FF FF - mov esi,-1 // 4294967295
TrainSimWorld.exe+104D854:                     8B C6 - mov eax,esi
TrainSimWorld.exe+104D856:            F0 0F C1 41 08 - lock xadd [rcx+8],eax
TrainSimWorld.exe+104D85B:                  83 F8 01 - cmp eax,1
TrainSimWorld.exe+104D85E:                     75 24 - jne 7FF7C8E9D884
TrainSimWorld.exe+104D860:            48 8B 5C 24 38 - mov rbx,[rsp+38]
TrainSimWorld.exe+104D865:                  48 8B CB - mov rcx,rbx
TrainSimWorld.exe+104D868:                  48 8B 03 - mov rax,[rbx]
TrainSimWorld.exe+104D86B:                     FF 10 - call qword ptr [rax]
TrainSimWorld.exe+104D86D:            F0 0F C1 73 0C - lock xadd [rbx+C],esi
TrainSimWorld.exe+104D872:                  83 FE 01 - cmp esi,1
TrainSimWorld.exe+104D875:                     75 0D - jne 7FF7C8E9D884
TrainSimWorld.exe+104D877:            48 8B 4C 24 38 - mov rcx,[rsp+38]
TrainSimWorld.exe+104D87C:                     8B D6 - mov edx,esi
TrainSimWorld.exe+104D87E:                  48 8B 01 - mov rax,[rcx]
TrainSimWorld.exe+104D881:                  FF 50 08 - call qword ptr [rax+8]
TrainSimWorld.exe+104D884:            48 8B 4C 24 20 - mov rcx,[rsp+20]
TrainSimWorld.exe+104D889:                  48 85 C9 - test rcx,rcx
TrainSimWorld.exe+104D88C:                     74 05 - je 7FF7C8E9D893
TrainSimWorld.exe+104D88E:            E8 1D 86 47 00 - call 7FF7C9315EB0
TrainSimWorld.exe+104D893:                  48 8B CF - mov rcx,rdi
TrainSimWorld.exe+104D896:            48 8B 5C 24 70 - mov rbx,[rsp+70]
TrainSimWorld.exe+104D89B:            48 8B 6C 24 78 - mov rbp,[rsp+78]
TrainSimWorld.exe+104D8A0:   48 8B B4 24 80 00 00 00 - mov rsi,[rsp+80]
TrainSimWorld.exe+104D8A8:               48 83 C4 60 - add rsp,60 // 96
TrainSimWorld.exe+104D8AC:                        5F - pop rdi

}"""
