[game]
name = "Planet of Lana II"
exe = "planet_of_lana_2_v1.0.13_danger_dash.exe"
notes = "Converted from a Cheat Engine table by Firstlast2s100. Source: https://fearlessrevolution.com/viewtopic.php?t=38475"
verified = []
author = "Firstlast2s100"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "lanamachine"
name = "LanaMachine"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Planet of Lana 2.exe
  Version: 
  Date   : 2026-03-07
  Author : DANGER DASH

  This script does blah blah blah
}

define(address,"GameAssembly.dll"+800A10)
define(bytes,48 89 5C 24 18)

[ENABLE]

assert(address,bytes)
alloc(newmem,$1000,"GameAssembly.dll"+800A10)

label(code)
label(return)

newmem:
mov [lanamachine_ptr],rcx

code:
  mov [rsp+18],rbx
  jmp return

lanamachine_ptr:
dq 0

address:
  jmp newmem
return:
registersymbol(lanamachine_ptr)

[DISABLE]

address:
  db bytes
  // mov [rsp+18],rbx

dealloc(newmem)
unregistersymbol(lanamachine_ptr)

{
// ORIGINAL CODE - INJECTION POINT: PoL.Characters.Lana.LanaMachine.Update

GameAssembly.dll+8009E9: E8 32 79 F2 FF        - call PoL.Characters.CharacterLookup.Remove
GameAssembly.dll+8009EE: 4C 8B 0D 23 9A BA 03  - mov r9,[GameAssembly.dll+43AA418]
GameAssembly.dll+8009F5: 45 33 C0              - xor r8d,r8d
GameAssembly.dll+8009F8: 48 8B 53 38           - mov rdx,[rbx+38]
GameAssembly.dll+8009FC: 48 8B CB              - mov rcx,rbx
GameAssembly.dll+8009FF: E8 5C 86 CA 00        - call GameAssembly.dll+14A9060
GameAssembly.dll+800A04: 33 C9                 - xor ecx,ecx
GameAssembly.dll+800A06: 48 83 C4 20           - add rsp,20
GameAssembly.dll+800A0A: 5B                    - pop rbx
GameAssembly.dll+800A0B: E9 90 86 00 00        - jmp GameAssembly.dll+8090A0
// ---------- INJECTING HERE ----------
PoL.Characters.Lana.LanaMachine.Update: 48 89 5C 24 18        - mov [rsp+18],rbx
// ---------- DONE INJECTING  ----------
GameAssembly.dll+800A15: 56                    - push rsi
GameAssembly.dll+800A16: 48 83 EC 60           - sub rsp,60
GameAssembly.dll+800A1A: 80 3D A6 9A DE 03 00  - cmp byte ptr [GameAssembly.dll+45EA4C7],00
GameAssembly.dll+800A21: 48 8B F1              - mov rsi,rcx
GameAssembly.dll+800A24: 75 18                 - jne GameAssembly.dll+800A3E
GameAssembly.dll+800A26: 48 8D 0D DB 99 BA 03  - lea rcx,[GameAssembly.dll+43AA408]
GameAssembly.dll+800A2D: E8 CE 5C C7 FF        - call GameAssembly.il2cpp_field_set_value+8C60
GameAssembly.dll+800A32: F0 83 0C 24 00        - lock or dword ptr [rsp],00
GameAssembly.dll+800A37: C6 05 89 9A DE 03 01  - mov byte ptr [GameAssembly.dll+45EA4C7],01
GameAssembly.dll+800A3E: 48 8B 5E 20           - mov rbx,[rsi+20]
}"""
