[game]
name = "Morphblade"
exe = "morphblade.exe"
notes = "Converted from a Cheat Engine table by Dread_Pony_Roberts. Source: https://fearlessrevolution.com/viewtopic.php?t=8439"
verified = []
author = "Dread_Pony_Roberts"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "unstoppable"
name = "Unstoppable"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ I know it's a bit useless to have two of these, it's mainly for consistency in my tables}

[ENABLE]

aobscanmodule(HEALTH_LOCK_2,Morphblade.exe,DD 1F 5F 5E 5D 5B 59) // should be unique
alloc(newmem,$1000)

label(code)
label(return)
label(newcode)

newmem:

code:
push eax
mov eax,["Morphblade.exe"+003C943C]
mov eax,[eax+00]
mov eax,[eax+78]
mov eax,[eax+0C]
mov eax,[eax+B8]
mov eax,[eax+08]
mov eax,[eax+34]
mov eax,[eax+10]
mov eax,[eax+D0]
  cmp eax,edi
  je newcode
  pop eax
  fstp qword ptr [edi]
  pop edi
  pop esi
  pop ebp
  jmp return

newcode:
pop eax
  //fstp qword ptr [edi]
  pop edi
  pop esi
  pop ebp
  jmp return

HEALTH_LOCK_2:
  jmp newmem
return:
registersymbol(HEALTH_LOCK_2)

[DISABLE]

HEALTH_LOCK_2:
  db DD 1F 5F 5E 5D

unregistersymbol(HEALTH_LOCK_2)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Morphblade.exe"+1292C6

"Morphblade.exe"+1292B2: 39 58 08              -  cmp [eax+08],ebx
"Morphblade.exe"+1292B5: 0F 85 A4 02 00 00     -  jne Morphblade.exe+12955F
"Morphblade.exe"+1292BB: 89 78 08              -  mov [eax+08],edi
"Morphblade.exe"+1292BE: 5F                    -  pop edi
"Morphblade.exe"+1292BF: 5E                    -  pop esi
"Morphblade.exe"+1292C0: 5D                    -  pop ebp
"Morphblade.exe"+1292C1: 5B                    -  pop ebx
"Morphblade.exe"+1292C2: 59                    -  pop ecx
"Morphblade.exe"+1292C3: C3                    -  ret 
"Morphblade.exe"+1292C4: DD 00                 -  fld qword ptr [eax]
// ---------- INJECTING HERE ----------
"Morphblade.exe"+1292C6: DD 1F                 -  fstp qword ptr [edi]
"Morphblade.exe"+1292C8: 5F                    -  pop edi
"Morphblade.exe"+1292C9: 5E                    -  pop esi
"Morphblade.exe"+1292CA: 5D                    -  pop ebp
// ---------- DONE INJECTING  ----------
"Morphblade.exe"+1292CB: 5B                    -  pop ebx
"Morphblade.exe"+1292CC: 59                    -  pop ecx
"Morphblade.exe"+1292CD: C3                    -  ret 
"Morphblade.exe"+1292CE: 8B 08                 -  mov ecx,[eax]
"Morphblade.exe"+1292D0: 89 0F                 -  mov [edi],ecx
"Morphblade.exe"+1292D2: 8B 50 04              -  mov edx,[eax+04]
"Morphblade.exe"+1292D5: 89 57 04              -  mov [edi+04],edx
"Morphblade.exe"+1292D8: 5F                    -  pop edi
"Morphblade.exe"+1292D9: 5E                    -  pop esi
"Morphblade.exe"+1292DA: 5D                    -  pop ebp
}"""

[[cheat]]
id = "health-lock"
name = "Health Lock"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ I know it's a bit useless to have two of these, it's mainly for consistency in my tables}

[ENABLE]

aobscanmodule(HEALTH_LOCK_2,Morphblade.exe,DD 1F 5F 5E 5D 5B 59) // should be unique
alloc(newmem,$1000)

label(code)
label(return)
label(newcode)

newmem:

code:
push eax
mov eax,["Morphblade.exe"+003C943C]
mov eax,[eax+00]
mov eax,[eax+78]
mov eax,[eax+0C]
mov eax,[eax+B8]
mov eax,[eax+08]
mov eax,[eax+34]
mov eax,[eax+10]
mov eax,[eax+D0]
  cmp eax,edi
  je newcode
  pop eax
  fstp qword ptr [edi]
  pop edi
  pop esi
  pop ebp
  jmp return

newcode:
pop eax
  //fstp qword ptr [edi]
  pop edi
  pop esi
  pop ebp
  jmp return

HEALTH_LOCK_2:
  jmp newmem
return:
registersymbol(HEALTH_LOCK_2)

[DISABLE]

HEALTH_LOCK_2:
  db DD 1F 5F 5E 5D

unregistersymbol(HEALTH_LOCK_2)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Morphblade.exe"+1292C6

"Morphblade.exe"+1292B2: 39 58 08              -  cmp [eax+08],ebx
"Morphblade.exe"+1292B5: 0F 85 A4 02 00 00     -  jne Morphblade.exe+12955F
"Morphblade.exe"+1292BB: 89 78 08              -  mov [eax+08],edi
"Morphblade.exe"+1292BE: 5F                    -  pop edi
"Morphblade.exe"+1292BF: 5E                    -  pop esi
"Morphblade.exe"+1292C0: 5D                    -  pop ebp
"Morphblade.exe"+1292C1: 5B                    -  pop ebx
"Morphblade.exe"+1292C2: 59                    -  pop ecx
"Morphblade.exe"+1292C3: C3                    -  ret 
"Morphblade.exe"+1292C4: DD 00                 -  fld qword ptr [eax]
// ---------- INJECTING HERE ----------
"Morphblade.exe"+1292C6: DD 1F                 -  fstp qword ptr [edi]
"Morphblade.exe"+1292C8: 5F                    -  pop edi
"Morphblade.exe"+1292C9: 5E                    -  pop esi
"Morphblade.exe"+1292CA: 5D                    -  pop ebp
// ---------- DONE INJECTING  ----------
"Morphblade.exe"+1292CB: 5B                    -  pop ebx
"Morphblade.exe"+1292CC: 59                    -  pop ecx
"Morphblade.exe"+1292CD: C3                    -  ret 
"Morphblade.exe"+1292CE: 8B 08                 -  mov ecx,[eax]
"Morphblade.exe"+1292D0: 89 0F                 -  mov [edi],ecx
"Morphblade.exe"+1292D2: 8B 50 04              -  mov edx,[eax+04]
"Morphblade.exe"+1292D5: 89 57 04              -  mov [edi+04],edx
"Morphblade.exe"+1292D8: 5F                    -  pop edi
"Morphblade.exe"+1292D9: 5E                    -  pop esi
"Morphblade.exe"+1292DA: 5D                    -  pop ebp
}"""

[[cheat]]
id = "health"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f64"
value = 2

[cheat.locator]
find = "static"
module = "Morphblade.exe"
offset = "0x3c943c"
hops = [
    "+0x0",
    "+0x78",
    "+0xc",
    "+0xb8",
    "+0x8",
    "+0x34",
    "+0x10",
    "+0xd0",
    "+0x0",
]

[[cheat]]
id = "turn"
name = "Turn"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f64"
value = 2

[cheat.locator]
find = "static"
module = "Morphblade.exe"
offset = "0x3bd168"
hops = [
    "+0x0",
    "+0x34",
    "+0x10",
    "+0xf4",
    "+0x0",
]

[[cheat]]
id = "starting-space-level"
name = "Starting Space Level"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f64"
value = 2

[cheat.locator]
find = "static"
module = "Morphblade.exe"
offset = "0x3c943c"
hops = [
    "+0x0",
    "+0x30",
    "+0xc",
    "+0xb8",
    "+0x8",
    "+0x34",
    "+0x10",
    "+0x154",
    "+0x0",
]

[[cheat]]
id = "right-of-start"
name = "Right of Start"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f64"
value = 2

[cheat.locator]
find = "static"
module = "Morphblade.exe"
offset = "0x3c943c"
hops = [
    "+0x0",
    "+0x30",
    "+0xc",
    "+0xac",
    "+0x0",
    "+0x8",
    "+0x34",
    "+0x10",
    "+0x154",
    "+0x0",
]

[[cheat]]
id = "top-right-of-start"
name = "Top Right of Start"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f64"
value = 0

[cheat.locator]
find = "static"
module = "Morphblade.exe"
offset = "0x3c943c"
hops = [
    "+0x0",
    "+0x60",
    "+0x1c",
    "+0xbc",
    "+0x8",
    "+0x14c",
    "+0x34",
    "+0x10",
    "+0x154",
    "+0x0",
]

[[cheat]]
id = "extreme-gameplay"
name = "EXTREME GAMEPLAY"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Morphblade.exe
  Version: 
  Date   : 2018-12-20
  Author : Dread Pony Roberts

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(HEALTH_LOCK_2,Morphblade.exe,DD 1F 5F 5E 5D 5B 59) // should be unique
alloc(newmem,$1000)

label(code)
label(return)
label(newcode)

newmem:

code:
push eax
mov eax,["Morphblade.exe"+003C943C]
mov eax,[eax+00]
mov eax,[eax+78]
mov eax,[eax+0C]
mov eax,[eax+B8]
mov eax,[eax+08]
mov eax,[eax+34]
mov eax,[eax+10]
mov eax,[eax+D0]
  cmp eax,edi
  je newcode
  pop eax
  fstp qword ptr [edi]
  pop edi
  pop esi
  pop ebp
  jmp return

newcode:
pop eax
add edi,2
  fstp qword ptr [edi]
  pop edi
  pop esi
  pop ebp
  jmp return

HEALTH_LOCK_2:
  jmp newmem
return:
registersymbol(HEALTH_LOCK_2)

[DISABLE]

HEALTH_LOCK_2:
  db DD 1F 5F 5E 5D

unregistersymbol(HEALTH_LOCK_2)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Morphblade.exe"+1292C6

"Morphblade.exe"+1292B2: 39 58 08              -  cmp [eax+08],ebx
"Morphblade.exe"+1292B5: 0F 85 A4 02 00 00     -  jne Morphblade.exe+12955F
"Morphblade.exe"+1292BB: 89 78 08              -  mov [eax+08],edi
"Morphblade.exe"+1292BE: 5F                    -  pop edi
"Morphblade.exe"+1292BF: 5E                    -  pop esi
"Morphblade.exe"+1292C0: 5D                    -  pop ebp
"Morphblade.exe"+1292C1: 5B                    -  pop ebx
"Morphblade.exe"+1292C2: 59                    -  pop ecx
"Morphblade.exe"+1292C3: C3                    -  ret 
"Morphblade.exe"+1292C4: DD 00                 -  fld qword ptr [eax]
// ---------- INJECTING HERE ----------
"Morphblade.exe"+1292C6: DD 1F                 -  fstp qword ptr [edi]
"Morphblade.exe"+1292C8: 5F                    -  pop edi
"Morphblade.exe"+1292C9: 5E                    -  pop esi
"Morphblade.exe"+1292CA: 5D                    -  pop ebp
// ---------- DONE INJECTING  ----------
"Morphblade.exe"+1292CB: 5B                    -  pop ebx
"Morphblade.exe"+1292CC: 59                    -  pop ecx
"Morphblade.exe"+1292CD: C3                    -  ret 
"Morphblade.exe"+1292CE: 8B 08                 -  mov ecx,[eax]
"Morphblade.exe"+1292D0: 89 0F                 -  mov [edi],ecx
"Morphblade.exe"+1292D2: 8B 50 04              -  mov edx,[eax+04]
"Morphblade.exe"+1292D5: 89 57 04              -  mov [edi+04],edx
"Morphblade.exe"+1292D8: 5F                    -  pop edi
"Morphblade.exe"+1292D9: 5E                    -  pop esi
"Morphblade.exe"+1292DA: 5D                    -  pop ebp
}"""
