[game]
name = "Gurumin"
exe = "game.exe"
notes = "Converted from a Cheat Engine table by zeebeegeebee. Source: https://fearlessrevolution.com/viewtopic.php?t=6254"
verified = []
author = "zeebeegeebee"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "dash-count-lock-to-0-1-or-2-for-inf-dashing"
name = "dash count (lock to 0, 1, or 2 for inf. dashing)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "game.exe"
offset = "0x7c87a5"
hops = []

[[cheat]]
id = "semi-invulnerable-lock-to-0-e-g-255"
name = "semi-invulnerable (lock to >0, e.g. 255)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "game.exe"
offset = "0x614f84"
hops = []

[[cheat]]
id = "boss-health-alt2"
name = "boss health (alt2)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "game.exe"
offset = "0x516f7c"
hops = []

[[cheat]]
id = "boss-health-alt3"
name = "boss health (alt3)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "game.exe"
offset = "0x516f90"
hops = []

[[cheat]]
id = "boss-health-try-this-first"
name = "boss health (try this first)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "game.exe"
offset = "0xb3dab4"
hops = []

[[cheat]]
id = "boss-health-alt4"
name = "boss health (alt4)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "game.exe"
offset = "0xb3dc3c"
hops = []

[[cheat]]
id = "boss-health-alt"
name = "boss health (alt)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "game.exe"
offset = "0xb3f954"
hops = []
