[game]
name = "Cell to singularity"
exe = "cell_to_singularity.exe"
notes = "Converted from a Cheat Engine table by spoopky. Source: https://fearlessrevolution.com/viewtopic.php?t=25464"
verified = []
author = "spoopky"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "darwinium"
name = "darwinium"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "static"
module = "mono-2.0-bdwgc.dll"
offset = "0x498da8"
hops = [
    "+0xa0",
    "+0x630",
    "+0x98",
    "+0x30",
    "+0x158",
    "+0x10",
    "+0x98",
]

[[cheat]]
id = "money"
name = "money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "static"
module = "mono-2.0-bdwgc.dll"
offset = "0x498de8"
hops = [
    "+0xb0",
    "+0xe18",
    "+0x130",
    "+0x0",
    "+0x158",
    "+0x10",
    "+0x88",
]

[[cheat]]
id = "lightbulb"
name = "lightbulb"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x19ede00"
hops = [
    "+0xf80",
    "+0x398",
    "+0x28",
    "+0x60",
    "+0x60",
    "+0x20",
    "+0x90",
]

[[cheat]]
id = "dinosaur-money"
name = "Dinosaur Money"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x1978080"
hops = [
    "+0x10",
    "+0xb0",
    "+0x20",
    "+0xb8",
    "+0xd0",
    "+0x60",
    "+0xb0",
]

[[cheat]]
id = "blackballs-blue-virus-thing"
name = "blackballs/blue virus thing"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x19ede00"
hops = [
    "+0xf80",
    "+0x398",
    "+0x28",
    "+0x60",
    "+0x60",
    "+0x20",
    "+0xa8",
]

[[cheat]]
id = "stardust"
name = "Stardust"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f64"

[cheat.locator]
find = "static"
module = "mono-2.0-bdwgc.dll"
offset = "0x498de0"
hops = [
    "+0x40",
    "+0xa0",
    "+0x10",
    "+0x88",
    "+0x28",
    "+0x28",
    "+0x88",
]
