[game]
name = "Cold Blooded"
exe = "coldblooded.exe"
notes = "Converted from a Cheat Engine table by anon9. Source: https://fearlessrevolution.com/viewtopic.php?t=31887"
verified = []
author = "anon9"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "recover-ammo-if-0"
name = "Recover Ammo if 0"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : ColdBlooded.exe
  Version: 
  Date   : 2024-10-06
  Author : User

  This script does blah blah blah
}

[ENABLE]

define(funMoreAmmoPlease,Invector.vShooter.vShooterWeapon:get_ammoCount+6b)
assert(funMoreAmmoPlease,48 63 86 98 00 00 00 EB) // should be unique
alloc(newmem,$1000,funMoreAmmoPlease)

label(code)
label(return)

newmem:

code:
  movsxd  rax,dword ptr [rsi+00000098]
  cmp eax,0
  jne return
  mov eax,#5
  mov dword ptr [rsi+00000098],eax
  jmp return

funMoreAmmoPlease:
  jmp newmem
  nop 2
return:
registersymbol(funMoreAmmoPlease)

[DISABLE]

funMoreAmmoPlease:
  db 48 63 86 98 00 00 00

unregistersymbol(funMoreAmmoPlease)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: Invector.vShooter.vShooterWeapon:get_ammoCount+6b

Invector.vShooter.vShooterWeapon:get_ammoCount+4b: 49 83 C0 E8           - add r8,-18
Invector.vShooter.vShooterWeapon:get_ammoCount+4f: 48 89 45 E0           - mov [rbp-20],rax
Invector.vShooter.vShooterWeapon:get_ammoCount+53: FF 50 18              - call qword ptr [rax+18]
Invector.vShooter.vShooterWeapon:get_ammoCount+56: 48 8B C8              - mov rcx,rax
Invector.vShooter.vShooterWeapon:get_ammoCount+59: 48 8B 45 E0           - mov rax,[rbp-20]
Invector.vShooter.vShooterWeapon:get_ammoCount+5d: 0F B6 45 F0           - movzx eax,byte ptr [rbp-10]
Invector.vShooter.vShooterWeapon:get_ammoCount+61: 85 C0                 - test eax,eax
Invector.vShooter.vShooterWeapon:get_ammoCount+63: 74 06                 - je Invector.vShooter.vShooterWeapon:get_ammoCount+6b
Invector.vShooter.vShooterWeapon:get_ammoCount+65: 48 63 45 E8           - movsxd  rax,dword ptr [rbp-18]
Invector.vShooter.vShooterWeapon:get_ammoCount+69: EB 10                 - jmp Invector.vShooter.vShooterWeapon:get_ammoCount+7b
// ---------- INJECTING HERE ----------
Invector.vShooter.vShooterWeapon:get_ammoCount+6b: 48 63 86 98 00 00 00  - movsxd  rax,dword ptr [rsi+00000098]
// ---------- DONE INJECTING  ----------
Invector.vShooter.vShooterWeapon:get_ammoCount+72: EB 07                 - jmp Invector.vShooter.vShooterWeapon:get_ammoCount+7b
Invector.vShooter.vShooterWeapon:get_ammoCount+74: 48 63 86 98 00 00 00  - movsxd  rax,dword ptr [rsi+00000098]
Invector.vShooter.vShooterWeapon:get_ammoCount+7b: 48 8B 75 F8           - mov rsi,[rbp-08]
Invector.vShooter.vShooterWeapon:get_ammoCount+7f: 48 8D 65 00           - lea rsp,[rbp+00]
Invector.vShooter.vShooterWeapon:get_ammoCount+83: 5D                    - pop rbp
Invector.vShooter.vShooterWeapon:get_ammoCount+84: C3                    - ret 
210DD6052F5: 00 00                 - add [rax],al
210DD6052F7: 00 01                 - add [rcx],al
210DD6052F9: 04 02                 - add al,02
210DD6052FB: 05 04 03 01 50        - add eax,50010304
}"""

[[cheat]]
id = "no-sprint-stamina"
name = "No Sprint Stamina"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game   : ColdBlooded.exe
  Author : Anon-9

  This script does blah blah blah
}

[ENABLE]

define(funNoRunStamina,Invector.vCharacterController.vThirdPersonMotor:ReduceStamina+75)

assert(funNoRunStamina,F2 0F 5C C1 F2 0F 5A E8 F3 0F 11 AF 60 01 00 00 E9) // should be unique


funNoRunStamina:
  nop 4
registersymbol(funNoRunStamina)

[DISABLE]

funNoRunStamina:
  db F2 0F 5C C1 F2 0F 5A E8

unregistersymbol(funNoRunStamina)

{
// ORIGINAL CODE - INJECTION POINT: 1FADD7D4425

1FADD7D43F4: F3 0F 10 45 F0                 - movss xmm0,[rbp-10]
1FADD7D43F9: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
1FADD7D43FD: F2 0F 11 45 D8                 - movsd [rbp-28],xmm0
1FADD7D4402: 48 8D 6D 00                    - lea rbp,[rbp+00]
1FADD7D4406: 49 BB D0 DB 6E B7 FB 01 00 00  - mov r11,000001FBB76EDBD0
1FADD7D4410: 41 FF D3                       - call r11
1FADD7D4413: F3 0F 5A D0                    - cvtss2sd xmm2,xmm0
1FADD7D4417: F2 0F 10 45 E0                 - movsd xmm0,[rbp-20]
1FADD7D441C: F2 0F 10 4D D8                 - movsd xmm1,[rbp-28]
1FADD7D4421: F2 0F 59 CA                    - mulsd xmm1,xmm2
// ---------- INJECTING HERE ----------
1FADD7D4425: F2 0F 5C C1                    - subsd xmm0,xmm1
// ---------- DONE INJECTING  ----------
1FADD7D4429: F2 0F 5A E8                    - cvtsd2ss xmm5,xmm0
1FADD7D442D: F3 0F 11 AF 60 01 00 00        - movss [rdi+00000160],xmm5
1FADD7D4435: E9 25 00 00 00                 - jmp 1FADD7D445F
1FADD7D443A: F3 0F 10 87 60 01 00 00        - movss xmm0,[rdi+00000160]
1FADD7D4442: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
1FADD7D4446: F3 0F 10 4D F0                 - movss xmm1,[rbp-10]
1FADD7D444B: F3 0F 5A C9                    - cvtss2sd xmm1,xmm1
1FADD7D444F: F2 0F 5C C1                    - subsd xmm0,xmm1
1FADD7D4453: F2 0F 5A E8                    - cvtsd2ss xmm5,xmm0
1FADD7D4457: F3 0F 11 AF 60 01 00 00        - movss [rdi+00000160],xmm5
}"""

[[cheat]]
id = "no-jump-stamina"
name = "No Jump Stamina"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game   : ColdBlooded.exe
  Version: 
  Date   : 2024-10-06
  Author : User

  This script does blah blah blah
}

[ENABLE]
define(funNoJumpStamina,Invector.vCharacterController.vThirdPersonMotor:ReduceStamina+9f)

assert(funNoJumpStamina,F2 0F 5C C1 F2 0F 5A E8 F3 0F 11 AF 60) // should be unique


funNoJumpStamina:
  nop 4
registersymbol(funNoJumpStamina)

[DISABLE]

funNoJumpStamina:
  db F2 0F 5C C1 F2 0F 5A E8

unregistersymbol(funNoJumpStamina)

{
// ORIGINAL CODE - INJECTION POINT: 1FADD7D444F

1FADD7D441C: F2 0F 10 4D D8           - movsd xmm1,[rbp-28]
1FADD7D4421: F2 0F 59 CA              - mulsd xmm1,xmm2
funNoRunStamina: 0F 1F 40 00              - nop dword ptr [rax+00]
1FADD7D4429: F2 0F 5A E8              - cvtsd2ss xmm5,xmm0
1FADD7D442D: F3 0F 11 AF 60 01 00 00  - movss [rdi+00000160],xmm5
1FADD7D4435: E9 25 00 00 00           - jmp 1FADD7D445F
1FADD7D443A: F3 0F 10 87 60 01 00 00  - movss xmm0,[rdi+00000160]
1FADD7D4442: F3 0F 5A C0              - cvtss2sd xmm0,xmm0
1FADD7D4446: F3 0F 10 4D F0           - movss xmm1,[rbp-10]
1FADD7D444B: F3 0F 5A C9              - cvtss2sd xmm1,xmm1
// ---------- INJECTING HERE ----------
1FADD7D444F: F2 0F 5C C1              - subsd xmm0,xmm1
// ---------- DONE INJECTING  ----------
1FADD7D4453: F2 0F 5A E8              - cvtsd2ss xmm5,xmm0
1FADD7D4457: F3 0F 11 AF 60 01 00 00  - movss [rdi+00000160],xmm5
1FADD7D445F: F3 0F 10 87 60 01 00 00  - movss xmm0,[rdi+00000160]
1FADD7D4467: F3 0F 5A C0              - cvtss2sd xmm0,xmm0
1FADD7D446B: 66 0F 57 C9              - xorpd xmm1,xmm1
1FADD7D446F: 66 0F 2F C8              - comisd xmm1,xmm0
1FADD7D4473: 76 2E                    - jna 1FADD7D44A3
1FADD7D4475: 66 0F 57 C0              - xorpd xmm0,xmm0
1FADD7D4479: F2 0F 5A E8              - cvtsd2ss xmm5,xmm0
1FADD7D447D: F3 0F 11 AF 60 01 00 00  - movss [rdi+00000160],xmm5
}"""

[[cheat]]
id = "no-punch-stamina"
name = "No Punch Stamina"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game   : ColdBlooded.exe
  Author : Anon-9

  This script does blah blah blah
}

[ENABLE]

define(funNoPunchStamina,Invector.vCharacterController.vThirdPersonMotor:ChangeStamina+29)

assert(funNoPunchStamina,F2 0F 58 C1 F2 0F 5A E8 F3 0F 11 AE 60 01 00 00 F3) // should be unique


funNoPunchStamina:
  nop 4
registersymbol(funNoPunchStamina)

[DISABLE]

funNoPunchStamina:
  db F2 0F 58 C1 F2 0F 5A E8

unregistersymbol(funNoPunchStamina)

{
// ORIGINAL CODE - INJECTION POINT: 1FADD7DDA99

1FADD7DDA70: 55                       - push rbp
1FADD7DDA71: 48 8B EC                 - mov rbp,rsp
1FADD7DDA74: 48 83 EC 30              - sub rsp,30
1FADD7DDA78: 48 89 75 F8              - mov [rbp-08],rsi
1FADD7DDA7C: 48 8B F1                 - mov rsi,rcx
1FADD7DDA7F: F3 0F 11 4D F0           - movss [rbp-10],xmm1
1FADD7DDA84: F3 0F 10 86 60 01 00 00  - movss xmm0,[rsi+00000160]
1FADD7DDA8C: F3 0F 5A C0              - cvtss2sd xmm0,xmm0
1FADD7DDA90: F3 0F 10 4D F0           - movss xmm1,[rbp-10]
1FADD7DDA95: F3 0F 5A C9              - cvtss2sd xmm1,xmm1
// ---------- INJECTING HERE ----------
1FADD7DDA99: F2 0F 58 C1              - addsd xmm0,xmm1
// ---------- DONE INJECTING  ----------
1FADD7DDA9D: F2 0F 5A E8              - cvtsd2ss xmm5,xmm0
1FADD7DDAA1: F3 0F 11 AE 60 01 00 00  - movss [rsi+00000160],xmm5
1FADD7DDAA9: F3 0F 10 86 60 01 00 00  - movss xmm0,[rsi+00000160]
1FADD7DDAB1: F3 0F 5A C0              - cvtss2sd xmm0,xmm0
1FADD7DDAB5: 66 0F 57 C9              - xorpd xmm1,xmm1
1FADD7DDAB9: F3 0F 10 96 58 01 00 00  - movss xmm2,[rsi+00000158]
1FADD7DDAC1: F3 0F 5A D2              - cvtss2sd xmm2,xmm2
1FADD7DDAC5: F2 0F 5A D2              - cvtsd2ss xmm2,xmm2
1FADD7DDAC9: F2 0F 5A C9              - cvtsd2ss xmm1,xmm1
1FADD7DDACD: F2 0F 5A C0              - cvtsd2ss xmm0,xmm0
}"""

[[cheat]]
id = "no-battery-flashlight-aob-turn-on-flashlight-first"
name = "No Battery Flashlight AOB (Turn on Flashlight first)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : ColdBlooded.exe
  Author : User

  This script does blah blah blah
}

[ENABLE]

aobscan(funFlashlightBattery,F2 0F 5C C1 F2 0F 5A E8 F3 41 0F 11 AF 88) // should be unique


funFlashlightBattery:
  nop 4
registersymbol(funFlashlightBattery)

[DISABLE]

funFlashlightBattery:
  db F2 0F 5C C1 F2 0F 5A E8

unregistersymbol(funFlashlightBattery)

{
// ORIGINAL CODE - INJECTION POINT: PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+ac

PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+7c: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+80: F2 0F 11 45 E0                 - movsd [rbp-20],xmm0
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+85: 90                             - nop 
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+86: 49 BB 40 1D 74 79 10 02 00 00  - mov r11,UnityEngine.Time:get_deltaTime
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+90: 41 FF D3                       - call r11
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+93: F3 0F 5A C8                    - cvtss2sd xmm1,xmm0
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+97: F2 0F 10 45 E0                 - movsd xmm0,[rbp-20]
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+9c: F3 0F 10 15 4C 04 00 00        - movss xmm2,[PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+4f0]
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+a4: F3 0F 5A D2                    - cvtss2sd xmm2,xmm2
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+a8: F2 0F 59 CA                    - mulsd xmm1,xmm2
// ---------- INJECTING HERE ----------
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+ac: F2 0F 5C C1                    - subsd xmm0,xmm1
// ---------- DONE INJECTING  ----------
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+b0: F2 0F 5A E8                    - cvtsd2ss xmm5,xmm0
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+b4: F3 41 0F 11 AF 88 07 00 00     - movss [r15+00000788],xmm5
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+bd: F3 41 0F 10 87 88 07 00 00     - movss xmm0,[r15+00000788]
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+c6: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+ca: F3 0F 10 0D 0E 04 00 00        - movss xmm1,[PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+4e0]
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+d2: F3 0F 5A C9                    - cvtss2sd xmm1,xmm1
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+d6: 66 0F 2F C8                    - comisd xmm1,xmm0
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+da: 0F 8A 90 00 00 00              - jp PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+170
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+e0: 0F 87 8A 00 00 00              - ja PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+170
PlayerActions+<<FlashLightOnLoop>g__FLONL|418_0>d:MoveNext+e6: 49 8B 87 C8 01 00 00           - mov rax,[r15+000001C8]
}"""
