[game]
name = "My Lovely Daughter"
exe = "my lovely daughter.exe"
notes = "Converted from a Cheat Engine table by hysspy. Source: https://fearlessrevolution.com/viewtopic.php?t=6253"
verified = []
author = "hysspy"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "full-item"
name = "FULL ITEM"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : My Lovely Daughter.exe
  Version: 1.00f3
  Date   : 2018-03-15
  Author : Herwin Yudha S

  Item always full 99 [Recommended to always activate this cheat]
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(subitem,89 08 8B 05 D4 EE 4B 03) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov [eax],(int)99
  mov eax,[034BEED4]
  jmp return

subitem:
  jmp newmem
  nop
  nop
  nop
return:
registersymbol(subitem)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
subitem:
  db 89 08 8B 05 D4 EE 4B 03

unregistersymbol(subitem)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 051CD3BA

051CD39A: EC                 -  in al,dx
051CD39B: 56                 -  push esi
051CD39C: 83 EC 24           -  sub esp,24
051CD39F: 8B 75 08           -  mov esi,[ebp+08]
051CD3A2: 8B 05 D4 EE 4B 03  -  mov eax,[034BEED4]
051CD3A8: 39 70 0C           -  cmp [eax+0C],esi
051CD3AB: 0F 86 21 01 00 00  -  jbe 051CD4D2
051CD3B1: 8D 44 B0 10        -  lea eax,[eax+esi*4+10]
051CD3B5: 8B 08              -  mov ecx,[eax]
051CD3B7: 03 4D 0C           -  add ecx,[ebp+0C]
// ---------- INJECTING HERE ----------
051CD3BA: 89 08              -  mov [eax],ecx
051CD3BC: 8B 05 D4 EE 4B 03  -  mov eax,[034BEED4]
// ---------- DONE INJECTING  ----------
051CD3C2: 39 70 0C           -  cmp [eax+0C],esi
051CD3C5: 0F 86 00 01 00 00  -  jbe 051CD4CB
051CD3CB: 8D 44 B0 10        -  lea eax,[eax+esi*4+10]
051CD3CF: 8B 00              -  mov eax,[eax]
051CD3D1: 85 C0              -  test eax,eax
051CD3D3: 0F 8D E0 00 00 00  -  jnl 051CD4B9
051CD3D9: B9 04 00 00 00     -  mov ecx,00000004
051CD3DE: B8 24 8D CB 04     -  mov eax,04CB8D24
051CD3E3: 83 EC 08           -  sub esp,08
051CD3E6: 51                 -  push ecx
}"""

[[cheat]]
id = "add-gold-work"
name = "ADD GOLD WORK"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : My Lovely Daughter.exe
  Version: 1.00f3
  Date   : 2018-03-15
  Author : Herwin Yudha S

  Set GOLD ALWAYS 9999 [Recommended to always activate this cheat]
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(addgold,89 48 20 83 EC 0C 50 E8 18) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov [eax+20],(int)9999
  sub esp,0C
  jmp return

addgold:
  jmp newmem
  nop
return:
registersymbol(addgold)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
addgold:
  db 89 48 20 83 EC 0C

unregistersymbol(addgold)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 051CA6FC

051CA6E0: 68 88 26 3D 0C     -  push 0C3D2688
051CA6E5: E9 3E 59 BF FF     -  jmp 04DC0028
051CA6EA: 00 00              -  add [eax],al
051CA6EC: 00 00              -  add [eax],al
051CA6EE: 00 00              -  add [eax],al
051CA6F0: 55                 -  push ebp
051CA6F1: 8B EC              -  mov ebp,esp
051CA6F3: 83 EC 08           -  sub esp,08
051CA6F6: 8B 4D 0C           -  mov ecx,[ebp+0C]
051CA6F9: 8B 45 08           -  mov eax,[ebp+08]
// ---------- INJECTING HERE ----------
051CA6FC: 89 48 20           -  mov [eax+20],ecx
051CA6FF: 83 EC 0C           -  sub esp,0C
// ---------- DONE INJECTING  ----------
051CA702: 50                 -  push eax
051CA703: E8 18 00 00 00     -  call 051CA720
051CA708: 83 C4 10           -  add esp,10
051CA70B: C9                 -  leave 
051CA70C: C3                 -  ret 
051CA70D: 00 00              -  add [eax],al
051CA70F: 00 68 08           -  add [eax+08],ch
051CA712: 27                 -  daa 
051CA713: 3D 0C E9 0E 59     -  cmp eax,590EE90C
051CA718: BF FF 00 00 00     -  mov edi,000000FF
}"""

[[cheat]]
id = "add-exp"
name = "ADD EXP"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : My Lovely Daughter.exe
  Version: 1.00f3
  Date   : 2018-03-15
  Author : Herwin Yudha S

  ADD EXP 9999 To All Homunculus [Recommended to activate this cheat
  before work, after work in 2 days DISABLE this cheat]
  You'll know you should DISABLE it after work in 2 days.
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(addexp,89 48 1C 8B 05 00 DF B8 10) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov [eax+1C],ecx
  add [eax+1C],(int)9999
  mov eax,[10B8DF00]
  jmp return

addexp:
  jmp newmem
  nop
  nop
  nop
  nop
return:
registersymbol(addexp)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
addexp:
  db 89 48 1C 8B 05 00 DF B8 10

unregistersymbol(addexp)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 14D14BFF

14D14BDB: 8D 44 B0 10           -  lea eax,[eax+esi*4+10]
14D14BDF: 8B 00                 -  mov eax,[eax]
14D14BE1: 8B 58 20              -  mov ebx,[eax+20]
14D14BE4: 8B 05 00 DF B8 10     -  mov eax,[10B8DF00]
14D14BEA: 39 70 0C              -  cmp [eax+0C],esi
14D14BED: 0F 86 36 01 00 00     -  jbe 14D14D29
14D14BF3: 8D 44 B0 10           -  lea eax,[eax+esi*4+10]
14D14BF7: 8B 00                 -  mov eax,[eax]
14D14BF9: 8B 48 1C              -  mov ecx,[eax+1C]
14D14BFC: 03 4D 0C              -  add ecx,[ebp+0C]
// ---------- INJECTING HERE ----------
14D14BFF: 89 48 1C              -  mov [eax+1C],ecx
14D14C02: 8B 05 00 DF B8 10     -  mov eax,[10B8DF00]
// ---------- DONE INJECTING  ----------
14D14C08: 39 70 0C              -  cmp [eax+0C],esi
14D14C0B: 0F 86 11 01 00 00     -  jbe 14D14D22
14D14C11: 8D 44 B0 10           -  lea eax,[eax+esi*4+10]
14D14C15: 8B 00                 -  mov eax,[eax]
14D14C17: C6 40 2E 01           -  mov byte ptr [eax+2E],01
14D14C1B: 83 FB 0A              -  cmp ebx,0A
14D14C1E: 0F 8D AA 00 00 00     -  jnl 14D14CCE
14D14C24: 8B 05 00 DF B8 10     -  mov eax,[10B8DF00]
14D14C2A: 39 70 0C              -  cmp [eax+0C],esi
14D14C2D: 0F 86 E8 00 00 00     -  jbe 14D14D1B
}"""

[[cheat]]
id = "add-affection"
name = "ADD AFFECTION"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : My Lovely Daughter.exe
  Version: 1.00f3
  Date   : 2018-03-15
  Author : Herwin Yudha S

  Set Affection Always 1000 [Recommended to always activate this cheat]
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(addaffection,89 48 28 33 FF) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov [eax+28],(int)1000
  xor edi,edi
  jmp return

addaffection:
  jmp newmem
return:
registersymbol(addaffection)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
addaffection:
  db 89 48 28 33 FF

unregistersymbol(addaffection)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 14D14D5D

14D14D3C: 56                    -  push esi
14D14D3D: 8B 75 08              -  mov esi,[ebp+08]
14D14D40: 8B 7D 0C              -  mov edi,[ebp+0C]
14D14D43: 8B 05 00 DF B8 10     -  mov eax,[10B8DF00]
14D14D49: 39 70 0C              -  cmp [eax+0C],esi
14D14D4C: 0F 86 F2 00 00 00     -  jbe 14D14E44
14D14D52: 8D 44 B0 10           -  lea eax,[eax+esi*4+10]
14D14D56: 8B 00                 -  mov eax,[eax]
14D14D58: 8B 48 28              -  mov ecx,[eax+28]
14D14D5B: 03 CF                 -  add ecx,edi
// ---------- INJECTING HERE ----------
14D14D5D: 89 48 28              -  mov [eax+28],ecx
14D14D60: 33 FF                 -  xor edi,edi
// ---------- DONE INJECTING  ----------
14D14D62: 8B 05 00 DF B8 10     -  mov eax,[10B8DF00]
14D14D68: 39 70 0C              -  cmp [eax+0C],esi
14D14D6B: 0F 86 CC 00 00 00     -  jbe 14D14E3D
14D14D71: 8D 44 B0 10           -  lea eax,[eax+esi*4+10]
14D14D75: 8B 00                 -  mov eax,[eax]
14D14D77: 8B 40 28              -  mov eax,[eax+28]
14D14D7A: 85 C0                 -  test eax,eax
14D14D7C: 7F 38                 -  jg 14D14DB6
14D14D7E: 8B 05 00 DF B8 10     -  mov eax,[10B8DF00]
14D14D84: 39 70 0C              -  cmp [eax+0C],esi
}"""

[[cheat]]
id = "no-sub-gift"
name = "NO SUB GIFT"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : My Lovely Daughter.exe
  Version: 1.00f3
  Date   : 2018-03-15
  Author : Herwin Yudha S

  Your GIFT Item Always 99 [Recommended to always activate this cheat]
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(subgift,89 08 8B 05 00 3E 4C 03) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov [eax],(int)99
  mov eax,[034C3E00]
  jmp return

subgift:
  jmp newmem
  nop
  nop
  nop
return:
registersymbol(subgift)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
subgift:
  db 89 08 8B 05 00 3E 4C 03

unregistersymbol(subgift)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 14D1FEE1

14D1FEBB: E8 04 D8 48 F0                 -  call 051AD6C4
14D1FEC0: 83 C4 10                       -  add esp,10
14D1FEC3: E9 6D 00 00 00                 -  jmp 14D1FF35
14D1FEC8: 8B 05 D4 EE 4B 03              -  mov eax,[034BEED4]
14D1FECE: 8B 4F 34                       -  mov ecx,[edi+34]
14D1FED1: 39 48 0C                       -  cmp [eax+0C],ecx
14D1FED4: 0F 86 61 00 00 00              -  jbe 14D1FF3B
14D1FEDA: 8D 44 88 10                    -  lea eax,[eax+ecx*4+10]
14D1FEDE: 8B 08                          -  mov ecx,[eax]
14D1FEE0: 49                             -  dec ecx
// ---------- INJECTING HERE ----------
14D1FEE1: 89 08                          -  mov [eax],ecx
14D1FEE3: 8B 05 00 3E 4C 03              -  mov eax,[034C3E00]
// ---------- DONE INJECTING  ----------
14D1FEE9: C7 80 D8 00 00 00 0B 00 00 00  -  mov [eax+000000D8],0000000B
14D1FEF3: 8B 47 2C                       -  mov eax,[edi+2C]
14D1FEF6: 83 EC 0C                       -  sub esp,0C
14D1FEF9: 50                             -  push eax
14D1FEFA: 39 00                          -  cmp [eax],eax
14D1FEFC: E8 C7 DC 48 F0                 -  call 051ADBC8
14D1FF01: 83 C4 10                       -  add esp,10
14D1FF04: 8B 47 30                       -  mov eax,[edi+30]
14D1FF07: 8B 4F 34                       -  mov ecx,[edi+34]
14D1FF0A: 83 EC 08                       -  sub esp,08
}"""

[[cheat]]
id = "add-soul-affinity"
name = "ADD SOUL AFFINITY"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : My Lovely Daughter.exe
  Version: 1.00f3
  Date   : 2018-03-15
  Author : Herwin Yudha S

  You can add Soul Affinity by Burning Item that Correspond to the type
  of Affinity. Joy/Sad/Anger/Fear.
  [Recommended is yes, but it's up to you to activate this cheat]
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(subhapaffi2,89 08 8B 05 F4 DE B8 10 39 70) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov [eax],(int)1000
  mov eax,[10B8DEF4]
  jmp return

subhapaffi2:
  jmp newmem
  nop
  nop
  nop
return:
registersymbol(subhapaffi2)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
subhapaffi2:
  db 89 08 8B 05 F4 DE B8 10

unregistersymbol(subhapaffi2)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 052108FB

052108DB: 53                 -  push ebx
052108DC: 56                 -  push esi
052108DD: 83 EC 10           -  sub esp,10
052108E0: 8B 75 08           -  mov esi,[ebp+08]
052108E3: 8B 05 F4 DE B8 10  -  mov eax,[10B8DEF4]
052108E9: 39 70 0C           -  cmp [eax+0C],esi
052108EC: 0F 86 C3 00 00 00  -  jbe 052109B5
052108F2: 8D 44 B0 10        -  lea eax,[eax+esi*4+10]
052108F6: 8B 08              -  mov ecx,[eax]
052108F8: 03 4D 0C           -  add ecx,[ebp+0C]
// ---------- INJECTING HERE ----------
052108FB: 89 08              -  mov [eax],ecx
052108FD: 8B 05 F4 DE B8 10  -  mov eax,[10B8DEF4]
// ---------- DONE INJECTING  ----------
05210903: 39 70 0C           -  cmp [eax+0C],esi
05210906: 0F 86 A2 00 00 00  -  jbe 052109AE
0521090C: 8D 44 B0 10        -  lea eax,[eax+esi*4+10]
05210910: 8B 00              -  mov eax,[eax]
05210912: 85 C0              -  test eax,eax
05210914: 7D 35              -  jnl 0521094B
05210916: 8B 05 F4 DE B8 10  -  mov eax,[10B8DEF4]
0521091C: 39 70 0C           -  cmp [eax+0C],esi
0521091F: 0F 86 82 00 00 00  -  jbe 052109A7
05210925: 8D 44 B0 10        -  lea eax,[eax+esi*4+10]
}"""
