[game]
name = "Rogue Spirit"
exe = "roguespirit-win64-shipping.exe"
notes = "Converted from a Cheat Engine table by KyleKatarn. Source: https://fearlessrevolution.com/viewtopic.php?t=20928"
verified = []
author = "KyleKatarn"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "inf-stamina"
name = "Inf Stamina"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game Executable   : RogueSpirit-Win64-Shipping.exe
  Author            : Beast
  Executable Version: 4.27.2.0
  Module Version    : 
  Script Date       : 2022-07-28
}
[ENABLE]

aobscanmodule(Stamina,RogueSpirit-Win64-Shipping.exe,F3 0F 11 8B C8 00 00 00 48)
registersymbol(Stamina)

alloc(bytesStamina,8)
registersymbol(bytesStamina)

bytesStamina:
  readmem(Stamina,8)

Stamina:
  db 90 90 90 90 90 90 90 90

[DISABLE]

Stamina:
  readmem(bytesStamina,8)

unregistersymbol(Stamina)
unregistersymbol(bytesStamina)
dealloc(bytesStamina)
{
// ORIGINAL CODE - INJECTION POINT: RogueSpirit-Win64-Shipping.exe+F59D64

RogueSpirit-Win64-Shipping.exe+F59D16: 48 8B C8                 - mov rcx,rax
RogueSpirit-Win64-Shipping.exe+F59D19: 48 8B 47 30              - mov rax,[rdi+30]
RogueSpirit-Win64-Shipping.exe+F59D1D: 48 39 14 C8              - cmp [rax+rcx*8],rdx
RogueSpirit-Win64-Shipping.exe+F59D21: 74 02                    - je RogueSpirit-Win64-Shipping.exe+F59D25
RogueSpirit-Win64-Shipping.exe+F59D23: 33 FF                    - xor edi,edi
RogueSpirit-Win64-Shipping.exe+F59D25: 48 8D 8E E0 00 00 00     - lea rcx,[rsi+000000E0]
RogueSpirit-Win64-Shipping.exe+F59D2C: 48 8B D7                 - mov rdx,rdi
RogueSpirit-Win64-Shipping.exe+F59D2F: E8 DC 88 ED 01           - call RogueSpirit-Win64-Shipping.exe+2E32610
RogueSpirit-Win64-Shipping.exe+F59D34: 48 85 C0                 - test rax,rax
RogueSpirit-Win64-Shipping.exe+F59D37: 74 06                    - je RogueSpirit-Win64-Shipping.exe+F59D3F
RogueSpirit-Win64-Shipping.exe+F59D39: 80 78 38 06              - cmp byte ptr [rax+38],06
RogueSpirit-Win64-Shipping.exe+F59D3D: 74 2D                    - je RogueSpirit-Win64-Shipping.exe+F59D6C
RogueSpirit-Win64-Shipping.exe+F59D3F: 40 80 FD 01              - cmp bpl,01
RogueSpirit-Win64-Shipping.exe+F59D43: 75 08                    - jne RogueSpirit-Win64-Shipping.exe+F59D4D
RogueSpirit-Win64-Shipping.exe+F59D45: F3 0F 10 B3 D8 00 00 00  - movss xmm6,[rbx+000000D8]
RogueSpirit-Win64-Shipping.exe+F59D4D: F3 0F 10 8B C8 00 00 00  - movss xmm1,[rbx+000000C8]
RogueSpirit-Win64-Shipping.exe+F59D55: 0F 57 C0                 - xorps xmm0,xmm0
RogueSpirit-Win64-Shipping.exe+F59D58: F3 0F 59 F7              - mulss xmm6,xmm7
RogueSpirit-Win64-Shipping.exe+F59D5C: F3 0F 5C CE              - subss xmm1,xmm6
RogueSpirit-Win64-Shipping.exe+F59D60: F3 0F 5F C8              - maxss xmm1,xmm0
// ---------- INJECTING HERE ----------
RogueSpirit-Win64-Shipping.exe+F59D64: F3 0F 11 8B C8 00 00 00  - movss [rbx+000000C8],xmm1
// ---------- DONE INJECTING  ----------
RogueSpirit-Win64-Shipping.exe+F59D6C: 48 8B 5C 24 50           - mov rbx,[rsp+50]
RogueSpirit-Win64-Shipping.exe+F59D71: 48 8B 6C 24 58           - mov rbp,[rsp+58]
RogueSpirit-Win64-Shipping.exe+F59D76: 48 8B 74 24 60           - mov rsi,[rsp+60]
RogueSpirit-Win64-Shipping.exe+F59D7B: 0F 28 74 24 30           - movaps xmm6,[rsp+30]
RogueSpirit-Win64-Shipping.exe+F59D80: 0F 28 7C 24 20           - movaps xmm7,[rsp+20]
RogueSpirit-Win64-Shipping.exe+F59D85: 48 83 C4 40              - add rsp,40
RogueSpirit-Win64-Shipping.exe+F59D89: 5F                       - pop rdi
RogueSpirit-Win64-Shipping.exe+F59D8A: C3                       - ret 
RogueSpirit-Win64-Shipping.exe+F59D8B: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F59D8C: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F59D8D: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F59D8E: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F59D8F: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F59D90: 48 8B 81 50 02 00 00     - mov rax,[rcx+00000250]
RogueSpirit-Win64-Shipping.exe+F59D97: F3 0F 10 0D 15 1C A1 02  - movss xmm1,[RogueSpirit-Win64-Shipping.exe+396B9B4]
RogueSpirit-Win64-Shipping.exe+F59D9F: 48 85 C0                 - test rax,rax
RogueSpirit-Win64-Shipping.exe+F59DA2: 74 03                    - je RogueSpirit-Win64-Shipping.exe+F59DA7
RogueSpirit-Win64-Shipping.exe+F59DA4: 48 8B C8                 - mov rcx,rax
RogueSpirit-Win64-Shipping.exe+F59DA7: E9 94 47 8B 01           - jmp RogueSpirit-Win64-Shipping.exe+280E540
RogueSpirit-Win64-Shipping.exe+F59DAC: CC                       - int 3 
}"""

[[cheat]]
id = "inf-spirit"
name = "Inf Spirit"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game Executable   : RogueSpirit-Win64-Shipping.exe
  Author            : Beast
  Executable Version: 4.27.2.0
  Module Version    : 
  Script Date       : 2022-07-28
F3 0F 11 81 B0 00 00 00 33
F3xxxxxxxxxxxxxx33xxxxxxxxxxE9xxxxxxxxxxE9xxxxxxxxxxCC
}
[ENABLE]

aobscanmodule(Spirit,RogueSpirit-Win64-Shipping.exe,F3xxxxxxxxxxxxxx33xxxxxxxxxxE9xxxxxxxxxxE9xxxxxxxxxxCC)
registersymbol(Spirit)

alloc(bytesSpirit,1)
registersymbol(bytesSpirit)

bytesSpirit:
  readmem(Spirit-1,1)

Spirit-1:
  db C9

[DISABLE]

Spirit-1:
  readmem(bytesSpirit,1)

unregistersymbol(Spirit)
unregistersymbol(bytesSpirit)
dealloc(bytesSpirit)
{
// ORIGINAL CODE - INJECTION POINT: RogueSpirit-Win64-Shipping.exe+F3F9BC

RogueSpirit-Win64-Shipping.exe+F3F98A: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F98B: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F98C: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F98D: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F98E: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F98F: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F990: F3 0F 58 49 2C           - addss xmm1,[rcx+2C]
RogueSpirit-Win64-Shipping.exe+F3F995: F3 0F 11 49 2C           - movss [rcx+2C],xmm1
RogueSpirit-Win64-Shipping.exe+F3F99A: C3                       - ret 
RogueSpirit-Win64-Shipping.exe+F3F99B: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F99C: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F99D: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F99E: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F99F: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9A0: F3 0F 58 89 B0 00 00 00  - addss xmm1,[rcx+000000B0]
RogueSpirit-Win64-Shipping.exe+F3F9A8: 0F 57 C0                 - xorps xmm0,xmm0
RogueSpirit-Win64-Shipping.exe+F3F9AB: 0F 2F C8                 - comiss xmm1,xmm0
RogueSpirit-Win64-Shipping.exe+F3F9AE: 72 0C                    - jb RogueSpirit-Win64-Shipping.exe+F3F9BC
RogueSpirit-Win64-Shipping.exe+F3F9B0: F3 0F 10 81 B4 00 00 00  - movss xmm0,[rcx+000000B4]
RogueSpirit-Win64-Shipping.exe+F3F9B8: F3 0F 5D C1              - minss xmm0,xmm1
// ---------- INJECTING HERE ----------
RogueSpirit-Win64-Shipping.exe+F3F9BC: F3 0F 11 81 B0 00 00 00  - movss [rcx+000000B0],xmm0
// ---------- DONE INJECTING  ----------
RogueSpirit-Win64-Shipping.exe+F3F9C4: 33 D2                    - xor edx,edx
RogueSpirit-Win64-Shipping.exe+F3F9C6: 48 83 C1 30              - add rcx,30
RogueSpirit-Win64-Shipping.exe+F3F9CA: E9 D1 26 90 FF           - jmp RogueSpirit-Win64-Shipping.exe+8420A0
RogueSpirit-Win64-Shipping.exe+F3F9CF: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9D0: E9 AB 2A 04 00           - jmp RogueSpirit-Win64-Shipping.exe+F82480
RogueSpirit-Win64-Shipping.exe+F3F9D5: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9D6: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9D7: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9D8: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9D9: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9DA: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9DB: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9DC: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9DD: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9DE: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9DF: CC                       - int 3 
RogueSpirit-Win64-Shipping.exe+F3F9E0: F3 0F 59 49 2C           - mulss xmm1,[rcx+2C]
RogueSpirit-Win64-Shipping.exe+F3F9E5: F3 0F 11 49 2C           - movss [rcx+2C],xmm1
RogueSpirit-Win64-Shipping.exe+F3F9EA: C3                       - ret 
RogueSpirit-Win64-Shipping.exe+F3F9EB: CC                       - int 3 
}"""

[[cheat]]
id = "no-currency-consume-only-activate-when-buying-something"
name = "No Currency Consume (Only activate when buying something)"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game Executable   : RogueSpirit-Win64-Shipping.exe
  Author            : Beast
  Executable Version: 4.27.2.0
  Module Version    : 
  Script Date       : 2022-07-28
}
[ENABLE]

aobscanmodule(Currency,RogueSpirit-Win64-Shipping.exe,44 01 77 08 33 C0)
registersymbol(Currency)

alloc(bytesCurrency,6)
registersymbol(bytesCurrency)

bytesCurrency:
  readmem(Currency,6)

Currency:
  db 90 90 90 90 90 90

[DISABLE]

Currency:
  readmem(bytesCurrency,6)

unregistersymbol(Currency)
unregistersymbol(bytesCurrency)
dealloc(bytesCurrency)
{
// ORIGINAL CODE - INJECTION POINT: RogueSpirit-Win64-Shipping.exe+F3F72E

RogueSpirit-Win64-Shipping.exe+F3F6F0: 48 8B 17              - mov rdx,[rdi]
RogueSpirit-Win64-Shipping.exe+F3F6F3: 4C 8D 40 30           - lea r8,[rax+30]
RogueSpirit-Win64-Shipping.exe+F3F6F7: 48 63 40 38           - movsxd  rax,dword ptr [rax+38]
RogueSpirit-Win64-Shipping.exe+F3F6FB: 3B 42 38              - cmp eax,[rdx+38]
RogueSpirit-Win64-Shipping.exe+F3F6FE: 7F 0D                 - jg RogueSpirit-Win64-Shipping.exe+F3F70D
RogueSpirit-Win64-Shipping.exe+F3F700: 48 8B C8              - mov rcx,rax
RogueSpirit-Win64-Shipping.exe+F3F703: 48 8B 42 30           - mov rax,[rdx+30]
RogueSpirit-Win64-Shipping.exe+F3F707: 4C 39 04 C8           - cmp [rax+rcx*8],r8
RogueSpirit-Win64-Shipping.exe+F3F70B: 74 02                 - je RogueSpirit-Win64-Shipping.exe+F3F70F
RogueSpirit-Win64-Shipping.exe+F3F70D: 33 D2                 - xor edx,edx
RogueSpirit-Win64-Shipping.exe+F3F70F: 48 85 F6              - test rsi,rsi
RogueSpirit-Win64-Shipping.exe+F3F712: 74 61                 - je RogueSpirit-Win64-Shipping.exe+F3F775
RogueSpirit-Win64-Shipping.exe+F3F714: 48 63 46 38           - movsxd  rax,dword ptr [rsi+38]
RogueSpirit-Win64-Shipping.exe+F3F718: 48 83 C6 30           - add rsi,30
RogueSpirit-Win64-Shipping.exe+F3F71C: 3B 42 38              - cmp eax,[rdx+38]
RogueSpirit-Win64-Shipping.exe+F3F71F: 7F 54                 - jg RogueSpirit-Win64-Shipping.exe+F3F775
RogueSpirit-Win64-Shipping.exe+F3F721: 48 8B C8              - mov rcx,rax
RogueSpirit-Win64-Shipping.exe+F3F724: 48 8B 42 30           - mov rax,[rdx+30]
RogueSpirit-Win64-Shipping.exe+F3F728: 48 39 34 C8           - cmp [rax+rcx*8],rsi
RogueSpirit-Win64-Shipping.exe+F3F72C: 75 47                 - jne RogueSpirit-Win64-Shipping.exe+F3F775
// ---------- INJECTING HERE ----------
RogueSpirit-Win64-Shipping.exe+F3F72E: 44 01 77 08           - add [rdi+08],r14d
// ---------- DONE INJECTING  ----------
RogueSpirit-Win64-Shipping.exe+F3F732: 33 C0                 - xor eax,eax
RogueSpirit-Win64-Shipping.exe+F3F734: 48 85 DB              - test rbx,rbx
RogueSpirit-Win64-Shipping.exe+F3F737: 74 1F                 - je RogueSpirit-Win64-Shipping.exe+F3F758
RogueSpirit-Win64-Shipping.exe+F3F739: 48 8B 83 18 01 00 00  - mov rax,[rbx+00000118]
RogueSpirit-Win64-Shipping.exe+F3F740: 48 85 C0              - test rax,rax
RogueSpirit-Win64-Shipping.exe+F3F743: 75 13                 - jne RogueSpirit-Win64-Shipping.exe+F3F758
RogueSpirit-Win64-Shipping.exe+F3F745: 48 8B 03              - mov rax,[rbx]
RogueSpirit-Win64-Shipping.exe+F3F748: 48 8B CB              - mov rcx,rbx
RogueSpirit-Win64-Shipping.exe+F3F74B: FF 90 A0 03 00 00     - call qword ptr [rax+000003A0]
RogueSpirit-Win64-Shipping.exe+F3F751: 48 8B 83 18 01 00 00  - mov rax,[rbx+00000118]
RogueSpirit-Win64-Shipping.exe+F3F758: 8B 40 40              - mov eax,[rax+40]
RogueSpirit-Win64-Shipping.exe+F3F75B: 85 C0                 - test eax,eax
RogueSpirit-Win64-Shipping.exe+F3F75D: 7E 13                 - jle RogueSpirit-Win64-Shipping.exe+F3F772
RogueSpirit-Win64-Shipping.exe+F3F75F: 8B 4F 08              - mov ecx,[rdi+08]
RogueSpirit-Win64-Shipping.exe+F3F762: 85 C9                 - test ecx,ecx
RogueSpirit-Win64-Shipping.exe+F3F764: 79 04                 - jns RogueSpirit-Win64-Shipping.exe+F3F76A
RogueSpirit-Win64-Shipping.exe+F3F766: 33 C0                 - xor eax,eax
RogueSpirit-Win64-Shipping.exe+F3F768: EB 05                 - jmp RogueSpirit-Win64-Shipping.exe+F3F76F
RogueSpirit-Win64-Shipping.exe+F3F76A: 3B C8                 - cmp ecx,eax
RogueSpirit-Win64-Shipping.exe+F3F76C: 0F 4C C1              - cmovl eax,ecx
}"""

[[cheat]]
id = "characterpointer"
name = "CharacterPointer"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]

aobscanmodule(Character,$process,48 8B BF 40 02 00 00 EB) // should be unique
alloc(newmem,$1000,Character)

label(code)
label(return)

newmem:
  mov [CharacterPointer],rdi //Pointer

code:
  mov rdi,[rdi+00000240]
  jmp return

CharacterPointer: //Pointer
  dq 0

Character:
  jmp newmem
  nop 2
return:
registersymbol(Character)
registersymbol(CharacterPointer)

[DISABLE]

Character:
  db 48 8B BF 40 02 00 00

unregistersymbol(Character)
unregistersymbol(CharacterPointer)
dealloc(newmem)"""

[[cheat]]
id = "maxwalkspeed"
name = "MaxWalkSpeed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x288",
    "+0x18c",
]

[[cheat]]
id = "movementmode"
name = "MovementMode"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x288",
    "+0x168",
]

[[cheat]]
id = "health"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x4d0",
    "+0x100",
]

[[cheat]]
id = "maxhealth"
name = "MaxHealth"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x4d0",
    "+0x104",
]

[[cheat]]
id = "bimmortal"
name = "bImmortal"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:False",
    "1:True",
]

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x4d0",
    "+0x10c",
]

[[cheat]]
id = "canregenerate"
name = "CanRegenerate"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:False",
    "1:True",
]

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x4d0",
    "+0x10f",
]

[[cheat]]
id = "isbleeding"
name = "IsBleeding"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:False",
    "1:True",
]

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x4d0",
    "+0x119",
]

[[cheat]]
id = "damagemultiplier"
name = "DamageMultiplier"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x4d0",
    "+0x124",
]

[[cheat]]
id = "itemdropchance"
name = "ItemDropChance"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x698",
    "+0x140",
]

[[cheat]]
id = "raredropchance"
name = "RareDropChance"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x698",
    "+0x144",
]

[[cheat]]
id = "legendarydropchance"
name = "LegendaryDropChance"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x698",
    "+0x148",
]

[[cheat]]
id = "tokenondyingmultiplier"
name = "TokenOnDyingMultiplier"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x698",
    "+0x160",
]

[[cheat]]
id = "healthglobehealthtoadd"
name = "HealthGlobeHealthToAdd"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x698",
    "+0x164",
]

[[cheat]]
id = "coinpursedropifcoinsmorethan"
name = "CoinPurseDropIfCoinsMoreThan"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x698",
    "+0x168",
]

[[cheat]]
id = "ghostpossesscost"
name = "GhostPossessCost"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x698",
    "+0x3e0",
]

[[cheat]]
id = "stamina"
name = "Stamina"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x5a0",
    "+0xc8",
]

[[cheat]]
id = "maxstamina"
name = "MaxStamina"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x5a0",
    "+0xd0",
]

[[cheat]]
id = "playerdiscoverydistance"
name = "PlayerDiscoveryDistance"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "CharacterPointer"
hops = [
    "+0x258",
    "+0x298",
    "+0x70",
    "+0x78",
    "+0x118",
    "+0x338",
    "+0xb4",
]
