[game]
name = "ELDEN RING NIGHTREIGN"
exe = "nightreign.exe"
notes = "Converted from a Cheat Engine table by matthew80. Source: https://fearlessrevolution.com/viewtopic.php?t=35248"
verified = []
author = "matthew80"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "cur-health"
name = "cur health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "liststat"
hops = ["+0x140"]

[[cheat]]
id = "max-health"
name = "max health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "liststat"
hops = ["+0x14c"]

[[cheat]]
id = "cur-fp"
name = "cur fp"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "liststat"
hops = ["+0x150"]

[[cheat]]
id = "max-fp"
name = "max fp"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "liststat"
hops = ["+0x154"]

[[cheat]]
id = "cur-stamina"
name = "cur stamina"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "liststat"
hops = ["+0x15c"]

[[cheat]]
id = "max-stamina"
name = "max stamina"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "liststat"
hops = ["+0x160"]

[[cheat]]
id = "level"
name = "level"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x68"]

[[cheat]]
id = "vigor"
name = "vigor"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x34"]

[[cheat]]
id = "mind"
name = "mind"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x38"]

[[cheat]]
id = "endurance"
name = "endurance"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x3c"]

[[cheat]]
id = "strength"
name = "strength"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x40"]

[[cheat]]
id = "dexterity"
name = "dexterity"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x44"]

[[cheat]]
id = "intelligence"
name = "intelligence"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x48"]

[[cheat]]
id = "faith"
name = "faith"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x4c"]

[[cheat]]
id = "arcane"
name = "arcane"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listattribute"
hops = ["+0x50"]

[[cheat]]
id = "currency"
name = "currency"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : nightreign.exe
  Version:
  Date   : 2025-07-03
  Author : Matthew80

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(currency,nightreign.exe,41 8B 46 6C 89 86 1C 01 00 00) // should be unique
alloc(newmem,$1000,currency)

label(code)
label(return)
label(listcurrency)
registersymbol(listcurrency)

newmem:

code:
  mov [listcurrency],r14
  mov eax,[r14+6C]
  mov [rsi+0000011C],eax
  jmp return
  listcurrency:
  dd 0

currency:
  jmp newmem
  nop 5
return:
registersymbol(currency)

[DISABLE]

currency:
  db 41 8B 46 6C 89 86 1C 01 00 00

unregistersymbol(*)
dealloc(*)

{
// ORIGINAL CODE - INJECTION POINT: nightreign.exe+7F299D

nightreign.exe+7F296D: 4C 8D 45 20                    - lea r8,[rbp+20]
nightreign.exe+7F2971: 49 8B D6                       - mov rdx,r14
nightreign.exe+7F2974: B9 06 00 00 00                 - mov ecx,00000006
nightreign.exe+7F2979: E8 32 7B EA FF                 - call nightreign.exe+69A4B0
nightreign.exe+7F297E: F3 0F 59 C7                    - mulss xmm0,xmm7
nightreign.exe+7F2982: F3 0F 2C C0                    - cvttss2si eax,xmm0
nightreign.exe+7F2986: 89 86 F8 00 00 00              - mov [rsi+000000F8],eax
nightreign.exe+7F298C: 41 0F BA E4 0A                 - bt r12d,0A
nightreign.exe+7F2991: 73 14                          - jae nightreign.exe+7F29A7
nightreign.exe+7F2993: C7 86 18 01 00 00 00 00 00 00  - mov [rsi+00000118],00000000
// ---------- INJECTING HERE ----------
nightreign.exe+7F299D: 41 8B 46 6C                    - mov eax,[r14+6C]
// ---------- DONE INJECTING  ----------
nightreign.exe+7F29A1: 89 86 1C 01 00 00              - mov [rsi+0000011C],eax
nightreign.exe+7F29A7: 41 0F BA E4 0B                 - bt r12d,0B
nightreign.exe+7F29AC: 73 15                          - jae nightreign.exe+7F29C3
nightreign.exe+7F29AE: 48 8B 06                       - mov rax,[rsi]
nightreign.exe+7F29B1: 4D 8D 86 D8 01 00 00           - lea r8,[r14+000001D8]
nightreign.exe+7F29B8: 48 8B 54 24 48                 - mov rdx,[rsp+48]
nightreign.exe+7F29BD: 48 8B CE                       - mov rcx,rsi
nightreign.exe+7F29C0: FF 50 28                       - call qword ptr [rax+28]
nightreign.exe+7F29C3: B0 01                          - mov al,01
nightreign.exe+7F29C5: 48 8B 4D 50                    - mov rcx,[rbp+50]
}"""

[[cheat]]
id = "rune"
name = "rune"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listcurrency"
hops = ["+0x6c"]

[[cheat]]
id = "murk"
name = "murk"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listcurrency"
hops = ["+0xd0"]

[[cheat]]
id = "sovereign-sigil"
name = "sovereign sigil"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "listcurrency"
hops = ["+0x5c"]

[[cheat]]
id = "multiply-by"
name = "multiply by"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "multiply"
hops = []

[[cheat]]
id = "player"
name = "player"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "playerSpeed"
hops = []

[[cheat]]
id = "enemy"
name = "enemy"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "enemySpeed"
hops = []

[[cheat]]
id = "pos-x"
name = "pos x"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "posxyz"
hops = ["+0x70"]

[[cheat]]
id = "pos-y"
name = "pos y"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "posxyz"
hops = ["+0x74"]

[[cheat]]
id = "pos-z"
name = "pos z"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "posxyz"
hops = ["+0x78"]

[[cheat]]
id = "night-s-tide-x100"
name = "Night's Tide x100"
category = "game"
description = ""
hint = ""
type = "script"
source = """
{ Game   : nightreign.exe
  Version: 
  Date   : 2025-06-20
  Original Author : Cissa90
  Update by: Matthew80

  This script does blah blah blah
}

[ENABLE]


aobscanmodule(tide,nightreign.exe,F3 0F 59 0D 81 DF BA 02) // should be unique
alloc(newmem,$1000,tide)

label(code)
label(return)
registersymbol(MultiTimer)
label(MultiTimer)

newmem:

code:
  mulss xmm1,[MultiTimer]
  jmp return
  MultiTimer:
  dd (float)100000

tide:
  jmp newmem
  nop 3
return:
registersymbol(tide)

[DISABLE]

tide:
  db F3 0F 59 0D 81 DF BA 02

unregistersymbol(*)
dealloc(*)

{
// ORIGINAL CODE - INJECTION POINT: nightreign.exe+66C7F7

nightreign.exe+66C7C8: 48 8B CB                 - mov rcx,rbx
nightreign.exe+66C7CB: 48 89 B4 24 A8 00 00 00  - mov [rsp+000000A8],rsi
nightreign.exe+66C7D3: 4C 89 74 24 70           - mov [rsp+70],r14
nightreign.exe+66C7D8: 0F 29 7C 24 50           - movaps [rsp+50],xmm7
nightreign.exe+66C7DD: E8 DE 34 FF FF           - call nightreign.exe+65FCC0
nightreign.exe+66C7E2: 48 8B 2F                 - mov rbp,[rdi]
nightreign.exe+66C7E5: 0F 28 CE                 - movaps xmm1,xmm6
nightreign.exe+66C7E8: F3 0F 59 8B 18 01 00 00  - mulss xmm1,[rbx+00000118]
nightreign.exe+66C7F0: 0F 28 F8                 - movaps xmm7,xmm0
nightreign.exe+66C7F3: 4C 8B 77 08              - mov r14,[rdi+08]
// ---------- INJECTING HERE ----------
nightreign.exe+66C7F7: F3 0F 59 0D 81 DF BA 02  - mulss xmm1,[nightreign.exe+321A780]
// ---------- DONE INJECTING  ----------
nightreign.exe+66C7FF: F3 0F 2C F1              - cvttss2si esi,xmm1
nightreign.exe+66C803: 85 F6                    - test esi,esi
nightreign.exe+66C805: 7E 7F                    - jle nightreign.exe+66C886
nightreign.exe+66C807: 48 8B CF                 - mov rcx,rdi
nightreign.exe+66C80A: E8 01 A0 A4 01           - call nightreign.exe+20B6810
nightreign.exe+66C80F: 48 8B 57 08              - mov rdx,[rdi+08]
nightreign.exe+66C813: C6 44 24 40 01           - mov byte ptr [rsp+40],01
nightreign.exe+66C818: 4C 8B DA                 - mov r11,rdx
nightreign.exe+66C81B: 49 C1 EB 0C              - shr r11,0C
nightreign.exe+66C81F: 4C 8B D2                 - mov r10,rdx
}"""
