[game]
name = "10 Minutes Till Dawn"
exe = "minutestilldawn.exe"
notes = "Converted from a Cheat Engine table by EpicBirdi. Source: https://fearlessrevolution.com/viewtopic.php?t=20166"
verified = []
author = "EpicBirdi"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "current-level-max-45"
name = "Current Level (Max 45)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "_pXP"
hops = ["+0x30"]

[[cheat]]
id = "total-xp-don-t-go-above-15000"
name = "Total XP (Don't go above 15000!!)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pXP"
hops = ["+0x34"]

[[cheat]]
id = "in-transition"
name = "In Transition"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:False",
    "1:True",
]

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x20",
]

[[cheat]]
id = "max-hp"
name = "Max HP"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x40",
    "+0x40",
]

[[cheat]]
id = "current-hp"
name = "Current HP"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x40",
    "+0x48",
]

[[cheat]]
id = "invincible-flag"
name = "Invincible Flag"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x40",
    "+0x48",
]

[[cheat]]
id = "movement-speed"
name = "Movement Speed"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x90",
]

[[cheat]]
id = "movement-speed-multiplier"
name = "Movement Speed Multiplier"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x9c",
]

[[cheat]]
id = "namestringid"
name = "nameStringID"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x18",
]

[[cheat]]
id = "descriptionstringid"
name = "descriptionStringID"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x20",
]

[[cheat]]
id = "damage"
name = "Damage"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x40",
]

[[cheat]]
id = "shot-cooldown"
name = "Shot Cooldown"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x44",
]

[[cheat]]
id = "max-ammo"
name = "Max Ammo"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x48",
]

[[cheat]]
id = "current-ammo"
name = "Current Ammo"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x58",
    "+0x38",
]

[[cheat]]
id = "reload-duration"
name = "Reload Duration"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x4c",
]

[[cheat]]
id = "number-of-projectiles"
name = "Number of Projectiles"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x50",
]

[[cheat]]
id = "spread"
name = "Spread"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x54",
]

[[cheat]]
id = "bullet-knockback"
name = "Bullet Knockback"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x58",
]

[[cheat]]
id = "projectile-speed"
name = "Projectile Speed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x5c",
]

[[cheat]]
id = "bounce"
name = "Bounce"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x60",
]

[[cheat]]
id = "piercing"
name = "Piercing"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x64",
]

[[cheat]]
id = "burn-chance"
name = "Burn Chance %"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x68",
]

[[cheat]]
id = "issummongun"
name = "isSummonGun"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:False",
    "1:True",
]

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x30",
    "+0x6c",
]

[[cheat]]
id = "is-shooting"
name = "Is Shooting"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:False",
    "1:True",
]

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x60",
]

[[cheat]]
id = "shot-timer"
name = "Shot Timer"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0
choices = [
    "0:False",
    "1:True",
]

[cheat.locator]
find = "symbol"
symbol = "_pBase"
hops = [
    "+0x18",
    "+0x50",
    "+0x64",
]

[[cheat]]
id = "maximum-time-elapsed-seconds"
name = "Maximum Time Elapsed (Seconds)"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "_gTimer"
hops = ["+0x18"]

[[cheat]]
id = "current-elapsed-time"
name = "Current Elapsed Time"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_gTimer"
hops = ["+0x1c"]

[[cheat]]
id = "currently-playing"
name = "Currently Playing"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:False - Timer Disabled",
    "1:True - Timer Enabled",
]

[cheat.locator]
find = "symbol"
symbol = "_gTimer"
hops = ["+0x20"]
