[game]
name = "Blur"
exe = "blur.exe"
notes = "Converted from a Cheat Engine table by Prismo. Source: https://fearlessrevolution.com/viewtopic.php?t=11812"
verified = []
author = "Prismo"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "position"
name = "Position"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "Blur.exe"
offset = "0xd33b34"
hops = [
    "+0x4c",
    "+0x0",
    "+0x38",
    "+0x90",
]

[[cheat]]
id = "armes"
name = "Armes"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "Blur.exe"
offset = "0xdeea04"
hops = [
    "+0x80",
    "+0x4",
    "+0x10",
    "+0x60",
    "+0x228",
]

[[cheat]]
id = "fans"
name = "Fans"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "Blur.exe"
offset = "0xdeea04"
hops = [
    "+0x7c",
    "+0x7a4",
    "+0x38",
]
