[game]
name = "Onechanbara Z2: Chaos"
exe = "onechanbaraz2.exe"
notes = "Converted from a Cheat Engine table by Cielos. Source: https://fearlessrevolution.com/viewtopic.php?t=185"
verified = []
author = "Cielos"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "enable"
name = "Enable"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
aobscanmodule(cPlayerHPReadRet,OnechanbaraZ2.exe,48 8D 8C 24 C8 00 00 00 0F 28 F0) //"OnechanbaraZ2.exe"+1A138D
registersymbol(cPlayerHPReadRet)
aobscanmodule(HPRead,OnechanbaraZ2.exe,0F 57 C0 C3 F3 0F 10 00 C3)
registersymbol(HPRead)

label(bMaxEcstasy)
registersymbol(bMaxEcstasy)
label(bCrossMergeReady)
registersymbol(bCrossMergeReady)
label(pCPlayer)
registersymbol(pCPlayer)

alloc(newmem,2048,HPRead+4) //"OnechanbaraZ2.exe"+190AEC)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here
push rbx
mov rbx,cPlayerHPReadRet
cmp [rsp+8],rbx
jne originalcode
mov [pCPlayer],rax
//movss xmm0,[rax]
cmp byte ptr [bMaxEcstasy],1
jne @f
mov dword ptr [rax+84],(float)3
@@:
cmp byte ptr [bCrossMergeReady],1
jne @f
mov dword ptr [rax+88],(float)1

originalcode:
pop rbx
movss xmm0,[rax]
ret 

exit:
jmp returnhere

///
bMaxEcstasy:
dd 0
bCrossMergeReady:
dd 0
pCPlayer:
///

HPRead+4: //"OnechanbaraZ2.exe"+190AEC:
jmp newmem
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
HPRead+4: //"OnechanbaraZ2.exe"+190AEC:
db F3 0F 10 00 C3
//Alt: movss xmm0,[rax]
//Alt: ret

unregistersymbol(bMaxEcstasy)
unregistersymbol(bCrossMergeReady)
unregistersymbol(pCPlayer)"""

[[cheat]]
id = "inf-vitality-controlling-character"
name = "Inf. Vitality (controlling character)"
category = "player"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
aobscanmodule(HPRead2OnHitAOB,OnechanbaraZ2.exe,F3 0F 10 08 F3 0F 5C C8)
registersymbol(HPRead2OnHitAOB)

alloc(newmem,2048,HPRead2OnHitAOB) //"OnechanbaraZ2.exe"+190582)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here
cmp [pCPlayer],rax
jne originalcode
xorps xmm0,xmm0

originalcode:
movss xmm1,[rax]
subss xmm1,xmm0

exit:
jmp returnhere

HPRead2OnHitAOB: //"OnechanbaraZ2.exe"+190582:
jmp newmem
nop
nop
nop
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
HPRead2OnHitAOB: //"OnechanbaraZ2.exe"+190582:
db F3 0F 10 08 F3 0F 5C C8
//Alt: movss xmm1,[rax]
//Alt: subss xmm1,xmm0"""

[[cheat]]
id = "max-ecstasy-controlling-character"
name = "Max Ecstasy (controlling character)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
bMaxEcstasy:
db 1

 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
bMaxEcstasy:
db 0"""

[[cheat]]
id = "cross-merge-ready"
name = "Cross Merge Ready"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
aobscanmodule(crossMergeZeroChkAOB,OnechanbaraZ2.exe,0F 2F A0 88 00 00 00 76 0F)
registersymbol(crossMergeZeroChkAOB)

alloc(newmem,2048,crossMergeZeroChkAOB) //"OnechanbaraZ2.exe"+19049A)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here
mov dword ptr [rax+88],(float)1

originalcode:
comiss xmm4,[rax+00000088]

exit:
jmp returnhere

///

crossMergeZeroChkAOB: //"OnechanbaraZ2.exe"+19049A:
jmp newmem
nop
nop
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
crossMergeZeroChkAOB: //"OnechanbaraZ2.exe"+19049A:
db 0F 2F A0 88 00 00 00
//Alt: comiss xmm4,[rax+00000088]"""

[[cheat]]
id = "cool-3"
name = "COOL .3"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
aobscanmodule(actionStatusWriteAOB,OnechanbaraZ2.exe,C0 E0 02 08 46 4C)
registersymbol(actionStatusWriteAOB)

alloc(newmem,2048,actionStatusWriteAOB) //"OnechanbaraZ2.exe"+E3AF4)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here
test al,al
jz originalcode
or al,3

originalcode:
shl al,02
or [rsi+4C],al

exit:
jmp returnhere

actionStatusWriteAOB: //"OnechanbaraZ2.exe"+E3AF4:
jmp newmem
nop
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
actionStatusWriteAOB: //"OnechanbaraZ2.exe"+E3AF4:
db C0 E0 02 08 46 4C
//Alt: shl al,02
//Alt: or [rsi+4C],al"""

[[cheat]]
id = "game-speed-fetch"
name = "Game Speed Fetch"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
label(pGameSpeed)
registersymbol(pGameSpeed)

alloc(newmem,2048,gameSpeedReadAOB+b) //"OnechanbaraZ2.exe"+190E58)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here
//comiss xmm0,[fCusGameSpeed+4]
//jne originalcode
push rax
push rbx
xor rax,rax
mov rbx,gameSpeedReadAOB
mov eax,[rbx+7]
lea rax,[rbx+rax+b]
mov [pGameSpeed],rax
//mov rax,gameSpeedReadAOB
//movzx eax,dword ptr [rax+7]
//lea rax,[gameSpeedReadAOB+rax+b]
//mov [fGameSpeed],rax

originalcode:
pop rbx
pop rax
ret 
int 3 
int 3 
int 3 
int 3 

exit:
jmp returnhere

///
pGameSpeed:
///

gameSpeedReadAOB+b: //"OnechanbaraZ2.exe"+190E58:
jmp newmem
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
gameSpeedReadAOB+b: //"OnechanbaraZ2.exe"+190E58:
db C3 CC CC CC CC
//Alt: ret
//Alt: int 3
//Alt: int 3
//Alt: int 3
//Alt: int 3

unregistersymbol(pGameSpeed)"""

[[cheat]]
id = "game-speed"
name = "Game Speed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "pGameSpeed"
hops = ["+0x0"]

[[cheat]]
id = "vitality"
name = "vitality"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "pCPlayer"
hops = ["+0x0"]

[[cheat]]
id = "ecstasy"
name = "ecstasy"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "pCPlayer"
hops = ["+0x84"]

[[cheat]]
id = "stain"
name = "stain"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "pCPlayer"
hops = ["+0xc"]

[[cheat]]
id = "cross-merge"
name = "cross merge"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "pCPlayer"
hops = ["+0x88"]

[[cheat]]
id = "weapon-1"
name = "weapon 1"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "pCPlayer"
hops = ["+0x20"]

[[cheat]]
id = "weapon-2"
name = "weapon 2"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "pCPlayer"
hops = ["+0x38"]
