[game]
name = "Sekiro Shadows Die Twice just auto parry(WIP)"
exe = "sekiro.exe"
notes = "Converted from a Cheat Engine table by fangg0219. Source: https://fearlessrevolution.com/viewtopic.php?t=11422"
verified = []
author = "fangg0219"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "read-player-ptr-aob"
name = "READ-player-ptr-aob"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : sekiro.exe
  Version: 
  Date   : 2020-01-26
  Author : holyy799

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(player,sekiro.exe,89 90 0C 0B 00 00) // should be unique
alloc(newmem,$1000,"sekiro.exe"+B43CBD)

label(code)
label(return)

label(player2)
label(maybeplayer)
globalalloc(playerptr,8)

newmem:

push rbx
push rcx
mov rcx,playerptr

mov rbx,[rax+8]
mov rbx,[rbx+30]
cmp [rbx+8],0x00300063
je maybeplayer


code:
pop rcx
pop rbx

  mov [rax+00000B0C],edx
  jmp return

maybeplayer:
cmp [rbx+c],0x00300030
je player2
jmp code

player2:
mov [rcx],rax
xor edx,edx
jmp code



player:
  jmp newmem
  nop
return:
registersymbol(player)

[DISABLE]

player:
  db 89 90 0C 0B 00 00

unregistersymbol(player)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "sekiro.exe"+B43CBD

"sekiro.exe"+B43C92: 0F B6 13              -  movzx edx,byte ptr [rbx]
"sekiro.exe"+B43C95: 48 8B 88 F8 1F 00 00  -  mov rcx,[rax+00001FF8]
"sekiro.exe"+B43C9C: 48 8B 09              -  mov rcx,[rcx]
"sekiro.exe"+B43C9F: 48 81 C4 90 00 00 00  -  add rsp,00000090
"sekiro.exe"+B43CA6: 5B                    -  pop rbx
"sekiro.exe"+B43CA7: E9 A4 01 FD FF        -  jmp sekiro.exe+B13E50
"sekiro.exe"+B43CAC: 49 8B 41 10           -  mov rax,[r9+10]
"sekiro.exe"+B43CB0: 0F B6 13              -  movzx edx,byte ptr [rbx]
"sekiro.exe"+B43CB3: 48 8B 88 F8 1F 00 00  -  mov rcx,[rax+00001FF8]
"sekiro.exe"+B43CBA: 48 8B 01              -  mov rax,[rcx]
// ---------- INJECTING HERE ----------
"sekiro.exe"+B43CBD: 89 90 0C 0B 00 00     -  mov [rax+00000B0C],edx
// ---------- DONE INJECTING  ----------
"sekiro.exe"+B43CC3: 48 81 C4 90 00 00 00  -  add rsp,00000090
"sekiro.exe"+B43CCA: 5B                    -  pop rbx
"sekiro.exe"+B43CCB: C3                    -  ret 
"sekiro.exe"+B43CCC: 49 8B C9              -  mov rcx,r9
"sekiro.exe"+B43CCF: 48 81 C4 90 00 00 00  -  add rsp,00000090
"sekiro.exe"+B43CD6: 5B                    -  pop rbx
"sekiro.exe"+B43CD7: E9 54 C7 FF FF        -  jmp sekiro.exe+B40430
"sekiro.exe"+B43CDC: 48 81 C4 90 00 00 00  -  add rsp,00000090
"sekiro.exe"+B43CE3: 5B                    -  pop rbx
"sekiro.exe"+B43CE4: E9 57 C4 FF FF        -  jmp sekiro.exe+B40140
}"""

[[cheat]]
id = "playerptr"
name = "PLAYERPTR"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i64"
hex = true

[cheat.locator]
find = "symbol"
symbol = "playerptr"
hops = []

[[cheat]]
id = "make-parry-always-in-time-new-aob"
name = "make parry always in time-new-aob"
category = "game"
description = ""
hint = ""
type = "script"
source = """
{ Game   : sekiro.exe
  Version: 
  Date   : 2020-01-26
  Author : holyy799

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(parryintime,sekiro.exe,48 8B 85 88 00 00 00 48 85 C0 74 07) // should be unique
alloc(newmem,$1000,"sekiro.exe"+B56BF6)

label(code)
label(return)

newmem:
push rbx
mov rbx,playerptr
cmp [rbx],rsi
jne code
mov cl,01


code:
  pop rbx
  mov rax,[rbp+00000088]
  jmp return

parryintime:
  jmp newmem
  nop 2
return:
registersymbol(parryintime)

[DISABLE]

parryintime:
  db 48 8B 85 88 00 00 00

unregistersymbol(parryintime)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "sekiro.exe"+B56BF6

"sekiro.exe"+B56BC7: 0F 84 D6 00 00 00        -  je sekiro.exe+B56CA3
"sekiro.exe"+B56BCD: 49 8B CC                 -  mov rcx,r12
"sekiro.exe"+B56BD0: E8 9B A5 FB FF           -  call sekiro.exe+B11170
"sekiro.exe"+B56BD5: 48 8B C8                 -  mov rcx,rax
"sekiro.exe"+B56BD8: 45 8B 8F D4 01 00 00     -  mov r9d,[r15+000001D4]
"sekiro.exe"+B56BDF: 45 8B 87 D0 01 00 00     -  mov r8d,[r15+000001D0]
"sekiro.exe"+B56BE6: 40 0F B6 D7              -  movzx edx,dil
"sekiro.exe"+B56BEA: E8 21 23 CE FF           -  call sekiro.exe+838F10
"sekiro.exe"+B56BEF: 41 39 47 40              -  cmp [r15+40],eax
"sekiro.exe"+B56BF3: 0F 9E C1                 -  setle cl
// ---------- INJECTING HERE ----------
"sekiro.exe"+B56BF6: 48 8B 85 88 00 00 00     -  mov rax,[rbp+00000088]
// ---------- DONE INJECTING  ----------
"sekiro.exe"+B56BFD: 48 85 C0                 -  test rax,rax
"sekiro.exe"+B56C00: 74 07                    -  je sekiro.exe+B56C09
"sekiro.exe"+B56C02: 0F B6 80 C4 01 00 00     -  movzx eax,byte ptr [rax+000001C4]
"sekiro.exe"+B56C09: 48 8B 55 B8              -  mov rdx,[rbp-48]
"sekiro.exe"+B56C0D: 84 C9                    -  test cl,cl
"sekiro.exe"+B56C0F: 74 52                    -  je sekiro.exe+B56C63
"sekiro.exe"+B56C11: 48 85 D2                 -  test rdx,rdx
"sekiro.exe"+B56C14: 74 3B                    -  je sekiro.exe+B56C51
"sekiro.exe"+B56C16: 3C 02                    -  cmp al,02
"sekiro.exe"+B56C18: 73 37                    -  jae sekiro.exe+B56C51
}"""

[[cheat]]
id = "make-attack-always-parry-new-aob"
name = "make attack always parry-new-aob"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
{ Game   : sekiro.exe
  Version: 
  Date   : 2020-01-26
  Author : holyy799

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(makeattackparry,sekiro.exe,48 8B 48 70 48 C1 E9 35 F6 C1 01 75) // should be unique
alloc(newmem,$1000,"sekiro.exe"+B591E2)

label(code)
label(return)

newmem:
push rbx
mov rbx,playerptr
cmp [rbx],rax
jne code
mov [rax+70],04


code:
pop rbx
  mov rcx,[rax+70]
  shr rcx,35
  jmp return

makeattackparry:
  jmp newmem
  nop 3
return:
registersymbol(makeattackparry)

[DISABLE]

makeattackparry:
  db 48 8B 48 70 48 C1 E9 35

unregistersymbol(makeattackparry)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "sekiro.exe"+B591E2

"sekiro.exe"+B591B9: 7E 4F                    -  jle sekiro.exe+B5920A
"sekiro.exe"+B591BB: 48 8B CF                 -  mov rcx,rdi
"sekiro.exe"+B591BE: E8 AD 7F FB FF           -  call sekiro.exe+B11170
"sekiro.exe"+B591C3: 48 8B 88 F8 1F 00 00     -  mov rcx,[rax+00001FF8]
"sekiro.exe"+B591CA: 48 83 39 00              -  cmp qword ptr [rcx],00
"sekiro.exe"+B591CE: 74 1F                    -  je sekiro.exe+B591EF
"sekiro.exe"+B591D0: 48 8B CF                 -  mov rcx,rdi
"sekiro.exe"+B591D3: E8 98 7F FB FF           -  call sekiro.exe+B11170
"sekiro.exe"+B591D8: 48 8B 88 F8 1F 00 00     -  mov rcx,[rax+00001FF8]
"sekiro.exe"+B591DF: 48 8B 01                 -  mov rax,[rcx]
// ---------- INJECTING HERE ----------
"sekiro.exe"+B591E2: 48 8B 48 70              -  mov rcx,[rax+70]
"sekiro.exe"+B591E6: 48 C1 E9 35              -  shr rcx,35
// ---------- DONE INJECTING  ----------
"sekiro.exe"+B591EA: F6 C1 01                 -  test cl,01
"sekiro.exe"+B591ED: 75 1B                    -  jne sekiro.exe+B5920A
"sekiro.exe"+B591EF: 48 8B CF                 -  mov rcx,rdi
"sekiro.exe"+B591F2: E8 79 7F FB FF           -  call sekiro.exe+B11170
"sekiro.exe"+B591F7: 48 8B 88 F8 1F 00 00     -  mov rcx,[rax+00001FF8]
"sekiro.exe"+B591FE: 48 8B 89 88 00 00 00     -  mov rcx,[rcx+00000088]
"sekiro.exe"+B59205: E8 76 1A 07 00           -  call sekiro.exe+BCAC80
"sekiro.exe"+B5920A: 48 8B CF                 -  mov rcx,rdi
"sekiro.exe"+B5920D: E8 5E 7F FB FF           -  call sekiro.exe+B11170
"sekiro.exe"+B59212: 48 8B 88 F8 1F 00 00     -  mov rcx,[rax+00001FF8]
}"""
