[game]
name = "The House of the Dead (Arcade) [Sega Model 2 Emulator 1.1a]"
exe = "emulator_multicpu.exe"
notes = "Converted from a Cheat Engine table by theo1996. Source: https://fearlessrevolution.com/viewtopic.php?t=35099"
verified = []
author = "theo1996"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "find-base-adrr"
name = "find base adrr"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : emulator_multicpu.exe
  Version: 
  Date   : 2025-05-19
  Author : TioFox

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJECT,emulator_multicpu.exe,89 14 01 5E C3 8B C8 8B 46 0C) // should be unique
alloc(newmem,$100)
alloc(base,$16)

label(code)
label(return)
base:
dq (float)0
newmem:

code:
  mov [ecx+eax],edx
  mov [base],ecx
  pop esi
  ret 
  jmp return

INJECT:
  jmp newmem
return:
registersymbol(INJECT base)

[DISABLE]

INJECT:
  db 89 14 01 5E C3

unregistersymbol(*)
dealloc(*)

{
// ORIGINAL CODE - INJECTION POINT: emulator_multicpu.exe+C2170

emulator_multicpu.exe+C2151: 8B 4A 10           - mov ecx,[edx+10]
emulator_multicpu.exe+C2154: 8B 11              - mov edx,[ecx]
emulator_multicpu.exe+C2156: 8B F0              - mov esi,eax
emulator_multicpu.exe+C2158: C1 EE 10           - shr esi,10
emulator_multicpu.exe+C215B: 81 C6 00 00 01 00  - add esi,00010000
emulator_multicpu.exe+C2161: C1 E6 04           - shl esi,04
emulator_multicpu.exe+C2164: 03 35 F4 A8 5A 00  - add esi,[emulator_multicpu.exe+1AA8F4]
emulator_multicpu.exe+C216A: 8B 0E              - mov ecx,[esi]
emulator_multicpu.exe+C216C: 85 C9              - test ecx,ecx
emulator_multicpu.exe+C216E: 74 05              - je emulator_multicpu.exe+C2175
// ---------- INJECTING HERE ----------
emulator_multicpu.exe+C2170: 89 14 01           - mov [ecx+eax],edx
// ---------- DONE INJECTING  ----------
emulator_multicpu.exe+C2173: 5E                 - pop esi
emulator_multicpu.exe+C2174: C3                 - ret 
emulator_multicpu.exe+C2175: 8B C8              - mov ecx,eax
emulator_multicpu.exe+C2177: 8B 46 0C           - mov eax,[esi+0C]
emulator_multicpu.exe+C217A: 5E                 - pop esi
emulator_multicpu.exe+C217B: FF E0              - jmp eax
emulator_multicpu.exe+C217D: CC                 - int 3 
emulator_multicpu.exe+C217E: CC                 - int 3 
emulator_multicpu.exe+C217F: CC                 - int 3 
emulator_multicpu.exe+C2180: A1 00 EB 5A 00     - mov eax,[emulator_multicpu.exe+1AEB00]
}"""
