[game]
name = "F1 2017"
exe = "f1_2017.exe"
notes = "Converted from a Cheat Engine table by Acido. Source: https://fearlessrevolution.com/viewtopic.php?t=5672"
verified = []
author = "Acido"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "max-out-a-given-core-competency-by-completing-only-1-event"
name = "Max out a given core competency by completing only 1 event."
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanmodule(competency,F1_2017.exe,CC CC 01 51 40 E9)

competency+2:
  db C7 41 40 64 00 00 00 E9 04 5A 00 00
registersymbol(competency)

[DISABLE]
competency+2:
  db 01 51 40 E9 08 5A 00 00 CC CC CC CC
unregistersymbol(competency)"""

[[cheat]]
id = "resource-points"
name = "Resource Points"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanmodule(ResourceAOB,F1_2017.exe,33 03 48 83 C4 20)
alloc(ResourceMem,128,"F1_2017.exe"+4A0CAE)
label(Return)
label(Code)
label(AddCode)
label(AddResource)
registersymbol(AddResource)
registersymbol(ResourceAOB)

ResourceMem:
  cmp dword ptr [AddResource+8],0
  je AddCode
  push edx
  mov edx,[rbx]
  xor edx,eax
  mov edx,[AddResource+8]
  mov [AddResource+4],0
  mov [AddResource+8],0
  xor edx,eax
  mov [rbx],edx
  pop edx
  jmp Code

AddCode:
  cmp dword ptr [AddResource+4],0
  je Code
  push edx
  mov edx,[rbx]
  xor edx,eax
  add edx,[AddResource+4]
  mov [AddResource+4],0
  mov [AddResource+8],0
  xor edx,eax
  mov [rbx],edx
  pop edx

Code:
  xor eax,[rbx]
  mov [AddResource],eax
  add rsp,20
  jmp Return

AddResource:
  dd 0

ResourceAOB:
  jmp ResourceMem
  nop
Return:

[DISABLE]
ResourceAOB:
  xor eax,[rbx]
  add rsp,20
unregistersymbol(AddResource)
unregistersymbol(ResourceAOB)
dealloc(ResourceMem)"""

[[cheat]]
id = "current-resource-points-read-only"
name = "Current Resource Points (Read Only)"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "AddResource"
hops = []

[[cheat]]
id = "add-resource-points"
name = "Add Resource Points"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "AddResource"
hops = []

[[cheat]]
id = "set-resource-points-to-specific-amount"
name = "Set Resource Points to specific amount"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "AddResource"
hops = []

[[cheat]]
id = "engine-wear"
name = "Engine Wear"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanmodule(Engine_MGUK_AOB,F1_2017.exe,41 33 04 1E)
aobscanmodule(Engine_ES_AOB,F1_2017.exe,33 04 2B)
aobscanmodule(Engine_CE1_AOB,F1_2017.exe,F3 41 0F 59 FB F3 0F 58 FE)
aobscanmodule(Engine_CE2_AOB,F1_2017.exe,33 83 60 08 00 00)
aobscanmodule(Engine_ICE_AOB,F1_2017.exe,F3 41 0F 59 CB F3 0F 58 8B)
aobscanmodule(Engine_MGUH_AOB,F1_2017.exe,F3 41 0F 59 C3 F3 0F 58 83 94 0A)
aobscanmodule(Engine_TC_AOB,F1_2017.exe,8B CF F3 0F 10 84 24)
aobscanmodule(Engine_Gearbox_AOB,F1_2017.exe,F3 0F 59 87 F4 0C 00 00 F3 0F 58 F8 80 BB)
alloc(EngineMem,4096,"F1_2017.exe"+DC098F)
label(Engine_MGUK)
label(Engine_ES)
label(Engine_CE1)
label(Engine_CE2)
label(Engine_ICE)
label(Engine_MGUH)
label(Engine_TC)
label(Engine_Gearbox)
label(Return_MGUK)
label(Return_ES)
label(Return_CE1)
label(Return_CE2)
label(Return_ICE)
label(Return_MGUH)
label(Return_TC)
label(Return_Gearbox)
label(EngineRate)
registersymbol(EngineRate)
registersymbol(Engine_MGUK_AOB)
registersymbol(Engine_ES_AOB)
registersymbol(Engine_CE1_AOB)
registersymbol(Engine_CE2_AOB)
registersymbol(Engine_ICE_AOB)
registersymbol(Engine_MGUH_AOB)
registersymbol(Engine_TC_AOB)
registersymbol(Engine_Gearbox_AOB)

EngineMem:

Engine_MGUK:
  mulss xmm0,xmm11
  mulss xmm0,[EngineRate]
  jmp Return_MGUK

Engine_ES:
  mulss xmm0,xmm11
  mulss xmm0,[EngineRate]
  jmp Return_ES

Engine_CE1:
  mulss xmm7,xmm11
  mulss xmm7,[EngineRate]
  jmp Return_CE1

Engine_CE2:
  mulss xmm0,xmm11
  mulss xmm0,[EngineRate]
  jmp Return_CE2

Engine_ICE:
  push rsi
  lea rsi,[rbx+A98]
  mov [EngineRate+10],rsi
  lea rsi,[rbx+A88]
  mov [EngineRate+20],rsi
  lea rsi,[rbx+AA4]
  mov [EngineRate+30],rsi
  lea rsi,[rbx+A80]
  mov [EngineRate+40],rsi
  lea rsi,[rbx+A94]
  mov [EngineRate+50],rsi
  lea rsi,[rbx+A84]
  mov [EngineRate+60],rsi
  pop rsi
  mulss xmm1,xmm11
  mulss xmm1,[EngineRate]
  jmp Return_ICE

Engine_MGUH:
  mulss xmm0,xmm11
  mulss xmm0,[EngineRate]
  jmp Return_MGUH

Engine_TC:
  mulss xmm0,xmm11
  mulss xmm0,[EngineRate]
  jmp Return_TC

Engine_Gearbox:
  push rsi
  lea rsi,[rbx+1CC]
  mov [EngineRate+70],rsi
  pop rsi
  mulss xmm0,[rdi+00000CF4]
  mulss xmm0,[EngineRate]
  jmp Return_Gearbox

EngineRate:
  dd 3F800000

Engine_MGUK_AOB+14:
  jmp Engine_MGUK
Return_MGUK:

Engine_ES_AOB+13:
  jmp Engine_ES
Return_ES:

Engine_CE1_AOB:
  jmp Engine_CE1
Return_CE1:

Engine_CE2_AOB+1F:
  jmp Engine_CE2
Return_CE2:

Engine_ICE_AOB:
  jmp Engine_ICE
Return_ICE:

Engine_MGUH_AOB:
  jmp Engine_MGUH
Return_MGUH:

Engine_TC_AOB+10:
  jmp Engine_TC
Return_TC:

Engine_Gearbox_AOB:
  jmp Engine_Gearbox
  db 90 90 90
Return_Gearbox:

[DISABLE]
Engine_MGUK_AOB+14:
  db F3 41 0F 59 C3
Engine_ES_AOB+13:
  db F3 41 0F 59 C3
Engine_CE1_AOB:
  db F3 41 0F 59 FB
Engine_CE2_AOB+1F:
  db F3 41 0F 59 C3
Engine_ICE_AOB:
  db F3 41 0F 59 CB
Engine_MGUH_AOB:
  db F3 41 0F 59 C3
Engine_TC_AOB+10:
  db F3 41 0F 59 C3
Engine_Gearbox_AOB:
  db F3 0F 59 87 F4 0C 00 00
unregistersymbol(EngineRate)
unregistersymbol(Engine_MGUK_AOB)
unregistersymbol(Engine_ES_AOB)
unregistersymbol(Engine_CE1_AOB)
unregistersymbol(Engine_CE2_AOB)
unregistersymbol(Engine_ICE_AOB)
unregistersymbol(Engine_MGUH_AOB)
unregistersymbol(Engine_TC_AOB)
unregistersymbol(Engine_Gearbox_AOB)
dealloc(EngineMem)"""

[[cheat]]
id = "internal-combustion-engine"
name = "Internal Combustion Engine"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "EngineRate"
hops = ["+0x0"]

[[cheat]]
id = "motor-generator-unit-kinetic"
name = "Motor Generator Unit - Kinetic"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "EngineRate"
hops = ["+0x0"]

[[cheat]]
id = "motor-generator-unit-heat"
name = "Motor Generator Unit - Heat"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "EngineRate"
hops = ["+0x0"]

[[cheat]]
id = "energy-store"
name = "Energy Store"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "EngineRate"
hops = ["+0x0"]

[[cheat]]
id = "turbo-charger"
name = "Turbo Charger"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "EngineRate"
hops = ["+0x0"]

[[cheat]]
id = "control-electronics"
name = "Control Electronics"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "EngineRate"
hops = ["+0x0"]

[[cheat]]
id = "gearbox"
name = "Gearbox"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "EngineRate"
hops = ["+0x0"]

[[cheat]]
id = "engine-wear-rate"
name = "Engine Wear Rate"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0
choices = [
    "0:No Engine Wear",
    "0.25:25% Engine Wear",
    "0.5:50% Engine Wear",
    "0.75:75% Engine Wear",
    "1:Normal Engine Wear",
    "1.25:125% Engine Wear",
    "1.5:150% Engine Wear",
    "1.75:175% Engine Wear",
    "2:200% Engine Wear",
]

[cheat.locator]
find = "symbol"
symbol = "EngineRate"
hops = []

[[cheat]]
id = "tyre-wear"
name = "Tyre Wear"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanmodule(TyreAOB,F1_2017.exe,F3 0F 58 43 60 F3 0F 10 D8)
alloc(TyreMem,128,"F1_2017.exe"+DC8726)
label(Return)
label(AICode)
label(OriginalCode)
label(TyreRate)
label(TyreAIRate)
registersymbol(TyreRate)
registersymbol(TyreAIRate)
registersymbol(TyreAOB)

TyreMem:
  cmp word ptr [rbx+BE],3F80
  je AICode
  mulss xmm0,[TyreRate]
  jmp OriginalCode

AICode:
  mulss xmm0,[TyreAIRate]

OriginalCode:
  addss xmm0,[rbx+60]
  jmp Return

TyreRate:
  dd 3F800000

TyreAIRate:
  dd 3F800000

TyreAOB:
  jmp TyreMem
Return:

[DISABLE]
TyreAOB:
  db F3 0F 58 43 60
unregistersymbol(TyreRate)
unregistersymbol(TyreAIRate)
unregistersymbol(TyreAOB)
dealloc(TyreMem)"""

[[cheat]]
id = "tyre-wear-rate-player"
name = "Tyre Wear Rate [Player]"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0
choices = [
    "0:No Tyre Wear",
    "0.25:25% Tyre Wear",
    "0.5:50% Tyre Wear",
    "0.75:75% Tyre Wear",
    "1:Normal Tyre Wear",
    "1.25:125% Tyre Wear",
    "1.5:150% Tyre Wear",
    "1.75:175% Tyre Wear",
    "2:200% Tyre Wear",
]

[cheat.locator]
find = "symbol"
symbol = "TyreRate"
hops = []

[[cheat]]
id = "tyre-wear-rate-ai"
name = "Tyre Wear Rate [AI]"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0
choices = [
    "0:No Tyre Wear",
    "0.25:25% Tyre Wear",
    "0.5:50% Tyre Wear",
    "0.75:75% Tyre Wear",
    "1:Normal Tyre Wear",
    "1.25:125% Tyre Wear",
    "1.5:150% Tyre Wear",
    "1.75:175% Tyre Wear",
    "2:200% Tyre Wear",
]

[cheat.locator]
find = "symbol"
symbol = "TyreAIRate"
hops = []

[[cheat]]
id = "fuel-consumption"
name = "Fuel Consumption"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanmodule(FuelAOB,F1_2017.exe,32 C8 F3 0F 5C C1)
alloc(FuelMem,128,"F1_2017.exe"+DE7FA6)
label(Return)
label(AICode)
label(OriginalCode)
label(FuelRate)
label(FuelAIRate)
registersymbol(FuelRate)
registersymbol(FuelAIRate)
registersymbol(FuelAOB)

FuelMem:
  push rsi
  mov rsi,[rbx+8]
  cmp dword ptr [rsi+1D8],13
  jne AICode
  lea rsi,[rbx+60]
  mov [FuelRate+10],rsi
  mulss xmm1,[FuelRate]
  jmp OriginalCode

AICode:
  mulss xmm1,[FuelAIRate]

OriginalCode:
  pop rsi
  xor cl,al
  subss xmm0,xmm1
  jmp Return

FuelRate:
  dd 3F800000

FuelAIRate:
  dd 3F800000

FuelAOB:
  jmp FuelMem
  nop
Return:

[DISABLE]
FuelAOB:
  db 32 C8 F3 0F 5C C1
unregistersymbol(FuelRate)
unregistersymbol(FuelAIRate)
unregistersymbol(FuelAOB)
dealloc(FuelMem)"""

[[cheat]]
id = "current-fuel-load"
name = "Current Fuel Load"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "FuelRate"
hops = ["+0x0"]

[[cheat]]
id = "fuel-consumption-rate-player"
name = "Fuel Consumption Rate [Player]"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0
choices = [
    "0:No Fuel Consumption",
    "0.25:25% Fuel Consumption",
    "0.5:50% Fuel Consumption",
    "0.75:75% Fuel Consumption",
    "1:Normal Fuel Consumption",
    "1.25:125% Fuel Consumption",
    "1.5:150% Fuel Consumption",
    "1.75:175% Fuel Consumption",
    "2:200% Fuel Consumption",
]

[cheat.locator]
find = "symbol"
symbol = "FuelRate"
hops = []

[[cheat]]
id = "fuel-consumption-rate-ai"
name = "Fuel Consumption Rate [AI]"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0
choices = [
    "0:No Fuel Consumption",
    "0.25:25% Fuel Consumption",
    "0.5:50% Fuel Consumption",
    "0.75:75% Fuel Consumption",
    "1:Normal Fuel Consumption",
    "1.25:125% Fuel Consumption",
    "1.5:150% Fuel Consumption",
    "1.75:175% Fuel Consumption",
    "2:200% Fuel Consumption",
]

[cheat.locator]
find = "symbol"
symbol = "FuelAIRate"
hops = []
