[game]
name = "Dark Souls 2 - HP, Durability, Torch time and more !"
exe = "darksoulsii.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=1653"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "character"
name = "Character"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

registersymbol(p_life)
alloc(p_life,8)

label(i_life)
registersymbol(i_life)
aobscan(aob_life,66 8B 80 04 01 00 00)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here
mov [p_life],eax

originalcode:
mov ax,[eax+00000104]

exit:
jmp returnhere

aob_life://"DarkSoulsII.exe"+22EDA2:
i_life:
jmp newmem
nop
nop
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
i_life:
mov ax,[eax+00000104]
//Alt: db 66 8B 80 04 01 00 00
unregistersymbol(p_life)
unregistersymbol(i_life)
dealloc(p_life)"""

[[cheat]]
id = "current-hp"
name = "Current HP"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0xfc"]

[[cheat]]
id = "max-hp"
name = "Max HP"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0x104"]

[[cheat]]
id = "current-max-hp"
name = "Current Max HP"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0x108"]

[[cheat]]
id = "current-stamina"
name = "Current Stamina"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0x140"]

[[cheat]]
id = "max-stamina"
name = "Max Stamina"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0x148"]

[[cheat]]
id = "current-poison-max-poison-cured"
name = "Current Poison (max poison = cured)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0x1ac"]

[[cheat]]
id = "max-poison-value"
name = "Max Poison Value"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0x1b4"]

[[cheat]]
id = "petrification-100-dead"
name = "Petrification (100 = dead)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0x1a0"]

[[cheat]]
id = "petrification-max-value"
name = "Petrification Max Value"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "p_life"
hops = ["+0x1a8"]

[[cheat]]
id = "spells"
name = "Spells"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

registersymbol(p_casts)
alloc(p_casts,8)

label(i_casts)
registersymbol(i_casts)
aobscan(aob_casts,0F B6 52 18 66 01 55 FC)

newmem:
mov [p_casts],edx

originalcode:
movzx edx,byte ptr [edx+18]
add [ebp-04],dx

exit:
jmp returnhere

aob_casts://"DarkSoulsII.exe"+1F06D8:
i_casts:
jmp newmem
nop
nop
nop
returnhere:


 
 
[DISABLE]
dealloc(newmem)
i_casts:
movzx edx,byte ptr [edx+18]
add [ebp-04],dx
//Alt: db 0F B6 52 18 66 01 55 FC
unregistersymbol(p_casts)
dealloc(p_casts)
unregistersymbol(i_casts)"""

[[cheat]]
id = "current-spell-casts-left"
name = "Current Spell Casts Left"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "p_casts"
hops = ["+0x18"]

[[cheat]]
id = "torch"
name = "Torch"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

registersymbol(p_torch)
alloc(p_torch,8)

label(i_torch)
registersymbol(i_torch)
aobscan(aob_torch,0F 2F 00 72 0D)


newmem:
mov [p_torch],eax

originalcode:
comiss xmm0,[eax]
jb DarkSoulsII.exe+1F9018

exit:
jmp returnhere

aob_torch://"DarkSoulsII.exe"+1F9006:
i_torch:
jmp newmem
returnhere:


 
 
[DISABLE]
dealloc(newmem)
i_torch:
comiss xmm0,[eax]
jb DarkSoulsII.exe+1F9018
//Alt: db CC 2F 00 72 0D
unregistersymbol(p_torch)
dealloc(p_torch)
unregistersymbol(i_torch)"""

[[cheat]]
id = "torch-time-left-in-seconds"
name = "Torch Time left (in seconds)"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "p_torch"
hops = ["+0x0"]

[[cheat]]
id = "consumable-in-first-slot"
name = "Consumable in first slot"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

registersymbol(p_item_first)
alloc(p_item_first,8)

label(i_item_first)
registersymbol(i_item_first)
aobscan(aob_item_first,0F B7 46 18 5E)

newmem:
mov [p_item_first], esi

originalcode:
movzx eax,word ptr [esi+18]
pop esi

exit:
jmp returnhere

aob_item_first://"DarkSoulsII.exe"+D86A2:
i_item_first:
jmp newmem
returnhere:


 
 
[DISABLE]
dealloc(newmem)
i_item_first:
movzx eax,word ptr [esi+18]
pop esi
//Alt: db 0F B7 46 18 5E"""

[[cheat]]
id = "quantity"
name = "Quantity"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "p_item_first"
hops = ["+0x18"]

[[cheat]]
id = "current-weapon"
name = "Current Weapon"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

registersymbol(p_current_weapon)
alloc(p_current_weapon,8)

label(i_current_weapon)
registersymbol(i_current_weapon)
aobscan(aob_current_weapon,F3 0F 10 47 6C)

newmem:
mov [p_current_weapon],edi

originalcode:
movss xmm0,[edi+6C]

exit:
jmp returnhere

aob_current_weapon://"DarkSoulsII.exe"+30B2EF:
i_current_weapon:
jmp newmem
returnhere:


 
 
[DISABLE]
dealloc(newmem)
i_current_weapon:
movss xmm0,[edi+6C]
//Alt: db F3 0F 10 47 6C
unregistersymbol(p_current_weapon)
dealloc(p_current_weapon)
unregistersymbol(i_current_weapon)"""

[[cheat]]
id = "weapon-durability"
name = "Weapon Durability"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "p_current_weapon"
hops = ["+0x6c"]

[[cheat]]
id = "infinite-item-certain-consumables-will-still-decrease"
name = "Infinite item (certain consumables will still decrease)"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

registersymbol(p_item)
alloc(p_item,8)

label(i_infinite_item)
registersymbol(i_infinite_item)
aobscan(aob_infinite_item,66 29 5E 18 56)

newmem:
mov [p_item],esi

originalcode:
sub [esi+18],0
nop
push esi

exit:
jmp returnhere

aob_infinite_item://"DarkSoulsII.exe"+1F3FE2:
i_infinite_item:
jmp newmem
returnhere:


 
 
[DISABLE]
dealloc(newmem)
i_infinite_item:
sub [esi+18],bx
push esi
//Alt: db 66 29 5E 18 56
unregistersymbol(i_infinite_item)
unregistersymbol(p_item)
dealloc(p_item)"""

[[cheat]]
id = "current-item-count"
name = "Current item count"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "p_item"
hops = ["+0x18"]

[[cheat]]
id = "player-base-stats"
name = "Player base stats"
category = "player"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

registersymbol(p_stats)
alloc(p_stats,8)

label(i_stats)
registersymbol(i_stats)
aobscan(aob_stats,F3 0F 7E 07 0F B7 57 14)


newmem:
mov [p_stats],edi

originalcode:
movq xmm0,[edi]
movzx edx,word ptr [edi+14]

exit:
jmp returnhere

aob_stats:
i_stats:
jmp newmem
nop
nop
nop
returnhere:


 
 
[DISABLE]
dealloc(newmem)
"DarkSoulsII.exe"+34716A:
movq xmm0,[edi]
movzx edx,word ptr [edi+14]
//Alt: db CC 0F 7E 07 0F B7 57 14
//Alt: db F3 0F 7E 07 0F B7 57 14
unregistersymbol(p_stats)
unregistersymbol(i_stats)
dealloc(p_life)"""

[[cheat]]
id = "vigor"
name = "Vigor"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x0"]

[[cheat]]
id = "endurance"
name = "Endurance"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x2"]

[[cheat]]
id = "vitality"
name = "Vitality"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x4"]

[[cheat]]
id = "attunement"
name = "Attunement"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x6"]

[[cheat]]
id = "strength"
name = "Strength"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x8"]

[[cheat]]
id = "dexterity"
name = "Dexterity"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0xa"]

[[cheat]]
id = "intelligence"
name = "Intelligence"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0xc"]

[[cheat]]
id = "faith"
name = "Faith"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0xe"]

[[cheat]]
id = "adaptability"
name = "Adaptability"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x10"]

[[cheat]]
id = "attunement-slots"
name = "Attunement slots"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x12"]

[[cheat]]
id = "level"
name = "Level"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0xc8"]

[[cheat]]
id = "souls"
name = "Souls"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0xe4"]

[[cheat]]
id = "max-health-tentative"
name = "Max Health (tentative)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 9999

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x2c"]

[[cheat]]
id = "max-stamina-tentative"
name = "Max Stamina (tentative)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 9999

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x2e"]

[[cheat]]
id = "carry-capacity-tentative"
name = "Carry Capacity (tentative)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "p_stats"
hops = ["+0x34"]
