[game]
name = "Fox Sex Farm"
exe = "fox sex farm.exe"
notes = "Converted from a Cheat Engine table by Firstlast2s100. Source: https://fearlessrevolution.com/viewtopic.php?t=37659"
verified = []
author = "Firstlast2s100"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "playeractor"
name = "PlayerActor"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Fox Sex Farm.exe
  Version: 
  Date   : 2025-12-14
  Author : DANGER DASH

  This script does blah blah blah
}

define(address,PlayerActor_玩家角色:Update)
define(bytes,55 48 8B EC 48 81 EC 60 02 00 00 48 89 5D D0)

[ENABLE]

assert(address,bytes)
alloc(newmem,$1000,PlayerActor_玩家角色:Update)

label(code)
label(return)

newmem:
mov [playeractor_ptr],rcx

code:
  push rbp
  mov rbp,rsp
  sub rsp,00000260
  mov [rbp-30],rbx
  jmp return

playeractor_ptr:
dq 0

address:
  jmp far newmem
  nop
return:
registersymbol(playeractor_ptr)

[DISABLE]

address:
  db bytes
  // push rbp
  // mov rbp,rsp
  // sub rsp,00000260
  // mov [rbp-30],rbx

dealloc(newmem)
unregistersymbol(playeractor_ptr)

{
// ORIGINAL CODE - INJECTION POINT: PlayerActor_玩家角色:Update

1CA53B9DA5C: 00 00                          - add [rax],al
1CA53B9DA5E: 00 00                          - add [rax],al
1CA53B9DA60: 00 00                          - add [rax],al
1CA53B9DA62: 00 00                          - add [rax],al
1CA53B9DA64: 00 00                          - add [rax],al
1CA53B9DA66: 00 00                          - add [rax],al
1CA53B9DA68: 00 00                          - add [rax],al
1CA53B9DA6A: 00 00                          - add [rax],al
1CA53B9DA6C: 00 00                          - add [rax],al
1CA53B9DA6E: 00 00                          - add [rax],al
// ---------- INJECTING HERE ----------
PlayerActor_玩家角色:Update: 55                             - push rbp
// ---------- DONE INJECTING  ----------
PlayerActor_玩家角色:Update+1: 48 8B EC                       - mov rbp,rsp
PlayerActor_玩家角色:Update+4: 48 81 EC 60 02 00 00           - sub rsp,00000260
PlayerActor_玩家角色:Update+b: 48 89 5D D0                    - mov [rbp-30],rbx
PlayerActor_玩家角色:Update+f: 48 89 75 D8                    - mov [rbp-28],rsi
PlayerActor_玩家角色:Update+13: 48 89 7D E0                    - mov [rbp-20],rdi
PlayerActor_玩家角色:Update+17: 4C 89 65 E8                    - mov [rbp-18],r12
PlayerActor_玩家角色:Update+1b: 4C 89 75 F0                    - mov [rbp-10],r14
PlayerActor_玩家角色:Update+1f: 4C 89 7D F8                    - mov [rbp-08],r15
PlayerActor_玩家角色:Update+23: 48 8B F1                       - mov rsi,rcx
PlayerActor_玩家角色:Update+26: C7 85 80 FE FF FF 00 00 00 00  - mov [rbp-00000180],00000000
}"""

[[cheat]]
id = "environmentmanager"
name = "EnvironmentManager"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Fox Sex Farm.exe
  Version: 
  Date   : 2025-12-14
  Author : DANGER DASH

  This script does blah blah blah
}

define(address,EnvironmentManager:Update)
define(bytes,55 48 8B EC 48 81 EC 30 02 00 00 48 89 75 E8)

[ENABLE]

assert(address,bytes)
alloc(newmem,$1000,EnvironmentManager:Update)

label(code)
label(return)

newmem:
mov [environmentmanager_ptr],rcx

code:
  push rbp
  mov rbp,rsp
  sub rsp,00000230
  mov [rbp-18],rsi
  jmp return

environmentmanager_ptr:
dq 0

address:
  jmp far newmem
  nop
return:
registersymbol(environmentmanager_ptr)

[DISABLE]

address:
  db bytes
  // push rbp
  // mov rbp,rsp
  // sub rsp,00000230
  // mov [rbp-18],rsi

dealloc(newmem)
unregistersymbol(environmentmanager_ptr)

{
// ORIGINAL CODE - INJECTION POINT: EnvironmentManager:Update

1CA53B8E9C9: 04 02                 - add al,02
1CA53B8E9CB: 05 04 03 01 50        - add eax,50010304
1CA53B8E9D0: 00 00                 - add [rax],al
1CA53B8E9D2: 00 00                 - add [rax],al
1CA53B8E9D4: 00 00                 - add [rax],al
1CA53B8E9D6: 00 00                 - add [rax],al
1CA53B8E9D8: 00 00                 - add [rax],al
1CA53B8E9DA: 00 00                 - add [rax],al
1CA53B8E9DC: 00 00                 - add [rax],al
1CA53B8E9DE: 00 00                 - add [rax],al
// ---------- INJECTING HERE ----------
EnvironmentManager:Update: 55                    - push rbp
// ---------- DONE INJECTING  ----------
EnvironmentManager:Update+1: 48 8B EC              - mov rbp,rsp
EnvironmentManager:Update+4: 48 81 EC 30 02 00 00  - sub rsp,00000230
EnvironmentManager:Update+b: 48 89 75 E8           - mov [rbp-18],rsi
EnvironmentManager:Update+f: 48 89 7D F0           - mov [rbp-10],rdi
EnvironmentManager:Update+13: 4C 89 7D F8           - mov [rbp-08],r15
EnvironmentManager:Update+17: 48 8B F1              - mov rsi,rcx
EnvironmentManager:Update+1a: 48 8B 46 40           - mov rax,[rsi+40]
EnvironmentManager:Update+1e: 48 85 C0              - test rax,rax
EnvironmentManager:Update+21: 0F 84 B4 07 00 00     - je EnvironmentManager:Update+7db
EnvironmentManager:Update+27: 48 8B 46 48           - mov rax,[rsi+48]
}"""

[[cheat]]
id = "fullinventorydata"
name = "FullInventoryData"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Fox Sex Farm.exe
  Version: 
  Date   : 2025-12-14
  Author : DANGER DASH

  This script does blah blah blah
}

define(address,FullInventoryData:AddItem)
define(bytes,55 48 8B EC 48 83 EC 50)

[ENABLE]

assert(address,bytes)
alloc(newmem,$1000,FullInventoryData:AddItem)

label(code)
label(return)

newmem:
mov [fullinventorydata_ptr],rcx

code:
  push rbp
  mov rbp,rsp
  sub rsp,50
  jmp return

fullinventorydata_ptr:
dq 0

address:
  jmp newmem
  nop 3
return:
registersymbol(fullinventorydata_ptr)

[DISABLE]

address:
  db bytes
  // push rbp
  // mov rbp,rsp
  // sub rsp,50

dealloc(newmem)
unregistersymbol(fullinventorydata_ptr)

{
// ORIGINAL CODE - INJECTION POINT: FullInventoryData:AddItem

ItemProcess+<>c__DisplayClass11_0:<tryAddToPlayerOrPlayer2>b__1+3b: C3              - ret 
1CAD796BD3C: 00 00           - add [rax],al
1CAD796BD3E: 00 00           - add [rax],al
1CAD796BD40: 01 04 01        - add [rcx+rax],eax
1CAD796BD43: 00 04 22        - add [rdx],al
1CAD796BD46: 00 00           - add [rax],al
1CAD796BD48: 00 00           - add [rax],al
1CAD796BD4A: 00 00           - add [rax],al
1CAD796BD4C: 00 00           - add [rax],al
1CAD796BD4E: 00 00           - add [rax],al
// ---------- INJECTING HERE ----------
FullInventoryData:AddItem: 55              - push rbp
// ---------- DONE INJECTING  ----------
FullInventoryData:AddItem+1: 48 8B EC        - mov rbp,rsp
FullInventoryData:AddItem+4: 48 83 EC 50     - sub rsp,50
FullInventoryData:AddItem+8: 48 89 4D F8     - mov [rbp-08],rcx
FullInventoryData:AddItem+c: 48 89 55 F0     - mov [rbp-10],rdx
FullInventoryData:AddItem+10: 4C 89 45 E8     - mov [rbp-18],r8
FullInventoryData:AddItem+14: 4C 89 4D E0     - mov [rbp-20],r9
FullInventoryData:AddItem+18: 0F B6 45 30     - movzx eax,byte ptr [rbp+30]
FullInventoryData:AddItem+1c: 48 89 44 24 20  - mov [rsp+20],rax
FullInventoryData:AddItem+21: 48 63 45 38     - movsxd  rax,dword ptr [rbp+38]
FullInventoryData:AddItem+25: 48 89 44 24 28  - mov [rsp+28],rax
}"""
