[game]
name = "Little Friends - Puppy Island"
exe = "dogs.exe"
notes = "Converted from a Cheat Engine table by Weresthebeef. Source: https://fearlessrevolution.com/viewtopic.php?t=30173"
verified = []
author = "Weresthebeef"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "instant-clean-3"
name = "Instant Clean <3"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : dogs.exe
  Version: 
  Date   : 2024-07-12
  Author : Kurar

  This script does blah blah blah
}

[ENABLE]


aobscanmodule(DirtyDog,GameAssembly.dll,F3 0F 11 B7 C0 01 00 00) // should be unique
alloc(newmem,$1000,DirtyDog)

label(code)
label(return)

newmem:
movss [rdi+000001C0],xmm10

code:
  //movss [rdi+000001C0],xmm6
  jmp return

DirtyDog:
  jmp newmem
  nop 3
return:
registersymbol(DirtyDog)

[DISABLE]

DirtyDog:
  db F3 0F 11 B7 C0 01 00 00

unregistersymbol(DirtyDog)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: GameAssembly.dll+4EA553

GameAssembly.dll+4EA52A: F3 0F 59 F7              - mulss xmm6,xmm7
GameAssembly.dll+4EA52E: F3 0F 58 B7 C0 01 00 00  - addss xmm6,[rdi+000001C0]
GameAssembly.dll+4EA536: 44 0F 2F CE              - comiss xmm9,xmm6
GameAssembly.dll+4EA53A: 77 0C                    - ja GameAssembly.dll+4EA548
GameAssembly.dll+4EA53C: 41 0F 2F F2              - comiss xmm6,xmm10
GameAssembly.dll+4EA540: 76 0A                    - jna GameAssembly.dll+4EA54C
GameAssembly.dll+4EA542: 41 0F 28 F2              - movaps xmm6,xmm10
GameAssembly.dll+4EA546: EB 04                    - jmp GameAssembly.dll+4EA54C
GameAssembly.dll+4EA548: 41 0F 28 F1              - movaps xmm6,xmm9
GameAssembly.dll+4EA54C: 48 8B 9F 50 01 00 00     - mov rbx,[rdi+00000150]
// ---------- INJECTING HERE ----------
GameAssembly.dll+4EA553: F3 0F 11 B7 C0 01 00 00  - movss [rdi+000001C0],xmm6
// ---------- DONE INJECTING  ----------
GameAssembly.dll+4EA55B: 48 8B 0D E6 94 51 03     - mov rcx,[GameAssembly.dll+3A03A48]
GameAssembly.dll+4EA562: 83 B9 E0 00 00 00 00     - cmp dword ptr [rcx+000000E0],00
GameAssembly.dll+4EA569: 75 05                    - jne GameAssembly.dll+4EA570
GameAssembly.dll+4EA56B: E8 90 01 D7 FF           - call GameAssembly.dll+25A700
GameAssembly.dll+4EA570: 45 33 C0                 - xor r8d,r8d
GameAssembly.dll+4EA573: 33 D2                    - xor edx,edx
GameAssembly.dll+4EA575: 48 8B CB                 - mov rcx,rbx
GameAssembly.dll+4EA578: E8 23 83 5F 02           - call UnityEngine.Object.op_Inequality
GameAssembly.dll+4EA57D: 84 C0                    - test al,al
GameAssembly.dll+4EA57F: 0F 84 7F FB FF FF        - je GameAssembly.dll+4EA104
}"""

[[cheat]]
id = "give-9999-bones-on-purchase"
name = "Give 9999 Bones On Purchase"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : dogs.exe
  Version: 
  Date   : 2024-07-13
  Author : Kurar

  This script does blah blah blah
}

[ENABLE]

label(code)
label(return)

aobscanmodule(GimmieBones,GameAssembly.dll,19 03 00 00 F7 D8 8B 57 3C 8D 0C 02 85 C9 78 19 03 D0 89 57 3C 48 8B 47 40) // should be unique
//aobscanmodule(GiveBones2,GameAssembly.dll,D1 89 57 3C 48 8B 47 40) // should be unique
//aobscanmodule(GiveBones3,GameAssembly.dll,89 50 3C 4C 8B 48 40) // should be unique

alloc(newmem,$1000,GimmieBones)

newmem:
  mov edx,270f

code:
  mov [rdi+3C],edx
  mov rax,[rdi+40]
  jmp return

GimmieBones+12:
//GiveBones2+01:
//GiveBones3:
  jmp newmem
  nop 2
return:

//GiveBones2+01:
//  jmp newmem
//  nop 2
//return:

//GiveBones3:
//  jmp newmem
//  nop 2
//return:

registersymbol(GimmieBones)
//registersymbol(GiveBones2)
//registersymbol(GiveBones3)

[DISABLE]

GimmieBones+12:
  db 89 57 3C 48 8B 47 40

//GiveBones2+01:
//  db 89 57 3C 48 8B 47 40

//GiveBones3:
//  db 89 50 3C 4C 8B 48 40

unregistersymbol(GimmieBones)
//unregistersymbol(GiveBones2)
//unregistersymbol(GiveBones3)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: GameAssembly.dll+41F5B7

GameAssembly.dll+41F598: 48 8B CB           - mov rcx,rbx
GameAssembly.dll+41F59B: E8 D0 E4 FF FF     - call MudPups.Menus.ToyMenu.GetCost
GameAssembly.dll+41F5A0: 48 85 FF           - test rdi,rdi
GameAssembly.dll+41F5A3: 0F 84 19 03 00 00  - je GameAssembly.dll+41F8C2
GameAssembly.dll+41F5A9: F7 D8              - neg eax
GameAssembly.dll+41F5AB: 8B 57 3C           - mov edx,[rdi+3C]
GameAssembly.dll+41F5AE: 8D 0C 02           - lea ecx,[rdx+rax]
GameAssembly.dll+41F5B1: 85 C9              - test ecx,ecx
GameAssembly.dll+41F5B3: 78 19              - js GameAssembly.dll+41F5CE
GameAssembly.dll+41F5B5: 03 D0              - add edx,eax
// ---------- INJECTING HERE ----------
GameAssembly.dll+41F5B7: 89 57 3C           - mov [rdi+3C],edx
// ---------- DONE INJECTING  ----------
GameAssembly.dll+41F5BA: 48 8B 47 40        - mov rax,[rdi+40]
GameAssembly.dll+41F5BE: 48 85 C0           - test rax,rax
GameAssembly.dll+41F5C1: 74 0B              - je GameAssembly.dll+41F5CE
GameAssembly.dll+41F5C3: 4C 8B 40 28        - mov r8,[rax+28]
GameAssembly.dll+41F5C7: 48 8B 48 40        - mov rcx,[rax+40]
GameAssembly.dll+41F5CB: FF 50 18           - call qword ptr [rax+18]
GameAssembly.dll+41F5CE: 48 8B 43 30        - mov rax,[rbx+30]
GameAssembly.dll+41F5D2: 48 85 C0           - test rax,rax
GameAssembly.dll+41F5D5: 0F 84 E1 02 00 00  - je GameAssembly.dll+41F8BC
GameAssembly.dll+41F5DB: 48 8B 78 10        - mov rdi,[rax+10]
}"""

[[cheat]]
id = "walk-hunger-happy-and-bath-full"
name = "Walk, Hunger, Happy and Bath Full"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game  : dogs.exe
  Version: 
  Date   : 2024-07-13
  Author : Kurar

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(KeepHerRunning,GameAssembly.dll,F3 44 0F 11 54 C3 40) // should be unique
alloc(newmem,$1000,KeepHerRunning)

label(code)
label(return)

//alloc(all_full, 4, KeepHerRunning)
//registersymbol(all_full)
//mov [all_full], 100.00  // Replace with your actual index value

//AllFull dd 100.0

newmem:
  //movss xmm10, dword ptr [rdi]
  mov [rbx+rax*8+40],(float)100.00
  //movss xmm15, all_full
  //mulss xmm10,[fCaptureMul]
  //movss xmm10, r11

code:
  //movss [rbx+rax*8+40],xmm10
  jmp return

  fCaptureMul:
    dd (float)100

KeepHerRunning:
  jmp newmem
  nop 2
return:
registersymbol(KeepHerRunning)

[DISABLE]

KeepHerRunning:
  db F3 44 0F 11 54 C3 40

unregistersymbol(KeepHerRunning)
//unregistersymbol(all_full)
dealloc(newmem)
//dealloc(all_full)

{
// ORIGINAL CODE - INJECTION POINT: GameAssembly.dll+13D0189

GameAssembly.dll+13D0157: 0F 11 45 AF                 - movups [rbp-51],xmm0
GameAssembly.dll+13D015B: F2 0F 11 4D BF              - movsd [rbp-41],xmm1
GameAssembly.dll+13D0160: 48 8B 81 A8 00 00 00        - mov rax,[rcx+000000A8]
GameAssembly.dll+13D0167: F6 80 32 01 00 00 01        - test byte ptr [rax+00000132],01
GameAssembly.dll+13D016E: 0F 85 AE 01 00 00           - jne GameAssembly.dll+13D0322
GameAssembly.dll+13D0174: E9 A1 01 00 00              - jmp GameAssembly.dll+13D031A
GameAssembly.dll+13D0179: 48 63 C6                    - movsxd  rax,esi
GameAssembly.dll+13D017C: 3B 43 18                    - cmp eax,[rbx+18]
GameAssembly.dll+13D017F: 0F 83 CE 01 00 00           - jae GameAssembly.dll+13D0353
GameAssembly.dll+13D0185: 48 8D 04 80                 - lea rax,[rax+rax*4]
// ---------- INJECTING HERE ----------
GameAssembly.dll+13D0189: F3 44 0F 11 54 C3 40        - movss [rbx+rax*8+40],xmm10
// ---------- DONE INJECTING  ----------
GameAssembly.dll+13D0190: B0 01                       - mov al,01
GameAssembly.dll+13D0192: 44 0F 28 84 24 90 00 00 00  - movaps xmm8,[rsp+00000090]
GameAssembly.dll+13D019B: 48 8B B4 24 08 01 00 00     - mov rsi,[rsp+00000108]
GameAssembly.dll+13D01A3: 44 0F 28 8C 24 80 00 00 00  - movaps xmm9,[rsp+00000080]
GameAssembly.dll+13D01AC: 0F 28 BC 24 A0 00 00 00     - movaps xmm7,[rsp+000000A0]
GameAssembly.dll+13D01B4: 0F 28 B4 24 B0 00 00 00     - movaps xmm6,[rsp+000000B0]
GameAssembly.dll+13D01BC: 44 0F 28 54 24 70           - movaps xmm10,[rsp+70]
GameAssembly.dll+13D01C2: 48 81 C4 C0 00 00 00        - add rsp,000000C0
GameAssembly.dll+13D01C9: 41 5F                       - pop r15
GameAssembly.dll+13D01CB: 41 5E                       - pop r14
}"""

[[cheat]]
id = "looking-for-work-challenge-accepted"
name = "Looking For Work (Challenge Accepted)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : dogs.exe
  Version: 
  Date   : 2024-07-13
  Author : Kurar

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(WorkReady,GameAssembly.dll,48 8B 44 C1 40 48 8B 5C 24 70) // should be unique
alloc(newmem,$1000,WorkReady)

label(code)
label(return)

newmem:
  mov [rcx+rax*8+40],5

code:
  mov rax,[rcx+rax*8+40]
  jmp return

WorkReady:
  jmp newmem
return:
registersymbol(WorkReady)

[DISABLE]

WorkReady:
  db 48 8B 44 C1 40

unregistersymbol(WorkReady)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: GameAssembly.dll+600966

GameAssembly.dll+60094C: FF D0                    - call rax
GameAssembly.dll+60094E: 85 C0                    - test eax,eax
GameAssembly.dll+600950: 78 24                    - js GameAssembly.dll+600976
GameAssembly.dll+600952: 48 8B 4F 18              - mov rcx,[rdi+18]
GameAssembly.dll+600956: 48 85 C9                 - test rcx,rcx
GameAssembly.dll+600959: 74 49                    - je GameAssembly.dll+6009A4
GameAssembly.dll+60095B: 48 98                    - cdqe 
GameAssembly.dll+60095D: 3B 41 18                 - cmp eax,[rcx+18]
GameAssembly.dll+600960: 73 3C                    - jae GameAssembly.dll+60099E
GameAssembly.dll+600962: 48 8D 04 80              - lea rax,[rax+rax*4]
// ---------- INJECTING HERE ----------
GameAssembly.dll+600966: 48 8B 44 C1 40           - mov rax,[rcx+rax*8+40]
// ---------- DONE INJECTING  ----------
GameAssembly.dll+60096B: 48 8B 5C 24 70           - mov rbx,[rsp+70]
GameAssembly.dll+600970: 48 83 C4 60              - add rsp,60
GameAssembly.dll+600974: 5F                       - pop rdi
GameAssembly.dll+600975: C3                       - ret 
GameAssembly.dll+600976: 48 8B 5C 24 70           - mov rbx,[rsp+70]
GameAssembly.dll+60097B: 33 C0                    - xor eax,eax
GameAssembly.dll+60097D: 48 89 44 24 78           - mov [rsp+78],rax
GameAssembly.dll+600982: 0F 57 C0                 - xorps xmm0,xmm0
GameAssembly.dll+600985: F3 0F 11 44 24 7C        - movss [rsp+7C],xmm0
GameAssembly.dll+60098B: C7 44 24 78 01 00 00 00  - mov [rsp+78],00000001
}"""
