[game]
name = "RETSNOM"
exe = "retsnom.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=1606"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "invincible"
name = "Invincible"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
aobscan(chkDontTouchHimInZombieMove_OnTriggerEnterAOB,0F B6 40 6D 85 C0 75)
registersymbol(chkDontTouchHimInZombieMove_OnTriggerEnterAOB)

chkDontTouchHimInZombieMove_OnTriggerEnterAOB+5: //ZombieMove:OnTriggerEnter+77:
db E4
//Alt: esp,esp


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
chkDontTouchHimInZombieMove_OnTriggerEnterAOB+5: //ZombieMove:OnTriggerEnter+77:
db C0
//Alt: eax,eax"""

[[cheat]]
id = "invisible"
name = "Invisible"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
aobscan(chkDontTouchHimInZombiePhysics_HeCheckAOB,0F B6 40 6D 85 C0 0F)
registersymbol(chkDontTouchHimInZombiePhysics_HeCheckAOB)

chkDontTouchHimInZombiePhysics_HeCheckAOB+5: //ZombiePhysics:HeCheck+40b:
db E4
//Alt: esp,esp




[DISABLE]
//code from here till the end of the code will be used to disable the cheat
chkDontTouchHimInZombiePhysics_HeCheckAOB+5: //ZombiePhysics:HeCheck+40b:
db C0
//Alt: eax,eax"""

[[cheat]]
id = "fly-mode"
name = "Fly Mode"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
aobscan(amountToMoveYWriteInPlatformerController_UpdateAOB,DE E9 D9 58 04 8B 47 2C)
registersymbol(amountToMoveYWriteInPlatformerController_UpdateAOB)

label(bFlyUpOnce)
label(fFlyVSpeed)
registersymbol(fFlyVSpeed)

alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)
label(flymodestart)
label(flymodeexit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here
//fstp st(0)
//fldz

pushad
push 20 //Spacebar
call GetAsyncKeyState
shr ax,#15
cmp ax,1
popad
jne flymodeexit

cmp byte ptr [bFlyUpOnce],1
jne @f
fstp st(0)
fldz
jmp flymodestart

@@:
fldz
fcomip st(0), st(1)
jbe @f
fstp st(0)
fldz

flymodestart:
pushad
push 'W'
call GetAsyncKeyState
shr ax,#15
cmp ax,1
popad
jne @f
mov byte ptr [bFlyUpOnce],1
fstp st(0)
fldz
fadd [fFlyVSpeed]
jmp originalcode

@@:
pushad
push 'S'
call GetAsyncKeyState
shr ax,#15
cmp ax,1
popad
jne @f
fstp st(0)
fldz
fsub [fFlyVSpeed]

@@:
jmp originalcode

flymodeexit:
mov byte ptr [bFlyUpOnce],0

originalcode:
fstp dword ptr [eax+04]
mov eax,[edi+2C]

exit:
jmp returnhere

///
bFlyUpOnce:
dd 0
fFlyVSpeed:
dd (float)1
///

amountToMoveYWriteInPlatformerController_UpdateAOB+2: //PlatformerController:Update+4b1:
jmp newmem
nop
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
amountToMoveYWriteInPlatformerController_UpdateAOB+2: //PlatformerController:Update+4b1:
db D9 58 04 8B 47 2C
//Alt: fstp dword ptr [eax+04]
//Alt: mov eax,[edi+2C]

unregistersymbol(fFlyVSpeed)"""

[[cheat]]
id = "isheholdinggun"
name = "isHeHoldingGun"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1

[cheat.locator]
find = "symbol"
symbol = "pController"
hops = ["+0x61"]

[[cheat]]
id = "killedzombie"
name = "killedZombie"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pController"
hops = ["+0x64"]

[[cheat]]
id = "deathnum"
name = "DeathNum"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pController"
hops = ["+0x68"]

[[cheat]]
id = "donttouchhim"
name = "DontTouchHim"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pController"
hops = ["+0x6d"]

[[cheat]]
id = "gravity"
name = "gravity"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 5

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x30"]

[[cheat]]
id = "speed"
name = "speed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 1

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x34"]

[[cheat]]
id = "acceleration"
name = "acceleration"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 2

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x38"]

[[cheat]]
id = "jumpheight"
name = "jumpHeight"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 2.349999905

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x3c"]

[[cheat]]
id = "isthistimeforfirstgunsound"
name = "isThisTimeForFirstGunSound"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x40"]

[[cheat]]
id = "isplayingsfx"
name = "isPlayingSFX"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x41"]

[[cheat]]
id = "indexofsfx"
name = "indexOfSFX"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 2

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x44"]

[[cheat]]
id = "gravitychangecorrect"
name = "gravityChangeCorrect"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0.1000000015

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x48"]

[[cheat]]
id = "currentspeed"
name = "currentSpeed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x4c"]

[[cheat]]
id = "targetspeed"
name = "targetSpeed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x50"]

[[cheat]]
id = "x"
name = "x"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x54"]

[[cheat]]
id = "y"
name = "y"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = -0.09999999404

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x58"]

[[cheat]]
id = "animationspeed"
name = "animationSpeed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x5c"]

[[cheat]]
id = "jumping"
name = "jumping"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x60"]

[[cheat]]
id = "sitting"
name = "sitting"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x61"]

[[cheat]]
id = "facingright"
name = "facingRight"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x62"]

[[cheat]]
id = "crawlfirst"
name = "crawlFirst"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x63"]

[[cheat]]
id = "iscrawling"
name = "isCrawling"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x64"]

[[cheat]]
id = "isheshooting"
name = "isHeShooting"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x65"]

[[cheat]]
id = "shootaniising"
name = "shootAniIsIng"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x66"]

[[cheat]]
id = "movingbycoding"
name = "movingByCoding"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x67"]

[[cheat]]
id = "canusemirror"
name = "canUseMirror"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1

[cheat.locator]
find = "symbol"
symbol = "pPlatformerController"
hops = ["+0x68"]

[[cheat]]
id = "maxtime"
name = "MaxTime"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 999999

[cheat.locator]
find = "symbol"
symbol = "pClock"
hops = ["+0x18"]

[[cheat]]
id = "timerstarted"
name = "timerStarted"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1

[cheat.locator]
find = "symbol"
symbol = "pClock"
hops = ["+0x1c"]

[[cheat]]
id = "timer"
name = "timer"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 12.73382854

[cheat.locator]
find = "symbol"
symbol = "pClock"
hops = ["+0x20"]

[[cheat]]
id = "clockison"
name = "clockIsOn"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0

[cheat.locator]
find = "symbol"
symbol = "pClock"
hops = ["+0x24"]
