[game]
name = "A Robot Named Fight"
exe = "arobotnamedfight.exe"
notes = "Converted from a Cheat Engine table by Squall8. Source: https://fearlessrevolution.com/viewtopic.php?t=4826"
verified = []
author = "Squall8"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "player-base-energy-float"
name = "Player Base (energy-float)"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : ARobotNamedFight.exe
  Version: 
  Date   : 2020-08-08
  Author : pongo

  This script does blah blah blah
}

[ENABLE]

aobscan(energy,D9 80 0C 03 00 00 C9) // should be unique
alloc(newmem,$1000)
globalalloc(_pb,4)
label(code)
label(return)

newmem:
mov [_pb],eax
code:
  fld dword ptr [eax+0000030C]
  jmp return

energy:
  jmp newmem
  nop
return:
registersymbol(energy)

[DISABLE]

energy:
  db D9 80 DC 02 00 00

unregistersymbol(energy)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: EnergyNumeric:GetValue+22 

12808B8E: 8B 45 08              -  mov eax,[ebp+08]
12808B91: 8B 40 60              -  mov eax,[eax+60]
12808B94: 89 04 24              -  mov [esp],eax
12808B97: E8 74 7B A8 FF        -  call 12290710
12808B9C: 85 C0                 -  test eax,eax
12808B9E: 75 04                 -  jne 12808BA4
12808BA0: D9 EE                 -  fldz 
12808BA2: EB 0C                 -  jmp 12808BB0
12808BA4: 8B 45 08              -  mov eax,[ebp+08]
12808BA7: 8B 40 60              -  mov eax,[eax+60]
// ---------- INJECTING HERE ----------
12808BAA: D9 80 DC 02 00 00     -  fld dword ptr [eax+000002DC]
// ---------- DONE INJECTING  ----------
12808BB0: C9                    -  leave 
12808BB1: C3                    -  ret 
12808BB2: 00 00                 -  add [eax],al
12808BB4: 00 00                 -  add [eax],al
12808BB6: 00 00                 -  add [eax],al
12808BB8: 55                    -  push ebp
12808BB9: 8B EC                 -  mov ebp,esp
12808BBB: 83 EC 18              -  sub esp,18
12808BBE: 8B 45 08              -  mov eax,[ebp+08]
12808BC1: 8B 40 60              -  mov eax,[eax+60]
}"""

[[cheat]]
id = "no-description"
name = "No description"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x0"]

[[cheat]]
id = "base-damage"
name = "Base Damage"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x340"]

[[cheat]]
id = "item-shot-size-multiplier"
name = "Item Shot Size Multiplier"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x390"]

[[cheat]]
id = "item-damage-multiplier"
name = "Item Damage Multiplier"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x350"]

[[cheat]]
id = "invincible"
name = "Invincible"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x7d"]

[[cheat]]
id = "current-playtime"
name = "Current Playtime"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x398"]

[[cheat]]
id = "current-life"
name = "Current Life"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x58"]

[[cheat]]
id = "max-life"
name = "Max Life"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x5c"]

[[cheat]]
id = "energy"
name = "Energy"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x30c"]

[[cheat]]
id = "max-energy"
name = "Max Energy"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x310"]

[[cheat]]
id = "life-regeneration-rate"
name = "Life Regeneration Rate"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x300"]

[[cheat]]
id = "energy-regeneration-rate"
name = "Energy Regeneration Rate"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x334"]

[[cheat]]
id = "bonus-energy-regeneration-rate"
name = "Bonus Energy Regeneration Rate"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x320"]

[[cheat]]
id = "item-energy-regenrate"
name = "Item Energy RegenRate ?"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x328"]

[[cheat]]
id = "energy-regen-time"
name = "Energy Regen Time"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x334"]

[[cheat]]
id = "energy-regen-time-mod"
name = "Energy Regen Time Mod"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x338"]

[[cheat]]
id = "item-energy-regen-counter"
name = "Item Energy Regen Counter"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x32c"]

[[cheat]]
id = "blue-scrap"
name = "Blue Scrap"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2ec"]

[[cheat]]
id = "gray-scrap"
name = "Gray Scrap"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2e0"]

[[cheat]]
id = "red-scrap"
name = "Red Scrap"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2e4"]

[[cheat]]
id = "green-scrap"
name = "Green Scrap"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2e8"]

[[cheat]]
id = "life"
name = "Life"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2f8"]

[[cheat]]
id = "energy-2"
name = "Energy"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x31c"]

[[cheat]]
id = "shot-power"
name = "Shot power"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x344"]

[[cheat]]
id = "fire-rate"
name = "Fire rate"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x358"]

[[cheat]]
id = "speed"
name = "Speed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x364"]

[[cheat]]
id = "shot-speed"
name = "Shot Speed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x374"]

[[cheat]]
id = "bonus-damage"
name = "Bonus Damage"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x34c"]

[[cheat]]
id = "bonus-attack"
name = "Bonus Attack"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x35c"]

[[cheat]]
id = "bonus-speed"
name = "Bonus Speed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x360"]

[[cheat]]
id = "bonus-shot-speed"
name = "Bonus Shot Speed"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x37c"]

[[cheat]]
id = "damage-multiplier-separate-to-base-damage"
name = "Damage Multiplier (separate to base damage)"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x250"]

[[cheat]]
id = "cloak-mode-not-targetable"
name = "Cloak Mode (Not targetable)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x61"]

[[cheat]]
id = "map-completion-read-only"
name = "Map Completion (read-only)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x400"]

[[cheat]]
id = "attack-delay-set-to-0-1-for-pretty-fast-rate-of-fire"
name = "Attack Delay (Set to 0.1 for pretty fast rate of fire)"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x24c"]

[[cheat]]
id = "max-jump-height"
name = "Max Jump Height"
category = "movement"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x1f0"]

[[cheat]]
id = "hover-timer"
name = "Hover Timer"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x290"]

[[cheat]]
id = "uxinvincible-temporary-invincibility"
name = "uxInvincible (Temporary Invincibility)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2d9"]

[[cheat]]
id = "paralyzed"
name = "Paralyzed"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2da"]

[[cheat]]
id = "slowed"
name = "Slowed"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2db"]

[[cheat]]
id = "confused"
name = "Confused"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2dc"]

[[cheat]]
id = "charge-time"
name = "Charge Time"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "_pb"
hops = ["+0x2d4"]
