[game]
name = "Crossroads Inn Anniversary Edition"
exe = "inn.exe"
notes = "Converted from a Cheat Engine table by N3rveMods. Source: https://fearlessrevolution.com/viewtopic.php?t=26613"
verified = []
author = "N3rveMods"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "no-fatigue"
name = "No Fatigue"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]




aobscanmodule(fatigue_aob,Crossroads Inn.exe,F3 0F 10 83 F0 22 00 00 F3 0F 59 05) // should be unique
alloc(newmem,$1000,fatigue_aob)

label(code)
label(return)

newmem:
mov [rbx+000022F0],0
code:
  movss xmm0,[rbx+000022F0]
  jmp return

fatigue_aob:
  jmp newmem
  nop
  nop
  nop
return:
registersymbol(fatigue_aob)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
fatigue_aob:
  db F3 0F 10 83 F0 22 00 00

unregistersymbol(fatigue_aob)
dealloc(newmem)"""
