[game]
name = "Fatekeeper"
exe = "slasher-win64-shipping.exe"
notes = "Converted from a Cheat Engine table by qteeq@proton.me. Source: https://fearlessrevolution.com/viewtopic.php?t=39638"
verified = []
author = "qteeq@proton.me"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "godmode-ohk-inf-stamina-inf-skills"
name = "GodMode+OHK+Inf.Stamina+Inf.Skills"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
alloc(newmem,2048,"SLASHER-Win64-Shipping.exe"+5E187A0) 
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
cmp [rsi+378],0
jne originalcode
mov [rsi+34],0
jmp exit

originalcode:
mov [rsi+34],(float)999

exit:
jmp returnhere

"SLASHER-Win64-Shipping.exe"+5E187A0:
jmp newmem
returnhere:




 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
"SLASHER-Win64-Shipping.exe"+5E187A0:
db F3 0F 11 76 34
//movss [rsi+34],xmm6

//F3 0F 11 76 34 E8 E6 C0 41 FD 48 8B F8 48 8B 18 8B CB E8 29 92 57 FB
//f3 0f 11 76 ? e8 ? ? ? ? 48 8b f8"""
