[game]
name = "Thriving City: Song"
exe = "song.exe"
notes = "Converted from a Cheat Engine table by BabyGroot. Source: https://fearlessrevolution.com/viewtopic.php?t=24419"
verified = []
author = "BabyGroot"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "unlimited-all-villager-stats-chance-in-script"
name = "Unlimited All Villager Stats - [ Chance In Script ]"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Song.exe
  Version: 
  Date   : 2023-04-22
  Author : BabyGroot

  This script does blah blah blah
}

[ENABLE]

aobscanregion(pData_VilagerData,ETModel.Villager:OnStateChange,ETModel.Villager:OnStateChange+400,48 63 80 80 00 00 00 83 F8 18) // should be unique
alloc(newmem,$1000,pData_VilagerData)

label(code)
label(return)

newmem:
  mov dword ptr [rax+00000080],#0                    //<Hunger>k__BackingField
  mov dword ptr [rax+00000084],#0                    //<Diet>k__BackingField
  mov dword ptr [rax+0000007C],#31                   //<Life>k__BackingField
  mov dword ptr [rax+00000078],#17                   //<Age>k__BackingField
  mov dword ptr [rax+0000006C],#100                  //<TargetHealth>k__BackingField
  mov dword ptr [rax+00000068],#100                  //<CurHealth>k__BackingField
  mov dword ptr [rax+00000098],(float)10000          //<Gold>k__BackingField

code:
  movsxd  rax,dword ptr [rax+00000080]
  jmp return

pData_VilagerData:
  jmp newmem
  nop 2
return:
registersymbol(pData_VilagerData)

[DISABLE]

pData_VilagerData:
  db 48 63 80 80 00 00 00

unregistersymbol(pData_VilagerData)
dealloc(newmem)"""

[[cheat]]
id = "annual-ring-component"
name = "Annual Ring Component"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Song.exe
  Version:
  Date   : 2023-04-22
  Author : BabyGroot

  This script does blah blah blah
}

[ENABLE]

aobscanregion(pData_AnnualRingComponent,ETModel.NormalUnitComponent:Update,ETModel.NormalUnitComponent:Update+100,48 63 80 C8 00 00 00 85) // should be unique
alloc(newmem,$1000,pData_AnnualRingComponent)

alloc(pBase_AnnualRingComponent,4)
registersymbol(pBase_AnnualRingComponent)

label(code)
label(return)

pBase_AnnualRingComponent:
dd

newmem:

code:
  mov [pBase_AnnualRingComponent],rax
  movsxd  rax,dword ptr [rax+000000C8]
  jmp return

pData_AnnualRingComponent:
  jmp newmem
  nop 2
return:
registersymbol(pData_AnnualRingComponent pBase_AnnualRingComponent)

[DISABLE]

pData_AnnualRingComponent:
  db 48 63 80 C8 00 00 00

unregistersymbol(*)
dealloc(*)"""

[[cheat]]
id = "base-data"
name = "Base Data"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Song.exe
  Version:
  Date   : 2023-04-22
  Author : BabyGroot

  This script does blah blah blah
}

[ENABLE]

aobscanregion(pData_BaseData,ETModel.BaseData:GetResSum,ETModel.BaseData:GetResSum+100,48 8B 80 30 02 00 00 48 63) // should be unique
alloc(newmem,$1000,pData_BaseData)

alloc(pBase_BaseData,8)
registersymbol(pBase_BaseData)

label(code)
label(return)

pBase_BaseData:
dd

newmem:

code:
  mov [pBase_BaseData],rax
  mov rax,[rax+00000230]
  jmp return

pData_BaseData:
  jmp newmem
  nop 2
return:
registersymbol(pData_BaseData pBase_BaseData)

[DISABLE]

pData_BaseData:
  db 48 8B 80 30 02 00 00

unregistersymbol(*)
dealloc(*)"""

[[cheat]]
id = "research-panel-new"
name = "Research Panel > New"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Song.exe
  Version: 
  Date   : 2023-04-23
  Author : resky

  This script does blah blah blah
}

//ETModel.ResearchPanel:Update+41

[ENABLE]

aobscanregion(pData_ResearchPanel,ETModel.ResearchPanel:Update,ETModel.ResearchPanel:Update+700,48 8B 4E 70 48 8B D1 83 3A 00 48 63 51) // should be unique
alloc(newmem,$1000,pData_ResearchPanel)

alloc(pBase_ResearchPanel,8)
registersymbol(pBase_ResearchPanel)

label(code)
label(return)

pBase_ResearchPanel:
dd

newmem:

code:
  mov [pBase_ResearchPanel],rsi
  mov rcx,[rsi+70]
  mov rdx,rcx
  jmp return

pData_ResearchPanel:
  jmp newmem
  nop 2
return:
registersymbol(pData_ResearchPanel pBase_ResearchPanel)

[DISABLE]

pData_ResearchPanel:
  db 48 8B 4E 70 48 8B D1

unregistersymbol(*)
dealloc(*)

{
// ORIGINAL CODE - INJECTION POINT: ETModel.ResearchPanel:Update+41

ETModel.ResearchPanel:Update+14: 4C 89 65 E0                    - mov [rbp-20],r12
ETModel.ResearchPanel:Update+18: 4C 89 6D E8                    - mov [rbp-18],r13
ETModel.ResearchPanel:Update+1c: 4C 89 75 F0                    - mov [rbp-10],r14
ETModel.ResearchPanel:Update+20: 4C 89 7D F8                    - mov [rbp-08],r15
ETModel.ResearchPanel:Update+24: 48 8B F1                       - mov rsi,rcx
ETModel.ResearchPanel:Update+27: 48 B8 C0 31 AC 71 1C 02 00 00  - mov rax,0000021C71AC31C0
ETModel.ResearchPanel:Update+31: 48 8B 00                       - mov rax,[rax]
ETModel.ResearchPanel:Update+34: 48 8B C8                       - mov rcx,rax
ETModel.ResearchPanel:Update+37: 83 39 00                       - cmp dword ptr [rcx],00
ETModel.ResearchPanel:Update+3a: 48 8B 80 90 01 00 00           - mov rax,[rax+00000190]
// ---------- INJECTING HERE ----------
ETModel.ResearchPanel:Update+41: 48 8B 4E 70                    - mov rcx,[rsi+70]
// ---------- DONE INJECTING  ----------
ETModel.ResearchPanel:Update+45: 48 8B D1                       - mov rdx,rcx
ETModel.ResearchPanel:Update+48: 83 3A 00                       - cmp dword ptr [rdx],00
ETModel.ResearchPanel:Update+4b: 48 63 51 18                    - movsxd  rdx,dword ptr [rcx+18]
ETModel.ResearchPanel:Update+4f: 48 8B C8                       - mov rcx,rax
ETModel.ResearchPanel:Update+52: 83 38 00                       - cmp dword ptr [rax],00
ETModel.ResearchPanel:Update+55: 90                             - nop 
ETModel.ResearchPanel:Update+56: 49 BB F0 F2 9C 4A 21 02 00 00  - mov r11,ETModel.TechConfig:GetDataAt
ETModel.ResearchPanel:Update+60: 41 FF D3                       - call r11
ETModel.ResearchPanel:Update+63: 4C 8B F8                       - mov r15,rax
ETModel.ResearchPanel:Update+66: 4C 8B 76 30                    - mov r14,[rsi+30]
}"""

[[cheat]]
id = "building-data"
name = "Building Data"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Song.exe
  Version:
  Date   : 2023-04-22
  Author : BabyGroot

  This script does blah blah blah
}

[ENABLE]

aobscanregion(pData_BuildingItem,ETModel.BuildingItem:OnEnter,ETModel.BuildingItem:OnEnter+200,48 63 46 78 48 89 45 E0) // should be unique
alloc(newmem,$1000,pData_BuildingItem)

alloc(pBase_BuildingItem,8)
registersymbol(pBase_BuildingItem)

label(code)
label(return)

pBase_BuildingItem:
dd

newmem:

code:
  mov [pBase_BuildingItem],rsi
  movsxd  rax,dword ptr [rsi+78]
  mov [rbp-20],rax
  jmp return

pData_BuildingItem:
  jmp newmem
  nop 3
return:
registersymbol(pData_BuildingItem pBase_BuildingItem)

[DISABLE]

pData_BuildingItem:
  db 48 63 46 78 48 89 45 E0

unregistersymbol(*)
dealloc(*)"""

[[cheat]]
id = "context-component-building"
name = "Context Component Building"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Song.exe
  Version:
  Date   : 2023-04-22
  Author : BabyGroot

  This script does blah blah blah
}

[ENABLE]

aobscanregion(pData_ContextComponent,ETModel.ContextComponent:CancelSelectSoldier,ETModel.ContextComponent:CancelSelectSoldier+200,48 8B 40 58 48 8B D5 48 83 C2 B0 48 8B C8 83 38 00 48 8D 6D 00 49 BB ??) // should be unique
alloc(newmem,$1000,pData_ContextComponent)

alloc(pBase_ContextComponent,8)
registersymbol(pBase_ContextComponent)

label(code)
label(return)

pBase_ContextComponent:
dd

newmem:

code:
  mov [pBase_ContextComponent],rax
  mov rax,[rax+58]
  mov rdx,rbp
  jmp return

pData_ContextComponent:
  jmp newmem
  nop 2
return:
registersymbol(pData_ContextComponent pBase_ContextComponent)

[DISABLE]

pData_ContextComponent:
  db 48 8B 40 58 48 8B D5

unregistersymbol(*)
dealloc(*)"""
