[game]
name = "The Solus Project"
exe = "solus-win64-shipping.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=997"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "infinite-hunger"
name = "Infinite Hunger"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Solus-Win64-Shipping.exe
  Version: 
  Date   : 2017-04-30
  Author : Iscariot

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(hunger,Solus-Win64-Shipping.exe,F3 0F 11 80 D8 62 03 00) // should be unique
alloc(newmem,$1000,"Solus-Win64-Shipping.exe"+14CC69)

label(code)
label(return)

newmem:

code:
  addss xmm0,xmm0
  movss [rax+000362D8],xmm0
  jmp return

hunger:
  jmp newmem
  nop
  nop
  nop
return:
registersymbol(hunger)

[DISABLE]

hunger:
  db F3 0F 11 80 D8 62 03 00

unregistersymbol(hunger)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Solus-Win64-Shipping.exe"+14CC69

"Solus-Win64-Shipping.exe"+14CC3F: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CC40: F3 0F 11 44 24 08        -  movss [rsp+08],xmm0
"Solus-Win64-Shipping.exe"+14CC46: 48 83 EC 38              -  sub rsp,38
"Solus-Win64-Shipping.exe"+14CC4A: E8 01 86 01 00           -  call Solus-Win64-Shipping.exe+165250
"Solus-Win64-Shipping.exe"+14CC4F: 48 89 44 24 20           -  mov [rsp+20],rax
"Solus-Win64-Shipping.exe"+14CC54: 48 83 7C 24 20 00        -  cmp qword ptr [rsp+20],00
"Solus-Win64-Shipping.exe"+14CC5A: 75 02                    -  jne Solus-Win64-Shipping.exe+14CC5E
"Solus-Win64-Shipping.exe"+14CC5C: EB 13                    -  jmp Solus-Win64-Shipping.exe+14CC71
"Solus-Win64-Shipping.exe"+14CC5E: 48 8B 44 24 20           -  mov rax,[rsp+20]
"Solus-Win64-Shipping.exe"+14CC63: F3 0F 10 44 24 40        -  movss xmm0,[rsp+40]
// ---------- INJECTING HERE ----------
"Solus-Win64-Shipping.exe"+14CC69: F3 0F 11 80 D8 62 03 00  -  movss [rax+000362D8],xmm0
// ---------- DONE INJECTING  ----------
"Solus-Win64-Shipping.exe"+14CC71: 48 83 C4 38              -  add rsp,38
"Solus-Win64-Shipping.exe"+14CC75: C3                       -  ret 
"Solus-Win64-Shipping.exe"+14CC76: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CC77: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CC78: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CC79: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CC7A: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CC7B: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CC7C: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CC7D: CC                       -  int 3 
}"""

[[cheat]]
id = "no-sleep"
name = "No Sleep"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]

aobscanmodule(sleep,Solus-Win64-Shipping.exe,F3 0F 11 80 E0 62 03 00) // should be unique
alloc(newmem,$1000,"Solus-Win64-Shipping.exe"+14CE49)

label(code)
label(return)

newmem:

code:
  //addss xmm0,xmm0
  //movss [rax+000362E0],xmm0
  jmp return

sleep:
  jmp newmem
  nop
  nop
  nop
return:
registersymbol(sleep)

[DISABLE]

sleep:
  db F3 0F 11 80 E0 62 03 00

unregistersymbol(sleep)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Solus-Win64-Shipping.exe"+14CE49

"Solus-Win64-Shipping.exe"+14CE1F: C3                       -  ret 
"Solus-Win64-Shipping.exe"+14CE20: F3 0F 11 44 24 08        -  movss [rsp+08],xmm0
"Solus-Win64-Shipping.exe"+14CE26: 48 83 EC 38              -  sub rsp,38
"Solus-Win64-Shipping.exe"+14CE2A: E8 21 84 01 00           -  call Solus-Win64-Shipping.exe+165250
"Solus-Win64-Shipping.exe"+14CE2F: 48 89 44 24 20           -  mov [rsp+20],rax
"Solus-Win64-Shipping.exe"+14CE34: 48 83 7C 24 20 00        -  cmp qword ptr [rsp+20],00
"Solus-Win64-Shipping.exe"+14CE3A: 75 02                    -  jne Solus-Win64-Shipping.exe+14CE3E
"Solus-Win64-Shipping.exe"+14CE3C: EB 13                    -  jmp Solus-Win64-Shipping.exe+14CE51
"Solus-Win64-Shipping.exe"+14CE3E: 48 8B 44 24 20           -  mov rax,[rsp+20]
"Solus-Win64-Shipping.exe"+14CE43: F3 0F 10 44 24 40        -  movss xmm0,[rsp+40]
// ---------- INJECTING HERE ----------
"Solus-Win64-Shipping.exe"+14CE49: F3 0F 11 80 E0 62 03 00  -  movss [rax+000362E0],xmm0
// ---------- DONE INJECTING  ----------
"Solus-Win64-Shipping.exe"+14CE51: 48 83 C4 38              -  add rsp,38
"Solus-Win64-Shipping.exe"+14CE55: C3                       -  ret 
"Solus-Win64-Shipping.exe"+14CE56: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CE57: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CE58: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CE59: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CE5A: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CE5B: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CE5C: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+14CE5D: CC                       -  int 3 
}"""

[[cheat]]
id = "infinite-inventory-space"
name = "Infinite Inventory Space"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]

aobscanmodule(inventory,Solus-Win64-Shipping.exe,FF 85 C0 68 03 00) // should be unique
alloc(newmem,$1000,"Solus-Win64-Shipping.exe"+1702AA)

label(code)
label(return)

newmem:

code:
  mov [rbp+000368C0],1
  jmp return

inventory:
  jmp newmem
  nop
return:
registersymbol(inventory)

[DISABLE]

inventory:
  db FF 85 C0 68 03 00

unregistersymbol(inventory)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Solus-Win64-Shipping.exe"+1702AA

"Solus-Win64-Shipping.exe"+170283: E8 48 92 18 00        -  call Solus-Win64-Shipping.exe+2F94D0
"Solus-Win64-Shipping.exe"+170288: 48 89 47 18           -  mov [rdi+18],rax
"Solus-Win64-Shipping.exe"+17028C: 48 8B 47 18           -  mov rax,[rdi+18]
"Solus-Win64-Shipping.exe"+170290: 48 8D 14 F0           -  lea rdx,[rax+rsi*8]
"Solus-Win64-Shipping.exe"+170294: 48 85 D2              -  test rdx,rdx
"Solus-Win64-Shipping.exe"+170297: 74 03                 -  je Solus-Win64-Shipping.exe+17029C
"Solus-Win64-Shipping.exe"+170299: 48 89 1A              -  mov [rdx],rbx
"Solus-Win64-Shipping.exe"+17029C: 80 BB 08 03 00 00 00  -  cmp byte ptr [rbx+00000308],00
"Solus-Win64-Shipping.exe"+1702A3: 48 8B 74 24 70        -  mov rsi,[rsp+70]
"Solus-Win64-Shipping.exe"+1702A8: 75 06                 -  jne Solus-Win64-Shipping.exe+1702B0
// ---------- INJECTING HERE ----------
"Solus-Win64-Shipping.exe"+1702AA: FF 85 C0 68 03 00     -  inc [rbp+000368C0]
// ---------- DONE INJECTING  ----------
"Solus-Win64-Shipping.exe"+1702B0: 48 8B 7C 24 50        -  mov rdi,[rsp+50]
"Solus-Win64-Shipping.exe"+1702B5: 48 83 C4 58           -  add rsp,58
"Solus-Win64-Shipping.exe"+1702B9: 5D                    -  pop rbp
"Solus-Win64-Shipping.exe"+1702BA: 5B                    -  pop rbx
"Solus-Win64-Shipping.exe"+1702BB: C3                    -  ret 
"Solus-Win64-Shipping.exe"+1702BC: 83 F8 FF              -  cmp eax,-01
"Solus-Win64-Shipping.exe"+1702BF: 0F 84 29 FF FF FF     -  je Solus-Win64-Shipping.exe+1701EE
"Solus-Win64-Shipping.exe"+1702C5: 48 63 C8              -  movsxd  rcx,eax
"Solus-Win64-Shipping.exe"+1702C8: 48 8D 3C 49           -  lea rdi,[rcx+rcx*2]
"Solus-Win64-Shipping.exe"+1702CC: 48 C1 E7 04           -  shl rdi,04
}"""

[[cheat]]
id = "item-dupe-caution-may-break-shit"
name = "Item Dupe [Caution: may break shit]"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]

aobscanmodule(items,Solus-Win64-Shipping.exe,FF 4F 18 41 B8 08 00 00 00 8B 4F 18 8B 57 1C E8 D6) // should be unique
alloc(newmem,$1000,"Solus-Win64-Shipping.exe"+171AD6)

label(code)
label(return)

newmem:

code:
  inc [rdi+18]
  mov r8d,00000008
  jmp return

items:
  jmp newmem
  nop
  nop
  nop
  nop
return:
registersymbol(items)

[DISABLE]

items:
  db FF 4F 18 41 B8 08 00 00 00

unregistersymbol(items)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Solus-Win64-Shipping.exe"+171AD6

"Solus-Win64-Shipping.exe"+171AB3: 74 21                             -  je Solus-Win64-Shipping.exe+171AD6
"Solus-Win64-Shipping.exe"+171AB5: 4C 63 C0                          -  movsxd  r8,eax
"Solus-Win64-Shipping.exe"+171AB8: 4C 8B CA                          -  mov r9,rdx
"Solus-Win64-Shipping.exe"+171ABB: 8D 43 01                          -  lea eax,[rbx+01]
"Solus-Win64-Shipping.exe"+171ABE: 49 C1 E0 03                       -  shl r8,03
"Solus-Win64-Shipping.exe"+171AC2: 48 63 C8                          -  movsxd  rcx,eax
"Solus-Win64-Shipping.exe"+171AC5: 48 63 C3                          -  movsxd  rax,ebx
"Solus-Win64-Shipping.exe"+171AC8: 48 8D 14 CA                       -  lea rdx,[rdx+rcx*8]
"Solus-Win64-Shipping.exe"+171ACC: 49 8D 0C C1                       -  lea rcx,[r9+rax*8]
"Solus-Win64-Shipping.exe"+171AD0: FF 15 62 91 A2 01                 -  call qword ptr [Solus-Win64-Shipping.exe+1B9AC38]
// ---------- INJECTING HERE ----------
"Solus-Win64-Shipping.exe"+171AD6: FF 4F 18                          -  dec [rdi+18]
"Solus-Win64-Shipping.exe"+171AD9: 41 B8 08 00 00 00                 -  mov r8d,00000008
// ---------- DONE INJECTING  ----------
"Solus-Win64-Shipping.exe"+171ADF: 8B 4F 18                          -  mov ecx,[rdi+18]
"Solus-Win64-Shipping.exe"+171AE2: 8B 57 1C                          -  mov edx,[rdi+1C]
"Solus-Win64-Shipping.exe"+171AE5: E8 D6 11 14 00                    -  call Solus-Win64-Shipping.exe+2B2CC0
"Solus-Win64-Shipping.exe"+171AEA: 3B 47 1C                          -  cmp eax,[rdi+1C]
"Solus-Win64-Shipping.exe"+171AED: 74 23                             -  je Solus-Win64-Shipping.exe+171B12
"Solus-Win64-Shipping.exe"+171AEF: 89 47 1C                          -  mov [rdi+1C],eax
"Solus-Win64-Shipping.exe"+171AF2: 48 8B 4F 10                       -  mov rcx,[rdi+10]
"Solus-Win64-Shipping.exe"+171AF6: 48 85 C9                          -  test rcx,rcx
"Solus-Win64-Shipping.exe"+171AF9: 75 04                             -  jne Solus-Win64-Shipping.exe+171AFF
"Solus-Win64-Shipping.exe"+171AFB: 85 C0                             -  test eax,eax
}"""

[[cheat]]
id = "auto-assemble-script"
name = "Auto Assemble script"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]

aobscanmodule(thirst,Solus-Win64-Shipping.exe,18 B6 FF 48 8B 5C 24 30 F3 0F 11 07 48 83 C4 20) // should be unique
alloc(newmem,$1000,"Solus-Win64-Shipping.exe"+13D8D75)

label(code)
label(return)

newmem:

code:
  //movss [rdi],xmm0
  add rsp,20
  jmp return

thirst+08:
  jmp newmem
  nop
  nop
  nop
return:
registersymbol(thirst)

[DISABLE]

thirst+08:
  db F3 0F 11 07 48 83 C4 20

unregistersymbol(thirst)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Solus-Win64-Shipping.exe"+13D8D75

"Solus-Win64-Shipping.exe"+13D8D4C: 48 8B 43 20              -  mov rax,[rbx+20]
"Solus-Win64-Shipping.exe"+13D8D50: 33 C9                    -  xor ecx,ecx
"Solus-Win64-Shipping.exe"+13D8D52: F3 0F 10 4C 24 38        -  movss xmm1,[rsp+38]
"Solus-Win64-Shipping.exe"+13D8D58: 48 85 C0                 -  test rax,rax
"Solus-Win64-Shipping.exe"+13D8D5B: F3 0F 10 44 24 40        -  movss xmm0,[rsp+40]
"Solus-Win64-Shipping.exe"+13D8D61: 0F 95 C1                 -  setne cl
"Solus-Win64-Shipping.exe"+13D8D64: 48 03 C8                 -  add rcx,rax
"Solus-Win64-Shipping.exe"+13D8D67: 48 89 4B 20              -  mov [rbx+20],rcx
"Solus-Win64-Shipping.exe"+13D8D6B: E8 A0 18 B6 FF           -  call Solus-Win64-Shipping.exe+F3A610
"Solus-Win64-Shipping.exe"+13D8D70: 48 8B 5C 24 30           -  mov rbx,[rsp+30]
// ---------- INJECTING HERE ----------
"Solus-Win64-Shipping.exe"+13D8D75: F3 0F 11 07              -  movss [rdi],xmm0
"Solus-Win64-Shipping.exe"+13D8D79: 48 83 C4 20              -  add rsp,20
// ---------- DONE INJECTING  ----------
"Solus-Win64-Shipping.exe"+13D8D7D: 5F                       -  pop rdi
"Solus-Win64-Shipping.exe"+13D8D7E: C3                       -  ret 
"Solus-Win64-Shipping.exe"+13D8D7F: CC                       -  int 3 
"Solus-Win64-Shipping.exe"+13D8D80: 48 89 5C 24 08           -  mov [rsp+08],rbx
"Solus-Win64-Shipping.exe"+13D8D85: 48 89 74 24 20           -  mov [rsp+20],rsi
"Solus-Win64-Shipping.exe"+13D8D8A: 57                       -  push rdi
"Solus-Win64-Shipping.exe"+13D8D8B: 48 83 EC 20              -  sub rsp,20
"Solus-Win64-Shipping.exe"+13D8D8F: 33 FF                    -  xor edi,edi
"Solus-Win64-Shipping.exe"+13D8D91: 49 8B F0                 -  mov rsi,r8
"Solus-Win64-Shipping.exe"+13D8D94: 48 8B DA                 -  mov rbx,rdx
}"""
