[game]
name = "Mass Effect Andromeda"
exe = "masseffectandromeda.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=596"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "unlimited-health"
name = "Unlimited Health"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : MassEffectAndromeda.exe
  Version: 
  Date   : 2017-03-17
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(health,MassEffectAndromeda.exe,48 8B 89 28 02 00 00 48 85 C9 74 09) // should be unique
alloc(newmem,$1000,"MassEffectAndromeda.exe"+5E64F7A)

label(code)
label(return)

newmem:
  mov rcx,[rcx+00000228]
  push rdx
  mov edx,[rcx+24]
  mov [rcx+20],edx
  mov edx,[rcx+00000640]
  mov [rcx+0000063C],edx
  pop rdx
code:

  jmp return

health:
  jmp newmem
  nop
  nop
return:
registersymbol(health)

[DISABLE]

health:
  db 48 8B 89 28 02 00 00

unregistersymbol(health)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "MassEffectAndromeda.exe"+5E64F7A

"MassEffectAndromeda.exe"+5E64F55: F3 0F 11 4C 24 68                       -  movss [rsp+68],xmm1
"MassEffectAndromeda.exe"+5E64F5B: 48 8B 07                                -  mov rax,[rdi]
"MassEffectAndromeda.exe"+5E64F5E: 48 89 F9                                -  mov rcx,rdi
"MassEffectAndromeda.exe"+5E64F61: FF 50 20                                -  call qword ptr [rax+20]
"MassEffectAndromeda.exe"+5E64F64: 0F B6 D8                                -  movzx ebx,al
"MassEffectAndromeda.exe"+5E64F67: 88 44 24 6C                             -  mov [rsp+6C],al
"MassEffectAndromeda.exe"+5E64F6B: 0F 28 C6                                -  movaps xmm0,xmm6
"MassEffectAndromeda.exe"+5E64F6E: 48 8B 8F B8 14 00 00                    -  mov rcx,[rdi+000014B8]
"MassEffectAndromeda.exe"+5E64F75: 48 85 C9                                -  test rcx,rcx
"MassEffectAndromeda.exe"+5E64F78: 74 15                                   -  je MassEffectAndromeda.exe+5E64F8F
// ---------- INJECTING HERE ----------
"MassEffectAndromeda.exe"+5E64F7A: 48 8B 89 28 02 00 00                    -  mov rcx,[rcx+00000228]
// ---------- DONE INJECTING  ----------
"MassEffectAndromeda.exe"+5E64F81: 48 85 C9                                -  test rcx,rcx
"MassEffectAndromeda.exe"+5E64F84: 74 09                                   -  je MassEffectAndromeda.exe+5E64F8F
"MassEffectAndromeda.exe"+5E64F86: 48 8B 11                                -  mov rdx,[rcx]
"MassEffectAndromeda.exe"+5E64F89: FF 92 E8 00 00 00                       -  call qword ptr [rdx+000000E8]
"MassEffectAndromeda.exe"+5E64F8F: F3 0F 11 44 24 70                       -  movss [rsp+70],xmm0
"MassEffectAndromeda.exe"+5E64F95: 84 DB                                   -  test bl,bl
"MassEffectAndromeda.exe"+5E64F97: 74 20                                   -  je MassEffectAndromeda.exe+5E64FB9
"MassEffectAndromeda.exe"+5E64F99: 48 89 F9                                -  mov rcx,rdi
"MassEffectAndromeda.exe"+5E64F9C: E8 4F DF FF FF                          -  call MassEffectAndromeda.exe+5E62EF0
"MassEffectAndromeda.exe"+5E64FA1: 48 8B 88 28 02 00 00                    -  mov rcx,[rax+00000228]
}"""

[[cheat]]
id = "no-reload"
name = "No Reload"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
{ Game   : MassEffectAndromeda.exe
  Version: 
  Date   : 2017-03-17
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(noreload,MassEffectAndromeda.exe,0F B7 88 F4 00 00 00 8D) // should be unique
alloc(newmem,$1000,"MassEffectAndromeda.exe"+509435A)

label(code)
label(return)

newmem:
mov word ptr [rax+000000F4], #99
code:
  movzx ecx,word ptr [rax+000000F4]
  jmp return

noreload:
  jmp newmem
  nop
  nop
return:
registersymbol(noreload)

[DISABLE]

noreload:
  db 0F B7 88 F4 00 00 00

unregistersymbol(noreload)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "MassEffectAndromeda.exe"+509435A

"MassEffectAndromeda.exe"+5094349: CC                    -  int 3 
"MassEffectAndromeda.exe"+509434A: CC                    -  int 3 
"MassEffectAndromeda.exe"+509434B: CC                    -  int 3 
"MassEffectAndromeda.exe"+509434C: CC                    -  int 3 
"MassEffectAndromeda.exe"+509434D: CC                    -  int 3 
"MassEffectAndromeda.exe"+509434E: CC                    -  int 3 
"MassEffectAndromeda.exe"+509434F: CC                    -  int 3 
"MassEffectAndromeda.exe"+5094350: 48 83 EC 28           -  sub rsp,28
"MassEffectAndromeda.exe"+5094354: 48 8B 01              -  mov rax,[rcx]
"MassEffectAndromeda.exe"+5094357: FF 50 38              -  call qword ptr [rax+38]
// ---------- INJECTING HERE ----------
"MassEffectAndromeda.exe"+509435A: 0F B7 88 F4 00 00 00  -  movzx ecx,word ptr [rax+000000F4]
// ---------- DONE INJECTING  ----------
"MassEffectAndromeda.exe"+5094361: 8D 51 FF              -  lea edx,[rcx-01]
"MassEffectAndromeda.exe"+5094364: 66 39 CA              -  cmp dx,cx
"MassEffectAndromeda.exe"+5094367: 74 07                 -  je MassEffectAndromeda.exe+5094370
"MassEffectAndromeda.exe"+5094369: 66 89 90 F4 00 00 00  -  mov [rax+000000F4],dx
"MassEffectAndromeda.exe"+5094370: 0F B7 88 F8 00 00 00  -  movzx ecx,word ptr [rax+000000F8]
"MassEffectAndromeda.exe"+5094377: 66 85 C9              -  test cx,cx
"MassEffectAndromeda.exe"+509437A: 74 0A                 -  je MassEffectAndromeda.exe+5094386
"MassEffectAndromeda.exe"+509437C: 66 FF C9              -  dec cx
"MassEffectAndromeda.exe"+509437F: 66 89 88 F8 00 00 00  -  mov [rax+000000F8],cx
"MassEffectAndromeda.exe"+5094386: 0F B7 80 F4 00 00 00  -  movzx eax,word ptr [rax+000000F4]
}"""

[[cheat]]
id = "unlimited-ammo"
name = "Unlimited Ammo"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : MassEffectAndromeda.exe
  Version: 
  Date   : 2017-03-17
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(ammo,MassEffectAndromeda.exe,0F B7 B1 F6 00 00 00) // should be unique
alloc(newmem,$1000,"MassEffectAndromeda.exe"+51C6138)

label(code)
label(return)

newmem:
mov word ptr [rcx+000000F6], #999
code:
  movzx esi,word ptr [rcx+000000F6]
  jmp return

ammo:
  jmp newmem
  nop
  nop
return:
registersymbol(ammo)

[DISABLE]

ammo:
  db 0F B7 B1 F6 00 00 00

unregistersymbol(ammo)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "MassEffectAndromeda.exe"+51C6138

"MassEffectAndromeda.exe"+51C611D: CC                    -  int 3 
"MassEffectAndromeda.exe"+51C611E: CC                    -  int 3 
"MassEffectAndromeda.exe"+51C611F: CC                    -  int 3 
"MassEffectAndromeda.exe"+51C6120: 48 89 5C 24 08        -  mov [rsp+08],rbx
"MassEffectAndromeda.exe"+51C6125: 48 89 6C 24 10        -  mov [rsp+10],rbp
"MassEffectAndromeda.exe"+51C612A: 48 89 74 24 18        -  mov [rsp+18],rsi
"MassEffectAndromeda.exe"+51C612F: 57                    -  push rdi
"MassEffectAndromeda.exe"+51C6130: 41 56                 -  push r14
"MassEffectAndromeda.exe"+51C6132: 41 57                 -  push r15
"MassEffectAndromeda.exe"+51C6134: 48 83 EC 20           -  sub rsp,20
// ---------- INJECTING HERE ----------
"MassEffectAndromeda.exe"+51C6138: 0F B7 B1 F6 00 00 00  -  movzx esi,word ptr [rcx+000000F6]
// ---------- DONE INJECTING  ----------
"MassEffectAndromeda.exe"+51C613F: 0F B7 99 F4 00 00 00  -  movzx ebx,word ptr [rcx+000000F4]
"MassEffectAndromeda.exe"+51C6146: 45 0F B6 F0           -  movzx r14d,r8l
"MassEffectAndromeda.exe"+51C614A: 66 39 F2              -  cmp dx,si
"MassEffectAndromeda.exe"+51C614D: 48 89 CF              -  mov rdi,rcx
"MassEffectAndromeda.exe"+51C6150: 66 0F 42 F2           -  cmovb si,dx
"MassEffectAndromeda.exe"+51C6154: E8 67 E8 FF FF        -  call MassEffectAndromeda.exe+51C49C0
"MassEffectAndromeda.exe"+51C6159: 41 BF 00 00 00 00     -  mov r15d,00000000
"MassEffectAndromeda.exe"+51C615F: 0F B7 E8              -  movzx ebp,ax
"MassEffectAndromeda.exe"+51C6162: 89 D8                 -  mov eax,ebx
"MassEffectAndromeda.exe"+51C6164: 29 DD                 -  sub ebp,ebx
}"""

[[cheat]]
id = "unlimited-skill-points"
name = "Unlimited Skill Points"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : MassEffectAndromeda.exe
  Version: 
  Date   : 2017-03-17
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(skillpoints,MassEffectAndromeda.exe,8B 02 44 39 C8 72) // should be unique
alloc(newmem,$1000,"MassEffectAndromeda.exe"+53C428B)

label(code)
label(return)

newmem:
mov [rdx], #99
code:
  mov eax,[rdx]
  cmp eax,r9d
  jmp return

skillpoints:
  jmp newmem
return:
registersymbol(skillpoints)

[DISABLE]

skillpoints:
  db 8B 02 44 39 C8

unregistersymbol(skillpoints)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "MassEffectAndromeda.exe"+53C428B

"MassEffectAndromeda.exe"+53C4264: 30 C0                       -  xor al,al
"MassEffectAndromeda.exe"+53C4266: 48 83 C4 28                 -  add rsp,28
"MassEffectAndromeda.exe"+53C426A: C3                          -  ret 
"MassEffectAndromeda.exe"+53C426B: CC                          -  int 3 
"MassEffectAndromeda.exe"+53C426C: 80 B9 13 02 00 00 00        -  cmp byte ptr [rcx+00000213],00
"MassEffectAndromeda.exe"+53C4273: 48 8D 91 08 02 00 00        -  lea rdx,[rcx+00000208]
"MassEffectAndromeda.exe"+53C427A: 75 07                       -  jne MassEffectAndromeda.exe+53C4283
"MassEffectAndromeda.exe"+53C427C: 48 8D 91 04 01 00 00        -  lea rdx,[rcx+00000104]
"MassEffectAndromeda.exe"+53C4283: 41 0F BE C1                 -  movsx eax,r9l
"MassEffectAndromeda.exe"+53C4287: 45 8B 0C 82                 -  mov r9d,[r10+rax*4]
// ---------- INJECTING HERE ----------
"MassEffectAndromeda.exe"+53C428B: 8B 02                       -  mov eax,[rdx]
"MassEffectAndromeda.exe"+53C428D: 44 39 C8                    -  cmp eax,r9d
// ---------- DONE INJECTING  ----------
"MassEffectAndromeda.exe"+53C4290: 72 D2                       -  jb MassEffectAndromeda.exe+53C4264
"MassEffectAndromeda.exe"+53C4292: 44 29 C8                    -  sub eax,r9d
"MassEffectAndromeda.exe"+53C4295: 89 02                       -  mov [rdx],eax
"MassEffectAndromeda.exe"+53C4297: 48 8B 89 B0 01 00 00        -  mov rcx,[rcx+000001B0]
"MassEffectAndromeda.exe"+53C429E: 48 85 C9                    -  test rcx,rcx
"MassEffectAndromeda.exe"+53C42A1: 74 1F                       -  je MassEffectAndromeda.exe+53C42C2
"MassEffectAndromeda.exe"+53C42A3: 45 8B 80 B8 01 00 00        -  mov r8d,[r8+000001B8]
"MassEffectAndromeda.exe"+53C42AA: BA 0F A2 C3 90              -  mov edx,90C3A20F
"MassEffectAndromeda.exe"+53C42AF: 8D 92 F9 5D 3C 6F           -  lea edx,[rdx+6F3C5DF9]
"MassEffectAndromeda.exe"+53C42B5: 45 0F B7 C8                 -  movzx r9d,r8w
}"""

[[cheat]]
id = "unlimited-credits"
name = "Unlimited Credits"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : MassEffectAndromeda.exe
  Version: 
  Date   : 2017-03-17
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(credits,MassEffectAndromeda.exe,43 8D 04 34 3B 43 1C) // should be unique
alloc(newmem,$1000,"MassEffectAndromeda.exe"+51394DE)

label(code)
label(return)

newmem:
//lea eax,[r12+r14]
mov [rbx+1C], #10003
mov eax, #10003
code:

  cmp eax,[rbx+1C]
  jmp return

credits:
  jmp newmem
  nop
  nop
return:
registersymbol(credits)

[DISABLE]

credits:
  db 43 8D 04 34 3B 43 1C

unregistersymbol(credits)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "MassEffectAndromeda.exe"+51394DE

"MassEffectAndromeda.exe"+51394C7: 49 8D 4F 30              -  lea rcx,[r15+30]
"MassEffectAndromeda.exe"+51394CB: 48 8B 01                 -  mov rax,[rcx]
"MassEffectAndromeda.exe"+51394CE: 48 89 DA                 -  mov rdx,rbx
"MassEffectAndromeda.exe"+51394D1: FF 50 28                 -  call qword ptr [rax+28]
"MassEffectAndromeda.exe"+51394D4: EB 2B                    -  jmp MassEffectAndromeda.exe+5139501
"MassEffectAndromeda.exe"+51394D6: B0 95                    -  mov al,-6B
"MassEffectAndromeda.exe"+51394D8: D3 04 AC                 -  rol [rsp+rbp*4],cl
"MassEffectAndromeda.exe"+51394DB: F1                       -  db F1
"MassEffectAndromeda.exe"+51394DC: EF                       -  out dx,eax
"MassEffectAndromeda.exe"+51394DD: A7                       -  cmpsd 
// ---------- INJECTING HERE ----------
"MassEffectAndromeda.exe"+51394DE: 43 8D 04 34              -  lea eax,[r12+r14]
"MassEffectAndromeda.exe"+51394E2: 3B 43 1C                 -  cmp eax,[rbx+1C]
// ---------- DONE INJECTING  ----------
"MassEffectAndromeda.exe"+51394E5: 74 1A                    -  je MassEffectAndromeda.exe+5139501
"MassEffectAndromeda.exe"+51394E7: 89 43 1C                 -  mov [rbx+1C],eax
"MassEffectAndromeda.exe"+51394EA: 80 7B 38 00              -  cmp byte ptr [rbx+38],00
"MassEffectAndromeda.exe"+51394EE: 75 11                    -  jne MassEffectAndromeda.exe+5139501
"MassEffectAndromeda.exe"+51394F0: 48 8B 4B 30              -  mov rcx,[rbx+30]
"MassEffectAndromeda.exe"+51394F4: 48 85 C9                 -  test rcx,rcx
"MassEffectAndromeda.exe"+51394F7: 74 08                    -  je MassEffectAndromeda.exe+5139501
"MassEffectAndromeda.exe"+51394F9: 48 8B 01                 -  mov rax,[rcx]
"MassEffectAndromeda.exe"+51394FC: 8B 53 28                 -  mov edx,[rbx+28]
"MassEffectAndromeda.exe"+51394FF: FF 10                    -  call qword ptr [rax]
}"""

[[cheat]]
id = "unlimited-skill-points-v1-05"
name = "Unlimited Skill Points v1.05"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]

aobscanmodule(skillpoints,MassEffectAndromeda.exe,8B 02 41 3B C1 72) // should be unique
alloc(newmem,$1000,skillpoints)

label(code)
label(return)

newmem:
mov [rdx], #99
code:
  mov eax,[rdx]
  cmp eax,r9d
  jmp return

skillpoints:
  jmp newmem
return:
registersymbol(skillpoints)

[DISABLE]

skillpoints:
  db 8B 02 41 3B C1

unregistersymbol(skillpoints)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "MassEffectAndromeda.exe"+8EC07A

"MassEffectAndromeda.exe"+8EC052: 7C 07                       -  jl MassEffectAndromeda.exe+8EC05B
"MassEffectAndromeda.exe"+8EC054: 32 C0                       -  xor al,al
"MassEffectAndromeda.exe"+8EC056: 48 83 C4 28                 -  add rsp,28
"MassEffectAndromeda.exe"+8EC05A: C3                          -  ret
"MassEffectAndromeda.exe"+8EC05B: 80 B9 13 02 00 00 00        -  cmp byte ptr [rcx+00000213],00
"MassEffectAndromeda.exe"+8EC062: 48 8D 91 08 02 00 00        -  lea rdx,[rcx+00000208]
"MassEffectAndromeda.exe"+8EC069: 75 07                       -  jne MassEffectAndromeda.exe+8EC072
"MassEffectAndromeda.exe"+8EC06B: 48 8D 91 04 01 00 00        -  lea rdx,[rcx+00000104]
"MassEffectAndromeda.exe"+8EC072: 41 0F BE C1                 -  movsx eax,r9l
"MassEffectAndromeda.exe"+8EC076: 45 8B 0C 82                 -  mov r9d,[r10+rax*4]
// ---------- INJECTING HERE ----------
"MassEffectAndromeda.exe"+8EC07A: 8B 02                       -  mov eax,[rdx]
"MassEffectAndromeda.exe"+8EC07C: 41 3B C1                    -  cmp eax,r9d
// ---------- DONE INJECTING  ----------
"MassEffectAndromeda.exe"+8EC07F: 72 D3                       -  jb MassEffectAndromeda.exe+8EC054
"MassEffectAndromeda.exe"+8EC081: 41 2B C1                    -  sub eax,r9d
"MassEffectAndromeda.exe"+8EC084: 89 02                       -  mov [rdx],eax
"MassEffectAndromeda.exe"+8EC086: 48 8B 89 B0 01 00 00        -  mov rcx,[rcx+000001B0]
"MassEffectAndromeda.exe"+8EC08D: 48 85 C9                    -  test rcx,rcx
"MassEffectAndromeda.exe"+8EC090: 74 19                       -  je MassEffectAndromeda.exe+8EC0AB
"MassEffectAndromeda.exe"+8EC092: 45 8B 80 B8 01 00 00        -  mov r8d,[r8+000001B8]
"MassEffectAndromeda.exe"+8EC099: BA 08 00 00 00              -  mov edx,00000008
"MassEffectAndromeda.exe"+8EC09E: 45 0F B7 C8                 -  movzx r9d,r8w
"MassEffectAndromeda.exe"+8EC0A2: 41 C1 E8 10                 -  shr r8d,10
}"""

[[cheat]]
id = "unlimited-cryo-pod-points"
name = "Unlimited Cryo Pod Points"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]

aobscanmodule(crypoints,MassEffectAndromeda.exe,44 39 38 7E 04) // should be unique
alloc(newmem,$1000,"MassEffectAndromeda.exe"+50EA807)

label(code)
label(return)

newmem:
mov [rax], #99
code:
  cmp [rax],r15d
  jle MassEffectAndromeda.exe+50EA810
  jmp return

crypoints:
  jmp newmem
return:
registersymbol(crypoints)

[DISABLE]

crypoints:
  db 44 39 38 7E 04

unregistersymbol(crypoints)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "MassEffectAndromeda.exe"+50EA807

"MassEffectAndromeda.exe"+50EA7ED: 48 89 C2                 -  mov rdx,rax
"MassEffectAndromeda.exe"+50EA7F0: 48 85 D2                 -  test rdx,rdx
"MassEffectAndromeda.exe"+50EA7F3: 74 0B                    -  je MassEffectAndromeda.exe+50EA800
"MassEffectAndromeda.exe"+50EA7F5: F6 42 1C 40              -  test byte ptr [rdx+1C],40
"MassEffectAndromeda.exe"+50EA7F9: 74 05                    -  je MassEffectAndromeda.exe+50EA800
"MassEffectAndromeda.exe"+50EA7FB: 48 8B 02                 -  mov rax,[rdx]
"MassEffectAndromeda.exe"+50EA7FE: EB 03                    -  jmp MassEffectAndromeda.exe+50EA803
"MassEffectAndromeda.exe"+50EA800: 4C 89 F8                 -  mov rax,r15
"MassEffectAndromeda.exe"+50EA803: 84 DB                    -  test bl,bl
"MassEffectAndromeda.exe"+50EA805: 74 09                    -  je MassEffectAndromeda.exe+50EA810
// ---------- INJECTING HERE ----------
"MassEffectAndromeda.exe"+50EA807: 44 39 38                 -  cmp [rax],r15d
"MassEffectAndromeda.exe"+50EA80A: 7E 04                    -  jle MassEffectAndromeda.exe+50EA810
// ---------- DONE INJECTING  ----------
"MassEffectAndromeda.exe"+50EA80C: B0 01                    -  mov al,01
"MassEffectAndromeda.exe"+50EA80E: EB 02                    -  jmp MassEffectAndromeda.exe+50EA812
"MassEffectAndromeda.exe"+50EA810: 30 C0                    -  xor al,al
"MassEffectAndromeda.exe"+50EA812: 41 88 46 21              -  mov [r14+21],al
"MassEffectAndromeda.exe"+50EA816: 45 38 7E 7C              -  cmp [r14+7C],r15l
"MassEffectAndromeda.exe"+50EA81A: 0F 84 E4 00 00 00        -  je MassEffectAndromeda.exe+50EA904
"MassEffectAndromeda.exe"+50EA820: 48 8B 45 C8              -  mov rax,[rbp-38]
"MassEffectAndromeda.exe"+50EA824: 48 8B 40 28              -  mov rax,[rax+28]
"MassEffectAndromeda.exe"+50EA828: 48 8B 70 28              -  mov rsi,[rax+28]
"MassEffectAndromeda.exe"+50EA82C: 4C 89 E7                 -  mov rdi,r12
}"""
