[game]
name = "Stygian: Reign of the Old Ones"
exe = "stygian.exe"
notes = "Converted from a Cheat Engine table by The Mogician. Source: https://fearlessrevolution.com/viewtopic.php?t=10374"
verified = []
author = "The Mogician"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "attribute-points"
name = "Attribute Points"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x144edf0"
hops = [
    "+0xdb8",
    "+0xa0",
    "+0x80",
    "+0x28",
    "+0x70",
    "+0x20",
    "+0x78",
]

[[cheat]]
id = "skill-points"
name = "Skill Points"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x144edf0"
hops = [
    "+0xdb8",
    "+0xa0",
    "+0x80",
    "+0x28",
    "+0x70",
    "+0x20",
    "+0x7c",
]

[[cheat]]
id = "health"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x144ebd8"
hops = [
    "+0x0",
    "+0x30",
    "+0x0",
    "+0x90",
    "+0x0",
    "+0xe8",
    "+0x30",
    "+0xa8",
    "+0x128",
]

[[cheat]]
id = "sanity"
name = "Sanity"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x144ebd8"
hops = [
    "+0x0",
    "+0x30",
    "+0x0",
    "+0x90",
    "+0x0",
    "+0xe8",
    "+0x30",
    "+0xa8",
    "+0x12c",
]

[[cheat]]
id = "xp"
name = "XP"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x144ebd8"
hops = [
    "+0x0",
    "+0x30",
    "+0x0",
    "+0x90",
    "+0x0",
    "+0xe8",
    "+0x30",
    "+0xa8",
    "+0xb4",
]

[[cheat]]
id = "skill-points-2"
name = "Skill Points"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x144ebd8"
hops = [
    "+0x0",
    "+0x30",
    "+0x0",
    "+0x90",
    "+0x0",
    "+0xe8",
    "+0x30",
    "+0xa8",
    "+0xc4",
]

[[cheat]]
id = "level"
name = "Level"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x144ebd8"
hops = [
    "+0x0",
    "+0x30",
    "+0x0",
    "+0x90",
    "+0x0",
    "+0xe8",
    "+0x30",
    "+0xa8",
    "+0xc0",
]

[[cheat]]
id = "angst"
name = "Angst"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x144ebd8"
hops = [
    "+0x0",
    "+0x30",
    "+0x0",
    "+0x90",
    "+0x0",
    "+0xe8",
    "+0x30",
    "+0xa8",
    "+0xd4",
]

[[cheat]]
id = "ap"
name = "AP"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x130",
]

[[cheat]]
id = "health-2"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x128",
]

[[cheat]]
id = "sanity-2"
name = "Sanity"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x12c",
]

[[cheat]]
id = "xp-2"
name = "XP"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0xb4",
]

[[cheat]]
id = "skill-points-when-leveling-up"
name = "Skill Points (when leveling up)"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0xc4",
]

[[cheat]]
id = "level-2"
name = "Level"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0xc0",
]

[[cheat]]
id = "angst-2"
name = "Angst"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0xd4",
]

[[cheat]]
id = "sanity-3"
name = "Sanity"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "mono.dll"
offset = "0x264110"
hops = [
    "+0x8",
    "+0x88",
    "+0x50",
    "+0x48",
    "+0x180",
    "+0x98",
    "+0xe8",
    "+0x118",
    "+0x12c",
]

[[cheat]]
id = "experience"
name = "Experience"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "mono.dll"
offset = "0x264110"
hops = [
    "+0x8",
    "+0x88",
    "+0x50",
    "+0x48",
    "+0x180",
    "+0x98",
    "+0xe8",
    "+0x118",
    "+0xb4",
]

[[cheat]]
id = "skill-points-3"
name = "Skill Points"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "mono.dll"
offset = "0x264110"
hops = [
    "+0x8",
    "+0x88",
    "+0x50",
    "+0x48",
    "+0x180",
    "+0x98",
    "+0xe8",
    "+0x118",
    "+0xc4",
]

[[cheat]]
id = "level-3"
name = "Level"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "mono.dll"
offset = "0x264110"
hops = [
    "+0x8",
    "+0x88",
    "+0x50",
    "+0x48",
    "+0x180",
    "+0x98",
    "+0xe8",
    "+0x118",
    "+0xc0",
]

[[cheat]]
id = "angst-3"
name = "Angst"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "mono.dll"
offset = "0x264110"
hops = [
    "+0x8",
    "+0x88",
    "+0x50",
    "+0x48",
    "+0x180",
    "+0x98",
    "+0xe8",
    "+0x118",
    "+0xd4",
]

[[cheat]]
id = "physique"
name = "Physique"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x48",
    "+0x20",
    "+0xe0",
]

[[cheat]]
id = "agility"
name = "Agility"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x48",
    "+0x20",
    "+0xe4",
]

[[cheat]]
id = "senses"
name = "Senses"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x48",
    "+0x20",
    "+0xe8",
]

[[cheat]]
id = "mind"
name = "Mind"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x48",
    "+0x20",
    "+0xec",
]

[[cheat]]
id = "will"
name = "Will"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x48",
    "+0x20",
    "+0xf0",
]

[[cheat]]
id = "presence"
name = "Presence"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x48",
    "+0x20",
    "+0xf4",
]

[[cheat]]
id = "athletics"
name = "Athletics"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "UnityPlayer.dll"
offset = "0x13d1e58"
hops = [
    "+0x40",
    "+0x18",
    "+0x60",
    "+0x90",
    "+0x28",
    "+0x20",
    "+0x50",
    "+0x28",
    "+0x20",
]
