[game]
name = "Emperor : Rise of the Middle Kingdom"
exe = "emperor.exe"
notes = "Converted from a Cheat Engine table by Shizuma. Source: https://fearlessrevolution.com/viewtopic.php?t=17493"
verified = []
author = "Shizuma"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "gold"
name = "Gold"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0xf0f970"
hops = []

[[cheat]]
id = "monthly-productions"
name = "Monthly productions"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:0 No prod",
    "400:4 Units",
]

[cheat.locator]
find = "symbol"
symbol = "iGoodsOrch"
hops = []

[[cheat]]
id = "building-unlock-all"
name = "< Building - Unlock all"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Emperor.exe
  Version:
  Date   : 2021-09-11
  Author : Ladmin

  This script does Unlock Buildings because dont works on main script
}
//=========================================
// Definitions
define(hpUnlockBlding,"Emperor.exe"+3660) // UnlockBuildings

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

assert(hpUnlockBlding,33 C0 5E)

label(_BackUnlockBlding)

hpUnlockBlding:
  jmp Emperor.exe+3659
  nop
_BackUnlockBlding:

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
hpUnlockBlding:
  db 33 C0 5E
  // xor eax,eax
  // pop esi
  // ret"""

[[cheat]]
id = "nu-wa"
name = "Nu Wa"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0ac"
hops = []

[[cheat]]
id = "shen-nong"
name = "Shen Nong"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0ad"
hops = []

[[cheat]]
id = "huang-di"
name = "Huang Di"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0ae"
hops = []

[[cheat]]
id = "confucius"
name = "Confucius"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b5"
hops = []

[[cheat]]
id = "sun-tzu"
name = "Sun Tzu"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b6"
hops = []

[[cheat]]
id = "mencius"
name = "Mencius"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b7"
hops = []

[[cheat]]
id = "guan-yin"
name = "Guan Yin"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b6"
hops = []

[[cheat]]
id = "xi-wang-mu"
name = "Xi Wang Mu"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0af"
hops = []

[[cheat]]
id = "zao-jun"
name = "Zao Jun"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b0"
hops = []

[[cheat]]
id = "guan-di"
name = "Guan Di"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b1"
hops = []

[[cheat]]
id = "guan-yin-2"
name = "Guan Yin"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b2"
hops = []

[[cheat]]
id = "bodhidharma"
name = "Bodhidharma"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b3"
hops = []

[[cheat]]
id = "sun-wu-kong"
name = "Sun Wu Kong"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x85d0b4"
hops = []

[[cheat]]
id = "monetary-str"
name = "Monetary Str"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 1
choices = [
    "1:1 Coin",
    "2:2 Coins",
    "3:3 Coins",
    "4:4 Coins",
    "5:5 Coins",
]

[cheat.locator]
find = "symbol"
symbol = "pCitySelector1"
hops = ["+0x3ab4"]

[[cheat]]
id = "military-str"
name = "Military Str"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:1 Shield",
    "40:2 Shields",
    "60:3 Shields",
    "80:4 Shields",
    "100:5 Shields",
    "120:6 Shields",
]

[cheat.locator]
find = "symbol"
symbol = "pCitySelector1"
hops = ["+0x3adc"]

[[cheat]]
id = "faction"
name = "Faction"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 65535
choices = [
    "65535:No Faction",
    "0:Faction 1",
    "1:Faction 2",
    "2:Faction 3",
    "3:Faction 4",
]

[cheat.locator]
find = "symbol"
symbol = "pCitySelector1"
hops = ["+0x3aee"]

[[cheat]]
id = "city-fortified"
name = "City Fortified"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:No",
    "1:Yes",
]

[cheat.locator]
find = "symbol"
symbol = "pCitySelector1"
hops = ["+0x3af2"]

[[cheat]]
id = "no-description"
name = "No description"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "symbol"
symbol = "pCitySelector1"
hops = ["+0x3acc"]

[[cheat]]
id = "greatly-pleased"
name = "Greatly Pleased"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:Nothing",
    "21:Docile",
    "50:Docile Max",
]

[cheat.locator]
find = "symbol"
symbol = "pCitySelector2"
hops = ["+0x518"]

[[cheat]]
id = "greatly-angered"
name = "Greatly Angered"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
choices = [
    "0:Nothing",
    "21:Hostile",
    "50:Hostile Max",
]

[cheat.locator]
find = "symbol"
symbol = "pCitySelector2"
hops = ["+0x51c"]

[[cheat]]
id = "relation"
name = "Relation"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:Ally",
    "1:Rival",
    "2:Vassal",
]

[cheat.locator]
find = "symbol"
symbol = "pCitySelector2"
hops = ["+0x520"]

[[cheat]]
id = "trade-road"
name = "Trade Road"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:Open",
    "1:Close",
]

[cheat.locator]
find = "symbol"
symbol = "pCitySelector2"
hops = ["+0x524"]

[[cheat]]
id = "brush-size"
name = "Brush size"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:Tiny Brush",
    "1:Small Brush",
    "2:Medium Brush",
    "3:Big Brush",
    "4:Biggest Brush",
    "5:Tiny Square",
    "6:Small Square",
    "7:Medium Square",
    "8:Big Square",
    "9:Biggest Square",
]

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x48ec34"
hops = []

[[cheat]]
id = "build-monuments"
name = "> Build Monuments"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 76
choices = [
    "76:Tumulus",
    "77:Grand Tumulus",
    "78:Great Temple",
    "79:Splendid Temple",
    "80:Temple Complex",
    "81:Grand Temple Complex",
    "82:Large Palace",
    "84:Underground Vault",
    "92:Clock Tower",
    "93:Grand Pagoda",
    "233:-Laborers camp",
    "52:-Carpenters Guild",
    "235:-Masons Guild",
    "236:-Ceramists Guild",
]

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x48ebdc"
hops = []

[[cheat]]
id = "additional-options"
name = "> Additional options"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 66
choices = [
    "66:Victory Mission menu",
    "67:Victory Campaign menu",
    "69:Difficulty setting menu",
]

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0xcde045"
hops = []

[[cheat]]
id = "month"
name = "Month"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:Jan",
    "1:Feb",
    "2:Mar",
    "3:Apr",
    "4:May",
    "5:Jun",
    "6:Jul",
    "7:Aug",
    "8:Sep",
    "9:Oct",
    "10:Nov",
    "11:Dec",
]

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x882eec"
hops = []

[[cheat]]
id = "year"
name = "Year"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i16"

[cheat.locator]
find = "static"
module = "Emperor.exe"
offset = "0x9623fc"
hops = []
