[game]
name = "Anomaly Agent"
exe = "anomaly agent.exe"
notes = "Converted from a Cheat Engine table by Dante. Source: https://fearlessrevolution.com/viewtopic.php?t=27432"
verified = []
author = "Dante"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "can-bul-health-find"
name = "Can Bul - Health Find"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Anomaly Agent Demo.exe
  Version: 
  Date   : 2023-10-11
  Author : Dante

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat


 
 
aobscan(Can_Bul,2E 48 8B 86 40 01 00 00 48 8B 8E E0 01 00 00 F3 0F 10 81 7C 02 00 00) // should be unique
alloc(newmem,$256,Can_Bul)
alloc(Ptr_Can,8)
registersymbol(Ptr_Can)
label(code)
label(return)
label(Olumsuz)
registersymbol(Olumsuz)
newmem:

mov [Ptr_Can],rcx
cmp [Olumsuz],0
je code
movss xmm0,[rcx+00000278]
movss [rcx+0000027C],xmm0
code:
  movss xmm0,[rcx+0000027C]
  jmp return
nop
nop
nop
nop
Olumsuz:
db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Can_Bul+0F:
  jmp newmem
  nop 3
return:
registersymbol(Can_Bul)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
Can_Bul+0F:
  db F3 0F 10 81 7C 02 00 00

unregistersymbol(Olumsuz)
unregistersymbol(Ptr_Can)
dealloc(Ptr_Can)
unregistersymbol(Can_Bul)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: UIController:OnGUI+3d

UIController:OnGUI+f: 48 8B 8E E8 01 00 00           - mov rcx,[rsi+000001E8]
UIController:OnGUI+16: 33 D2                          - xor edx,edx
UIController:OnGUI+18: 48 8D 64 24 00                 - lea rsp,[rsp+00]
UIController:OnGUI+1d: 90                             - nop 
UIController:OnGUI+1e: 49 BB 80 BB 28 F6 A7 02 00 00  - mov r11,UnityEngine.Object:op_Inequality
UIController:OnGUI+28: 41 FF D3                       - call r11
UIController:OnGUI+2b: 85 C0                          - test eax,eax
UIController:OnGUI+2d: 74 2E                          - je UIController:OnGUI+5d
UIController:OnGUI+2f: 48 8B 86 58 01 00 00           - mov rax,[rsi+00000158]
UIController:OnGUI+36: 48 8B 8E E8 01 00 00           - mov rcx,[rsi+000001E8]
// ---------- INJECTING HERE ----------
UIController:OnGUI+3d: F3 0F 10 81 7C 02 00 00        - movss xmm0,[rcx+0000027C]
// ---------- DONE INJECTING  ----------
UIController:OnGUI+45: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
2A861EC1A09: 48 8B C8                       - mov rcx,rax
2A861EC1A0C: F2 0F 10 C8                    - movsd xmm1,xmm0
2A861EC1A10: F2 0F 5A C9                    - cvtsd2ss xmm1,xmm1
2A861EC1A14: 48 8B 00                       - mov rax,[rax]
2A861EC1A17: FF 90 F8 01 00 00              - call qword ptr [rax+000001F8]
2A861EC1A1D: 48 8B 75 F8                    - mov rsi,[rbp-08]
UIController:OnGUI+61: 48 8D 65 00                    - lea rsp,[rbp+00]
UIController:OnGUI+65: 5D                             - pop rbp
UIController:OnGUI+66: C3                             - ret 
}"""

[[cheat]]
id = "olumsuz-god-mode"
name = "Olumsuz - God Mode"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:Disabled",
    "1:Enabled",
]

[cheat.locator]
find = "symbol"
symbol = "Olumsuz"
hops = []

[[cheat]]
id = "can-health"
name = "Can - Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "Ptr_Can"
hops = ["+0x27c"]

[[cheat]]
id = "can-max-health-max"
name = "Can Max - Health Max"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "Ptr_Can"
hops = ["+0x278"]

[[cheat]]
id = "parabul-envanteri-a-nca-find-coin-when-open-inventory"
name = "Parabul (Envanteri Açınca) - Find Coin (When Open Inventory )"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Anomaly Agent.exe
  Version:
  Date   : 2024-01-25
  Author : Dante

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat



aobscan(Get_Coin,48 63 40 28 0F B6 87 A6 00 00 00) // should be unique
alloc(newmem,$128,Get_Coin)

label(code)
label(return)

alloc(Coin_Ptr,8)
registersymbol(Coin_Ptr)
newmem:
mov [Coin_Ptr],rax
code:
  movsxd  rax,dword ptr [rax+28]
  movzx eax,byte ptr [rdi+000000A6]
  jmp return

Get_Coin:
  jmp newmem
  nop 6
return:
registersymbol(Get_Coin)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
Get_Coin:
  db 48 63 40 28 0F B6 87 A6 00 00 00

unregistersymbol(Get_Coin)
dealloc(newmem)

dealloc(Coin_Ptr)
unregistersymbol(Coin_Ptr)
{
// ORIGINAL CODE - INJECTION POINT: 1DE3BFBBD98

1DE3BFBBD6B: 48 8B C8                       - mov rcx,rax
1DE3BFBBD6E: BA 01 00 00 00                 - mov edx,00000001
1DE3BFBBD73: 83 38 00                       - cmp dword ptr [rax],00
1DE3BFBBD76: 49 BB 10 C2 D1 7F DE 01 00 00  - mov r11,000001DE7FD1C210
1DE3BFBBD80: 41 FF D3                       - call r11
1DE3BFBBD83: 48 8B 47 60                    - mov rax,[rdi+60]
1DE3BFBBD87: 48 8B 40 48                    - mov rax,[rax+48]
1DE3BFBBD8B: 48 8B 80 78 01 00 00           - mov rax,[rax+00000178]
1DE3BFBBD92: 48 8B C8                       - mov rcx,rax
1DE3BFBBD95: 83 39 00                       - cmp dword ptr [rcx],00
// ---------- INJECTING HERE ----------
1DE3BFBBD98: 48 63 40 28                    - movsxd  rax,dword ptr [rax+28]
// ---------- DONE INJECTING  ----------
1DE3BFBBD9C: 0F B6 87 A6 00 00 00           - movzx eax,byte ptr [rdi+000000A6]
1DE3BFBBDA3: 85 C0                          - test eax,eax
1DE3BFBBDA5: 75 29                          - jne 1DE3BFBBDD0
1DE3BFBBDA7: 0F B6 87 A5 00 00 00           - movzx eax,byte ptr [rdi+000000A5]
1DE3BFBBDAE: 85 C0                          - test eax,eax
1DE3BFBBDB0: 74 1E                          - je 1DE3BFBBDD0
1DE3BFBBDB2: 48 8B CF                       - mov rcx,rdi
1DE3BFBBDB5: 90                             - nop
1DE3BFBBDB6: 49 BB 60 CF FB 3B DE 01 00 00  - mov r11,000001DE3BFBCF60
1DE3BFBBDC0: 41 FF D3                       - call r11
}"""

[[cheat]]
id = "para-coin"
name = "Para - Coin"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Coin_Ptr"
hops = ["+0x28"]

[[cheat]]
id = "pozitif-karma"
name = "Pozitif Karma"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Coin_Ptr"
hops = ["+0x30"]

[[cheat]]
id = "negatif-karma"
name = "Negatif Karma"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Coin_Ptr"
hops = ["+0x2c"]

[[cheat]]
id = "coin-ptr"
name = "Coin_Ptr"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i64"
hex = true

[cheat.locator]
find = "symbol"
symbol = "Coin_Ptr"
hops = []

[[cheat]]
id = "parabul-para-al-nca-find-coin-when-u-get-a-coin"
name = "Parabul (Para Alınca)- Find Coin (When u get a coin)"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Anomaly Agent Demo.exe
  Version: 
  Date   : 2023-10-11
  Author : Dante

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(ParaBul,48 63 45 F0 89 47 28 48 8B CF) // should be unique
alloc(newmem,$128,ParaBul)
alloc(Ptr_1,8)
label(code)
label(return)
registersymbol(Ptr_1)
newmem:
  mov [Ptr_1],rdi
code:
  movsxd  rax,dword ptr [rbp-10]
  mov [rdi+28],eax
  jmp return

ParaBul:
  jmp newmem
  nop 2
return:
registersymbol(ParaBul)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
ParaBul:
  db 48 63 45 F0 89 47 28

unregistersymbol(ParaBul)
dealloc(newmem)
dealloc(Ptr_1)
unregistersymbol(Ptr_1)
{
// ORIGINAL CODE - INJECTION POINT: CoinController:Coin_Set+13

2A861BD9BC8: 00 00                          - add [rax],al
2A861BD9BCA: 00 00                          - add [rax],al
2A861BD9BCC: 00 00                          - add [rax],al
2A861BD9BCE: 00 00                          - add [rax],al
CoinController:Coin_Set: 55                             - push rbp
CoinController:Coin_Set+1: 48 8B EC                       - mov rbp,rsp
CoinController:Coin_Set+4: 48 83 EC 30                    - sub rsp,30
CoinController:Coin_Set+8: 48 89 7D F8                    - mov [rbp-08],rdi
CoinController:Coin_Set+c: 48 8B F9                       - mov rdi,rcx
CoinController:Coin_Set+f: 48 89 55 F0                    - mov [rbp-10],rdx
// ---------- INJECTING HERE ----------
CoinController:Coin_Set+13: 48 63 45 F0                    - movsxd  rax,dword ptr [rbp-10]
// ---------- DONE INJECTING  ----------
CoinController:Coin_Set+17: 89 47 28                       - mov [rdi+28],eax
CoinController:Coin_Set+1a: 48 8B CF                       - mov rcx,rdi
CoinController:Coin_Set+1d: 90                             - nop 
CoinController:Coin_Set+1e: 49 BB 50 9C BD 61 A8 02 00 00  - mov r11,CoinController:UI_Update_Coins
CoinController:Coin_Set+28: 41 FF D3                       - call r11
CoinController:Coin_Set+2b: 48 8B 7D F8                    - mov rdi,[rbp-08]
CoinController:Coin_Set+2f: 48 8D 65 00                    - lea rsp,[rbp+00]
CoinController:Coin_Set+33: 5D                             - pop rbp
CoinController:Coin_Set+34: C3                             - ret 
2A861BD9C05: 00 00                          - add [rax],al
}"""

[[cheat]]
id = "para-coin-2"
name = "Para - Coin"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Ptr_1"
hops = ["+0x28"]

[[cheat]]
id = "pozitif-karma-2"
name = "Pozitif Karma"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Ptr_1"
hops = ["+0x30"]

[[cheat]]
id = "negatif-karma-2"
name = "Negatif Karma"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Ptr_1"
hops = ["+0x2c"]

[[cheat]]
id = "ptr-1"
name = "Ptr_1"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i64"
hex = true

[cheat.locator]
find = "symbol"
symbol = "Ptr_1"
hops = []

[[cheat]]
id = "para4x-coin-4x"
name = "Para4x - Coin 4x"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Anomaly Agent Demo.exe
  Version: 
  Date   : 2023-10-11
  Author : Dante

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat


 
 
aobscan(Para4x,48 63 57 28 03 D6) // should be unique
alloc(newmem,$1000,Para4x)

label(code)
label(return)

newmem:
add esi,esi
add esi,esi
code:
  movsxd  rdx,dword ptr [rdi+28]
  add edx,esi
  jmp return

Para4x:
  jmp newmem
  nop
return:
registersymbol(Para4x)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
Para4x:
  db 48 63 57 28 03 D6

unregistersymbol(Para4x)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: CoinController:Coin_Increase+16

2A864ACABAA: 00 00                          - add [rax],al
2A864ACABAC: 00 00                          - add [rax],al
2A864ACABAE: 00 00                          - add [rax],al
CoinController:Coin_Increase: 55                             - push rbp
CoinController:Coin_Increase+1: 48 8B EC                       - mov rbp,rsp
CoinController:Coin_Increase+4: 48 83 EC 30                    - sub rsp,30
CoinController:Coin_Increase+8: 48 89 75 F0                    - mov [rbp-10],rsi
CoinController:Coin_Increase+c: 48 89 7D F8                    - mov [rbp-08],rdi
CoinController:Coin_Increase+10: 48 8B F9                       - mov rdi,rcx
CoinController:Coin_Increase+13: 48 8B F2                       - mov rsi,rdx
// ---------- INJECTING HERE ----------
CoinController:Coin_Increase+16: 48 63 57 28                    - movsxd  rdx,dword ptr [rdi+28]
// ---------- DONE INJECTING  ----------
CoinController:Coin_Increase+1a: 03 D6                          - add edx,esi
CoinController:Coin_Increase+1c: 48 8B CF                       - mov rcx,rdi
CoinController:Coin_Increase+1f: 48 8D AD 00 00 00 00           - lea rbp,[rbp+00000000]
CoinController:Coin_Increase+26: 49 BB D0 9B BD 61 A8 02 00 00  - mov r11,CoinController:Coin_Set
CoinController:Coin_Increase+30: 41 FF D3                       - call r11
CoinController:Coin_Increase+33: 83 FE 64                       - cmp esi,64
CoinController:Coin_Increase+36: 7C 23                          - jl CoinController:Coin_Increase+5b
CoinController:Coin_Increase+38: 48 8B 47 20                    - mov rax,[rdi+20]
CoinController:Coin_Increase+3c: 48 8B 80 48 01 00 00           - mov rax,[rax+00000148]
CoinController:Coin_Increase+43: 48 8B C8                       - mov rcx,rax
}"""

[[cheat]]
id = "s-n-rs-z-mermi-unlimited-ammo"
name = "Sınırsız Mermi - Unlimited Ammo"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Anomaly Agent Demo.exe
  Version: 
  Date   : 2023-10-11
  Author : Dante

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(AtesS,48 63 48 24 FF C9) // should be unique
alloc(newmem,$128,AtesS)
alloc(Ptr_2,8)
registersymbol(Ptr_2)
label(code)
label(return)

newmem:

 mov [Ptr_2],rax
 inc [rax+24]
 //inc ecx
 //mov [rax+24],5

code:
  movsxd  rcx,dword ptr [rax+24]
  dec ecx
  jmp return

AtesS:
  jmp newmem
  nop
return:
registersymbol(AtesS)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
AtesS:
  db 48 63 48 24 FF C9

unregistersymbol(AtesS)
dealloc(newmem)
unregistersymbol(Ptr_2)
dealloc(Ptr_2)
{
// ORIGINAL CODE - INJECTION POINT: Player+<Fire>d__262:MoveNext+5037

Player+<Fire>d__262:MoveNext+5010: 41 FF D3           - call r11
Player+<Fire>d__262:MoveNext+5013: 0F B6 46 38        - movzx eax,byte ptr [rsi+38]
Player+<Fire>d__262:MoveNext+5017: 85 C0              - test eax,eax
Player+<Fire>d__262:MoveNext+5019: 0F 85 11 00 00 00  - jne Player+<Fire>d__262:MoveNext+5030
Player+<Fire>d__262:MoveNext+501f: 48 8B 46 20        - mov rax,[rsi+20]
Player+<Fire>d__262:MoveNext+5023: 48 63 40 20        - movsxd  rax,dword ptr [rax+20]
Player+<Fire>d__262:MoveNext+5027: 83 F8 05           - cmp eax,05
Player+<Fire>d__262:MoveNext+502a: 0F 85 78 03 00 00  - jne Player+<Fire>d__262:MoveNext+53a8
Player+<Fire>d__262:MoveNext+5030: 48 8B 46 20        - mov rax,[rsi+20]
Player+<Fire>d__262:MoveNext+5034: 48 8B D0           - mov rdx,rax
// ---------- INJECTING HERE ----------
Player+<Fire>d__262:MoveNext+5037: 48 63 48 24        - movsxd  rcx,dword ptr [rax+24]
// ---------- DONE INJECTING  ----------
Player+<Fire>d__262:MoveNext+503b: FF C9              - dec ecx
Player+<Fire>d__262:MoveNext+503d: 89 48 24           - mov [rax+24],ecx
Player+<Fire>d__262:MoveNext+5040: 48 8B 46 20        - mov rax,[rsi+20]
Player+<Fire>d__262:MoveNext+5044: 48 63 40 20        - movsxd  rax,dword ptr [rax+20]
Player+<Fire>d__262:MoveNext+5048: 83 F8 05           - cmp eax,05
Player+<Fire>d__262:MoveNext+504b: 0F 85 2F 00 00 00  - jne Player+<Fire>d__262:MoveNext+5080
Player+<Fire>d__262:MoveNext+5051: 48 8B 46 20        - mov rax,[rsi+20]
Player+<Fire>d__262:MoveNext+5055: 48 63 40 24        - movsxd  rax,dword ptr [rax+24]
Player+<Fire>d__262:MoveNext+5059: 85 C0              - test eax,eax
Player+<Fire>d__262:MoveNext+505b: 0F 8F 7A 03 00 00  - jg Player+<Fire>d__262:MoveNext+53db
}"""

[[cheat]]
id = "mermi-ammo"
name = "Mermi - Ammo"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Ptr_2"
hops = ["+0x24"]

[[cheat]]
id = "s-n-rs-z-kart-kullan-m-unlimited-card-usage"
name = "Sınırsız Kart Kullanımı - Unlimited Card Usage"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Anomaly Agent.exe
  Version: 
  Date   : 2024-01-25
  Author : Dante

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscan(Kart_Kul,F3 0F 11 AE 98 00 00 00 48 8B) // should be unique
alloc(newmem,$128,Kart_Kul)
alloc(Kart_Ptr,8)
registersymbol(Kart_Ptr)
label(code)
label(return)
label(F_100)
newmem:
movss    xmm5,[F_100]
mov [Kart_Ptr],rsi
code:
  movss [rsi+00000098],xmm5
  jmp return

F_100:
dd (float)100

Kart_Kul:
  jmp newmem
  nop 3
return:
registersymbol(Kart_Kul)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
Kart_Kul:
  db F3 0F 11 AE 98 00 00 00

dealloc(Kart_Ptr)
unregistersymbol(Kart_Ptr)

unregistersymbol(Kart_Kul)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: 1DE3C17DADE

1DE3C17DAAB: 66 66 90                       - nop 3
1DE3C17DAAE: 49 BB 80 59 F8 3B DE 01 00 00  - mov r11,000001DE3BF85980
1DE3C17DAB8: 41 FF D3                       - call r11
1DE3C17DABB: F3 0F 10 86 9C 00 00 00        - movss xmm0,[rsi+0000009C]
1DE3C17DAC3: F3 0F 5A C0                    - cvtss2sd xmm0,xmm0
1DE3C17DAC7: 48 63 86 94 00 00 00           - movsxd  rax,dword ptr [rsi+00000094]
1DE3C17DACE: F3 0F 2A C8                    - cvtsi2ss xmm1,eax
1DE3C17DAD2: F3 0F 5A C9                    - cvtss2sd xmm1,xmm1
1DE3C17DAD6: F2 0F 59 C1                    - mulsd xmm0,xmm1
1DE3C17DADA: F2 0F 5A E8                    - cvtsd2ss xmm5,xmm0
// ---------- INJECTING HERE ----------
1DE3C17DADE: F3 0F 11 AE 98 00 00 00        - movss [rsi+00000098],xmm5
// ---------- DONE INJECTING  ----------
1DE3C17DAE6: 48 8B CE                       - mov rcx,rsi
1DE3C17DAE9: 48 8D 64 24 00                 - lea rsp,[rsp+00]
1DE3C17DAEE: 49 BB A0 5A F8 3B DE 01 00 00  - mov r11,000001DE3BF85AA0
1DE3C17DAF8: 41 FF D3                       - call r11
1DE3C17DAFB: 48 8B CE                       - mov rcx,rsi
1DE3C17DAFE: 49 BB 60 DB 17 3C DE 01 00 00  - mov r11,000001DE3C17DB60
1DE3C17DB08: 41 FF D3                       - call r11
1DE3C17DB0B: 48 8B 75 F8                    - mov rsi,[rbp-08]
1DE3C17DB0F: 48 8D 65 00                    - lea rsp,[rbp+00]
1DE3C17DB13: 5D                             - pop rbp
}"""

[[cheat]]
id = "timer"
name = "Timer"
category = "game"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "Kart_Ptr"
hops = ["+0x98"]
