[game]
name = "CHAOS CODE NEW SIGN OF CATASTROPHE"
exe = "chaoscode.exe"
notes = "Converted from a Cheat Engine table by ChaosMerchant. Source: https://fearlessrevolution.com/viewtopic.php?t=39309"
verified = []
author = "ChaosMerchant"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "infinite-health"
name = "Infinite Health"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : ChaosCode.exe
  Version: 
  Date   : 2017-03-19
  Author : 

  This script does blah blah blah
}

[ENABLE]


aobscanmodule(health,ChaosCode.exe,83 BF 38 07 00 00 00 7F 6E) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:

fild [edi+0000073c]
  fistp [edi+00000738]
  cmp dword ptr [edi+00000738],00
  jmp return

health:
  jmp newmem
  nop
  nop
return:
registersymbol(health)

[DISABLE]

health:
  db 83 BF 38 07 00 00 00

unregistersymbol(health)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "ChaosCode.exe"+45989

"ChaosCode.exe"+45962: 85 C0                          -  test eax,eax
"ChaosCode.exe"+45964: 75 23                          -  jne ChaosCode.exe+45989
"ChaosCode.exe"+45966: E8 15 56 FC FF                 -  call ChaosCode.exe+AF80
"ChaosCode.exe"+4596B: 85 C0                          -  test eax,eax
"ChaosCode.exe"+4596D: B8 03 00 00 00                 -  mov eax,00000003
"ChaosCode.exe"+45972: 0F 45 F0                       -  cmovne esi,eax
"ChaosCode.exe"+45975: 89 35 88 3E DF 00              -  mov [ChaosCode.exe+3B3E88],esi
"ChaosCode.exe"+4597B: EB 0C                          -  jmp ChaosCode.exe+45989
"ChaosCode.exe"+4597D: 8B 3D 90 3E DF 00              -  mov edi,[ChaosCode.exe+3B3E90]
"ChaosCode.exe"+45983: 8B 35 88 3E DF 00              -  mov esi,[ChaosCode.exe+3B3E88]
// ---------- INJECTING HERE ----------
"ChaosCode.exe"+45989: 83 BF 38 07 00 00 00           -  cmp dword ptr [edi+00000738],00
// ---------- DONE INJECTING  ----------
"ChaosCode.exe"+45990: 7F 6E                          -  jg ChaosCode.exe+45A00
"ChaosCode.exe"+45992: C6 05 86 3E DF 00 00           -  mov byte ptr [ChaosCode.exe+3B3E86],00
"ChaosCode.exe"+45999: C6 05 B7 45 DF 00 01           -  mov byte ptr [ChaosCode.exe+3B45B7],01
"ChaosCode.exe"+459A0: C7 87 38 07 00 00 00 00 00 00  -  mov [edi+00000738],00000000
"ChaosCode.exe"+459AA: E8 D1 55 FC FF                 -  call ChaosCode.exe+AF80
"ChaosCode.exe"+459AF: 85 C0                          -  test eax,eax
"ChaosCode.exe"+459B1: B8 01 00 00 00                 -  mov eax,00000001
"ChaosCode.exe"+459B6: 0F 45 F0                       -  cmovne esi,eax
"ChaosCode.exe"+459B9: A1 94 3E DF 00                 -  mov eax,[ChaosCode.exe+3B3E94]
"ChaosCode.exe"+459BE: 89 35 88 3E DF 00              -  mov [ChaosCode.exe+3B3E88],esi
}"""

[[cheat]]
id = "freeze-timer"
name = "Freeze Timer"
category = "game"
description = ""
hint = ""
type = "script"
source = """
{ Game   : GuiltyGearXrd.exe
  Version: 
  Date   : 2016-12-15
  Author : 

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscanmodule(TIMER,ChaosCode.exe,40 8B 0D ???????? A3 ???????? 66 0F6E C0 F3 0FE6 C0 C1 E8 1F F2 0F58 04 C5 ????????) // should be unique

TIMER:
nop
registersymbol(TIMER)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
TIMER:
  db 40

unregistersymbol(TIMER)
{
// ORIGINAL CODE - INJECTION POINT: "GuiltyGearXrd.exe"+B62A0B

"GuiltyGearXrd.exe"+B629F2: 89 51 18              -  mov [ecx+18],edx
"GuiltyGearXrd.exe"+B629F5: 39 51 10              -  cmp [ecx+10],edx
"GuiltyGearXrd.exe"+B629F8: 74 23                 -  je GuiltyGearXrd.exe+B62A1D
"GuiltyGearXrd.exe"+B629FA: 39 51 14              -  cmp [ecx+14],edx
"GuiltyGearXrd.exe"+B629FD: 75 1E                 -  jne GuiltyGearXrd.exe+B62A1D
"GuiltyGearXrd.exe"+B629FF: 39 51 18              -  cmp [ecx+18],edx
"GuiltyGearXrd.exe"+B62A02: 75 19                 -  jne GuiltyGearXrd.exe+B62A1D
"GuiltyGearXrd.exe"+B62A04: 8B 41 08              -  mov eax,[ecx+08]
"GuiltyGearXrd.exe"+B62A07: 3B C2                 -  cmp eax,edx
"GuiltyGearXrd.exe"+B62A09: 7E 12                 -  jle GuiltyGearXrd.exe+B62A1D
// ---------- INJECTING HERE ----------
"GuiltyGearXrd.exe"+B62A0B: 2B 41 0C              -  sub eax,[ecx+0C]
"GuiltyGearXrd.exe"+B62A0E: 89 41 08              -  mov [ecx+08],eax
// ---------- DONE INJECTING  ----------
"GuiltyGearXrd.exe"+B62A11: 79 03                 -  jns GuiltyGearXrd.exe+B62A16
"GuiltyGearXrd.exe"+B62A13: 89 51 08              -  mov [ecx+08],edx
"GuiltyGearXrd.exe"+B62A16: C7 41 0C 01 00 00 00  -  mov [ecx+0C],00000001
"GuiltyGearXrd.exe"+B62A1D: C3                    -  ret 
"GuiltyGearXrd.exe"+B62A1E: CC                    -  int 3 
"GuiltyGearXrd.exe"+B62A1F: CC                    -  int 3 
"GuiltyGearXrd.exe"+B62A20: 53                    -  push ebx
"GuiltyGearXrd.exe"+B62A21: 8B 5C 24 0C           -  mov ebx,[esp+0C]
"GuiltyGearXrd.exe"+B62A25: 55                    -  push ebp
"GuiltyGearXrd.exe"+B62A26: 56                    -  push esi
}"""

[[cheat]]
id = "infinite-tention"
name = "Infinite Tention"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : ChaosCode.exe
  Version:
  Date   : 2017-03-19
  Author : 

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(charge,ChaosCode.exe,39 87 1C 2D 01 00) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
cmp [edi+3c],0
jne @f


mov [edi+00012D1C],eax
@@:
  cmp [edi+00012D1C],eax
  jmp return

charge:
  jmp newmem
  nop
return:
registersymbol(charge)

[DISABLE]

charge:
  db 39 87 1C 2D 01 00

unregistersymbol(charge)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "ChaosCode.exe"+8A98

"ChaosCode.exe"+8A61: 83 BE 1C 2D 01 00 00           -  cmp dword ptr [esi+00012D1C],00
"ChaosCode.exe"+8A68: 75 22                          -  jne ChaosCode.exe+8A8C
"ChaosCode.exe"+8A6A: 80 3D 20 E0 BD 00 00           -  cmp byte ptr [ChaosCode.exe+19E020],00
"ChaosCode.exe"+8A71: 75 19                          -  jne ChaosCode.exe+8A8C
"ChaosCode.exe"+8A73: 3B 35 94 3E DF 00              -  cmp esi,[ChaosCode.exe+3B3E94]
"ChaosCode.exe"+8A79: 75 11                          -  jne ChaosCode.exe+8A8C
"ChaosCode.exe"+8A7B: C6 05 38 E0 BD 00 01           -  mov byte ptr [ChaosCode.exe+19E038],01
"ChaosCode.exe"+8A82: C7 05 34 E0 BD 00 05 00 00 00  -  mov [ChaosCode.exe+19E034],00000005
"ChaosCode.exe"+8A8C: 0F BF 05 54 BF E3 00           -  movsx eax,word ptr [ChaosCode.exe+3FBF54]
"ChaosCode.exe"+8A93: BA 01 00 00 00                 -  mov edx,00000001
// ---------- INJECTING HERE ----------
"ChaosCode.exe"+8A98: 39 87 1C 2D 01 00              -  cmp [edi+00012D1C],eax
// ---------- DONE INJECTING  ----------
"ChaosCode.exe"+8A9E: 0F B6 0D 21 E0 BD 00           -  movzx ecx,byte ptr [ChaosCode.exe+19E021]
"ChaosCode.exe"+8AA5: 0F B7 87 1C 2D 01 00           -  movzx eax,word ptr [edi+00012D1C]
"ChaosCode.exe"+8AAC: 0F 4F CA                       -  cmovg ecx,edx
"ChaosCode.exe"+8AAF: 8B 15 94 3E DF 00              -  mov edx,[ChaosCode.exe+3B3E94]
"ChaosCode.exe"+8AB5: 66 A3 54 BF E3 00              -  mov [ChaosCode.exe+3FBF54],ax
"ChaosCode.exe"+8ABB: 0F BF 05 58 BF E3 00           -  movsx eax,word ptr [ChaosCode.exe+3FBF58]
"ChaosCode.exe"+8AC2: 88 0D 21 E0 BD 00              -  mov [ChaosCode.exe+19E021],cl
"ChaosCode.exe"+8AC8: 39 82 1C 2D 01 00              -  cmp [edx+00012D1C],eax
"ChaosCode.exe"+8ACE: B8 01 00 00 00                 -  mov eax,00000001
"ChaosCode.exe"+8AD3: 0F B6 0D 39 E0 BD 00           -  movzx ecx,byte ptr [ChaosCode.exe+19E039]
}"""
