[game]
name = "THE LAST ORICRU"
exe = "losthero-win64-shipping.exe"
notes = "Converted from a Cheat Engine table by sanitka. Source: https://fearlessrevolution.com/viewtopic.php?t=21846"
verified = []
author = "sanitka"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "god-mode"
name = "God Mode"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : LostHero-Win64-Shipping.exe
  Version:
  Date   : 2023-01-04
  Author : SanitKa

  This script does blah blah blah
}

//define(address,"LostHero-Win64-Shipping.exe"+11287AD)
define(origbytes,8B 4C 24 70 29 88) //  B8 06 00 00 49 8B CE)

[ENABLE]
// to find the location
// assert(address,bytes)
aobscanmodule(INJGOD,LostHero-Win64-Shipping.exe,0F 5B C9 F2 0F 10 15)
// verify if this is correct version of script
assert(INJGOD+1B,origbytes)

INJGOD+1B:
  xor ecx,ecx              // dmg = 0
  nop 2

registersymbol(INJGOD)

[DISABLE]

INJGOD+1B:
  db origbytes
  // mov ecx,[rsp+70]

unregistersymbol(INJGOD)

{
// ORIGINAL CODE - INJECTION POINT: LostHero-Win64-Shipping.exe.text+11277CC

LostHero-Win64-Shipping.exe.text+112779E: E8 5D 2C 43 00           - call LostHero-Win64-Shipping.exe.text+155A400
LostHero-Win64-Shipping.exe.text+11277A3: E9 99 05 00 00           - jmp LostHero-Win64-Shipping.exe.text+1127D41
LostHero-Win64-Shipping.exe.text+11277A8: 66 0F 6E 4D A8           - movd xmm1,[rbp-58]
LostHero-Win64-Shipping.exe.text+11277AD: 0F 5B C9                 - cvtdq2ps xmm1,xmm1
LostHero-Win64-Shipping.exe.text+11277B0: F2 0F 10 15 28 CE C3 02  - movsd xmm2,[LostHero-Win64-Shipping.exe.rdata+1765E0]
LostHero-Win64-Shipping.exe.text+11277B8: 49 8B CF                 - mov rcx,r15
LostHero-Win64-Shipping.exe.text+11277BB: E8 D0 ED FE FF           - call LostHero-Win64-Shipping.exe.text+1116590
LostHero-Win64-Shipping.exe.text+11277C0: 49 8B CE                 - mov rcx,r14
LostHero-Win64-Shipping.exe.text+11277C3: E8 28 56 43 00           - call LostHero-Win64-Shipping.exe.text+155CDF0
// ---------- INJECTING HERE ----------
LostHero-Win64-Shipping.exe.text+11277C8: 8B 4C 24 70              - mov ecx,[rsp+70]
// ---------- DONE INJECTING  ----------
LostHero-Win64-Shipping.exe.text+11277CC: 29 88 B8 06 00 00        - sub [rax+000006B8],ecx
LostHero-Win64-Shipping.exe.text+11277D2: 49 8B CE                 - mov rcx,r14
LostHero-Win64-Shipping.exe.text+11277D5: E8 16 56 43 00           - call LostHero-Win64-Shipping.exe.text+155CDF0
LostHero-Win64-Shipping.exe.text+11277DA: 48 8B C8                 - mov rcx,rax
LostHero-Win64-Shipping.exe.text+11277DD: 33 D2                    - xor edx,edx
LostHero-Win64-Shipping.exe.text+11277DF: E8 BC 56 06 00           - call LostHero-Win64-Shipping.exe.text+118CEA0
LostHero-Win64-Shipping.exe.text+11277E4: 8B 44 24 70              - mov eax,[rsp+70]
LostHero-Win64-Shipping.exe.text+11277E8: 85 C0                    - test eax,eax
LostHero-Win64-Shipping.exe.text+11277EA: 0F 8E 9D 01 00 00        - jng LostHero-Win64-Shipping.exe.text+112798D
LostHero-Win64-Shipping.exe.text+11277F0: 49 8B CE                 - mov rcx,r14
LostHero-Win64-Shipping.exe.text+11277F3: 89 B5 50 03 00 00        - mov [rbp+00000350],esi
}"""

[[cheat]]
id = "ohk-one-hit-kill"
name = "OHK (One Hit Kill)"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
{ Game   : LostHero-Win64-Shipping.exe
  Version:
  Date   : 2023-01-04
  Author : SanitKa

  This script does blah blah blah
}

// define(address,"LostHero-Win64-Shipping.exe"+F819FA)
define(origbytes,8B CA 8B 9E 14 19 00 00 2B CB F3 0F 10 8E 48 15 00 00)

[ENABLE]

// to find the location
// assert(address,bytes)
aobscanmodule(INJOHK,LostHero-Win64-Shipping.exe,24 F7 0A C8 80 E1 EF)
// verify if this is correct version of script
assert(INJOHK+2D,origbytes)

INJOHK+2D:
//  mov edx,[rsi+000019C0]                                // orig HP
  mov [rsi+00001914],edx                                // hit size
  xor ecx, ecx                                          // new HP
  nop 2

registersymbol(INJOHK)

[DISABLE]

INJOHK+2D:
  db origbytes
  // mov ecx,edx
  // mov ebx,[rsi+00001914]
  // sub ecx,ebx

unregistersymbol(INJOHK)

{
// ORIGINAL CODE - INJECTION POINT: LostHero-Win64-Shipping.exe.text+F809FA

LostHero-Win64-Shipping.exe.text+F809C6: 48 89 86 5C 19 00 00     - mov [rsi+0000195C],rax
LostHero-Win64-Shipping.exe.text+F809CD: 48 8B 06                 - mov rax,[rsi]
LostHero-Win64-Shipping.exe.text+F809D0: FF 90 60 01 00 00        - call qword ptr [rax+00000160]
LostHero-Win64-Shipping.exe.text+F809D6: 8B 88 A0 05 00 00        - mov ecx,[rax+000005A0]
LostHero-Win64-Shipping.exe.text+F809DC: 89 8E 6C 19 00 00        - mov [rsi+0000196C],ecx
LostHero-Win64-Shipping.exe.text+F809E2: 0F B6 CB                 - movzx ecx,bl
LostHero-Win64-Shipping.exe.text+F809E5: 41 0F B6 45 00           - movzx eax,byte ptr [r13+00]
LostHero-Win64-Shipping.exe.text+F809EA: C0 E1 03                 - shl cl,03
LostHero-Win64-Shipping.exe.text+F809ED: 88 86 64 19 00 00        - mov [rsi+00001964],al
LostHero-Win64-Shipping.exe.text+F809F3: 0F B6 86 48 19 00 00     - movzx eax,byte ptr [rsi+00001948]
// ---------- INJECTING HERE ----------
LostHero-Win64-Shipping.exe.text+F809FA: 24 F7                    - and al,-09
// ---------- DONE INJECTING  ----------
LostHero-Win64-Shipping.exe.text+F809FC: 0A C8                    - or cl,al
LostHero-Win64-Shipping.exe.text+F809FE: 80 E1 EF                 - and cl,-11
LostHero-Win64-Shipping.exe.text+F80A01: 0A 4C 24 63              - or cl,[rsp+63]
LostHero-Win64-Shipping.exe.text+F80A05: 88 8E 48 19 00 00        - mov [rsi+00001948],cl
LostHero-Win64-Shipping.exe.text+F80A0B: 48 8B CE                 - mov rcx,rsi
LostHero-Win64-Shipping.exe.text+F80A0E: 41 0F B6 85 99 00 00 00  - movzx eax,byte ptr [r13+00000099]
LostHero-Win64-Shipping.exe.text+F80A16: 88 86 71 19 00 00        - mov [rsi+00001971],al
LostHero-Win64-Shipping.exe.text+F80A1C: E8 0F A1 01 00           - call LostHero-Win64-Shipping.exe.text+F9AB30
LostHero-Win64-Shipping.exe.text+F80A21: 8B 96 C0 19 00 00        - mov edx,[rsi+000019C0]
LostHero-Win64-Shipping.exe.text+F80A27: 8B CA                    - mov ecx,edx
LostHero-Win64-Shipping.exe.text+F80A29: 8B 9E 14190000           - mov ebx,[rsi+00001914]
LostHero-Win64-Shipping.exe.text+F80A2F: 2B CB                    - sub ecx,ebx
LostHero-Win64-Shipping.exe.text+F80A31: F3 0F10 8E 48150000      - movss xmm1,[rsi+00001548]
LostHero-Win64-Shipping.exe.text+F80A39: 41 0F2F CA               - comiss xmm1,xmm10
}"""

[[cheat]]
id = "xpptr-after-xp-change"
name = "XPPtr (After XP change)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : LostHero-Win64-Shipping.exe
  Version: 
  Date   : 2022-10-18
  Author : SanitKa

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJECT_XP,LostHero-Win64-Shipping.exe,01 42 04 8B 72 04) // should be unique
alloc(newmem,$1000,INJECT_XP)

label(return)
label(skip)

newmem:

// injecting materials routine, xp is treated as a material and is the very first one :)
code:
  add [rdx+04],eax
  mov rsi,rdx
  add rsi,04
@@:
  cmp byte ptr[rsi-04],0c    // type = 0c ~ XP
  je @f
  jg skip
  sub rsi,10
  jmp @b
@@:
  mov [xpPtr],rsi
skip:
  mov esi,[rdx+04]
  jmp return

xpPtr:
  dq dead beef

INJECT_XP:
  jmp newmem
  nop
return:
registersymbol(INJECT_XP)
registersymbol(xpPtr)

[DISABLE]

INJECT_XP:
  db 01 42 04 8B 72 04

unregistersymbol(INJECT_XP)
unregistersymbol(xpPtr)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: LostHero-Win64-Shipping.exe+10CA680

LostHero-Win64-Shipping.exe+10CA660: 48 63 D0              - movsxd  rdx,eax
LostHero-Win64-Shipping.exe+10CA663: 48 C1 E2 04           - shl rdx,04
LostHero-Win64-Shipping.exe+10CA667: 49 03 D0              - add rdx,r8
LostHero-Win64-Shipping.exe+10CA66A: 44 38 0A              - cmp [rdx],r9l
LostHero-Win64-Shipping.exe+10CA66D: 74 0B                 - je LostHero-Win64-Shipping.exe+10CA67A
LostHero-Win64-Shipping.exe+10CA66F: 8B 42 08              - mov eax,[rdx+08]
LostHero-Win64-Shipping.exe+10CA672: 83 F8 FF              - cmp eax,-01
LostHero-Win64-Shipping.exe+10CA675: 75 E9                 - jne LostHero-Win64-Shipping.exe+10CA660
LostHero-Win64-Shipping.exe+10CA677: 48 8B D7              - mov rdx,rdi
LostHero-Win64-Shipping.exe+10CA67A: 8B 85 B4 03 00 00     - mov eax,[rbp+000003B4]
// ---------- INJECTING HERE ----------
LostHero-Win64-Shipping.exe+10CA680: 01 42 04              - add [rdx+04],eax
// ---------- DONE INJECTING  ----------
LostHero-Win64-Shipping.exe+10CA683: 8B 72 04              - mov esi,[rdx+04]
LostHero-Win64-Shipping.exe+10CA686: 8B 85 B4 03 00 00     - mov eax,[rbp+000003B4]
LostHero-Win64-Shipping.exe+10CA68C: 89 75 C8              - mov [rbp-38],esi
LostHero-Win64-Shipping.exe+10CA68F: 80 BD B0 03 00 00 0C  - cmp byte ptr [rbp+000003B0],0C
LostHero-Win64-Shipping.exe+10CA696: 0F B6 8D B8 03 00 00  - movzx ecx,byte ptr [rbp+000003B8]
LostHero-Win64-Shipping.exe+10CA69D: 75 1A                 - jne LostHero-Win64-Shipping.exe+10CA6B9
LostHero-Win64-Shipping.exe+10CA69F: F6 C1 01              - test cl,01
LostHero-Win64-Shipping.exe+10CA6A2: 74 15                 - je LostHero-Win64-Shipping.exe+10CA6B9
LostHero-Win64-Shipping.exe+10CA6A4: 85 C0                 - test eax,eax
LostHero-Win64-Shipping.exe+10CA6A6: 7E 11                 - jle LostHero-Win64-Shipping.exe+10CA6B9
}"""

[[cheat]]
id = "xp-ptr"
name = "XP Ptr"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i64"
hex = true

[cheat.locator]
find = "symbol"
symbol = "xpPtr"
hops = []

[[cheat]]
id = "attribute-ptr-after-lvl-up"
name = "Attribute Ptr (After Lvl Up)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : LostHero-Win64-Shipping.exe
  Version: 
  Date   : 2023-01-05
  Author : SanitKa

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJATT,LostHero-Win64-Shipping.exe,48 8B 87 C0 33 00 00) // should be unique
alloc(newmem,$1000,INJATT)

label(code)
label(return)

newmem:

code:
  mov rax,[rdi+000033C0]
  mov [attrPtr],rax
  jmp return

attrPtr:
  dq dead beef

INJATT:
  jmp newmem
  nop 2
return:
registersymbol(INJATT)
registersymbol(attrPtr)

[DISABLE]

INJATT:
  db 48 8B 87 C0 33 00 00

unregistersymbol(INJATT)
unregistersymbol(attrPtr)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: LostHero-Win64-Shipping.exe.text+10BA8B0

LostHero-Win64-Shipping.exe.text+10BA889: 4C 8B 87 30 30 00 00  - mov r8,[rdi+00003030]
LostHero-Win64-Shipping.exe.text+10BA890: 48 63 D1              - movsxd  rdx,ecx
LostHero-Win64-Shipping.exe.text+10BA893: 48 03 D2              - add rdx,rdx
LostHero-Win64-Shipping.exe.text+10BA896: 41 80 3C D0 0C        - cmp byte ptr [r8+rdx*8],0C
LostHero-Win64-Shipping.exe.text+10BA89B: 0F 84 DF 00 00 00     - je LostHero-Win64-Shipping.exe.text+10BA980
LostHero-Win64-Shipping.exe.text+10BA8A1: 41 8B 4C D0 08        - mov ecx,[r8+rdx*8+08]
LostHero-Win64-Shipping.exe.text+10BA8A6: 83 F9 FF              - cmp ecx,-01
LostHero-Win64-Shipping.exe.text+10BA8A9: 75 E5                 - jne LostHero-Win64-Shipping.exe.text+10BA890
LostHero-Win64-Shipping.exe.text+10BA8AB: 45 84 FF              - test r15l,r15l
LostHero-Win64-Shipping.exe.text+10BA8AE: 74 0B                 - je LostHero-Win64-Shipping.exe.text+10BA8BB
// ---------- INJECTING HERE ----------
LostHero-Win64-Shipping.exe.text+10BA8B0: 48 8B 87 C0 33 00 00  - mov rax,[rdi+000033C0]
// ---------- DONE INJECTING  ----------
LostHero-Win64-Shipping.exe.text+10BA8B7: 42 FF 04 A0           - inc [rax+r12*4]
LostHero-Win64-Shipping.exe.text+10BA8BB: 48 8D 4F 30           - lea rcx,[rdi+30]
LostHero-Win64-Shipping.exe.text+10BA8BF: 41 80 F6 01           - xor r14l,01
LostHero-Win64-Shipping.exe.text+10BA8C3: E8 28 25 4A 00        - call LostHero-Win64-Shipping.exe.text+155CDF0
LostHero-Win64-Shipping.exe.text+10BA8C8: 48 8B C8              - mov rcx,rax
LostHero-Win64-Shipping.exe.text+10BA8CB: 44 89 6C 24 20        - mov [rsp+20],r13d
LostHero-Win64-Shipping.exe.text+10BA8D0: 41 B1 01              - mov r9l,01
LostHero-Win64-Shipping.exe.text+10BA8D3: 48 8D 97 80 33 00 00  - lea rdx,[rdi+00003380]
LostHero-Win64-Shipping.exe.text+10BA8DA: 45 0F B6 C6           - movzx r8d,r14l
LostHero-Win64-Shipping.exe.text+10BA8DE: E8 CD F4 FB FF        - call LostHero-Win64-Shipping.exe.text+1079DB0
}"""

[[cheat]]
id = "attribute-ptr"
name = "Attribute Ptr"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i64"
hex = true

[cheat.locator]
find = "symbol"
symbol = "attrPtr"
hops = []

[[cheat]]
id = "playerptr"
name = "PlayerPtr"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : LostHero-Win64-Shipping.exe
  Version:
  Date   : 2023-01-06
  Author : SanitKa

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJSTATS,LostHero-Win64-Shipping.exe,89 96 08 02 00 00 44) // should be unique
alloc(newmem,$1000,INJSTATS)

label(code)
label(return)

newmem:
  mov [statsPtr],rsi

code:
  mov [rsi+00000208],edx
  jmp return

statsPtr:
  dq dead beef

INJSTATS:
  jmp newmem
  nop
return:
registersymbol(INJSTATS)
registersymbol(statsPtr)

[DISABLE]

INJSTATS:
  db 89 96 08 02 00 00

unregistersymbol(INJSTATS)
unregistersymbol(statsPtr)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: LostHero-Win64-Shipping.exe.text+FDBC8D

LostHero-Win64-Shipping.exe.text+FDBC5A: 8B D1                    - mov edx,ecx
LostHero-Win64-Shipping.exe.text+FDBC5C: 8B 86 28 02 00 00        - mov eax,[rsi+00000228]
LostHero-Win64-Shipping.exe.text+FDBC62: 44 8B C0                 - mov r8d,eax
LostHero-Win64-Shipping.exe.text+FDBC65: 89 8E 00 02 00 00        - mov [rsi+00000200],ecx
LostHero-Win64-Shipping.exe.text+FDBC6B: 4C 8D B6 F8 0A 00 00     - lea r14,[rsi+00000AF8]
LostHero-Win64-Shipping.exe.text+FDBC72: 89 86 F4 01 00 00        - mov [rsi+000001F4],eax
LostHero-Win64-Shipping.exe.text+FDBC78: 4C 8B E7                 - mov r12,rdi
LostHero-Win64-Shipping.exe.text+FDBC7B: 66 0F 6E 86 24 02 00 00  - movd xmm0,[rsi+00000224]
LostHero-Win64-Shipping.exe.text+FDBC83: 83 8E 10 02 00 00 01     - or dword ptr [rsi+00000210],01
LostHero-Win64-Shipping.exe.text+FDBC8A: 0F 5B C0                 - cvtdq2ps xmm0,xmm0
// ---------- INJECTING HERE ----------
LostHero-Win64-Shipping.exe.text+FDBC8D: 89 96 08 02 00 00        - mov [rsi+00000208],edx
// ---------- DONE INJECTING  ----------
LostHero-Win64-Shipping.exe.text+FDBC93: 44 89 86 FC 01 00 00     - mov [rsi+000001FC],r8d
LostHero-Win64-Shipping.exe.text+FDBC9A: F3 0F 11 86 EC 01 00 00  - movss [rsi+000001EC],xmm0
LostHero-Win64-Shipping.exe.text+FDBCA2: 3B BE 28 0B 00 00        - cmp edi,[rsi+00000B28]
LostHero-Win64-Shipping.exe.text+FDBCA8: 0F 8C 84 00 00 00        - jl LostHero-Win64-Shipping.exe.text+FDBD32
LostHero-Win64-Shipping.exe.text+FDBCAE: 49 63 5E 30              - movsxd  rbx,dword ptr [r14+30]
LostHero-Win64-Shipping.exe.text+FDBCB2: 8D 4F 01                 - lea ecx,[rdi+01]
LostHero-Win64-Shipping.exe.text+FDBCB5: 3B CB                    - cmp ecx,ebx
LostHero-Win64-Shipping.exe.text+FDBCB7: 7E 35                    - jle LostHero-Win64-Shipping.exe.text+FDBCEE
LostHero-Win64-Shipping.exe.text+FDBCB9: 44 8B FF                 - mov r15d,edi
LostHero-Win64-Shipping.exe.text+FDBCBC: 44 2B FB                 - sub r15d,ebx
}"""

[[cheat]]
id = "playerptr-2"
name = "PlayerPtr"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i64"
hex = true

[cheat.locator]
find = "symbol"
symbol = "statsPtr"
hops = []
