[game]
name = "RV There Yet?"
exe = "ride-win64-shipping.exe"
notes = "Converted from a Cheat Engine table by jjcho849. Source: https://fearlessrevolution.com/viewtopic.php?t=37043"
verified = []
author = "jjcho849"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "cheats"
name = "Cheats"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Ride-Win64-Shipping.exe
  Version: 
  Date   : 2025-10-26
  Author : joeyc

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(GINSTANCE,Ride-Win64-Shipping.exe,48 8B B8 28 02 00 00 48 85 FF 74 54) // should be unique
alloc(newmem,$500,GINSTANCE)

label(code)
label(return)
label(getGameInstance)

newmem:

code:
  mov rdi,[rax+00000228]
  mov [getGameInstance],rdi
  jmp return

getGameInstance:
dd 0

GINSTANCE:
  jmp newmem
  nop 2
return:
registersymbol(GINSTANCE getGameInstance)

[DISABLE]

GINSTANCE:
  db 48 8B B8 28 02 00 00

unregistersymbol(*)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+41

Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+18: 41 57                 - push r15
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+1A: 48 83 EC 30           - sub rsp,30
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+1E: 8B EA                 - mov ebp,edx
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+20: 41 B8 01 00 00 00     - mov r8d,00000001
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+26: 48 8B D1              - mov rdx,rcx
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+29: 48 8B 0D A0 EF 60 05  - mov rcx,[Ride-Win64-Shipping.GEngine]
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+30: E8 8B 2D 7D 00        - call Ride-Win64-Shipping.UEngine::GetWorldFromContextObject
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+35: 4C 8B F8              - mov r15,rax
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+38: 48 85 C0              - test rax,rax
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+3B: 0F 84 13 01 00 00     - je Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+154
// ---------- INJECTING HERE ----------
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+41: 48 8B B8 28 02 00 00  - mov rdi,[rax+00000228]
// ---------- DONE INJECTING  ----------
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+48: 48 85 FF              - test rdi,rdi
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+4B: 74 54                 - je Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+A1
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+4D: 48 8B CF              - mov rcx,rdi
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+50: E8 BB 77 FC FF        - call Ride-Win64-Shipping.UGameInstance::GetWorld
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+55: 49 3B C7              - cmp rax,r15
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+58: 75 47                 - jne Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+A1
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+5A: 48 8B CF              - mov rcx,rdi
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+5D: 41 B4 01              - mov r12b,01
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+60: 33 DB                 - xor ebx,ebx
Ride-Win64-Shipping.UGameplayStatics::GetPlayerController+62: E8 89 47 63 FD        - call Ride-Win64-Shipping.UE::Dataflow::TContextCacheElement<FLinearColor>::GetUntypedData
}"""

[[cheat]]
id = "infinite-health-script"
name = "Infinite Health Script"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Ride-Win64-Shipping.exe
  Version: 
  Date   : 2025-12-28
  Author : joeyc

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(HEALTH,Ride-Win64-Shipping.exe,89 4F 08 48 8D 0C 40 48 8B 07 48 89 1C 88 89) // should be unique
alloc(newmem,$500,HEALTH)

label(code)
label(return)

newmem:

code:
  mov [rdi+08],0
  lea rcx,[rax+rax*2]
  jmp return

HEALTH:
  jmp newmem
  nop 2
return:
registersymbol(HEALTH)

[DISABLE]

HEALTH:
  db 89 4F 08 48 8D 0C 40

unregistersymbol(HEALTH)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Ride-Win64-Shipping.exe"+4C8246F

"Ride-Win64-Shipping.exe"+4C8244C: 75 F2           - jne "Ride-Win64-Shipping.exe"+4C82440
"Ride-Win64-Shipping.exe"+4C8244E: 44 3B 51 0C     - cmp r10d,[rcx+0C]
"Ride-Win64-Shipping.exe"+4C82452: 4C 8D 41 0C     - lea r8,[rcx+0C]
"Ride-Win64-Shipping.exe"+4C82456: 75 10           - jne "Ride-Win64-Shipping.exe"+4C82468
"Ride-Win64-Shipping.exe"+4C82458: B9 0C 04 00 00  - mov ecx,0000040C
"Ride-Win64-Shipping.exe"+4C8245D: 48 8B D7        - mov rdx,rdi
"Ride-Win64-Shipping.exe"+4C82460: E8 5B B5 3D FC  - call "Ride-Win64-Shipping.exe"+105D9C0
"Ride-Win64-Shipping.exe"+4C82465: 44 8B D0        - mov r10d,eax
"Ride-Win64-Shipping.exe"+4C82468: 49 63 C2        - movsxd  rax,r10d
"Ride-Win64-Shipping.exe"+4C8246B: 41 8D 4A 01     - lea ecx,[r10+01]
// ---------- INJECTING HERE ----------
"Ride-Win64-Shipping.exe"+4C8246F: 89 4F 08        - mov [rdi+08],ecx
// ---------- DONE INJECTING  ----------
"Ride-Win64-Shipping.exe"+4C82472: 48 8D 0C 40     - lea rcx,[rax+rax*2]
"Ride-Win64-Shipping.exe"+4C82476: 48 8B 07        - mov rax,[rdi]
"Ride-Win64-Shipping.exe"+4C82479: 48 89 1C 88     - mov [rax+rcx*4],rbx
"Ride-Win64-Shipping.exe"+4C8247D: 89 74 88 08     - mov [rax+rcx*4+08],esi
"Ride-Win64-Shipping.exe"+4C82481: 48 8B 5C 24 30  - mov rbx,[rsp+30]
"Ride-Win64-Shipping.exe"+4C82486: 48 8B 74 24 38  - mov rsi,[rsp+38]
"Ride-Win64-Shipping.exe"+4C8248B: 48 83 C4 20     - add rsp,20
"Ride-Win64-Shipping.exe"+4C8248F: 5F              - pop rdi
"Ride-Win64-Shipping.exe"+4C82490: C3              - ret 
"Ride-Win64-Shipping.exe"+4C82491: 48 8B 5C 24 30  - mov rbx,[rsp+30]
}"""

[[cheat]]
id = "rv-teleport-hook-wip-not-fully-working"
name = "RV Teleport Hook (WIP Not Fully Working)"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Ride-Win64-Shipping.exe
  Version: 
  Date   : 2025-12-28
  Author : joeyc

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(RVCOORDS,Ride-Win64-Shipping.exe,F2 0F 10 74 C8 10 F2 0F 10 2C) // should be unique
alloc(newmem,$500,RVCOORDS)

label(code)
label(return)
label(getRVCoords)

newmem:
push rdi
lea rdi,[rax+rcx*8+10]
mov [getRVCoords],rdi
pop rdi
jmp code

code:
  movsd xmm6,[rax+rcx*8+10]
  jmp return

getRVCoords:
dd 0

RVCOORDS:
  jmp newmem
  nop
return:
registersymbol(RVCOORDS getRVCoords)

[DISABLE]

RVCOORDS:
  db F2 0F 10 74 C8 10

unregistersymbol(*)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "Ride-Win64-Shipping.exe"+48DFE1E

"Ride-Win64-Shipping.exe"+48DFDF2: 48 C1 E0 04        - shl rax,04
"Ride-Win64-Shipping.exe"+48DFDF6: 48 8D 0C 49        - lea rcx,[rcx+rcx*2]
"Ride-Win64-Shipping.exe"+48DFDFA: 48 03 42 48        - add rax,[rdx+48]
"Ride-Win64-Shipping.exe"+48DFDFE: F3 0F 10 00        - movss xmm0,[rax]
"Ride-Win64-Shipping.exe"+48DFE02: F3 0F 10 48 04     - movss xmm1,[rax+04]
"Ride-Win64-Shipping.exe"+48DFE07: F3 0F 10 58 08     - movss xmm3,[rax+08]
"Ride-Win64-Shipping.exe"+48DFE0C: F3 0F 10 60 0C     - movss xmm4,[rax+0C]
"Ride-Win64-Shipping.exe"+48DFE11: 48 8B 42 28        - mov rax,[rdx+28]
"Ride-Win64-Shipping.exe"+48DFE15: 0F 5A C9           - cvtps2pd xmm1,xmm1
"Ride-Win64-Shipping.exe"+48DFE18: F2 0F 10 54 C8 08  - movsd xmm2,[rax+rcx*8+08]
// ---------- INJECTING HERE ----------
"Ride-Win64-Shipping.exe"+48DFE1E: F2 0F 10 74 C8 10  - movsd xmm6,[rax+rcx*8+10]
// ---------- DONE INJECTING  ----------
"Ride-Win64-Shipping.exe"+48DFE24: F2 0F 10 2C C8     - movsd xmm5,[rax+rcx*8]
"Ride-Win64-Shipping.exe"+48DFE29: 48 8B C3           - mov rax,rbx
"Ride-Win64-Shipping.exe"+48DFE2C: 0F 5A C0           - cvtps2pd xmm0,xmm0
"Ride-Win64-Shipping.exe"+48DFE2F: 0F 5A DB           - cvtps2pd xmm3,xmm3
"Ride-Win64-Shipping.exe"+48DFE32: 66 0F 14 C1        - unpcklpd xmm0,xmm1
"Ride-Win64-Shipping.exe"+48DFE36: 0F 11 03           - movups [rbx],xmm0
"Ride-Win64-Shipping.exe"+48DFE39: 0F 28 CB           - movaps xmm1,xmm3
"Ride-Win64-Shipping.exe"+48DFE3C: 0F 28 C2           - movaps xmm0,xmm2
"Ride-Win64-Shipping.exe"+48DFE3F: 0F 28 D5           - movaps xmm2,xmm5
"Ride-Win64-Shipping.exe"+48DFE42: 66 0F 14 D0        - unpcklpd xmm2,xmm0
}"""
