[game]
name = "Dying Light 2 (1.9.4 Steam)"
exe = "dyinglightgame_x64_rwdi.exe"
notes = "Converted from a Cheat Engine table by BeatEngine. Source: https://fearlessrevolution.com/viewtopic.php?t=24330"
verified = []
author = "BeatEngine"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "freezethrowables"
name = "FreezeThrowables"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : DyingLightGame_x64_rwdi.exe
  Version:
  Date   : 2023-05-13
  Author : David

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJECT_INF_THROW,gamedll_ph_x64_rwdi.dll,89 33 48 8B 5C 24 30 48 8B 6C) // should be unique
alloc(newmem,$1000,INJECT_INF_THROW)

label(code)
label(return)

newmem:
  add esi,1
  mov [rbx],esi
  mov rbx,[rsp+30]
  jmp return

code:
  mov [rbx],esi
  mov rbx,[rsp+30]
  jmp return

INJECT_INF_THROW:
  jmp newmem
  nop 2
return:
registersymbol(INJECT_INF_THROW)

[DISABLE]

INJECT_INF_THROW:
  db 89 33 48 8B 5C 24 30

unregistersymbol(INJECT_INF_THROW)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: gamedll_ph_x64_rwdi.dll+51FB16

gamedll_ph_x64_rwdi.dll+51FAEE: 48 8B 43 30              - mov rax,[rbx+30]
gamedll_ph_x64_rwdi.dll+51FAF2: 48 8D 4B 30              - lea rcx,[rbx+30]
gamedll_ph_x64_rwdi.dll+51FAF6: FF 90 90 0B 00 00        - call qword ptr [rax+00000B90]
gamedll_ph_x64_rwdi.dll+51FAFC: 0F 57 C9                 - xorps xmm1,xmm1
gamedll_ph_x64_rwdi.dll+51FAFF: 0F 2F C1                 - comiss xmm0,xmm1
gamedll_ph_x64_rwdi.dll+51FB02: 76 14                    - jna gamedll_ph_x64_rwdi.dll+51FB18
gamedll_ph_x64_rwdi.dll+51FB04: F3 0F 10 0D 68 21 AF 01  - movss xmm1,[gamedll_ph_x64_rwdi.dll+2011C74]
gamedll_ph_x64_rwdi.dll+51FB0C: 48 8B CB                 - mov rcx,rbx
gamedll_ph_x64_rwdi.dll+51FB0F: E8 EC 81 F9 FF           - call gamedll_ph_x64_rwdi.dll+4B7D00
gamedll_ph_x64_rwdi.dll+51FB14: EB 02                    - jmp gamedll_ph_x64_rwdi.dll+51FB18
// ---------- INJECTING HERE ----------
gamedll_ph_x64_rwdi.dll+51FB16: 89 33                    - mov [rbx],esi
// ---------- DONE INJECTING  ----------
gamedll_ph_x64_rwdi.dll+51FB18: 48 8B 5C 24 30           - mov rbx,[rsp+30]
gamedll_ph_x64_rwdi.dll+51FB1D: 48 8B 6C 24 38           - mov rbp,[rsp+38]
gamedll_ph_x64_rwdi.dll+51FB22: 48 8B 74 24 40           - mov rsi,[rsp+40]
gamedll_ph_x64_rwdi.dll+51FB27: 48 83 C4 20              - add rsp,20
gamedll_ph_x64_rwdi.dll+51FB2B: 5F                       - pop rdi
gamedll_ph_x64_rwdi.dll+51FB2C: C3                       - ret
gamedll_ph_x64_rwdi.dll+51FB2D: 0F 1F 00                 - nop dword ptr [rax]
gamedll_ph_x64_rwdi.dll+51FB30: EA FA 51 00 18 FB 51     - jmp 51FB:180051FA
gamedll_ph_x64_rwdi.dll+51FB37: 00 00                    - add [rax],al
gamedll_ph_x64_rwdi.dll+51FB39: 01 00                    - add [rax],eax
}"""

[[cheat]]
id = "freezearrows"
name = "FreezeArrows"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : DyingLightGame_x64_rwdi.exe
  Version: 
  Date   : 2023-05-13
  Author : David

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJECT_INF_AM,gamedll_ph_x64_rwdi.dll,89 33 48 8B 5C 24 30 48 8B 6C) // should be unique
alloc(newmem,$1000,INJECT_INF_AM)

label(code)
label(return)

newmem:
  add esi, rdi
  mov [rbx],esi
  mov rbx,[rsp+30]
  jmp return

code:
  mov [rbx],esi
  mov rbx,[rsp+30]
  jmp return

INJECT_INF_AM:
  jmp newmem
  nop 2
return:
registersymbol(INJECT_INF_AM)

[DISABLE]

INJECT_INF_AM:
  db 89 33 48 8B 5C 24 30

unregistersymbol(INJECT_INF_AM)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: gamedll_ph_x64_rwdi.dll+51FB16

gamedll_ph_x64_rwdi.dll+51FAEE: 48 8B 43 30              - mov rax,[rbx+30]
gamedll_ph_x64_rwdi.dll+51FAF2: 48 8D 4B 30              - lea rcx,[rbx+30]
gamedll_ph_x64_rwdi.dll+51FAF6: FF 90 90 0B 00 00        - call qword ptr [rax+00000B90]
gamedll_ph_x64_rwdi.dll+51FAFC: 0F 57 C9                 - xorps xmm1,xmm1
gamedll_ph_x64_rwdi.dll+51FAFF: 0F 2F C1                 - comiss xmm0,xmm1
gamedll_ph_x64_rwdi.dll+51FB02: 76 14                    - jna gamedll_ph_x64_rwdi.dll+51FB18
gamedll_ph_x64_rwdi.dll+51FB04: F3 0F 10 0D 68 21 AF 01  - movss xmm1,[gamedll_ph_x64_rwdi.dll+2011C74]
gamedll_ph_x64_rwdi.dll+51FB0C: 48 8B CB                 - mov rcx,rbx
gamedll_ph_x64_rwdi.dll+51FB0F: E8 EC 81 F9 FF           - call gamedll_ph_x64_rwdi.dll+4B7D00
gamedll_ph_x64_rwdi.dll+51FB14: EB 02                    - jmp gamedll_ph_x64_rwdi.dll+51FB18
// ---------- INJECTING HERE ----------
gamedll_ph_x64_rwdi.dll+51FB16: 89 33                    - mov [rbx],esi
// ---------- DONE INJECTING  ----------
gamedll_ph_x64_rwdi.dll+51FB18: 48 8B 5C 24 30           - mov rbx,[rsp+30]
gamedll_ph_x64_rwdi.dll+51FB1D: 48 8B 6C 24 38           - mov rbp,[rsp+38]
gamedll_ph_x64_rwdi.dll+51FB22: 48 8B 74 24 40           - mov rsi,[rsp+40]
gamedll_ph_x64_rwdi.dll+51FB27: 48 83 C4 20              - add rsp,20
gamedll_ph_x64_rwdi.dll+51FB2B: 5F                       - pop rdi
gamedll_ph_x64_rwdi.dll+51FB2C: C3                       - ret 
gamedll_ph_x64_rwdi.dll+51FB2D: 0F 1F 00                 - nop dword ptr [rax]
gamedll_ph_x64_rwdi.dll+51FB30: EA FA 51 00 18 FB 51     - jmp 51FB:180051FA
gamedll_ph_x64_rwdi.dll+51FB37: 00 00                    - add [rax],al
gamedll_ph_x64_rwdi.dll+51FB39: 01 00                    - add [rax],eax
}"""

[[cheat]]
id = "freezeresistantatnight"
name = "FreezeResistantAtNight"
category = "game"
description = ""
hint = ""
type = "script"
source = """
{ Game   : DyingLightGame_x64_rwdi.exe
  Version: 
  Date   : 2023-04-23
  Author : David

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJECT_dark_resist,gamedll_ph_x64_rwdi.dll,F3 0F 5C C1 0F 57 C9 E8 C1) // should be unique
alloc(newmem,$1000,INJECT_dark_resist)

label(code)
label(return)

newmem:
  movss xmm0,xmm2
  xorps xmm1,xmm1
  jmp return

code:
  subss xmm0,xmm1
  xorps xmm1,xmm1
  jmp return

INJECT_dark_resist:
  jmp newmem
  nop 2
return:
registersymbol(INJECT_dark_resist)

[DISABLE]

INJECT_dark_resist:
  db F3 0F 5C C1 0F 57 C9

unregistersymbol(INJECT_dark_resist)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: gamedll_ph_x64_rwdi.dll+945CB3

gamedll_ph_x64_rwdi.dll+945C8A: F3 41 0F 59 C8        - mulss xmm1,xmm8
gamedll_ph_x64_rwdi.dll+945C8F: 45 33 C0              - xor r8d,r8d
gamedll_ph_x64_rwdi.dll+945C92: 48 8B CF              - mov rcx,rdi
gamedll_ph_x64_rwdi.dll+945C95: E8 16 B7 F6 FF        - call gamedll_ph_x64_rwdi.dll+8B13B0
gamedll_ph_x64_rwdi.dll+945C9A: F3 0F 10 4F 58        - movss xmm1,[rdi+58]
gamedll_ph_x64_rwdi.dll+945C9F: 0F 2E CF              - ucomiss xmm1,xmm7
gamedll_ph_x64_rwdi.dll+945CA2: 74 20                 - je gamedll_ph_x64_rwdi.dll+945CC4
gamedll_ph_x64_rwdi.dll+945CA4: F3 0F 10 47 2C        - movss xmm0,[rdi+2C]
gamedll_ph_x64_rwdi.dll+945CA9: F3 0F 10 57 20        - movss xmm2,[rdi+20]
gamedll_ph_x64_rwdi.dll+945CAE: F3 41 0F 59 C8        - mulss xmm1,xmm8
// ---------- INJECTING HERE ----------
gamedll_ph_x64_rwdi.dll+945CB3: F3 0F 5C C1           - subss xmm0,xmm1
// ---------- DONE INJECTING  ----------
gamedll_ph_x64_rwdi.dll+945CB7: 0F 57 C9              - xorps xmm1,xmm1
gamedll_ph_x64_rwdi.dll+945CBA: E8 C1 61 CE 00        - call gamedll_ph_x64_rwdi.dll+162BE80
gamedll_ph_x64_rwdi.dll+945CBF: F3 0F 11 47 2C        - movss [rdi+2C],xmm0
gamedll_ph_x64_rwdi.dll+945CC4: 44 0F 2F D7           - comiss xmm10,xmm7
gamedll_ph_x64_rwdi.dll+945CC8: 0F B6 8F 0D 13 00 00  - movzx ecx,byte ptr [rdi+0000130D]
gamedll_ph_x64_rwdi.dll+945CCF: 76 10                 - jna gamedll_ph_x64_rwdi.dll+945CE1
gamedll_ph_x64_rwdi.dll+945CD1: 44 0F 2F 5F 2C        - comiss xmm11,[rdi+2C]
gamedll_ph_x64_rwdi.dll+945CD6: 0F 97 C0              - seta al
gamedll_ph_x64_rwdi.dll+945CD9: 88 87 0D 13 00 00     - mov [rdi+0000130D],al
gamedll_ph_x64_rwdi.dll+945CDF: EB 03                 - jmp gamedll_ph_x64_rwdi.dll+945CE4
}"""

[[cheat]]
id = "test-func-attack"
name = "test-func-attack"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
{ Game   : DyingLightGame_x64_rwdi.exe
  Version: 
  Date   : 2023-04-22
  Author : David

  This script does blah blah blah
}
globalalloc(PLAYER_IS_ATTACKING,$4)
[ENABLE]

aobscanmodule(INJECT_PLY_ATT,gamedll_ph_x64_rwdi.dll,E8 BE 67 E0 FF) // should be unique
alloc(newmem,$1000,INJECT_PLY_ATT)

label(code)
label(return)

newmem:
  mov [rsp+20],rax
  mov rax, 1
  mov [PLAYER_IS_ATTACKING], rax
  mov rax, [rsp+20]
  call gamedll_ph_x64_rwdi.dll+822BF0
  mov [rsp+20],rax
  mov rax, 0
  mov [PLAYER_IS_ATTACKING], rax
  mov rax, [rsp+20]
  jmp return

code:
  call gamedll_ph_x64_rwdi.dll+822BF0
  jmp return

INJECT_PLY_ATT:
  jmp newmem
return:
registersymbol(INJECT_PLY_ATT)

[DISABLE]

INJECT_PLY_ATT:
  db E8 BE 67 E0 FF

unregistersymbol(INJECT_PLY_ATT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: gamedll_ph_x64_rwdi.dll+A1C42D

gamedll_ph_x64_rwdi.dll+A1C3F6: 48 8B C8                    - mov rcx,rax
gamedll_ph_x64_rwdi.dll+A1C3F9: E8 B2 A3 ED FF              - call gamedll_ph_x64_rwdi.dll+8F67B0
gamedll_ph_x64_rwdi.dll+A1C3FE: 48 8D 4C 24 30              - lea rcx,[rsp+30]
gamedll_ph_x64_rwdi.dll+A1C403: 48 C7 44 24 30 00 00 00 00  - mov qword ptr [rsp+30],00000000
gamedll_ph_x64_rwdi.dll+A1C40C: FF 15 EE D7 5C 01           - call qword ptr [gamedll_ph_x64_rwdi.dll+1FE9C00]
gamedll_ph_x64_rwdi.dll+A1C412: 4C 8D 0D 0F E3 86 01        - lea r9,[gamedll_ph_x64_rwdi.dll+228A728]
gamedll_ph_x64_rwdi.dll+A1C419: 4D 8B C7                    - mov r8,r15
gamedll_ph_x64_rwdi.dll+A1C41C: 48 8D 54 24 38              - lea rdx,[rsp+38]
gamedll_ph_x64_rwdi.dll+A1C421: 48 89 44 24 20              - mov [rsp+20],rax
gamedll_ph_x64_rwdi.dll+A1C426: 48 8D 8F 28 0C 00 00        - lea rcx,[rdi+00000C28]
// ---------- INJECTING HERE ----------
gamedll_ph_x64_rwdi.dll+A1C42D: E8 BE 67 E0 FF              - call gamedll_ph_x64_rwdi.dll+822BF0
// ---------- DONE INJECTING  ----------
gamedll_ph_x64_rwdi.dll+A1C432: 48 8D 48 10                 - lea rcx,[rax+10]
gamedll_ph_x64_rwdi.dll+A1C436: EB 3E                       - jmp gamedll_ph_x64_rwdi.dll+A1C476
gamedll_ph_x64_rwdi.dll+A1C438: 8B 15 36 D0 2D 02           - mov edx,[gamedll_ph_x64_rwdi.dll+2CF9474]
gamedll_ph_x64_rwdi.dll+A1C43E: 83 FA FF                    - cmp edx,-01
gamedll_ph_x64_rwdi.dll+A1C441: 75 16                       - jne gamedll_ph_x64_rwdi.dll+A1C459
gamedll_ph_x64_rwdi.dll+A1C443: 8B 05 1B 89 88 02           - mov eax,[gamedll_ph_x64_rwdi.dll+32A4D64]
gamedll_ph_x64_rwdi.dll+A1C449: 8B D0                       - mov edx,eax
gamedll_ph_x64_rwdi.dll+A1C44B: 89 05 23 D0 2D 02           - mov [gamedll_ph_x64_rwdi.dll+2CF9474],eax
gamedll_ph_x64_rwdi.dll+A1C451: FF C0                       - inc eax
gamedll_ph_x64_rwdi.dll+A1C453: 89 05 0B 89 88 02           - mov [gamedll_ph_x64_rwdi.dll+32A4D64],eax
}"""

[[cheat]]
id = "playergodmodeonehitkill"
name = "PlayerGodModeOneHitKill"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : DyingLightGame_x64_rwdi.exe
  Version: 
  Date   : 2023-04-28
  Author : David

  This script does blah blah blah
}
[ENABLE]
//F3 0F 5C C6 0F 28 C8 E8 14
aobscanmodule(INJECT_PL_GM_HP_ONEHIT,gamedll_ph_x64_rwdi.dll,F3 0F 5C C6 0F 28 C8 E8 B4) // should be unique
alloc(newmem,$1000,INJECT_PL_GM_HP_ONEHIT)
alloc(playerMaxHp,$8,gamedll_ph_x64_rwdi.dll)
registersymbol(playerMaxHp)
label(code)
label(return)

newmem:
// Next line writes HP after hit = xmm7 (max)
  movd r14, xmm7
  and r14, 0x7F800000
  cmp r14, 0x7F800000 // Check if xmm13 is NaN, infinity, or zero
  je code
  movss xmm0,xmm7
  movaps xmm1,xmm0
  movss xmm13, [playerMaxHp]
  comiss xmm7, xmm13
  je return // If this max hp == playerMaxHp set hp to max
  movss xmm0,xmm14 // set hp (xmm14 == 0)
  movaps xmm1,xmm0
  jmp return

code:
  subss xmm0,xmm6
  movaps xmm1,xmm0
  jmp return

INJECT_PL_GM_HP_ONEHIT:
  jmp newmem
  nop 2
return:
registersymbol(INJECT_PL_GM_HP_ONEHIT)

[DISABLE]

INJECT_PL_GM_HP_ONEHIT:
  db F3 0F 5C C6 0F 28 C8
unregistersymbol(playerMaxHp)
dealloc(playerMaxHp)
unregistersymbol(INJECT_PL_GM_HP_ONEHIT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: gamedll_ph_x64_rwdi.dll+11C4121

gamedll_ph_x64_rwdi.dll+823A09: F3 0F 10 30     - movss xmm6,[rax]
gamedll_ph_x64_rwdi.dll+823A0D: 0F 28 CE        - movaps xmm1,xmm6
gamedll_ph_x64_rwdi.dll+823A10: E8 3B 45 1E 01  - call gamedll_ph_x64_rwdi.dll+1A07F50
gamedll_ph_x64_rwdi.dll+823A15: 48 8B CF        - mov rcx,rdi
gamedll_ph_x64_rwdi.dll+823A18: E8 53 12 C8 00  - call gamedll_ph_x64_rwdi.dll+14A4C70
gamedll_ph_x64_rwdi.dll+823A1D: 48 8B CF        - mov rcx,rdi
gamedll_ph_x64_rwdi.dll+823A20: 0F 28 F8        - movaps xmm7,xmm0
gamedll_ph_x64_rwdi.dll+823A23: E8 48 12 C8 00  - call gamedll_ph_x64_rwdi.dll+14A4C70
gamedll_ph_x64_rwdi.dll+823A28: F3 41 0F 5F F0  - maxss xmm6,xmm8
gamedll_ph_x64_rwdi.dll+823A2D: 48 8B CF        - mov rcx,rdi
// ---------- INJECTING HERE ----------
gamedll_ph_x64_rwdi.dll+823A30: F3 0F 5C C6     - subss xmm0,xmm6
// ---------- DONE INJECTING  ----------
gamedll_ph_x64_rwdi.dll+823A34: 0F 28 C8        - movaps xmm1,xmm0
gamedll_ph_x64_rwdi.dll+823A37: E8 14 45 1E 01  - call gamedll_ph_x64_rwdi.dll+1A07F50
gamedll_ph_x64_rwdi.dll+823A3C: 49 8D 4C 24 08  - lea rcx,[r12+08]
gamedll_ph_x64_rwdi.dll+823A41: 49 03 CF        - add rcx,r15
gamedll_ph_x64_rwdi.dll+823A44: E8 27 12 C8 00  - call gamedll_ph_x64_rwdi.dll+14A4C70
gamedll_ph_x64_rwdi.dll+823A49: 83 7D CB 00     - cmp dword ptr [rbp-35],00
gamedll_ph_x64_rwdi.dll+823A4D: 0F 28 F0        - movaps xmm6,xmm0
gamedll_ph_x64_rwdi.dll+823A50: 74 16           - je gamedll_ph_x64_rwdi.dll+823A68
gamedll_ph_x64_rwdi.dll+823A52: 45 8B C6        - mov r8d,r14d
gamedll_ph_x64_rwdi.dll+823A55: 48 8D 55 B7     - lea rdx,[rbp-49]
}"""

[[cheat]]
id = "findcurrentmaxhp"
name = "FindCurrentMaxHp"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : DyingLightGame_x64_rwdi.exe
  Version: 
  Date   : 2023-04-28
  Author : David

  This script does blah blah blah
}
[ENABLE]

aobscanmodule(INJECT_SET_CURRENT_MAX_HP,gamedll_ph_x64_rwdi.dll,F3 0F 11 57 34 F3) // should be unique
alloc(newmem,$1000,INJECT_SET_CURRENT_MAX_HP)
label(code)
label(return)

newmem:
  movss [rdi+34],xmm2
  movss [playerMaxHp],xmm2 // Set current max hp
  jmp return

code:
  movss [rdi+34],xmm2
  jmp return

INJECT_SET_CURRENT_MAX_HP:
  jmp newmem
return:
registersymbol(INJECT_SET_CURRENT_MAX_HP)

[DISABLE]

INJECT_SET_CURRENT_MAX_HP:
  db F3 0F 11 57 34

unregistersymbol(INJECT_SET_CURRENT_MAX_HP)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: gamedll_ph_x64_rwdi.dll+C7FED7

gamedll_ph_x64_rwdi.dll+C7FEAC: FF 56 F8                 - call qword ptr [rsi-08]
gamedll_ph_x64_rwdi.dll+C7FEAF: 0F B6 44 24 40           - movzx eax,byte ptr [rsp+40]
gamedll_ph_x64_rwdi.dll+C7FEB4: 84 C0                    - test al,al
gamedll_ph_x64_rwdi.dll+C7FEB6: 0F 84 9C 00 00 00        - je gamedll_ph_x64_rwdi.dll+C7FF58
gamedll_ph_x64_rwdi.dll+C7FEBC: F3 0F 10 4F 34           - movss xmm1,[rdi+34]
gamedll_ph_x64_rwdi.dll+C7FEC1: F3 0F 11 4F 38           - movss [rdi+38],xmm1
gamedll_ph_x64_rwdi.dll+C7FEC6: 3C 02                    - cmp al,02
gamedll_ph_x64_rwdi.dll+C7FEC8: 0F 85 DE 00 00 00        - jne gamedll_ph_x64_rwdi.dll+C7FFAC
gamedll_ph_x64_rwdi.dll+C7FECE: F3 0F 10 54 24 30        - movss xmm2,[rsp+30]
gamedll_ph_x64_rwdi.dll+C7FED4: 0F 28 C2                 - movaps xmm0,xmm2
// ---------- INJECTING HERE ----------
gamedll_ph_x64_rwdi.dll+C7FED7: F3 0F 11 57 34           - movss [rdi+34],xmm2
// ---------- DONE INJECTING  ----------
gamedll_ph_x64_rwdi.dll+C7FEDC: F3 0F 58 05 28 D5 4F 01  - addss xmm0,[gamedll_ph_x64_rwdi.dll+217D40C]
gamedll_ph_x64_rwdi.dll+C7FEE4: 0F 2F C1                 - comiss xmm0,xmm1
gamedll_ph_x64_rwdi.dll+C7FEE7: 73 0E                    - jae gamedll_ph_x64_rwdi.dll+C7FEF7
gamedll_ph_x64_rwdi.dll+C7FEE9: F3 0F 5C CA              - subss xmm1,xmm2
gamedll_ph_x64_rwdi.dll+C7FEED: F3 0F 58 4F 3C           - addss xmm1,[rdi+3C]
gamedll_ph_x64_rwdi.dll+C7FEF2: F3 0F 11 4F 3C           - movss [rdi+3C],xmm1
gamedll_ph_x64_rwdi.dll+C7FEF7: 48 8B 47 18              - mov rax,[rdi+18]
gamedll_ph_x64_rwdi.dll+C7FEFB: 48 8D 4F 18              - lea rcx,[rdi+18]
gamedll_ph_x64_rwdi.dll+C7FEFF: FF 50 08                 - call qword ptr [rax+08]
gamedll_ph_x64_rwdi.dll+C7FF02: 84 C0                    - test al,al
}"""

[[cheat]]
id = "set-this-to-current-max-hp"
name = "SET THIS TO CURRENT MAX HP"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "playerMaxHp"
hops = []
