[game]
name = "MELTY BLOOD: TYPE LUMINA"
exe = "mbtl.exe"
notes = "Converted from a Cheat Engine table by Piotrixek. Source: https://fearlessrevolution.com/viewtopic.php?t=25345"
verified = []
author = "Piotrixek"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "after-buying-things-money-increase-or-decrease-little"
name = "AFTER BUYING THINGS MONEY INCREASE OR DECREASE LITTLE"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here

originalcode:
//mov [MBTL.exe+1AC5C69],al

exit:
jmp returnhere

"MBTL.exe"+219BFD:
jmp newmem
returnhere:


 
 
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
"MBTL.exe"+219BFD:
db A2 69 5C F1 01
//mov [MBTL.exe+1AC5C69],al"""
