[game]
name = "Dark Messiah of Might & Magic SinglePlayer"
exe = "dark_messiah_of_might_magic_singleplayer.exe"
notes = "Converted from a Cheat Engine table by Marc. Source: https://fearlessrevolution.com/viewtopic.php?t=17062"
verified = []
author = "Marc"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "current-health"
name = "Current Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 50

[cheat.locator]
find = "static"
module = "server.dll"
offset = "0x7d2b6c"
hops = ["+0x310"]

[[cheat]]
id = "max-health"
name = "Max Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "static"
module = "server.dll"
offset = "0x7d2b6c"
hops = ["+0x30c"]

[[cheat]]
id = "available-skill-points"
name = "Available Skill Points"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 4

[cheat.locator]
find = "static"
module = "server.dll"
offset = "0x7d2b6c"
hops = ["+0x2b3c"]
