[game]
name = "Plants Vs Zombies RH 2.1.3 (Plants Vs Zombies Fusion)"
exe = "plantsvszombiesrh.exe"
notes = "Converted from a Cheat Engine table by arkadyavian. Source: https://fearlessrevolution.com/viewtopic.php?t=31920"
verified = []
author = "arkadyavian"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "sun"
name = "SUN"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : PlantsVsZombiesRH.exe
  Version: 
  Date   : 2024-10-05
  Author : Arkadya

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJECT,GameAssembly.dll,89 81 A4 00 00 00 48 8B 43) // should be unique
alloc(newmem,$1000,INJECT)

label(code)
label(return)

newmem:

code:
  mov [rcx+000000A4], 9999
  nop
  jmp return

INJECT:
  jmp newmem
  nop
return:
registersymbol(INJECT)

[DISABLE]

INJECT:
  db 89 81 A4 00 00 00

unregistersymbol(INJECT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: GameAssembly.dll+3CC4D0

GameAssembly.dll+3CC4A2: E9 79 FF FF FF        - jmp GameAssembly.dll+3CC420
GameAssembly.dll+3CC4A7: 48 8B 82 B8 00 00 00  - mov rax,[rdx+000000B8]
GameAssembly.dll+3CC4AE: 48 8B 08              - mov rcx,[rax]
GameAssembly.dll+3CC4B1: 48 85 C9              - test rcx,rcx
GameAssembly.dll+3CC4B4: 0F 84 DD 00 00 00     - je GameAssembly.dll+3CC597
GameAssembly.dll+3CC4BA: 48 8B 53 60           - mov rdx,[rbx+60]
GameAssembly.dll+3CC4BE: 48 85 D2              - test rdx,rdx
GameAssembly.dll+3CC4C1: 0F 84 D0 00 00 00     - je GameAssembly.dll+3CC597
GameAssembly.dll+3CC4C7: 8B 81 A4 00 00 00     - mov eax,[rcx+000000A4]
GameAssembly.dll+3CC4CD: 2B 42 24              - sub eax,[rdx+24]
// ---------- INJECTING HERE ----------
GameAssembly.dll+3CC4D0: 89 81 A4 00 00 00     - mov [rcx+000000A4],eax
// ---------- DONE INJECTING  ----------
GameAssembly.dll+3CC4D6: 48 8B 43 60           - mov rax,[rbx+60]
GameAssembly.dll+3CC4DA: 48 85 C0              - test rax,rax
GameAssembly.dll+3CC4DD: 0F 84 B4 00 00 00     - je GameAssembly.dll+3CC597
GameAssembly.dll+3CC4E3: 89 78 44              - mov [rax+44],edi
GameAssembly.dll+3CC4E6: 48 8B 4B 60           - mov rcx,[rbx+60]
GameAssembly.dll+3CC4EA: 48 85 C9              - test rcx,rcx
GameAssembly.dll+3CC4ED: 0F 84 A4 00 00 00     - je GameAssembly.dll+3CC597
GameAssembly.dll+3CC4F3: FF 41 4C              - inc [rcx+4C]
GameAssembly.dll+3CC4F6: 48 8B 4B 60           - mov rcx,[rbx+60]
GameAssembly.dll+3CC4FA: 48 85 C9              - test rcx,rcx
}"""

[[cheat]]
id = "no-cooldown"
name = "NO COOLDOWN"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : PlantsVsZombiesRH.exe
  Version: 
  Date   : 2024-10-05
  Author : Arkadya

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJECT,GameAssembly.dll,89 78 44 48 8B 4B 60) // should be unique
alloc(newmem,$1000,INJECT)

label(code)
label(return)

newmem:

code:
  nop
  nop
  jmp return

INJECT:
  jmp newmem
  nop 2
return:
registersymbol(INJECT)

[DISABLE]

INJECT:
  db 89 78 44 48 8B 4B 60

unregistersymbol(INJECT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: GameAssembly.dll+3CC4E3

GameAssembly.dll+3CC4B4: 0F 84 DD 00 00 00     - je GameAssembly.dll+3CC597
GameAssembly.dll+3CC4BA: 48 8B 53 60           - mov rdx,[rbx+60]
GameAssembly.dll+3CC4BE: 48 85 D2              - test rdx,rdx
GameAssembly.dll+3CC4C1: 0F 84 D0 00 00 00     - je GameAssembly.dll+3CC597
GameAssembly.dll+3CC4C7: 8B 81 A4 00 00 00     - mov eax,[rcx+000000A4]
GameAssembly.dll+3CC4CD: 2B 42 24              - sub eax,[rdx+24]
GameAssembly.dll+3CC4D0: 89 81 A4 00 00 00     - mov [rcx+000000A4],eax
GameAssembly.dll+3CC4D6: 48 8B 43 60           - mov rax,[rbx+60]
GameAssembly.dll+3CC4DA: 48 85 C0              - test rax,rax
GameAssembly.dll+3CC4DD: 0F 84 B4 00 00 00     - je GameAssembly.dll+3CC597
// ---------- INJECTING HERE ----------
GameAssembly.dll+3CC4E3: 89 78 44              - mov [rax+44],edi
// ---------- DONE INJECTING  ----------
GameAssembly.dll+3CC4E6: 48 8B 4B 60           - mov rcx,[rbx+60]
GameAssembly.dll+3CC4EA: 48 85 C9              - test rcx,rcx
GameAssembly.dll+3CC4ED: 0F 84 A4 00 00 00     - je GameAssembly.dll+3CC597
GameAssembly.dll+3CC4F3: FF 41 4C              - inc [rcx+4C]
GameAssembly.dll+3CC4F6: 48 8B 4B 60           - mov rcx,[rbx+60]
GameAssembly.dll+3CC4FA: 48 85 C9              - test rcx,rcx
GameAssembly.dll+3CC4FD: 0F 84 94 00 00 00     - je GameAssembly.dll+3CC597
GameAssembly.dll+3CC503: 33 D2                 - xor edx,edx
GameAssembly.dll+3CC505: E8 06 00 F5 FF        - call GameAssembly.dll+31C510
GameAssembly.dll+3CC50A: 48 8B 0D 7F E6 79 01  - mov rcx,[GameAssembly.dll+1B6AB90]
}"""

[[cheat]]
id = "immune-plant"
name = "IMMUNE PLANT"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : PlantsVsZombiesRH.exe
  Version: 
  Date   : 2024-10-05
  Author : Arkadya

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(INJECT,GameAssembly.dll,44 29 76 2C 48 8B 9C 24 90 00 00 00) // should be unique
alloc(newmem,$1000,INJECT)

label(code)
label(return)

newmem:

code:
  nop
  mov rbx,[rsp+00000090]
  jmp return

INJECT:
  jmp newmem
  nop 7
return:
registersymbol(INJECT)

[DISABLE]

INJECT:
  db 44 29 76 2C 48 8B 9C 24 90 00 00 00

unregistersymbol(INJECT)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: GameAssembly.dll+34F05C

GameAssembly.dll+34F02A: E8 E1 11 FC FF           - call GameAssembly.dll+310210
GameAssembly.dll+34F02F: EB 2B                    - jmp GameAssembly.dll+34F05C
GameAssembly.dll+34F031: 48 8B 15 48 E2 82 01     - mov rdx,[GameAssembly.dll+1B7D280]
GameAssembly.dll+34F038: 48 8B 4C 24 38           - mov rcx,[rsp+38]
GameAssembly.dll+34F03D: E8 CE 11 FC FF           - call GameAssembly.dll+310210
GameAssembly.dll+34F042: 48 8B 4C 24 30           - mov rcx,[rsp+30]
GameAssembly.dll+34F047: 48 85 C9                 - test rcx,rcx
GameAssembly.dll+34F04A: 75 43                    - jne GameAssembly.dll+34F08F
GameAssembly.dll+34F04C: 44 8B B4 24 88 00 00 00  - mov r14d,[rsp+00000088]
GameAssembly.dll+34F054: 48 8B B4 24 80 00 00 00  - mov rsi,[rsp+00000080]
// ---------- INJECTING HERE ----------
GameAssembly.dll+34F05C: 44 29 76 2C              - sub [rsi+2C],r14d
// ---------- DONE INJECTING  ----------
GameAssembly.dll+34F060: 48 8B 9C 24 90 00 00 00  - mov rbx,[rsp+00000090]
GameAssembly.dll+34F068: 48 83 C4 60              - add rsp,60
GameAssembly.dll+34F06C: 41 5E                    - pop r14
GameAssembly.dll+34F06E: 5F                       - pop rdi
GameAssembly.dll+34F06F: 5E                       - pop rsi
GameAssembly.dll+34F070: C3                       - ret 
GameAssembly.dll+34F071: E8 9A CF F2 FF           - call GameAssembly.dll+27C010
GameAssembly.dll+34F076: 90                       - nop 
GameAssembly.dll+34F077: E8 94 CF F2 FF           - call GameAssembly.dll+27C010
GameAssembly.dll+34F07C: 90                       - nop 
}"""
