[game]
name = "Grandia 2 HD Remaster"
exe = "grandia2.exe"
notes = "Converted from a Cheat Engine table by ashuraman. Source: https://fearlessrevolution.com/viewtopic.php?t=10666"
verified = []
author = "ashuraman"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "current-hp-in-battle"
name = "Current HP in battle"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 476

[cheat.locator]
find = "static"
module = "grandia2.exe"
offset = "0x5c3c24"
hops = []

[[cheat]]
id = "current-mp-in-battle"
name = "Current MP in battle"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 58

[cheat.locator]
find = "static"
module = "grandia2.exe"
offset = "0x5c3c2c"
hops = []

[[cheat]]
id = "current-sp-in-battle"
name = "Current SP in battle"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 80

[cheat.locator]
find = "static"
module = "grandia2.exe"
offset = "0x5c3c34"
hops = []

[[cheat]]
id = "current-hp-in-battle-2"
name = "Current HP in battle"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 391

[cheat.locator]
find = "static"
module = "grandia2.exe"
offset = "0x5c3e78"
hops = []

[[cheat]]
id = "current-mp-in-battle-2"
name = "Current MP in battle"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 71

[cheat.locator]
find = "static"
module = "grandia2.exe"
offset = "0x5c3e80"
hops = []

[[cheat]]
id = "current-sp-in-battle-2"
name = "Current SP in battle"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 75

[cheat.locator]
find = "static"
module = "grandia2.exe"
offset = "0x5c3e88"
hops = []
