[game]
name = "HuniePop 2: Double Date [CONSOLE + COMMANDS]"
exe = "huniepop_2_-_double_date.exe"
notes = "Converted from a Cheat Engine table by GreenHouse. Source: https://fearlessrevolution.com/viewtopic.php?t=15232"
verified = []
author = "GreenHouse"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "infinite-date-moves"
name = "Infinite Date Moves"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_setMoves,PuzzleStatus:set_movesRemaining,PuzzleStatus:set_movesRemaining+100,89 47 64 48 8B 7D F8)
alloc(newmem,$1000,get_setMoves)
label(code)
label(return)

newmem:
cmp [rdi+64],eax
jb code
mov rdi,[rbp-08]
jmp return

code:
  mov [rdi+64],eax
  mov rdi,[rbp-08]
  jmp return

get_setMoves:
  jmp newmem
  nop 2
return:
registersymbol(get_setMoves)

[DISABLE]
get_setMoves:
  db 89 47 64 48 8B 7D F8

unregistersymbol(get_setMoves)
dealloc(newmem)"""

[[cheat]]
id = "insta-max-passion"
name = "Insta-Max Passion"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_setPassion,PuzzleStatusGirl:set_passion,PuzzleStatusGirl:set_passion+50,89 48 64 48 8D 65 00)
alloc(newmem,$1000,get_setPassion)
label(code)
label(return)

newmem:

code:
  mov [rax+64],64
  lea rsp,[rbp+00]
  jmp return

get_setPassion:
  jmp newmem
  nop 2
return:
registersymbol(get_setPassion)

[DISABLE]
get_setPassion:
  db 89 48 64 48 8D 65 00

unregistersymbol(get_setPassion)
dealloc(newmem)"""

[[cheat]]
id = "infinite-seeds-open-store"
name = "Infinite Seeds [Open Store]"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_Seeds,UiAppStoreSlot:Refresh,UiAppStoreSlot:Refresh+200,48 63 00 48 8B 4F 30)
aobscanregion(get_SeedsGOG,PlayerFile:GetFruitCount,PlayerFile:GetFruitCount+50,48 63 00 48 83 C4 18)
alloc(newmem,$1000,get_Seeds)
label(code)
label(return)
label(SeedsGOG)
label(SeedsGOGRet)

newmem:

code:
  mov [rax],#900
  movsxd rax,dword ptr [rax]
  mov rcx,[rdi+30]
  jmp return

SeedsGOG:
  mov [rax],#900
  movsxd rax,dword ptr [rax]
  add rsp,18
  jmp SeedsGOGRet

get_Seeds:
  jmp newmem
  nop 2
return:
registersymbol(get_Seeds)

get_SeedsGOG:
  jmp SeedsGOG
  nop 2
SeedsGOGRet:
registersymbol(get_SeedsGOG)

[DISABLE]
get_Seeds:
  db 48 63 00 48 8B 4F 30

get_SeedsGOG:
  db 48 63 00 48 83 C4 18

unregistersymbol(get_Seeds)
unregistersymbol(get_SeedsGOG)
dealloc(newmem)"""

[[cheat]]
id = "unlock-all-outfits-and-hairstyles-permanently"
name = "Unlock All Outfits and Hairstyles [PERMANENTLY]"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_doUnlockOutfit,PlayerFileGirl:IsOutfitUnlocked,PlayerFileGirl:IsOutfitUnlocked+110,41 FF D3 85 C0 0F 84 5F 00 00 00 66 66 90)
aobscanregion(get_doUnlockOutfit2,PlayerFileGirl:IsOutfitUnlocked,PlayerFileGirl:IsOutfitUnlocked+110,41 FF D3 85 C0 74 1B)
aobscanregion(get_doUnlockHairstyle,PlayerFileGirl:IsHairstyleUnlocked,PlayerFileGirl:IsHairstyleUnlocked+110,41 FF D3 85 C0 0F 84 5F 00 00 00 66 66 90)
aobscanregion(get_doUnlockHairstyle2,PlayerFileGirl:IsHairstyleUnlocked,PlayerFileGirl:IsHairstyleUnlocked+110,41 FF D3 85 C0 74 1B)
registersymbol(get_doUnlockOutfit)
registersymbol(get_doUnlockOutfit2)
registersymbol(get_doUnlockHairstyle)
registersymbol(get_doUnlockHairstyle2)

get_doUnlockOutfit+5:
db 90 90 90 90 90 90

get_doUnlockOutfit2+3:
db 90 90 90 90

get_doUnlockHairstyle+5:
db 90 90 90 90 90 90

get_doUnlockHairstyle2+3:
db 90 90 90 90

[DISABLE]
get_doUnlockOutfit+5:
db 0F 84 5F 00 00 00

get_doUnlockOutfit2+3:
db 85 C0 74 1B

get_doUnlockHairstyle+5:
db 0F 84 5F 00 00 00

get_doUnlockHairstyle2+3:
db 85 C0 74 1B

unregistersymbol(get_doUnlockOutfit)
unregistersymbol(get_doUnlockOutfit2)
unregistersymbol(get_doUnlockHairstyle)
unregistersymbol(get_doUnlockHairstyle2)"""

[[cheat]]
id = "date-affection-cheats"
name = "[ Date Affection Cheats ]"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_addAffection,PuzzleStatus:AddResourceValue,PuzzleStatus:AddResourceValue+200,41 FF D3 41 89 46 5C)
alloc(newmem,$1000,get_addAffection)
label(code)
label(return)
label(incBonus)
alloc(_incBonus,3)
registersymbol(_incBonus)


newmem:
  call r11
  cmp byte ptr [r14+51],01
  je incBonus
  cmp byte ptr [_incBonus],01
  jne code
  mov eax,[r14+60]
  jmp code

incBonus:
  cmp byte ptr [_incBonus+1],01
  jne @f
  mov eax,[r14+60]
  jmp code
@@:
  cmp byte ptr [_incBonus+2],01
  je return

code:
  mov [r14+5C],eax
  jmp return

get_addAffection:
  jmp newmem
  nop 2
return:
registersymbol(get_addAffection)

[DISABLE]
get_addAffection:
  db 41 FF D3 41 89 46 5C

unregistersymbol(get_addAffection)
dealloc(newmem)"""

[[cheat]]
id = "insta-max-affection"
name = "Insta-Max Affection?"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1
choices = [
    "1:YES",
    "0:NO",
]

[cheat.locator]
find = "symbol"
symbol = "_incBonus"
hops = []

[[cheat]]
id = "insta-max-bonus-affection"
name = "Insta-Max Bonus Affection?"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1
choices = [
    "1:YES",
    "0:NO",
]

[cheat.locator]
find = "symbol"
symbol = "_incBonus"
hops = []

[[cheat]]
id = "freeze-bonus-affection-decrease"
name = "Freeze Bonus Affection Decrease?"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1
choices = [
    "1:YES",
    "0:NO",
]

[cheat.locator]
find = "symbol"
symbol = "_incBonus"
hops = []

[[cheat]]
id = "infinite-stamina-talking-dates"
name = "Infinite Stamina (TALKING+DATES)"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_setStamina,PuzzleStatusGirl:set_stamina,PuzzleStatusGirl:set_stamina+100,41 FF D3 89 47 5C)
aobscanregion(get_talkWith,TalkManager:TalkWith+200,TalkManager:TalkWith+500,48 63 40 5C 83 F8 02)
alloc(newmem,$1000,get_setStamina)
label(code)
label(return)
label(talkWith)
label(talkWithRet)

newmem:

code:
  mov [rdi+5C],6
  jmp return

talkWith:
mov [rax+5C],6
movsxd rax,dword ptr [rax+5C]
cmp eax,02
jmp talkWithRet

get_setStamina:
  jmp newmem
  nop
return:
registersymbol(get_setStamina)

get_talkWith:
jmp talkWith
nop 2
talkWithRet:
registersymbol(get_talkWith)

[DISABLE]
get_setStamina:
  db 41 FF D3 89 47 5C

get_talkWith:
db 48 63 40 5C 83 F8 02

unregistersymbol(get_setStamina)
unregistersymbol(get_talkWith)
dealloc(newmem)"""

[[cheat]]
id = "infinite-stamina-talking-only"
name = "Infinite Stamina (TALKING ONLY)"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_infiniteTalkingStamina,TalkManager:TalkWith+500,TalkManager:TalkWith+7a0,41 FF D3 48 B8 ? ? ? ? ? ? ? ? 48 8B 00)
aobscanregion(get_talkWith,TalkManager:TalkWith+200,TalkManager:TalkWith+500,48 63 40 5C 83 F8 02)
registersymbol(get_infiniteTalkingStamina)
alloc(newmem,$1000,get_talkWith)
label(code)
label(return)

newmem:

code:
mov [rax+5C],6
movsxd rax,dword ptr [rax+5C]
cmp eax,02
jmp return

get_infiniteTalkingStamina:
db 90 90 90

get_talkWith:
jmp newmem
nop 2
return:
registersymbol(get_talkWith)

[DISABLE]
get_infiniteTalkingStamina:
db 41 FF D3

get_talkWith:
db 48 63 40 5C 83 F8 02

unregistersymbol(get_infiniteTalkingStamina)
unregistersymbol(get_talkWith)
dealloc(newmem)"""

[[cheat]]
id = "run"
name = "Run"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 1
choices = [
    "1:Play Cutscene",
    "0:Waiting",
]

[cheat.locator]
find = "symbol"
symbol = "playCutscene"
hops = []

[[cheat]]
id = "desired-cutscene"
name = "Desired Cutscene"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i64"
value = 160

[cheat.locator]
find = "symbol"
symbol = "desiredCutscene"
hops = []

[[cheat]]
id = "auto-assemble-script"
name = "Auto Assemble script"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_cPuzzle,UiPuzzleGrid:Update+1000,UiPuzzleGrid:Update+1300,83 39 00 0F B6 40 51 85 C0)
alloc(newmem,$1000,get_cPuzzle)
label(code)
label(return)
alloc(cPuzzle,8)
registersymbol(cPuzzle)

newmem:
mov [cPuzzle],rcx

code:
  cmp dword ptr [rcx],00
  movzx eax,byte ptr [rax+51]
  jmp return

get_cPuzzle:
  jmp newmem
  nop 2
return:
registersymbol(get_cPuzzle)

[DISABLE]
get_cPuzzle:
  db 83 39 00 0F B6 40 51

unregistersymbol(get_cPuzzle)
dealloc(newmem)"""

[[cheat]]
id = "unlock-girls-no-it-doesn-t"
name = "Unlock Girls [No It Doesn't]"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_playerMet,UiAppHeadSlot:Refresh+50,UiAppHeadSlot:Refresh+150,0F B6 40 60 85 C0 0F 84 66)
registersymbol(get_playerMet)

get_playerMet:
db B0 01 90 90

[DISABLE]
get_playerMet:
db 0F B6 40 60

unregistersymbol(get_playerMet)"""

[[cheat]]
id = "get-girl-hover-talk-bubble"
name = "[ Get Girl ] (Hover Talk Bubble)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_Girl,UiPuzzleStaminaHint:Refresh+100,UiPuzzleStaminaHint:Refresh+300,48 8B 50 30 49 8B CE)
alloc(newmem,$1000,get_Girl)
label(code)
label(return)
alloc(Girl,8)
registersymbol(Girl)

newmem:

code:
  mov [Girl],rax
  mov rdx,[rax+30]
  mov rcx,r14
  jmp return

get_Girl:
  jmp newmem
  nop 2
return:
registersymbol(get_Girl)

[DISABLE]
get_Girl:
  db 48 8B 50 30 49 8B CE

unregistersymbol(get_Girl)
dealloc(newmem)"""

[[cheat]]
id = "no-description"
name = "No description"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Girl"
hops = [
    "+0x188",
    "+0x0",
]

[[cheat]]
id = "is-dialogue-box-locked"
name = "is Dialogue Box Locked?"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "Girl"
hops = ["+0x26a"]

[[cheat]]
id = "is-exhausted"
name = "is Exhausted?"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "Girl"
hops = ["+0x26c"]

[[cheat]]
id = "infinite-date-stamina"
name = "Infinite Date Stamina"
category = "movement"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_infiniteDateStamina,PuzzleStatus:AddResourceValue+50,PuzzleStatus:AddResourceValue+200,41 FF D3 E9 ? ? ? ? 41 83 7D 00 00 49 63 55 64)
registersymbol(get_infiniteDateStamina)

get_infiniteDateStamina:
  db 90 90 90

[DISABLE]
get_infiniteDateStamina:
  db 41 FF D3

unregistersymbol(get_infiniteDateStamina)"""

[[cheat]]
id = "get-selected-inventory-item"
name = "[ Get Selected Inventory Item ]"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_invItem,UiTooltipItem:Populate+50,UiTooltipItem:Populate+200,83 3F 00 66 90)
alloc(newmem,$1000,get_invItem)
label(code)
label(return)
alloc(invItem,8)
registersymbol(invItem)

newmem:
  mov [invItem],rdi
code:
  cmp dword ptr [rdi],00
  nop 2
  jmp return

get_invItem:
  jmp newmem
return:
registersymbol(get_invItem)

[DISABLE]
get_invItem:
  db 83 3F 00 66 90

unregistersymbol(get_invItem)
dealloc(newmem)"""

[[cheat]]
id = "id"
name = "ID"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "invItem"
hops = ["+0x18"]

[[cheat]]
id = "don-t-stop-audio-on-skip"
name = "Don't Stop Audio on Skip"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_fadeAudio,UiDoll:StopDialogLine,UiDoll:StopDialogLine+100,41 FF D3 49 C7 87 B8 01 00 00 00 00 00 00)
registersymbol(get_fadeAudio)

get_fadeAudio:
db 90 90 90 90 90 90 90 90 90 90 90 90 90 90

[DISABLE]
get_fadeAudio:
db 41 FF D3 49 C7 87 B8 01 00 00 00 00 00 00

unregistersymbol(get_fadeAudio)"""

[[cheat]]
id = "get-current-girls-click-on-any-of-the-girls-picture"
name = "[ Get Current Girls ] (Click on any of the girls picture)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscanregion(get_cGirls,UiCellphoneAppProfile:Start+300,UiCellphoneAppProfile:Start+500,83 38 00 66 90)
alloc(newmem,$1000,get_cGirls)
label(code)
label(return)
alloc(cGirls,8)
registersymbol(cGirls)
alloc(expressionS,8)
registersymbol(expressionS)
alloc(chExp,1)
registersymbol(chExp)

newmem:
mov [cGirls],rax
cmp byte ptr [chExp],01
jne code
mov byte ptr [chExp],00


code:
  cmp dword ptr [rax],00
  nop 2
  jmp return

get_cGirls:
  jmp newmem
return:
registersymbol(get_cGirls)

[DISABLE]
get_cGirls:
  db 83 38 00 66 90

unregistersymbol(get_cGirls)
dealloc(newmem)"""

[[cheat]]
id = "unique-type"
name = "Unique Type"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
choices = [
    "0:TAILORING",
    "1:ALCOHOL",
    "2:OCCULT",
    "3:SPIRITUAL",
    "4:WEEABOO",
    "5:SPA",
    "6:TODDLER_TOYS",
    "7:BABY_BOY",
    "8:HANDBAGS",
    "9:BAND",
    "10:KINKY",
    "11:ANTIQUES",
]

[cheat.locator]
find = "symbol"
symbol = "cGirls"
hops = [
    "+0x20",
    "+0x13c",
]

[[cheat]]
id = "no-description-2"
name = "No description"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "cGirls"
hops = [
    "+0x28",
    "+0x0",
]

[[cheat]]
id = "no-description-3"
name = "No description"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "cGirls"
hops = ["+0x0"]
