[game]
name = "Duke Nukem 3D 20th Anniversary World Tour (Plaza)"
exe = "duke3d.exe"
notes = "Converted from a Cheat Engine table by vova123. Source: https://fearlessrevolution.com/viewtopic.php?t=1038"
verified = []
author = "vova123"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "infinite-health"
name = "Infinite Health"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : duke3d.exe
  Version: 
  Date   : 2017-04-05
  Author : Vovan

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(healthB,duke3d.exe,66 29 82 2A 48 * 01) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  sub [edx+duke3d.sprite+2A],ax
  mov word ptr [edx+duke3d.sprite+2A],03E7
  jmp return

healthB:
  jmp newmem
  nop
  nop
return:
registersymbol(healthB)

[DISABLE]

healthB:
  db 66 29 82 2A 48 * 01

unregistersymbol(healthB)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "duke3d.exe"+73C69

"duke3d.exe"+73C4E: CC                             -  int 3 
"duke3d.exe"+73C4F: CC                             -  int 3 
"duke3d.exe"+73C50: 55                             -  push ebp
"duke3d.exe"+73C51: 8B EC                          -  mov ebp,esp
"duke3d.exe"+73C53: 51                             -  push ecx
"duke3d.exe"+73C54: 53                             -  push ebx
"duke3d.exe"+73C55: 8B D9                          -  mov ebx,ecx
"duke3d.exe"+73C57: 0F BF 83 28 03 00 00           -  movsx eax,word ptr [ebx+00000328]
"duke3d.exe"+73C5E: 6B D0 2C                       -  imul edx,eax,2C
"duke3d.exe"+73C61: 66 0F BE 83 39 03 00 00        -  movsx ax,byte ptr [ebx+00000339]
// ---------- INJECTING HERE ----------
"duke3d.exe"+73C69: 66 29 82 2A 48 A7 01           -  sub [edx+duke3d.exe+C8482A],ax
// ---------- DONE INJECTING  ----------
"duke3d.exe"+73C70: 0F BF 83 28 03 00 00           -  movsx eax,word ptr [ebx+00000328]
"duke3d.exe"+73C77: 6B C0 2C                       -  imul eax,eax,2C
"duke3d.exe"+73C7A: 0F BF 88 2A 48 A7 01           -  movsx ecx,word ptr [eax+duke3d.exe+C8482A]
"duke3d.exe"+73C81: 0F BF 83 D6 02 00 00           -  movsx eax,word ptr [ebx+000002D6]
"duke3d.exe"+73C88: 2B C8                          -  sub ecx,eax
"duke3d.exe"+73C8A: 89 4D FC                       -  mov [ebp-04],ecx
"duke3d.exe"+73C8D: 0F 89 23 01 00 00              -  jns duke3d.exe+73DB6
"duke3d.exe"+73C93: 33 C0                          -  xor eax,eax
"duke3d.exe"+73C95: 56                             -  push esi
"duke3d.exe"+73C96: 66 89 83 38 03 00 00           -  mov [ebx+00000338],ax
}"""

[[cheat]]
id = "all-weapons"
name = "All Weapons"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
{ Game   : duke3d.exe
  Version: 
  Date   : 2017-04-04
  Author : Vovan

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(weaponsA,duke3d.exe,8A BC 31 CA 03 00 00) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov bh,[ecx+esi+000003CA]
  mov dword ptr [duke3d.exe+5FB97B],01010101 // RPG,Chaingun,Shotgun,Pistol
  mov dword ptr [duke3d.exe+5FB97F],01010101 //Mines,Devastator,Shrinker,Pipebombs
  mov dword ptr [duke3d.exe+5FB983],01010101 //Flame,Expander,Freezer
  jmp return

weaponsA:
  jmp newmem
  nop
  nop
return:
registersymbol(weaponsA)

[DISABLE]

weaponsA:
  db 8A BC 31 CA 03 00 00

unregistersymbol(weaponsA)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "duke3d.exe"+8A06F

"duke3d.exe"+8A04E: 8B 0F                    -  mov ecx,[edi]
"duke3d.exe"+8A050: 83 F9 05                 -  cmp ecx,05
"duke3d.exe"+8A053: 75 0E                    -  jne duke3d.exe+8A063
"duke3d.exe"+8A055: 66 83 BE FA 02 00 00 0A  -  cmp word ptr [esi+000002FA],0A
"duke3d.exe"+8A05D: 75 04                    -  jne duke3d.exe+8A063
"duke3d.exe"+8A05F: B3 01                    -  mov bl,01
"duke3d.exe"+8A061: EB 0C                    -  jmp duke3d.exe+8A06F
"duke3d.exe"+8A063: 0F BF 86 FA 02 00 00     -  movsx eax,word ptr [esi+000002FA]
"duke3d.exe"+8A06A: 3B C1                    -  cmp eax,ecx
"duke3d.exe"+8A06C: 0F 94 C3                 -  sete bl
// ---------- INJECTING HERE ----------
"duke3d.exe"+8A06F: 8A BC 31 CA 03 00 00     -  mov bh,[ecx+esi+000003CA]
// ---------- DONE INJECTING  ----------
"duke3d.exe"+8A076: 8D 41 01                 -  lea eax,[ecx+01]
"duke3d.exe"+8A079: 99                       -  cdq 
"duke3d.exe"+8A07A: B9 0A 00 00 00           -  mov ecx,0000000A
"duke3d.exe"+8A07F: F7 F9                    -  idiv ecx
"duke3d.exe"+8A081: 89 55 F0                 -  mov [ebp-10],edx
"duke3d.exe"+8A084: 84 DB                    -  test bl,bl
"duke3d.exe"+8A086: 74 09                    -  je duke3d.exe+8A091
"duke3d.exe"+8A088: C7 45 08 EE FF FF FF     -  mov [ebp+08],FFFFFFEE
"duke3d.exe"+8A08F: EB 12                    -  jmp duke3d.exe+8A0A3
"duke3d.exe"+8A091: 84 FF                    -  test bh,bh
}"""

[[cheat]]
id = "weap-rpg-chaingun-shotgun-pistol"
name = "Weap-RPG,Chaingun,Shotgun,Pistol"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 1
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb97b"
hops = []

[[cheat]]
id = "weap-mines-devastator-shrinker-pipebombs"
name = "Weap-Mines,Devastator,Shrinker,Pipebombs"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb97f"
hops = []

[[cheat]]
id = "weap-flame-expander-freezer"
name = "Weap-Flame,Expander,Freezer"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"
value = 100
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb983"
hops = []

[[cheat]]
id = "ammo"
name = "Ammo"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : duke3d.exe
  Version: 
  Date   : 2017-04-04
  Author : Vovan

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(ammoA,duke3d.exe,0F B7 00 50 E8 10 02 00 00) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  movzx eax,word ptr [eax]
  mov word ptr [duke3d.exe+5FB88C],03E7 // Pistol
  mov word ptr [duke3d.exe+5FB88E],03E7 // Shotgun
  mov word ptr [duke3d.exe+5FB890],03E7 // Chaingun
  mov word ptr [duke3d.exe+5FB892],03E7 // RPG
  mov word ptr [duke3d.exe+5FB898],03E7 // Devastator
  mov word ptr [duke3d.exe+5FB894],03E7 // Pipebombs
  mov word ptr [duke3d.exe+5FB896],03E7 // Shrinker
  mov word ptr [duke3d.exe+5FB8A0],03E7 // Expander
  mov word ptr [duke3d.exe+5FB89C],03E7 // Freezer
  mov word ptr [duke3d.exe+5FB89A],03E7 // Mines
  mov word ptr [duke3d.exe+5FB8A2],03E7 // Flame
  push eax
  call "duke3d.std::basic_ostream<char,std::char_traits<char> >::operator<<"
  jmp return

ammoA:
  jmp newmem
  nop
  nop
  nop
  nop
return:
registersymbol(ammoA)

[DISABLE]

ammoA:
  db 0F B7 00 50 E8 10 02 00 00

unregistersymbol(ammoA)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "duke3d.exe"+5F6D7

"duke3d.exe"+5F6C0: 85 C0              -  test eax,eax
"duke3d.exe"+5F6C2: 78 10              -  js duke3d.exe+5F6D4
"duke3d.exe"+5F6C4: 8B 55 10           -  mov edx,[ebp+10]
"duke3d.exe"+5F6C7: 50                 -  push eax
"duke3d.exe"+5F6C8: E8 53 04 00 00     -  call duke3d.exe+5FB20
"duke3d.exe"+5F6CD: 83 C4 04           -  add esp,04
"duke3d.exe"+5F6D0: 8B E5              -  mov esp,ebp
"duke3d.exe"+5F6D2: 5D                 -  pop ebp
"duke3d.exe"+5F6D3: C3                 -  ret 
"duke3d.exe"+5F6D4: 8B 45 10           -  mov eax,[ebp+10]
// ---------- INJECTING HERE ----------
"duke3d.exe"+5F6D7: 0F B7 00           -  movzx eax,word ptr [eax]
"duke3d.exe"+5F6DA: 50                 -  push eax
"duke3d.exe"+5F6DB: E8 10 02 00 00     -  call duke3d.exe+5F8F0
// ---------- DONE INJECTING  ----------
"duke3d.exe"+5F6E0: 8B E5              -  mov esp,ebp
"duke3d.exe"+5F6E2: 5D                 -  pop ebp
"duke3d.exe"+5F6E3: C3                 -  ret 
"duke3d.exe"+5F6E4: CC                 -  int 3 
"duke3d.exe"+5F6E5: CC                 -  int 3 
"duke3d.exe"+5F6E6: CC                 -  int 3 
"duke3d.exe"+5F6E7: CC                 -  int 3 
"duke3d.exe"+5F6E8: CC                 -  int 3 
"duke3d.exe"+5F6E9: CC                 -  int 3 
"duke3d.exe"+5F6EA: CC                 -  int 3 
}"""

[[cheat]]
id = "pistol"
name = "Pistol"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 36

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb88c"
hops = []

[[cheat]]
id = "shotgun"
name = "Shotgun"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb88e"
hops = []

[[cheat]]
id = "chaingun"
name = "Chaingun"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb890"
hops = []

[[cheat]]
id = "rpg"
name = "RPG"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb892"
hops = []

[[cheat]]
id = "devastator"
name = "Devastator"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb898"
hops = []

[[cheat]]
id = "pipebombs"
name = "Pipebombs"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb894"
hops = []

[[cheat]]
id = "shrinker"
name = "Shrinker"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb896"
hops = []

[[cheat]]
id = "expander"
name = "Expander"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb8a0"
hops = []

[[cheat]]
id = "freezer"
name = "Freezer"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb89c"
hops = []

[[cheat]]
id = "mines"
name = "Mines"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb89a"
hops = []

[[cheat]]
id = "flame"
name = "Flame"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb8a2"
hops = []

[[cheat]]
id = "inventory"
name = "Inventory"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : duke3d.exe
  Version: 
  Date   : 2017-04-04
  Author : Vovan

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(inventoryA,duke3d.exe,0F B7 86 80 03 00 00 66 85 C0 7E 4C) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  movzx eax,word ptr [esi+00000380]
  mov word ptr [duke3d.exe+5FB932],00C8 // Armor
  mov word ptr [duke3d.exe+5FB8D2],03E7 // Medkit
  mov word ptr [duke3d.exe+5FB92E],061A // Jetpack
  mov word ptr [duke3d.exe+5FB92C],1900 // Scuba
  mov word ptr [duke3d.exe+5FB8EC],04D0 // NightVis
  mov word ptr [duke3d.exe+5FB942],00CA // Boots
  mov word ptr [duke3d.exe+5FB8B4],0960 // HoloDuke
  cmp word ptr [duke3d.exe+5FB930],0000 // Check, if Steroids is 0
  jne return                            // If Steroids is not 0, exit
  mov word ptr [duke3d.exe+5FB930],0190 // If Steroids is 0, set value to 0190 (100%)
  jmp return

inventoryA:
  jmp newmem
  nop
  nop
return:
registersymbol(inventoryA)

[DISABLE]

inventoryA:
  db 0F B7 86 80 03 00 00

unregistersymbol(inventoryA)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "duke3d.exe"+7977E

"duke3d.exe"+7974A: C6 86 C8 03 00 00 00           -  mov byte ptr [esi+000003C8],00
"duke3d.exe"+79751: 66 89 96 88 03 00 00           -  mov [esi+00000388],dx
"duke3d.exe"+79758: 8B 86 80 02 00 00              -  mov eax,[esi+00000280]
"duke3d.exe"+7975E: 85 C0                          -  test eax,eax
"duke3d.exe"+79760: 7E 1C                          -  jle duke3d.exe+7977E
"duke3d.exe"+79762: 83 C0 FF                       -  add eax,-01
"duke3d.exe"+79765: 89 86 80 02 00 00              -  mov [esi+00000280],eax
"duke3d.exe"+7976B: 75 11                          -  jne duke3d.exe+7977E
"duke3d.exe"+7976D: C6 86 DD 03 00 00 01           -  mov byte ptr [esi+000003DD],01
"duke3d.exe"+79774: C7 86 80 02 00 00 09 03 00 00  -  mov [esi+00000280],00000309
// ---------- INJECTING HERE ----------
"duke3d.exe"+7977E: 0F B7 86 80 03 00 00           -  movzx eax,word ptr [esi+00000380]
// ---------- DONE INJECTING  ----------
"duke3d.exe"+79785: 66 85 C0                       -  test ax,ax
"duke3d.exe"+79788: 7E 4C                          -  jle duke3d.exe+797D6
"duke3d.exe"+7978A: B9 90 01 00 00                 -  mov ecx,00000190
"duke3d.exe"+7978F: 66 3B C1                       -  cmp ax,cx
"duke3d.exe"+79792: 7D 42                          -  jnl duke3d.exe+797D6
"duke3d.exe"+79794: 48                             -  dec eax
"duke3d.exe"+79795: 66 89 86 80 03 00 00           -  mov [esi+00000380],ax
"duke3d.exe"+7979C: 66 85 C0                       -  test ax,ax
"duke3d.exe"+7979F: 75 07                          -  jne duke3d.exe+797A8
"duke3d.exe"+797A1: 8B CE                          -  mov ecx,esi
}"""

[[cheat]]
id = "armor-00c8"
name = "Armor_00C8"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb932"
hops = []

[[cheat]]
id = "medkit-03e7"
name = "Medkit_03E7"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb8d2"
hops = []

[[cheat]]
id = "jetpack-0640"
name = "Jetpack_0640"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb92e"
hops = []

[[cheat]]
id = "steroids-0190"
name = "Steroids_0190"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb930"
hops = []

[[cheat]]
id = "scuba-1900"
name = "Scuba_1900"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb92c"
hops = []

[[cheat]]
id = "nightvis-04d0"
name = "NightVis_04D0"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb8ec"
hops = []

[[cheat]]
id = "holoduke-0960"
name = "HoloDuke_0960"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb8b4"
hops = []

[[cheat]]
id = "boots-00ca"
name = "Boots_00CA"
category = "resources"
description = ""
hint = ""
type = "value"
value_type = "i16"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb942"
hops = []

[[cheat]]
id = "all-keys"
name = "All Keys"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0x5fb8ce"
hops = []

[[cheat]]
id = "no-clipping-mode"
name = "No Clipping Mode"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0xedd6a7"
hops = []

[[cheat]]
id = "no-clipping-mode-2"
name = "No Clipping Mode"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 0
hex = true

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0xedd6a7"
hops = []

[[cheat]]
id = "god-mode"
name = "God Mode"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 255

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0xedd6a0"
hops = []

[[cheat]]
id = "god-mode-2"
name = "God Mode"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"
value = 255

[cheat.locator]
find = "static"
module = "duke3d.exe"
offset = "0xedd6a0"
hops = []
