[game]
name = "Need for Speed Unbound"
exe = "needforspeedunbound.exe"
notes = "Converted from a Cheat Engine table by Vinnie_Irish. Source: https://fearlessrevolution.com/viewtopic.php?t=22836"
verified = []
author = "Vinnie_Irish"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "cartoon-smokes"
name = "Cartoon Smokes"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version:
  Date   : 2022-12-10
  Author : Enthuse

  Script disables all cartoon smokes
}

[ENABLE]

aobscanmodule(Burnout,NeedForSpeedUnbound.exe,,0F 2E 00 74 0C 41 B0 01 48 8D 55 40 E8 F3)
aobscanmodule(Drifting,NeedForSpeedUnbound.exe,0F 2E 00 74 14 41 B0 01 48 8D 54 24 38 48 8D 8B 60)
aobscanmodule(Donut,NeedForSpeedUnbound.exe,38 02 74 0F 41 B0 01 48 8D 97 B9)

Burnout:
  db 90 90 90 74 0C

Drifting:
  db 90 90 90 74 14

Donut:
  db 90 90 74 0F 41 B0 01

registersymbol(Burnout)
registersymbol(Drifting)
registersymbol(Donut)


[DISABLE]

Burnout:
  db 0F 2E 00 74 0C

Drifting:
  db 0F 2E 00 74 14

Donut:
  db 38 02 74 0F 41 B0 01

unregistersymbol(Burnout)
unregistersymbol(Drifting)
unregistersymbol(Donut)"""

[[cheat]]
id = "cartoon-wings-while-airborne"
name = "Cartoon Wings While Airborne"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version: 
  Date   : 2022-12-10
  Author : Enthuse

  Disables wings when your car is mid-air
}

[ENABLE]

aobscanmodule(Cartoon_Wings,NeedForSpeedUnbound.exe,0F 2E 00 74 13 41 B0 01 48 8D 55 40 48 8D 8B D8) // should be unique

Cartoon_Wings:
  db 90 90 90 74 13

registersymbol(Cartoon_Wings)


[DISABLE]

Cartoon_Wings:
  db 0F 2E 00 74 13

unregistersymbol(Cartoon_Wings)"""

[[cheat]]
id = "trail-lights-and-air-lines"
name = "Trail Lights and Air Lines"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version: 
  Date   : 2022-12-18
  Author : Enthuse

  Disables Trail Lights and Air Lines

  Please be aware that this code is only executed when
  your speed is above 100mph / 160kmh
}

[ENABLE]


aobscanmodule(Trail_Lights,NeedForSpeedUnbound.exe,E8 13 5A AE 00) // should be unique

Trail_Lights:
  db 90 90 90 90 90

registersymbol(Trail_Lights)

[DISABLE]

Trail_Lights:
  db E8 13 5A AE 00

unregistersymbol(Trail_Lights)"""

[[cheat]]
id = "wheel-confetti"
name = "Wheel Confetti"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version: 
  Date   : 2022-12-17
  Author : Enthuse

  Disables Wheel Confetti
}

[ENABLE]
 
aobscanmodule(Grip_Turn,NeedForSpeedUnbound.exe,80 BF BC 06 00 00 00 74 2E)
aobscanmodule(Interact_Cop_NM,NeedForSpeedUnbound.exe,F6 87 BE 06 00 00 01 74 0E)
aobscanmodule(Interact_Cop_Death,NeedForSpeedUnbound.exe,F6 87 BE 06 00 00 02 74 0E)

Grip_Turn:
  db 90 90 90 90 90 90 90 74 2E

Interact_Cop_NM:
  db 90 90 90 90 90 90 90 74 0E

Interact_Cop_Death:
  db 90 90 90 90 90 90 90 74 0E

registersymbol(Grip_Turn)
registersymbol(Interact_Cop_NM)
registersymbol(Interact_Cop_Death)

[DISABLE]

Grip_Turn:
  db 80 BF BC 06 00 00 00 74 2E

Interact_Cop_NM:
  db F6 87 BE 06 00 00 01 74 0E

Interact_Cop_Death:
  db F6 87 BE 06 00 00 02 74 0E

unregistersymbol(Grip_Turn)
unregistersymbol(Interact_Cop_NM)
unregistersymbol(Interact_Cop_Death)"""

[[cheat]]
id = "cleaner-burst-nos-effect"
name = "Cleaner Burst Nos Effect"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version: 
  Date   : 2022-12-10
  Author : Enthuse

  Disables unnecessary effects related to burst nos.

  // Opcode for wings and logo above head needed (seperate codes)
}

[ENABLE]
aobscanmodule(SN_CarOutline,NeedForSpeedUnbound.exe,E8 73 91 FF FF 48 8B 46)
aobscanmodule(SN_CarMisc,NeedForSpeedUnbound.exe,E8 80 09 BD FF 84 DB)
aobscanmodule(SN_Level,NeedForSpeedUnbound.exe,8B 87 D4 08 00 00 48 8D 15)

SN_CarOutline:
  db 90 90 90 90 90

SN_CarMisc:
  db 90 90 90 90 90

SN_Level:
  db B8 01 00 00 00 90

registersymbol(SN_CarOutline)
registersymbol(SN_CarMisc)
registersymbol(SN_Level)

[DISABLE]

SN_CarOutline:
  db E8 73 91 FF FF

SN_CarMisc:
  db E8 80 09 BD FF

SN_Level:
  db 8B 87 D4 08 00 00

unregistersymbol(SN_CarOutline)
unregistersymbol(SN_CarMisc)
unregistersymbol(SN_Level)"""

[[cheat]]
id = "preview-sn-caroutline"
name = "Preview SN_CarOutline"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version: 
  Date   : 2022-12-17
  Author : Enthuse

  Preview SN_CarOutline
}

[ENABLE]
 
aobscanmodule(Preview_SN_CarOutline,NeedForSpeedUnbound.exe,0F B6 10 E8 73 91 FF FF)

Preview_SN_CarOutline:
  db 90 90 90 E8 73 91 FF FF

registersymbol(Preview_SN_CarOutline)

[DISABLE]

Preview_SN_CarOutline:
  db 0F B6 10 E8 73 91 FF FF

unregistersymbol(Preview_SN_CarOutline)"""

[[cheat]]
id = "preview-sn-carmisc"
name = "Preview SN_CarMisc"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version: 
  Date   : 2022-12-17
  Author : Enthuse

  Preview SN_CarMisc
}

[ENABLE]
 
aobscanmodule(Preview_SN_CarMisc,NeedForSpeedUnbound.exe,0F B6 D3 E8 80 09 BD FF)

Preview_SN_CarMisc:
  db 90 90 90 E8 80 09 BD FF

registersymbol(Preview_SN_CarMisc)

[DISABLE]

Preview_SN_CarMisc:
  db 0F B6 D3 E8 80 09 BD FF

unregistersymbol(Preview_SN_CarMisc)"""

[[cheat]]
id = "forces-level-1-burst-nos-effect"
name = "Forces Level 1 Burst Nos Effect"
category = "game"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version: 
  Date   : 2022-12-18
  Author : Enthuse

  Forces Level 1 Burst Nos Effect to be used so no wings are present.
}

[ENABLE]
 
aobscanmodule(SN_Level,NeedForSpeedUnbound.exe,8B 87 D4 08 00 00 48 8D 15)

SN_Level:
  db B8 01 00 00 00 90

registersymbol(SN_Level)

[DISABLE]

SN_Level:
  db 8B 87 D4 08 00 00

unregistersymbol(SN_Level)"""

[[cheat]]
id = "disables-electricity-element"
name = "Disables Electricity Element"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : NeedForSpeedUnbound.exe
  Version: 
  Date   : 2022-12-18
  Author : Enthuse

  Did not include this in the main 'Cleaner Burst Nos' script because I think it's a good
  way to tell what if you have your burst nos, you can toggle it on yourself.
}

[ENABLE]
 
aobscanmodule(Electricity,NeedForSpeedUnbound.exe,44 8B 87 D4 08 00 00 48 8D 8B)

Electricity:
  db 90 90 90 90 90 90 90

registersymbol(Electricity)

[DISABLE]

Electricity:
  db 44 8B 87 D4 08 00 00

unregistersymbol(Electricity)"""
