[game]
name = "Noita"
exe = "noita.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=10369"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "unlimited-health"
name = "Unlimited Health"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : noita.exe
  Version: 
  Date   : 2019-09-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(health,noita.exe,F3 0F 10 48 30) // should be unique
alloc(newmem,$1000)

label(code)
label(return)
label(playastruct)
registersymbol(playastruct)

newmem:
mov [playastruct], eax
movss xmm1,[eax+34]
movss [eax+30], xmm1
code:
// movss xmm1,[eax+30]
  jmp return
playastruct:
dd 0

health:
  jmp newmem
return:
registersymbol(health)

[DISABLE]

health:
  db F3 0F 10 48 30

unregistersymbol(health)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "noita.exe"+B2EBF4

"noita.exe"+B2EBCE: 33 C0                             -  xor eax,eax
"noita.exe"+B2EBD0: C7 84 24 C0 02 00 00 FF FF FF FF  -  mov [esp+000002C0],FFFFFFFF
"noita.exe"+B2EBDB: A3 C0 A6 76 01                    -  mov [noita.exe+136A6C0],eax
"noita.exe"+B2EBE0: FF 36                             -  push [esi]
"noita.exe"+B2EBE2: 8B C8                             -  mov ecx,eax
"noita.exe"+B2EBE4: E8 37 7C 52 FF                    -  call noita.exe+56820
"noita.exe"+B2EBE9: 8B C8                             -  mov ecx,eax
"noita.exe"+B2EBEB: E8 49 CE 50 FF                    -  call noita.exe+3BA39
"noita.exe"+B2EBF0: 85 C0                             -  test eax,eax
"noita.exe"+B2EBF2: 74 4D                             -  je noita.exe+B2EC41
// ---------- INJECTING HERE ----------
"noita.exe"+B2EBF4: F3 0F 10 48 30                    -  movss xmm1,[eax+30]
// ---------- DONE INJECTING  ----------
"noita.exe"+B2EBF9: F3 0F 10 05 68 64 71 01           -  movss xmm0,[noita.exe+1316468]
"noita.exe"+B2EC01: 0F 2F C1                          -  comiss xmm0,xmm1
"noita.exe"+B2EC04: 0F 97 C0                          -  seta al
"noita.exe"+B2EC07: 84 C0                             -  test al,al
"noita.exe"+B2EC09: 74 36                             -  je noita.exe+B2EC41
"noita.exe"+B2EC0B: F3 0F 5E C8                       -  divss xmm1,xmm0
"noita.exe"+B2EC0F: 8D 44 24 38                       -  lea eax,[esp+38]
"noita.exe"+B2EC13: 8D 4C 24 4C                       -  lea ecx,[esp+4C]
"noita.exe"+B2EC17: F3 0F 10 05 E0 1B 49 01           -  movss xmm0,[noita.exe+1091BE0]
"noita.exe"+B2EC1F: F3 0F 5C C1                       -  subss xmm0,xmm1
}"""

[[cheat]]
id = "easy-kills"
name = "Easy Kills"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
{ Game   : noita.exe
  Version: 
  Date   : 2019-09-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(easykills,noita.exe,F3 0F 5C C1 F3 0F 11 01 F3) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:
push ecx
sub ecx, 30
cmp [playastruct], ecx
pop ecx
je code
xorps xmm0,xmm0
subss xmm0,xmm1
movss [ecx],xmm0
code:
  jmp return

easykills:
  jmp newmem
  nop 3
return:
registersymbol(easykills)

[DISABLE]

easykills:
  db F3 0F 5C C1 F3 0F 11 01

unregistersymbol(easykills)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "noita.exe"+854516

"noita.exe"+8544E5: 8D 4C 24 78                       -  lea ecx,[esp+78]
"noita.exe"+8544E9: E8 B7 88 7C FF                    -  call noita.exe+1CDA5
"noita.exe"+8544EE: F3 0F 10 05 D8 C1 4C 01           -  movss xmm0,[noita.exe+10CC1D8]
"noita.exe"+8544F6: 8D 4E 30                          -  lea ecx,[esi+30]
"noita.exe"+8544F9: F3 0F 5E 05 F0 5C 71 01           -  divss xmm0,[noita.exe+1315CF0]
"noita.exe"+854501: 8B 44 24 48                       -  mov eax,[esp+48]
"noita.exe"+854505: F3 0F 11 46 30                    -  movss [esi+30],xmm0
"noita.exe"+85450A: FF 80 CC 00 00 00                 -  inc [eax+000000CC]
"noita.exe"+854510: EB 0C                             -  jmp noita.exe+85451E
"noita.exe"+854512: F3 0F 10 01                       -  movss xmm0,[ecx]
// ---------- INJECTING HERE ----------
"noita.exe"+854516: F3 0F 5C C1                       -  subss xmm0,xmm1
"noita.exe"+85451A: F3 0F 11 01                       -  movss [ecx],xmm0
// ---------- DONE INJECTING  ----------
"noita.exe"+85451E: F3 0F 10 46 34                    -  movss xmm0,[esi+34]
"noita.exe"+854523: 8D 46 34                          -  lea eax,[esi+34]
"noita.exe"+854526: 0F 2F 01                          -  comiss xmm0,[ecx]
"noita.exe"+854529: 0F 57 C9                          -  xorps xmm1,xmm1
"noita.exe"+85452C: 0F 47 C1                          -  cmova eax,ecx
"noita.exe"+85452F: F3 0F 10 00                       -  movss xmm0,[eax]
"noita.exe"+854533: 0F 2F C8                          -  comiss xmm1,xmm0
"noita.exe"+854536: F3 0F 11 46 30                    -  movss [esi+30],xmm0
"noita.exe"+85453B: 0F 82 8D 00 00 00                 -  jb noita.exe+8545CE
"noita.exe"+854541: 57                                -  push edi
}"""

[[cheat]]
id = "unlimited-mana"
name = "Unlimited Mana"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : noita.exe
  Version: 
  Date   : 2019-09-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(mana,noita.exe,F3 0F 10 46 70 8D) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:
movss xmm0,[esi+74]
movss [esi+70], xmm0
code:

  jmp return

mana:
  jmp newmem
return:
registersymbol(mana)

[DISABLE]

mana:
  db F3 0F 10 46 70

unregistersymbol(mana)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "noita.exe"+4AB031

"noita.exe"+4AB005: C7 85 04 FF FF FF 00 00 00 00  -  mov [ebp-000000FC],00000000
"noita.exe"+4AB00F: C7 44 24 04 00 00 00 00        -  mov [esp+04],00000000
"noita.exe"+4AB017: C7 04 24 00 00 80 3F           -  mov [esp],3F800000
"noita.exe"+4AB01E: 50                             -  push eax
"noita.exe"+4AB01F: 8D 85 44 FF FF FF              -  lea eax,[ebp-000000BC]
"noita.exe"+4AB025: 50                             -  push eax
"noita.exe"+4AB026: 8D 85 5C FF FF FF              -  lea eax,[ebp-000000A4]
"noita.exe"+4AB02C: 50                             -  push eax
"noita.exe"+4AB02D: 8D 45 A8                       -  lea eax,[ebp-58]
"noita.exe"+4AB030: 50                             -  push eax
// ---------- INJECTING HERE ----------
"noita.exe"+4AB031: F3 0F 10 46 70                 -  movss xmm0,[esi+70]
// ---------- DONE INJECTING  ----------
"noita.exe"+4AB036: 8D 85 54 FE FF FF              -  lea eax,[ebp-000001AC]
"noita.exe"+4AB03C: F3 0F 5E 46 74                 -  divss xmm0,[esi+74]
"noita.exe"+4AB041: 83 EC 18                       -  sub esp,18
"noita.exe"+4AB044: 8B CF                          -  mov ecx,edi
"noita.exe"+4AB046: C7 44 24 14 00 00 80 40        -  mov [esp+14],40800000
"noita.exe"+4AB04E: C7 44 24 10 00 00 20 42        -  mov [esp+10],42200000
"noita.exe"+4AB056: C7 44 24 0C 00 00 00 00        -  mov [esp+0C],00000000
"noita.exe"+4AB05E: C7 44 24 08 00 00 00 00        -  mov [esp+08],00000000
"noita.exe"+4AB066: C7 44 24 04 00 00 80 3F        -  mov [esp+04],3F800000
"noita.exe"+4AB06E: F3 0F 11 04 24                 -  movss [esp],xmm0
}"""

[[cheat]]
id = "unlimited-ammo"
name = "Unlimited Ammo"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : noita.exe
  Version: 
  Date   : 2019-09-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(ammo,noita.exe,89 85 FC FB FF FF 85) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:
mov [ebp-00000404],eax
test eax,eax
je code
mov [eax+4C], #9999
code:
  jmp return

ammo:
  jmp newmem
  nop
return:
registersymbol(ammo)

[DISABLE]

ammo:
  db 89 85 FC FB FF FF

unregistersymbol(ammo)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "noita.exe"+4A5078

"noita.exe"+4A5056: E8 10 31 BB FF        -  call noita.exe+5816B
"noita.exe"+4A505B: EB 02                 -  jmp noita.exe+4A505F
"noita.exe"+4A505D: 33 C0                 -  xor eax,eax
"noita.exe"+4A505F: C6 45 FC 09           -  mov byte ptr [ebp-04],09
"noita.exe"+4A5063: A3 C0 A6 76 01        -  mov [noita.exe+136A6C0],eax
"noita.exe"+4A5068: FF 36                 -  push [esi]
"noita.exe"+4A506A: 8B C8                 -  mov ecx,eax
"noita.exe"+4A506C: E8 AF 17 BB FF        -  call noita.exe+56820
"noita.exe"+4A5071: 8B C8                 -  mov ecx,eax
"noita.exe"+4A5073: E8 5B 35 B8 FF        -  call noita.exe+285D3
// ---------- INJECTING HERE ----------
"noita.exe"+4A5078: 89 85 FC FB FF FF     -  mov [ebp-00000404],eax
// ---------- DONE INJECTING  ----------
"noita.exe"+4A507E: 85 C0                 -  test eax,eax
"noita.exe"+4A5080: 74 5F                 -  je noita.exe+4A50E1
"noita.exe"+4A5082: 83 78 4C FF           -  cmp dword ptr [eax+4C],-01
"noita.exe"+4A5086: 7E 59                 -  jle noita.exe+4A50E1
"noita.exe"+4A5088: 50                    -  push eax
"noita.exe"+4A5089: E8 E0 7C B7 FF        -  call noita.exe+1CD6E
"noita.exe"+4A508E: 83 C4 04              -  add esp,04
"noita.exe"+4A5091: 84 C0                 -  test al,al
"noita.exe"+4A5093: 75 08                 -  jne noita.exe+4A509D
"noita.exe"+4A5095: 38 05 3E 67 71 01     -  cmp [noita.exe+131673E],al
}"""

[[cheat]]
id = "unlimited-oxygen"
name = "Unlimited Oxygen"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : noita.exe
  Version: 
  Date   : 2019-09-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(oxygen,noita.exe,F3 0F 10 86 94 00 00 00 0F 2F) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:
  movss xmm0,[esi+00000094]
  movss [esi+00000090], xmm0
code:

  jmp return

oxygen:
  jmp newmem
  nop 3
return:
registersymbol(oxygen)

[DISABLE]

oxygen:
  db F3 0F 10 86 94 00 00 00

unregistersymbol(oxygen)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "noita.exe"+4A9C70

"noita.exe"+4A9C47: A3 C0 A6 76 01                 -  mov [noita.exe+136A6C0],eax
"noita.exe"+4A9C4C: FF B5 D8 FE FF FF              -  push [ebp-00000128]
"noita.exe"+4A9C52: 8B C8                          -  mov ecx,eax
"noita.exe"+4A9C54: E8 C7 CB BA FF                 -  call noita.exe+56820
"noita.exe"+4A9C59: 8B C8                          -  mov ecx,eax
"noita.exe"+4A9C5B: E8 D9 1D B9 FF                 -  call noita.exe+3BA39
"noita.exe"+4A9C60: 8B F0                          -  mov esi,eax
"noita.exe"+4A9C62: 89 B5 F4 FE FF FF              -  mov [ebp-0000010C],esi
"noita.exe"+4A9C68: 85 F6                          -  test esi,esi
"noita.exe"+4A9C6A: 0F 84 EB 0C 00 00              -  je noita.exe+4AA95B
// ---------- INJECTING HERE ----------
"noita.exe"+4A9C70: F3 0F 10 86 94 00 00 00        -  movss xmm0,[esi+00000094]
// ---------- DONE INJECTING  ----------
"noita.exe"+4A9C78: 0F 2F 86 90 00 00 00           -  comiss xmm0,[esi+00000090]
"noita.exe"+4A9C7F: 0F 86 F5 05 00 00              -  jbe noita.exe+4AA27A
"noita.exe"+4A9C85: C7 85 FC FE FF FF 00 00 00 40  -  mov [ebp-00000104],40000000
"noita.exe"+4A9C8F: 8B CF                          -  mov ecx,edi
"noita.exe"+4A9C91: FF B5 FC FE FF FF              -  push [ebp-00000104]
"noita.exe"+4A9C97: C7 85 F8 FE FF FF 00 00 00 40  -  mov [ebp-00000108],40000000
"noita.exe"+4A9CA1: FF B5 F8 FE FF FF              -  push [ebp-00000108]
"noita.exe"+4A9CA7: C7 85 E8 FE FF FF 00 00 00 00  -  mov [ebp-00000118],00000000
"noita.exe"+4A9CB1: FF B5 E8 FE FF FF              -  push [ebp-00000118]
"noita.exe"+4A9CB7: C7 85 E4 FE FF FF 00 00 00 00  -  mov [ebp-0000011C],00000000
}"""

[[cheat]]
id = "unlimited-gold"
name = "Unlimited Gold"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : noita.exe
  Version: 
  Date   : 2019-09-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(gold,noita.exe,8B 4E 30 8D 46 30) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:
mov [esi+30], #99999999
code:
  mov ecx,[esi+30]
  lea eax,[esi+30]
  jmp return

gold:
  jmp newmem
  nop
return:
registersymbol(gold)

[DISABLE]

gold:
  db 8B 4E 30 8D 46 30

unregistersymbol(gold)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "noita.exe"+4AB5E2

"noita.exe"+4AB5C6: E8 4F 33 B8 FF                 -  call noita.exe+2E91A
"noita.exe"+4AB5CB: 8B 08                          -  mov ecx,[eax]
"noita.exe"+4AB5CD: B8 56 55 55 55                 -  mov eax,55555556
"noita.exe"+4AB5D2: F7 E9                          -  imul ecx
"noita.exe"+4AB5D4: 8B C2                          -  mov eax,edx
"noita.exe"+4AB5D6: C1 E8 1F                       -  shr eax,1F
"noita.exe"+4AB5D9: 03 C2                          -  add eax,edx
"noita.exe"+4AB5DB: 8D 04 40                       -  lea eax,[eax+eax*2]
"noita.exe"+4AB5DE: 2B C8                          -  sub ecx,eax
"noita.exe"+4AB5E0: 75 74                          -  jne noita.exe+4AB656
// ---------- INJECTING HERE ----------
"noita.exe"+4AB5E2: 8B 4E 30                       -  mov ecx,[esi+30]
"noita.exe"+4AB5E5: 8D 46 30                       -  lea eax,[esi+30]
// ---------- DONE INJECTING  ----------
"noita.exe"+4AB5E8: 89 85 E0 FE FF FF              -  mov [ebp-00000120],eax
"noita.exe"+4AB5EE: 8B 85 D0 FE FF FF              -  mov eax,[ebp-00000130]
"noita.exe"+4AB5F4: 8B 70 34                       -  mov esi,[eax+34]
"noita.exe"+4AB5F7: 3B CE                          -  cmp ecx,esi
"noita.exe"+4AB5F9: 0F 8E EA 06 00 00              -  jng noita.exe+4ABCE9
"noita.exe"+4AB5FF: 2B CE                          -  sub ecx,esi
"noita.exe"+4AB601: C7 85 FC FE FF FF 01 00 00 00  -  mov [ebp-00000104],00000001
"noita.exe"+4AB60B: 8B C1                          -  mov eax,ecx
"noita.exe"+4AB60D: 8D 8D 04 FF FF FF              -  lea ecx,[ebp-000000FC]
"noita.exe"+4AB613: 99                             -  cdq 
}"""

[[cheat]]
id = "unlimited-hover"
name = "Unlimited Hover"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : noita.exe
  Version: 
  Date   : 2019-09-26
  Author : STN

  This script does blah blah blah
}

[ENABLE]

aobscanmodule(jetpack,noita.exe,F3 0F 11 81 F0 00 00 00 0F) // should be unique

jetpack:
  nop
  nop
  nop
  nop
  nop
  nop
  nop
  nop
registersymbol(jetpack)

[DISABLE]

jetpack:
  db F3 0F 11 81 F0 00 00 00

unregistersymbol(jetpack)

{
// ORIGINAL CODE - INJECTION POINT: "noita.exe"+88A7BB

"noita.exe"+88A799: 0F 2F C2                          -  comiss xmm0,xmm2
"noita.exe"+88A79C: 76 25                             -  jna noita.exe+88A7C3
"noita.exe"+88A79E: 84 C0                             -  test al,al
"noita.exe"+88A7A0: 74 21                             -  je noita.exe+88A7C3
"noita.exe"+88A7A2: 80 B9 84 00 00 00 00              -  cmp byte ptr [ecx+00000084],00
"noita.exe"+88A7A9: 74 18                             -  je noita.exe+88A7C3
"noita.exe"+88A7AB: 80 7C 24 58 00                    -  cmp byte ptr [esp+58],00
"noita.exe"+88A7B0: 75 11                             -  jne noita.exe+88A7C3
"noita.exe"+88A7B2: 8B 44 24 1C                       -  mov eax,[esp+1C]
"noita.exe"+88A7B6: F3 0F 5C 40 24                    -  subss xmm0,[eax+24]
// ---------- INJECTING HERE ----------
"noita.exe"+88A7BB: F3 0F 11 81 F0 00 00 00           -  movss [ecx+000000F0],xmm0
// ---------- DONE INJECTING  ----------
"noita.exe"+88A7C3: 0F B6 44 24 2C                    -  movzx eax,byte ptr [esp+2C]
"noita.exe"+88A7C8: 89 44 24 78                       -  mov [esp+78],eax
"noita.exe"+88A7CC: 39 87 1C 01 00 00                 -  cmp [edi+0000011C],eax
"noita.exe"+88A7D2: 74 5A                             -  je noita.exe+88A82E
"noita.exe"+88A7D4: 68 8C C0 4A 01                    -  push noita.exe+10AC08C
"noita.exe"+88A7D9: 8D 8C 24 AC 00 00 00              -  lea ecx,[esp+000000AC]
"noita.exe"+88A7E0: E8 97 D0 79 FF                    -  call noita.exe+2787C
"noita.exe"+88A7E5: C7 84 24 E8 00 00 00 01 00 00 00  -  mov [esp+000000E8],00000001
"noita.exe"+88A7F0: 8D 84 24 A8 00 00 00              -  lea eax,[esp+000000A8]
"noita.exe"+88A7F7: FF 74 24 2C                       -  push [esp+2C]
}"""
