[game]
name = "Pardon My French Toast"
exe = "pardon my french toast.exe"
notes = "Converted from a Cheat Engine table by Firstlast2s100. Source: https://fearlessrevolution.com/viewtopic.php?t=37851"
verified = []
author = "Firstlast2s100"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "pmftcharacterez"
name = "PMFTCharacterEZ"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
{ Game   : Pardon My French Toast.exe
  Version: 
  Date   : 2026-01-06
  Author : DANGER DASH

  This script does blah blah blah
}

define(address,PMFTCharacterEZ:OnUpdate)
define(bytes,55 48 8B EC 48 83 EC 30)

[ENABLE]

assert(address,bytes)
alloc(newmem,$1000,PMFTCharacterEZ:OnUpdate)

label(code)
label(return)

newmem:
mov [pmftcharacterez_ptr],rcx

code:
  push rbp
  mov rbp,rsp
  sub rsp,30
  jmp return

pmftcharacterez_ptr:
dq 0

address:
  jmp newmem
  nop 3
return:
registersymbol(pmftcharacterez_ptr)

[DISABLE]

address:
  db bytes
  // push rbp
  // mov rbp,rsp
  // sub rsp,30

dealloc(newmem)
unregistersymbol(pmftcharacterez_ptr)

{
// ORIGINAL CODE - INJECTION POINT: PMFTCharacterEZ:OnUpdate

1F0530E8AE8: 01 04 02                       - add [rdx+rax],eax
1F0530E8AEB: 05 04 03 01 50                 - add eax,50010304
1F0530E8AF0: 00 00                          - add [rax],al
1F0530E8AF2: 00 00                          - add [rax],al
1F0530E8AF4: 00 00                          - add [rax],al
1F0530E8AF6: 00 00                          - add [rax],al
1F0530E8AF8: 00 00                          - add [rax],al
1F0530E8AFA: 00 00                          - add [rax],al
1F0530E8AFC: 00 00                          - add [rax],al
1F0530E8AFE: 00 00                          - add [rax],al
// ---------- INJECTING HERE ----------
PMFTCharacterEZ:OnUpdate: 55                             - push rbp
// ---------- DONE INJECTING  ----------
PMFTCharacterEZ:OnUpdate+1: 48 8B EC                       - mov rbp,rsp
PMFTCharacterEZ:OnUpdate+4: 48 83 EC 30                    - sub rsp,30
PMFTCharacterEZ:OnUpdate+8: 48 89 75 F8                    - mov [rbp-08],rsi
PMFTCharacterEZ:OnUpdate+c: 48 8B F1                       - mov rsi,rcx
PMFTCharacterEZ:OnUpdate+f: 48 8D AD 00 00 00 00           - lea rbp,[rbp+00000000]
PMFTCharacterEZ:OnUpdate+16: 49 BB B0 8B 0E 53 F0 01 00 00  - mov r11,EasyCharacterMovement.Character:OnUpdate
PMFTCharacterEZ:OnUpdate+20: 41 FF D3                       - call r11
PMFTCharacterEZ:OnUpdate+23: 48 8B CE                       - mov rcx,rsi
PMFTCharacterEZ:OnUpdate+26: 49 BB 80 A6 0E 53 F0 01 00 00  - mov r11,PMFTCharacterEZ:CheckGroundSurface
PMFTCharacterEZ:OnUpdate+30: 41 FF D3                       - call r11
}"""
