[game]
name = "Sanctum 2 Road to Elysion"
exe = "sanctumgame-win32-shipping.exe"
notes = "Converted from a Cheat Engine table by ModEngine. Source: https://fearlessrevolution.com/viewtopic.php?t=24244"
verified = []
author = "ModEngine"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "inf-ammo"
name = "Inf.Ammo"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : SanctumGame-Win32-Shipping.exe
  Version: 
  Date   : 2016-10-13
  Author : 

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscanmodule(ammo,SanctumGame-Win32-Shipping.exe,8B 44 24 10 01 03) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:


mov eax,ebx
sub eax,[esp+60]

cmp eax,624
jne @f
cmp [esp+10],0
jng @f
cmp [esp+10],1
jne @f
//cmp [ebx+4],a
//jne @f
mov [esp+10],0
mov [ebx-4],0
mov [ebx],0

@@:
  mov eax,[esp+10]
  add [ebx],eax
  jmp return

ammo:
  jmp code
  nop
return:
registersymbol(ammo)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
ammo:
  db 8B 44 24 10 01 03

unregistersymbol(ammo)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "SanctumGame-Win32-Shipping.exe"+529CD

"SanctumGame-Win32-Shipping.exe"+529B2: FF 46 18                       -  inc [esi+18]
"SanctumGame-Win32-Shipping.exe"+529B5: 8B 46 18                       -  mov eax,[esi+18]
"SanctumGame-Win32-Shipping.exe"+529B8: 80 38 41                       -  cmp byte ptr [eax],41
"SanctumGame-Win32-Shipping.exe"+529BB: 75 10                          -  jne SanctumGame-Win32-Shipping.exe+529CD
"SanctumGame-Win32-Shipping.exe"+529BD: 8B 4E 14                       -  mov ecx,[esi+14]
"SanctumGame-Win32-Shipping.exe"+529C0: 6A 00                          -  push 00
"SanctumGame-Win32-Shipping.exe"+529C2: 40                             -  inc eax
"SanctumGame-Win32-Shipping.exe"+529C3: 56                             -  push esi
"SanctumGame-Win32-Shipping.exe"+529C4: 89 46 18                       -  mov [esi+18],eax
"SanctumGame-Win32-Shipping.exe"+529C7: FF 15 B4 01 53 03              -  call dword ptr [SanctumGame-Win32-Shipping.exe+25F01B4]
// ---------- INJECTING HERE ----------
"SanctumGame-Win32-Shipping.exe"+529CD: 8B 44 24 10                    -  mov eax,[esp+10]
"SanctumGame-Win32-Shipping.exe"+529D1: 01 03                          -  add [ebx],eax
// ---------- DONE INJECTING  ----------
"SanctumGame-Win32-Shipping.exe"+529D3: 8B 1B                          -  mov ebx,[ebx]
"SanctumGame-Win32-Shipping.exe"+529D5: 8B 4C 24 14                    -  mov ecx,[esp+14]
"SanctumGame-Win32-Shipping.exe"+529D9: 5E                             -  pop esi
"SanctumGame-Win32-Shipping.exe"+529DA: 89 19                          -  mov [ecx],ebx
"SanctumGame-Win32-Shipping.exe"+529DC: 5B                             -  pop ebx
"SanctumGame-Win32-Shipping.exe"+529DD: 59                             -  pop ecx
"SanctumGame-Win32-Shipping.exe"+529DE: C2 08 00                       -  ret 0008
"SanctumGame-Win32-Shipping.exe"+529E1: CC                             -  int 3 
"SanctumGame-Win32-Shipping.exe"+529E2: CC                             -  int 3 
"SanctumGame-Win32-Shipping.exe"+529E3: CC                             -  int 3 
}"""

[[cheat]]
id = "inf-construction-resources"
name = "Inf.Construction Resources"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
{ Game   : SanctumGame-Win32-Shipping.exe
  Version: 
  Date   : 2016-10-13
  Author : 

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscanmodule(resources,SanctumGame-Win32-Shipping.exe,8B 10 8B 92 2C 01 00 00 51) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:
//3ec , 4 credit
code:
mov edx,[eax+3ec]
cmp edx,100000
jna @f
mov [edx+4],#9999999
mov [edx+8],#999

@@:
  mov edx,[eax]
  mov edx,[edx+0000012C]
  jmp return

resources:
  jmp code
  nop
  nop
  nop
return:
registersymbol(resources)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
resources:
  db 8B 10 8B 92 2C 01 00 00

unregistersymbol(resources)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "SanctumGame-Win32-Shipping.exe"+6A27BD

"SanctumGame-Win32-Shipping.exe"+6A2792: 85 C0                 -  test eax,eax
"SanctumGame-Win32-Shipping.exe"+6A2794: 0F 85 FD FE FF FF     -  jne SanctumGame-Win32-Shipping.exe+6A2697
"SanctumGame-Win32-Shipping.exe"+6A279A: 8B 0D 70 9F 5D 03     -  mov ecx,[SanctumGame-Win32-Shipping.exe+2699F70]
"SanctumGame-Win32-Shipping.exe"+6A27A0: E8 EB E3 16 00        -  call SanctumGame-Win32-Shipping.exe+810B90
"SanctumGame-Win32-Shipping.exe"+6A27A5: 85 C0                 -  test eax,eax
"SanctumGame-Win32-Shipping.exe"+6A27A7: 74 2B                 -  je SanctumGame-Win32-Shipping.exe+6A27D4
"SanctumGame-Win32-Shipping.exe"+6A27A9: 8B 0D 70 9F 5D 03     -  mov ecx,[SanctumGame-Win32-Shipping.exe+2699F70]
"SanctumGame-Win32-Shipping.exe"+6A27AF: E8 DC E3 16 00        -  call SanctumGame-Win32-Shipping.exe+810B90
"SanctumGame-Win32-Shipping.exe"+6A27B4: 8B 4E 04              -  mov ecx,[esi+04]
"SanctumGame-Win32-Shipping.exe"+6A27B7: 8B 89 DC 01 00 00     -  mov ecx,[ecx+000001DC]
// ---------- INJECTING HERE ----------
"SanctumGame-Win32-Shipping.exe"+6A27BD: 8B 10                 -  mov edx,[eax]
"SanctumGame-Win32-Shipping.exe"+6A27BF: 8B 92 2C 01 00 00     -  mov edx,[edx+0000012C]
// ---------- DONE INJECTING  ----------
"SanctumGame-Win32-Shipping.exe"+6A27C5: 51                    -  push ecx
"SanctumGame-Win32-Shipping.exe"+6A27C6: 55                    -  push ebp
"SanctumGame-Win32-Shipping.exe"+6A27C7: 57                    -  push edi
"SanctumGame-Win32-Shipping.exe"+6A27C8: 8B C8                 -  mov ecx,eax
"SanctumGame-Win32-Shipping.exe"+6A27CA: FF D2                 -  call edx
"SanctumGame-Win32-Shipping.exe"+6A27CC: 85 C0                 -  test eax,eax
"SanctumGame-Win32-Shipping.exe"+6A27CE: 0F 85 C3 FE FF FF     -  jne SanctumGame-Win32-Shipping.exe+6A2697
"SanctumGame-Win32-Shipping.exe"+6A27D4: 8B 46 04              -  mov eax,[esi+04]
"SanctumGame-Win32-Shipping.exe"+6A27D7: 83 B8 44 04 00 00 00  -  cmp dword ptr [eax+00000444],00
"SanctumGame-Win32-Shipping.exe"+6A27DE: 74 21                 -  je SanctumGame-Win32-Shipping.exe+6A2801
}"""

[[cheat]]
id = "inf-core-health"
name = "Inf.Core Health"
category = "player"
description = ""
hint = ""
type = "script"
source = """
{ Game   : SanctumGame-Win32-Shipping.exe
  Version: 
  Date   : 2016-10-13
  Author : 

  This script does blah blah blah
}

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

 
 
aobscanmodule(corehealth,SanctumGame-Win32-Shipping.exe,8B 54 24 04 89 0A C2 14 00 8B) // should be unique
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:

  mov edx,[esp+04]
sub edx,[esp+28]

cmp edx,23c
mov edx,[esp+04]
jne @f

mov ecx,#9999


  @@:
  mov [edx],ecx
  jmp return

corehealth:
  jmp code
  nop
return:
registersymbol(corehealth)

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
corehealth:
  db 8B 54 24 04 89 0A

unregistersymbol(corehealth)
dealloc(newmem)

{
// ORIGINAL CODE - INJECTION POINT: "SanctumGame-Win32-Shipping.exe"+D7A2E

"SanctumGame-Win32-Shipping.exe"+D7A14: 8B 08              -  mov ecx,[eax]
"SanctumGame-Win32-Shipping.exe"+D7A16: 8B 54 24 04        -  mov edx,[esp+04]
"SanctumGame-Win32-Shipping.exe"+D7A1A: 89 0A              -  mov [edx],ecx
"SanctumGame-Win32-Shipping.exe"+D7A1C: C2 14 00           -  ret 0014
"SanctumGame-Win32-Shipping.exe"+D7A1F: CC                 -  int 3 
"SanctumGame-Win32-Shipping.exe"+D7A20: 8B 41 40           -  mov eax,[ecx+40]
"SanctumGame-Win32-Shipping.exe"+D7A23: 83 F8 01           -  cmp eax,01
"SanctumGame-Win32-Shipping.exe"+D7A26: 75 0F              -  jne SanctumGame-Win32-Shipping.exe+D7A37
"SanctumGame-Win32-Shipping.exe"+D7A28: 8B 44 24 08        -  mov eax,[esp+08]
"SanctumGame-Win32-Shipping.exe"+D7A2C: 8B 08              -  mov ecx,[eax]
// ---------- INJECTING HERE ----------
"SanctumGame-Win32-Shipping.exe"+D7A2E: 8B 54 24 04        -  mov edx,[esp+04]
"SanctumGame-Win32-Shipping.exe"+D7A32: 89 0A              -  mov [edx],ecx
// ---------- DONE INJECTING  ----------
"SanctumGame-Win32-Shipping.exe"+D7A34: C2 14 00           -  ret 0014
"SanctumGame-Win32-Shipping.exe"+D7A37: 8B 49 44           -  mov ecx,[ecx+44]
"SanctumGame-Win32-Shipping.exe"+D7A3A: 8B 54 24 08        -  mov edx,[esp+08]
"SanctumGame-Win32-Shipping.exe"+D7A3E: 0F AF C8           -  imul ecx,eax
"SanctumGame-Win32-Shipping.exe"+D7A41: 8B 44 24 04        -  mov eax,[esp+04]
"SanctumGame-Win32-Shipping.exe"+D7A45: 51                 -  push ecx
"SanctumGame-Win32-Shipping.exe"+D7A46: 52                 -  push edx
"SanctumGame-Win32-Shipping.exe"+D7A47: 50                 -  push eax
"SanctumGame-Win32-Shipping.exe"+D7A48: E8 3F 5C 9B 01     -  call SanctumGame-Win32-Shipping.exe+1A8D68C
"SanctumGame-Win32-Shipping.exe"+D7A4D: 83 C4 0C           -  add esp,0C
}"""
