[game]
name = "Hand of Fate"
exe = "hand_of_fate.exe"
notes = "Converted from a Cheat Engine table by STN. Source: https://fearlessrevolution.com/viewtopic.php?t=1824"
verified = []
author = "STN"

[meta]
source = "community"
submitted_by = ""
checked_at = ""
checked_build = ""

[[cheat]]
id = "invulnerability"
name = "Invulnerability"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(invuln4,D9 9F A8 00 00 00 D9 87)
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  fstp st(0)
  mov eax,[edi+3C]
  fld dword ptr [eax+8]
  fstp dword ptr [edi+000000A8]
  jmp return

invuln4:
  jmp code
  nop
return:
registersymbol(invuln4)

[DISABLE]
invuln4:
  db D9 9F A8 00 00 00
unregistersymbol(invuln4)
dealloc(newmem)"""

[[cheat]]
id = "always-have-100-food"
name = "Always Have 100 Food"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(food,8B 89 AC 00 00 00 3B)
alloc(newmem,$1000)

label(code)
label(return)

newmem:
  cmp [ecx+000000AC],#100
  jnl code
  mov [ecx+000000AC],#100

code:
  mov ecx,[ecx+000000AC]
  jmp return

food:
  jmp newmem
  nop
return:
registersymbol(food)

[DISABLE]
food:
  db 8B 89 AC 00 00 00
unregistersymbol(food)
dealloc(newmem)"""

[[cheat]]
id = "always-have-9-999-gold"
name = "Always Have 9,999 Gold"
category = "resources"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(gold,8B 89 B0 00 00 00 3B)
alloc(newmem,$1000)

label(code)
label(return)

newmem:
  cmp [ecx+000000B0],#9999
  jnl code
  mov [ecx+000000B0],#9999

code:
  mov ecx,[ecx+000000B0]
  jmp return

gold:
  jmp newmem
  nop
return:
registersymbol(gold)

[DISABLE]
gold:
  db 8B 89 B0 00 00 00
unregistersymbol(gold)
dealloc(newmem)"""

[[cheat]]
id = "always-have-huge-success-must-first-move-over-a-new-card"
name = "Always Have Huge Success (must first move over a new card)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(success,8B 45 0C 8B 40 14 89 45 F0)
success:
  db B8 01 00 00 00 90
registersymbol(success)

[DISABLE]
success:
  db 8B 45 0C 8B 40 14
unregistersymbol(success)"""

[[cheat]]
id = "unlimited-artifact-use"
name = "Unlimited Artifact Use"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(artifact,8B 48 2C 49 89 48 2C)
artifact+3:
  db 90
registersymbol(artifact)

[DISABLE]
artifact+3:
  db 49
unregistersymbol(artifact)"""

[[cheat]]
id = "no-cooldowns"
name = "No Cooldowns"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(cooldown,D9 40 2C DD 5D F0)
cooldown:
  db D9 EE 90
registersymbol(cooldown)

[DISABLE]
cooldown:
  db D9 40 2C
unregistersymbol(cooldown)"""

[[cheat]]
id = "player-is-dead"
name = "Player Is Dead"
category = "player"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(isdead,D9 40 48 D9 EE)
alloc(newmem,$1000)

label(code)
label(return)

newmem:
  cmp [eax+30],0
  je code
  fldz
  fldz
  jmp return

code:
  fld dword ptr [eax+48]
  fldz 
  jmp return

isdead:
  jmp newmem
return:
registersymbol(isdead)

[DISABLE]
isdead:
  db D9 40 48 D9 EE
unregistersymbol(isdead)
dealloc(newmem)"""

[[cheat]]
id = "player-pointers"
name = "Player Pointers"
category = "player"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(pointers,D9 80 A8 00 00 00 D9 5D F4 D9 45 F4 83) // should be unique
alloc(newmem,$1000)

label(code)
label(return)
label(stats)

newmem:

stats:
  db 00 00 00 00

code:
  mov [stats],eax
  fld dword ptr [eax+000000A8]
  jmp return

pointers:
  jmp code
  nop
return:
registersymbol(pointers)
registersymbol(stats)

[DISABLE]
pointers:
  db D9 80 A8 00 00 00
unregistersymbol(pointers)
unregistersymbol(stats)
dealloc(newmem)"""

[[cheat]]
id = "base-don-t-touch"
name = "Base (Don't Touch)"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "stats"
hops = []

[[cheat]]
id = "health"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "stats"
hops = ["+0xa8"]

[[cheat]]
id = "max-health"
name = "Max Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "stats"
hops = [
    "+0x3c",
    "+0x8",
]

[[cheat]]
id = "food"
name = "Food"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "stats"
hops = ["+0xac"]

[[cheat]]
id = "gold"
name = "Gold"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "stats"
hops = ["+0xb0"]

[[cheat]]
id = "combat-hacks-must-first-enter-combat"
name = "Combat Hacks (must first enter combat)"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(combat,83 C4 10 89 45 DC 8B 05 * * * * 8B C8)
alloc(newmem,$1000)

label(code)
label(return)
label(player)
label(invuln)

newmem:

player:
  db 00 00 00 00

invuln:
  db 00 00 00 00

code:
  add esp,10
  mov [ebp-24],eax
  // new code
  mov [player],eax
  cmp [invuln],1
  jne return
  mov eax,[eax+1C]
  mov [eax+44],1
  jmp return

combat:
  jmp code
  nop
return:
registersymbol(combat)
registersymbol(player)
registersymbol(invuln)

[DISABLE]
combat:
  db 83 C4 10 89 45 DC
unregistersymbol(combat)
unregistersymbol(player)
unregistersymbol(invuln)
dealloc(newmem)"""

[[cheat]]
id = "base-don-t-touch-2"
name = "Base (don't touch)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "player"
hops = ["+0x0"]

[[cheat]]
id = "is-invulnerable-0-1"
name = "Is Invulnerable (0/1)"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "player"
hops = [
    "+0x1c",
    "+0x44",
]

[[cheat]]
id = "current-health"
name = "Current Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "player"
hops = [
    "+0x1c",
    "+0x48",
]

[[cheat]]
id = "maximum-health"
name = "Maximum Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "player"
hops = [
    "+0x1c",
    "+0x4c",
]

[[cheat]]
id = "yet-another-invulnerability"
name = "Yet Another Invulnerability"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
invuln:
db 1

[DISABLE]
invuln:
db 0"""

[[cheat]]
id = "invulnerability-2-activates-after-you-re-hit-once"
name = "Invulnerability 2 (activates after you're hit once)"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(invuln2,8B 45 08 0F B6 40 51)
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  mov eax,[ebp+08]
  mov [eax+44],1
  push [eax+4C]
  pop [eax+48]
  movzx eax,byte ptr [eax+51]
  jmp return

invuln2:
  jmp code
  nop
  nop
return:
registersymbol(invuln2)

[DISABLE]
invuln2:
  db 8B 45 08 0F B6 40 51
unregistersymbol(invuln2)
dealloc(newmem)"""

[[cheat]]
id = "invulnerability-3-must-first-enter-combat"
name = "Invulnerability 3 (must first enter combat)"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(invuln3,D9 80 A8 00 00 00 D9 5D FC D9 45 FC 8B 45 08 D9 58 48)
alloc(newmem,$1000)

label(code)
label(return)

newmem:

code:
  push eax
  mov eax,[ebp+08]
  fld dword ptr [eax+4C]
  pop eax
  fst dword ptr [eax+000000A8]
  jmp return

invuln3:
  jmp code
  nop
return:
registersymbol(invuln3)

[DISABLE]
invuln3:
  db D9 80 A8 00 00 00
unregistersymbol(invuln3)
dealloc(newmem)"""

[[cheat]]
id = "destroyable-pointer"
name = "Destroyable Pointer"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(Destroyable_ptr,4)
registersymbol(Destroyable_ptr)
[DISABLE]
dealloc(Destroyable_ptr)
unregistersymbol(Destroyable_ptr)"""

[[cheat]]
id = "no-description"
name = "No description"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "Destroyable_ptr"
hops = []

[[cheat]]
id = "hide-model-on-destroy"
name = "Hide Model On Destroy"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "Destroyable_ptr"
hops = ["+0x40"]

[[cheat]]
id = "invulnerable"
name = "Invulnerable"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Destroyable_ptr"
hops = ["+0x44"]

[[cheat]]
id = "force-killed"
name = "Force Killed"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "Destroyable_ptr"
hops = ["+0x51"]

[[cheat]]
id = "health-2"
name = "Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "Destroyable_ptr"
hops = ["+0x48"]

[[cheat]]
id = "on-damage"
name = "On Damage"
category = "combat"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "Destroyable_ptr"
hops = ["+0x30"]

[[cheat]]
id = "targetable"
name = "Targetable"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(Targetable,4)
Targetable:
  db 00 00 00 00
registersymbol(Targetable)
[DISABLE]
dealloc(Targetable)
unregistersymbol(Targetable)"""

[[cheat]]
id = "pointer"
name = "Pointer"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "Targetable"
hops = []

[[cheat]]
id = "hidden"
name = "Hidden"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "u8"

[cheat.locator]
find = "symbol"
symbol = "Targetable"
hops = ["+0x28"]

[[cheat]]
id = "invulnerable-2"
name = "Invulnerable"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Targetable"
hops = [
    "+0x1c",
    "+0x44",
]

[[cheat]]
id = "current-health-2"
name = "Current Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"

[cheat.locator]
find = "symbol"
symbol = "Targetable"
hops = [
    "+0x1c",
    "+0x48",
]

[[cheat]]
id = "maximum-health-2"
name = "Maximum Health"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "f32"
value = 9999.0

[cheat.locator]
find = "symbol"
symbol = "Targetable"
hops = [
    "+0x1c",
    "+0x4c",
]

[[cheat]]
id = "team"
name = "Team"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Targetable"
hops = ["+0x20"]

[[cheat]]
id = "current-team"
name = "Current Team"
category = "misc"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "Targetable"
hops = ["+0x2c"]

[[cheat]]
id = "one-hit-kill"
name = "One Hit Kill"
category = "combat"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(onehit,D9 47 48 D9 45 10 DE E9)
alloc(newmem,$1000)

label(code)
label(return)

newmem:
  jmp code // skip hack
  cmp edi,[player]
  je code
  fldz
  jmp return

code:
  fld dword ptr [edi+48]
  fld dword ptr [ebp+10]
  fsubp st(1),st(0)
  jmp return

onehit:
  jmp newmem
  nop
  nop
  nop
return:
registersymbol(onehit)

[DISABLE]
onehit:
  db D9 47 48 D9 45 10 DE E9
unregistersymbol(onehit)
dealloc(newmem)"""

[[cheat]]
id = "card-manager-pointer"
name = "Card Manager Pointer"
category = "player"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(CardManager_ptr, 4)
registersymbol(CardManager_ptr)
[DISABLE]
dealloc(CardManager_ptr, 4)
unregistersymbol(CardManager_ptr)"""

[[cheat]]
id = "base"
name = "Base"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "CardManager_ptr"
hops = []

[[cheat]]
id = "success-card"
name = "Success Card"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "CardManager_ptr"
hops = ["+0x24"]

[[cheat]]
id = "huge-success-card"
name = "Huge Success Card"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "CardManager_ptr"
hops = ["+0x28"]

[[cheat]]
id = "failure-card"
name = "Failure Card"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "CardManager_ptr"
hops = ["+0x2c"]

[[cheat]]
id = "huge-failure-card"
name = "Huge Failure Card"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "CardManager_ptr"
hops = ["+0x30"]

[[cheat]]
id = "invulnerability-3"
name = "Invulnerability 3"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(invuln3,D9 80 A8 00 00 00 D9 5D FC D9 45 FC 8B 45 08 D9 58 48)
invuln3:
  db 8B 45 08 D9 40 4C
registersymbol(invuln3)

[DISABLE]
invuln3:
  db D9 80 A8 00 00 00
unregistersymbol(invuln3)
dealloc(newmem)"""

[[cheat]]
id = "player-controller-pointer"
name = "Player Controller Pointer"
category = "player"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
alloc(PlayerController_ptr,4)
registersymbol(PlayerController_ptr)
[DISABLE]
dealloc(PlayerController_ptr)
unregistersymbol(PlayerController_ptr)"""

[[cheat]]
id = "base-address"
name = "Base Address"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "PlayerController_ptr"
hops = []

[[cheat]]
id = "disable-weapon-ability"
name = "Disable Weapon Ability"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "PlayerController_ptr"
hops = ["+0x1c8"]

[[cheat]]
id = "disable-artifact-ability"
name = "Disable Artifact Ability"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "PlayerController_ptr"
hops = ["+0x1cc"]

[[cheat]]
id = "disable-artifact-ability-2"
name = "Disable Artifact Ability"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"

[cheat.locator]
find = "symbol"
symbol = "PlayerController_ptr"
hops = ["+0x1d0"]

[[cheat]]
id = "player-combat"
name = "Player Combat"
category = "player"
description = ""
hint = ""
type = "value"
value_type = "i32"
hex = true

[cheat.locator]
find = "symbol"
symbol = "PlayerController_ptr"
hops = ["+0x1ac"]

[[cheat]]
id = "destroyable"
name = "Destroyable"
category = "misc"
description = ""
hint = ""
type = "script"
source = """
[ENABLE]
aobscan(destroyable,D9 47 48 D9 45 10 DE E9)
registersymbol(destroyable)

[DISABLE]
unregistersymbol(destroyable)"""
